### ISSUE TITLE
How to update part of a `Texture`? (For caching glyphs on the GPU using RustType)

### ISSUE THREAD

**Issue by mitchmindtree** [gfx-rs/gfx#1002]
Hey there fine gfx folks 😸 

I'm currently integrating [RustType](https://github.com/dylanede/rusttype) directly into conrod in order to remove the last non-pure-rust dependency (FreeType) and also to take advantage of RustType's [`gpu_cache::Cache`](https://dylanede.github.io/rusttype/rusttype/gpu_cache/index.html) for greater rendering efficiency.

The RustType repository provides [an example](https://github.com/dylanede/rusttype/blob/master/examples/gpu_cache.rs) demonstrating how to use the GPU cache with glutin and a glium texture. For the most part, I've been able to adapt this into conrod without issues, however I'm having difficulties when it comes to caching the glyphs. Specifically, [this section](https://github.com/dylanede/rusttype/blob/master/examples/gpu_cache.rs#L133-L145) demonstrates how to cache the queued glyphs within the glium texture, however I'm unsure of what the equivalent would be using a gfx texture?

Most of the conrod examples use `piston_window`, which uses the `gfx_graphics` backend internally. As a result, I'm attempting to update them to use the `UpdateTexture::update` method. Here's [the relevant section](https://github.com/mitchmindtree/conrod/blob/07a79dd172917441ac3d91f517c04715f7f676d8/examples/text.rs#L48-L60) of the updated text.rs example (note that the `rect` and `data` arguments there are identical to those given in the rusttype example [here](https://github.com/dylanede/rusttype/blob/master/examples/gpu_cache.rs#L133)). Using that code, the [`UpdateTexture::update` method call](https://github.com/mitchmindtree/conrod/blob/07a79dd172917441ac3d91f517c04715f7f676d8/examples/text.rs#L58) fails with the following error:
```
thread '<main>' panicked at 'Failed to update texture: UnitCountMismatch { target: 777600, slice: 48 }', ../src/libcore/result.rs:785
```

When searching for the error in this repo, I noticed the only place it seems to occur is within `Encoder::update_texture`. It seems that if the length of the given data does not exactly match the `tex::NewImageInfo::get_texel_count`, [the error is returned](https://github.com/gfx-rs/gfx/blob/d02cb59f794d2ab7e5aa58e673b96be20bbbf260/src/render/src/encoder.rs#L171). This seems to imply that the texture may only be updated if the entire texture is updated - is that correct? Is there a way to update a sub-section of the texture as RustType's GPU cache seems to require? Am I on the right track? I'm quite the graphics newbie, so any help or direction on this is greatly appreciated!

As a side note, it might be worth contributing a gfx example to the RustType repo, to compliment the glutin/glium one? I'd be happy to have a go at it myself if I can sort this out!

**Comment by kvark** [comment]
> This seems to imply that the texture may only be updated if the entire texture is updated - is that correct?

No. The `img` there defines a sub-region of the texture. I'm trying to figure out what piston layers do before calling GFX, looking for a problem there...

As a side note, @ozkriff also did some heavy lifting for the GPU text with GFX. Have a look at his repo:  https://github.com/ozkriff/gpu_cache_gfx

**Comment by kvark** [comment]
I can't wrap my head around this `UpdateTexture` usage. It appears to be a part of piston-texture, and the `update` function [looks](https://github.com/PistonDevelopers/texture/blob/master/src/lib.rs#L175) like this:
```rust
    fn update<S: Into<[u32; 2]>>(
        &mut self,
        factory: &mut F,
        format: Format,
        memory: &[u8],
        size: S,
    ) -> Result<(), Self::Error>;
```
Thus, I don't understand how you are calling it via `UpdateTexture::update(cache, encoder, format, data, dim)` - it looks like an entirely different function.

Perhaps, if you jump on our gitter, we could resolve it faster.

**Comment by mitchmindtree** [comment]
Agh thanks for taking a look @kvark, for some reason I was assuming `UpdateTexture` was defined in gfx, I didn't realise that it comes from `PistonDevelopers/texture`. I realise this is all buried in a crazy amount of abstraction so I appreciate you having a stab.

I've managed to track this down a bit further. The layers seem to go something like this:
- PistonDevelopers/texture defines an [`UpdateTexture` trait](https://github.com/PistonDevelopers/texture/blob/master/src/lib.rs#L170)
- PistonDevelopers/gfx_texture [declares a `Texture` type](https://github.com/PistonDevelopers/gfx_texture/blob/e9c5da0f98db0122ed0daafa4206129756b452a2/src/lib.rs#L29) and [implements the `texture::UpdateTexture` for it](https://github.com/PistonDevelopers/gfx_texture/blob/e9c5da0f98db0122ed0daafa4206129756b452a2/src/lib.rs#L142), in which [encoder.update_texture is called](https://github.com/PistonDevelopers/gfx_texture/blob/e9c5da0f98db0122ed0daafa4206129756b452a2/src/lib.rs#L155) which is where `UnitCountMismatch` is being returned.

> Thus, I don't understand how you are calling it via UpdateTexture::update(cache, encoder, format, data, dim) - it looks like an entirely different function.

I think the call makes sense, perhaps the use of UFCS is throwing you off?

I'm still unsure exactly what's causing the error, but will continue to dive deeper and see if I can work out what's going on here and report back. If it turns out the issue is downstream (which seems to be the case) I'll close this :+1:

cc @bvssvni

**Comment by mitchmindtree** [comment]
Hmm it seems that the `gfx_texture` `UpdateTexture` implementation [calls `encoder.update_texture` with a `gfx::tex::NewImageInfo` for the entire surface of the texture that is being updated](https://github.com/PistonDevelopers/gfx_texture/blob/e9c5da0f98db0122ed0daafa4206129756b452a2/src/lib.rs#L158), whereas it should really be called with a `gfx::tex::NewImageInfo` that represents the sub-section of the texture that we wish to update as done [here in the gpu_cache_gfx src](https://github.com/ozkriff/gpu_cache_gfx/blob/master/src/main.rs#L79-L89)? @kvark does this seem like it might be the cause?

**Comment by kvark** [comment]
Yes, looks like you narrowed it down. Since it's not in GFX, I'm closing the bug.
BTW, the thing that confused me about `update_texture` is not just UFCS (which is already here? I didn't know). Look at the second parameter. It's `factory: &mut F` in the trait, and `encoder: &mut gfx::Encoder<R, C>` in the implementation - looks like a different function!

**Comment by mitchmindtree** [comment]
@kvark heh totally! Come to think of it, this confused me also when I first had a look. Thanks again, I've opened up a PR downstream to address the issue at its [source](https://github.com/PistonDevelopers/gfx_texture/pull/88).
