### ISSUE TITLE
Enable CI for Metal backend

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1014]
We've got quite a few backends now. DX11 is tested by AppVeyor, GL and Vulkan are tested by Travis. Metal seems to be rotting a bit, but before fixing it we need to establish the continuous integration to keep it up.
cc @fkaa

**Comment by kvark** [comment]
Travis can do OSX: https://docs.travis-ci.com/user/multi-os/

**Comment by kvark** [comment]
We should make sure to not use `--features vulkan` on OSX too.

**Comment by fkaa** [comment]
Fixed in #1049
