### ISSUE TITLE
Persistent mapping

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1020]
Make [persistent mapping](https://www.opengl.org/wiki/Buffer_Object#Persistent_mapping) available by some API.
- [x] OpenGL (with temporary mapping fallback: #1026)
- [ ] Vulkan (should be close to OpenGL)
- [x] D3D11 (temporary mapping with the same API: #1098)
- [ ] Metal

**edit:** @tomaka helped me figuring out some details, in particular:

> The rule is simple: the CPU and GPU must not use the buffer at the same time

The comments below did not take this into account.

**Comment by Bastacyclop** [comment]
Some considerations about the OpenGL implementation.

### Creation

The persistent mapped buffer must be created with immutable storage (`glBufferStorage`),
the backend should check `self.share.private_caps.buffer_storage_supported` for this.
It must also be created with `GL_MAP_PERSISTENT_BIT`, therefore the user should somehow specify that his buffer will be used for persistent mapping.
The actual mapping is done with `glMapBuffer` and `GL_MAP_PERSISTENT_BIT`.

After discussing with @kvark, I suggest adding `map_persistent_buffer*` methods to the `Factory`, similar to the current `map_buffer*` ones. The raw version would still return a `Factory::Mapper` but the other ones would return specialized mapping structs (`mapping::Persistent{Readable, Writable, RW}`) that would not be lifetime-bound.
These structs should hold a buffer handle to ensure that the buffer is alive while the mapping is.

The `BufferInfo` struct could contain information about persistent mapping use in `Usage` or `Bind`.

### Write synchronisation

After writing to a persistent map, the mapped buffer needs to be flushed with `glFlushMappedBufferRange`
for the modifications to become visible to OpenGL. That is, it should be done before submitting a draw call using this buffer.

The mapping structs should track writings so that the mapped buffer can be automatically flushed during `device.submit()`. This could be done by maintaining a list/map of the persistent mapped buffers in need of flush. Tracking this on each index write would probably be inefficient and I suggest having methods like `PersistentWritable::write()` and `PersistentRW::to_mut_slice()` that would handle the tracking operation only once and provide regular mutable access afterwards.

### Read synchronisation

After submitting a draw call that would write to the mapped buffer and before reading from it, the following steps must be taken:
- issue a memory barrier (`glMemoryBarrier`) to ensure that what OpenGL has written is visible.
- create a fence (`glFenceSync`).
- "do something else for a while, so that you don't waste precious CPU time waiting for the GPU to be done."
- wait for the fence to become signaled (`glWaitSync` or `glClientWaitSync`).
 
This seems to be the hardest part to implement correctly since it requires the memory barrier and the fence to be setup right after the draw call. Waiting for the fence to become signaled should be done as late as possible (i.e right before reading) and could be done in a `to_slice()` method.

### Notes

The `mapping::Builder` trait should probably be extended with `*persistent*` methods.

`mapping::Writable` currently being usable as a mutable slice means that reading from it is possible,
while it shouldn't.

Obviously, the resulting API should avoid as much user boilerplate as possible while remaining efficient and compatible with the other backends. Help and comments would be much appreciated :smiley:.

**Comment by Bastacyclop** [comment]
The current non-persistent mapping should be completely replaced by persistent mapping, since Vulkan, Metal and DirectX are using it by design. The non-persistent behavior could eventually be automatically used as a fallback for OpenGL.

Some considerations about the Vulkan implementation:

There is nothing special to do at buffer creation since it is the standard use of buffers in Vulkan.
The other required operations are close to those of OpenGL.
The mapping is done with `vkMapMemory`.
The memory needs to be flushed with `vkFlushMappedMemoryRanges` (several memory ranges from different memory objects can be specified in a single call, does it give better performance ?).
Read synchronisation must also be handled by setting up a memory barrier and a fence.

A common API with the OpenGL backend seems pretty straightforward to establish.

**Comment by Bastacyclop** [comment]
related to: #426, #283 (I believe this one should be closed ?), #688, #236

**Comment by Bastacyclop** [comment]
starting a draft [branch](https://github.com/Bastacyclop/gfx/tree/persistent), for now focusing on OpenGL implementation. first version of buffer/mapping creation is done. introducing a mapping resource. no tracking, synchronisation or cleanup is implemented yet.

there is this API issue to keep in mind:
```rust
let slice = readable.as_slice(..); // may sync
// read slice
// draw stuff
encoder.flush(device);
// read slice, should have been synced but was not
```

**Comment by Bastacyclop** [comment]
It seems important to be able to `Send` a mapping. This means that the `Factory` and the `Device` are not appropriate to track mapping status without additionnal thread-safe mecanisms. The `Encoder` is not appropriate either since it would make the use of multiple `Encoder`s related to a common mapping unsafe and/or weird. This also simply does not seem to fit the `Encoder`'s role.
I'm currently considering the possibility of interior mutability inside the mapping resource that would allow to track the mapping status with more flexibility.

The memory barrier and fence necessary for a given submit being the backend responsibility, the `Device` could take care of this.

Things would look like this:
```rust
let writer = writable.write(); // the mapping status is set to "user access"
for (i, v) in stuff_to_write {
    writer.set(i, v); // direct access, just bound checking
}
writer.done(); // the mapping status is set to "cpu modified", also done on `Drop`
encoder.draw(..); // draw something using the mapped buffer
// [ ... ]
encoder.flush(device); // the device looks the mapping status of buffers being read from
                       // if it is "user access" it crashes, reporting an user error
                       // if it is "cpu modified" the mapping is flushed before continuing
                       // the device also looks at the buffers being written to.
                       // a memory barrier and a fence are set up if necessary
                       // the status of the concerned mappings is set to `GpuModified(fence)`
// [ ... ]
let reader = readable.read(); // if the status is `GpuModified(fence)`,
                              // the fence is waited for
                              // and then the status is set to "user access"
// use the reader
reader.done(); // the status is set to "clean"
```

In practice the status would probably be something like:

```rust
struct Status {
    user_access: bool,
    modification: ModificationStatus,
}

enum ModificationStatus {
    None,
    Cpu,
    Gpu(Fence),
}
```

The device already has access to buffer input/output but it now needs to be able to associate those with buffer mappings in order to perform the above operations which I don't know how to handle nicely for now.

Also a backend-side enum will be introduced. This way the synchronisation will only be applied to persistent mappings while regular ones can still be supported as a fallback with automatic mapping/unmapping instead of the synchronisation. While staged mappings will have no special treatment.

```rust
enum MappingKind {
    Persistent,
    Regular,
    Staged,
}
```

**Comment by kvark** [comment]
I believe this is done
