### ISSUE TITLE
gfx_defines! macro throws unintuitive error when missing trailing commas

### ISSUE THREAD

**Issue by LPGhatguy** [gfx-rs/gfx#1021]
Following the sample triangle code, I decided to extend the `gfx_defines!` block to include texture coordinates when I discovered:

```rust
gfx_defines!{
	vertex Vertex {
		pos: [f32; 2] = "a_Pos",
		color: [f32; 3] = "a_Color",
		texcoords: [f32; 2] = "a_Texcoords" // <-- error: no rules expect the token `}`
	}
}
```

As I understand it (and I am new to Rust), its idiomatic to use trailing commas in initializer blocks, but not required.

Is this a case where it would be more clear to allow missing a trailing comma?

**Comment by brendanzab** [comment]
Often Rust macros allow both trailing and non-trailing commas (see the `vec!` macro). Would be good to have it here as well.

But yes, this is part and parcel of non-procedural macros - they often give generic, unhelpful errors :(
