### ISSUE TITLE
MSAA FB/FBO Blit resolution missing

### ISSUE THREAD

**Issue by norru** [gfx-rs/gfx#1024]
I'm using the OpenGL backend on Linux. I've created a HDR FBO where I'm doing my main rendering/lighting. After the lighting/forward pass I postprocess the FBO for bloom, tonemapping etc. and so far it works.

If I create the FBO as a MSAA-enabled target, nothing else changed, I get a "red screen" instead. OpenGL documentation say I have to resolve the MSAA target into another FBO by using a framebuffer blit. In openGL seems to be straightforward but I couldn't find how to do it in gfx-rs. Any pointers?

If I don't create the surface as MSAA it's fine, "blit from texture" does work.

``` rust
fn create_render_target(factory: &mut F,
                            w: u16,
                            h: u16)
                            -> Result<effects::HDRRenderSurface<R>, gfx::CombinedError> {
        let kind = gfx::tex::Kind::D2(w, h, gfx::tex::AaMode::Multi(4));
        let tex = try!(factory.create_texture(kind,
                                              1,
                                              gfx::SHADER_RESOURCE | gfx::RENDER_TARGET,
                                              gfx::Usage::GpuOnly,
                                              Some(gfx::format::ChannelType::Float)));
        let hdr_srv = try!(factory.view_texture_as_shader_resource::<HDRColorFormat>(&tex,
                                                                                     (0, 0),
                                                                                     gfx::format::Swizzle::new()));
        let hdr_color_buffer = try!(factory.view_texture_as_render_target(&tex, 0, None));
        Ok((tex, hdr_srv, hdr_color_buffer))
    }
```

Replacing

``` rust
let kind = gfx::tex::Kind::D2(w, h, gfx::tex::AaMode::Multi(4));
```

with

``` rust
let kind = gfx::tex::Kind::D2(w, h, gfx::tex::AaMode::Single);
```

works.

Digging in the OpenGL docs points me to the fact that the render target needs to be resolved before it can be used as a texture source or displayed.

There is no straightforward way to do this in Gfx-rs. The Blit functionality appears to be incomplete/missing.

@Kvark suggestion to use a fragment shader in the PostprocessFX passes to do the downsampling/averaging did the trick but requires a substantial effort to implement, especially no infrastructure for full screen PostprocessFX is in place.

For reference, this is the frag shader which I've applied full screen with source: the MSAA 4x buffer, and destination the first FBO of the PostprocessFX. I don't take credit for it, I found it on an OpenGL forum but couldn't find the original link to credit the author.

``` glsl
#version 150 core

uniform sampler2DMS t_Source;

in vec2 v_TexCoord;
out vec4 o_Color;

void main() {
    vec2 d = textureSize(t_Source);
    ivec2 i = ivec2(d * v_TexCoord);
    o_Color = (texelFetch(t_Source, i, 0) + texelFetch(t_Source, i, 1)
            + texelFetch(t_Source, i, 2) + texelFetch(t_Source, i, 3)) / 4.0;
}
```

Here's a link to my project where I'm using it

https://github.com/itadinanta/rust-oids/blob/master/resources/shaders/effects/msaa4x_resolve.frag

**Comment by kvark** [comment]
not happened in pre-ll, sorry!
