### ISSUE TITLE
Runtime version of `ConstantBuffer`

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#1038]
When trying to update https://github.com/pistondevelopers/skeletal_animation, the old version uses:

```
u_skinning_transforms@ u_skinning_transforms: gfx::handle::RawBuffer<R>,
```

This is a uniform but with two different formats,

one for Linear Blend Skinning:
```
uniform u_skinning_transforms {
    mat4 skinning_transforms[MAX_JOINTS];
};
```

one for Dual Quaternion Linear Blend Skinning:
```
uniform u_skinning_transforms {
    mat2x4 skinning_transforms[MAX_JOINTS];
};
```

I was told by @fkaa to use `ConstantBuffer`, but this requires a generic parameter `T: Structure<ConstFormat>`.

It seems that this format must be known in advance, and I could not find an alternative.

**Comment by Bastacyclop** [comment]
You can still use raw methods/handles like: https://docs.rs/gfx/0.12.0/gfx/trait.Factory.html#tymethod.create_buffer_raw.
However you will need to provide actual (typed) pipeline state/data on draw: https://docs.rs/gfx/0.12.0/gfx/struct.Encoder.html#method.draw.
Maybe you can do it by dynamically providing type information with https://docs.rs/gfx/0.12.0/gfx/trait.Typed.html ?

**Comment by kvark** [comment]
It sounds like the linear and DQ variants should have separate PSO definitions then. They use different shaders, and these use different formats for the constant buffers.
