### ISSUE TITLE
Document mirroring between gfx and backend shaders

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1039]
- [x] OpenGL
- [ ] Vulkan
- [ ] DirectX
- [ ] Metal

As suggested by @bvssvni in [this comment](https://github.com/PistonDevelopers/skeletal_animation/pull/48#issuecomment-245363346), documenting this relationship would be useful.
Like @kvark said, this could be located in the backend documentation or in the backend `README.md`. I think it would be most suited in the `mirror` and `shade` backend modules. The only problem is that few people will look there, this could be solved by introducing some links from the main `README.md` and/or the gfx documentation to the official backend documentations.

**Comment by Bastacyclop** [comment]
Actually the backend modules are private, let's keep it that way and use the backend `README.md`.

**Comment by kvark** [comment]
I believe this is documented now
