### ISSUE TITLE
[GL] Factory cloning is incompatible with mapping

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1053]
Our mapping `map_buffer_*` takes `&mut self`, disallowing multiple maps at the same time. This can be worked around by cloning a factory first, and then mapping. However, each mapping goes through `GL_ARRAY_BUFFER` target, so they can't be used together. This is a loophole, needs to be closed by removing the `Clone` implementation on a `Factory`.

**Comment by Bastacyclop** [comment]
@kvark Actually the mapping structs are not borrowing the factory anymore. I don't think that using `GL_ARRAY_BUFFER` target for multiple mappings is problematic since this is only a way to refer to the buffer currently bound to it and should still be able to produce multiple independent mappings ?

**Comment by kvark** [comment]
@Bastacyclop Ah, I suppose we are just missing a `gl.BindBuffer()` before the `unmap()` call.

**Comment by Bastacyclop** [comment]
I'm pretty sure I fixed it:
https://gitter.im/gfx-rs/gfx?at=57bb81ba187885ef4f6bcea2
https://github.com/gfx-rs/gfx/blob/a015a3a6e0dac56d877e54a5427d28714ca30e72/src/backend/gl/src/factory.rs#L239

**Comment by kvark** [comment]
@Bastacyclop you kick ass, sir
closed by #1031
