### ISSUE TITLE
Memory leak when updating large textures every frame

### ISSUE THREAD

**Issue by yeliknewo** [gfx-rs/gfx#1054]
https://github.com/yeliknewo/algorithm_art
When running this on Windows 10 if you set the texture time to lower numbers it continuously uses more RAM until the computer grinds to a halt

**Comment by kvark** [comment]
Is this a blocker for you?

**Comment by yeliknewo** [comment]
I have a lot of small projects I like to work on. This just prevents cellular automata and procedural generated art. Its not a big deal.

**Comment by kvark** [comment]
from @msiglreith 
> a possible cause for memory leak might be the frame_handles of the factory, which never gets cleared iirc.
https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/factory.rs#L73

**Comment by kvark** [comment]
Fixed by #1397
