### ISSUE TITLE
gfx Rusty Planet demo will be open sourced in few days...

### ISSUE THREAD

**Issue by greenmughal** [gfx-rs/gfx#1057]
![01](https://cloud.githubusercontent.com/assets/19550918/18922753/9ba6fa02-85b2-11e6-8f3a-f39a99ece5a0.png)

![02](https://cloud.githubusercontent.com/assets/19550918/18922767/a6cd5d22-85b2-11e6-99ee-1d26eb85cbc0.png)

Hi All,
Im going to open source the procedural planet dx11 version very soon under probably gpl 2 or 3, I am unable to commit time to it due to day job and family commitments and other distractions.

I made modification to gfx and the pull request was not successful, i hope if anyone interested will carry on with it.

Its provides a simple CPU based approach combined with Hardware tessellation with NO support for cracks filling. The operations are mostly GPU friendly, i havent implemented hardware instancing however nothing probably should stop you. details later....

Regards
Ahmed

**Comment by kvark** [comment]
This looks incredible!
If the PR you mentioned is #1027, then we'll get someone updating it in order to merge. Can't proceed when CI is red otherwise.
It's sad that you can't continue developing it, life happens to the best of us... It'd be interested to at least fixing the cracks, as this would be one of the most impressive demoes to date.

**Comment by kvark** [comment]
@greenmughal Ping! The tessellation is merged now.

**Comment by kvark** [comment]
@greenmughal so have you opened the code yet? We can update it to the latest gfx-rs so that you don't base off your own fork.

**Comment by greenmughal** [comment]
Ok give me a couple of days (friday is the weekend here) to open it, need to clean up the code, I also need help in various areas to improve the overall planet rendering.

**Comment by greenmughal** [comment]
its uploaded

https://github.com/greenmughal/rustyplanet

**Comment by kvark** [comment]
Screenshot added to README in https://github.com/gfx-rs/gfx/commit/c54a35ea3b57d9c7d0d014cffe426e5afaca14b6
Thank you, awesome stuff!
