### ISSUE TITLE
Feature request: DeviceInfo

### ISSUE THREAD

**Issue by Oskuz** [gfx-rs/gfx#1059]
Add new `DeviceInfo` enum, and `get_device_info()` to `gfx::Device`, which would include  some data about platform at run-time, such as operating system version and the backend API version

**Comment by kvark** [comment]
What would you use it for?

**Comment by Kerollmops** [comment]
It can for example be used by openCL for data sharing

**Comment by kvark** [comment]
not happened in pre-ll, sorry!
