### ISSUE TITLE
Crash when using more than one PSO definition on Mac

### ISSUE THREAD

**Issue by thedarkduscher** [gfx-rs/gfx#1062]
After we switched to GLSL 150 core profile our game crashes as soon as we use a different PSO than the first one we used.

## Trace
[trace.txt](https://github.com/gfx-rs/gfx/files/517308/trace.txt)

## Pipeline Definitions
```rust
pub type ColorFormat = gfx::format::Srgba8;
pub type DepthFormat = gfx::format::DepthStencil;
pub type SurfaceFormat = gfx::format::R8_G8_B8_A8;
pub type FullFormat = (SurfaceFormat, gfx::format::Unorm);

gfx_defines! {
    vertex Vertex {
        pos: [f32; 3] = "a_Pos",
        uv: [f32; 2] = "a_Uv",
    }
    
    constant ProjectionStuff {
        model: [[f32; 4]; 4] = "u_Model",
        view: [[f32; 4]; 4] = "u_View",
        proj: [[f32; 4]; 4] = "u_Proj",
    }

    pipeline sprite {
        color: gfx::Global<[f32; 4]> = "u_Color",
        projection_cb: gfx::ConstantBuffer<ProjectionStuff> = "b_Proj",
        vbuf: gfx::VertexBuffer<Vertex> = (),
        texture: gfx::TextureSampler<[f32; 4]> = "t_Tex",
        out: gfx::BlendTarget<ColorFormat> = ("Target0", gfx::state::MASK_ALL,
            gfx::preset::blend::ALPHA),
        out_depth: gfx::DepthTarget<DepthFormat> =
            gfx::preset::depth::LESS_EQUAL_WRITE,
    }

    pipeline simple_mesh {
        color: gfx::Global<[f32; 4]> = "u_Color",
        projection_cb: gfx::ConstantBuffer<ProjectionStuff> = "b_Proj",
        vbuf: gfx::VertexBuffer<Vertex> = (),
        out: gfx::BlendTarget<ColorFormat> = ("Target0", gfx::state::MASK_ALL,
            gfx::preset::blend::ALPHA),
        out_depth: gfx::DepthTarget<DepthFormat> =
            gfx::preset::depth::LESS_EQUAL_WRITE,
    }
}
```

#### sprite.v.glsl
```glsl
#version 150 core

in vec3 a_Pos;
in vec2 a_Uv;

uniform b_Proj {
    mat4 u_Model;
    mat4 u_View;
    mat4 u_Proj;
};

out vec2 v_TexCoord;

void main() {
    v_TexCoord = a_Uv;
    gl_Position = u_Proj * u_View * u_Model * vec4(a_Pos, 1.0);
}
```

#### sprite.f.glsl
```glsl
#version 150 core

uniform sampler2D t_Tex;
uniform vec4 u_Color;

in vec2 v_TexCoord;

out vec4 Target0;
 
void main() {
    vec4 color = texture(t_Tex, v_TexCoord) * u_Color;
    Target0 = color;
}
```

#### simple_mesh.v.glsl
```glsl
#version 150 core

in vec3 a_Pos;

uniform b_Proj {
    mat4 u_Model;
    mat4 u_View;
    mat4 u_Proj;
};

void main() {
    gl_Position = u_Proj * u_View * u_Model * vec4(a_Pos, 1.0);
}
```

#### simple_mesh.f.glsl
```glsl
#version 150 core

uniform vec4 u_Color;

out vec4 Target0;
 
void main() {
    Target0 = u_Color;
}
```

**Comment by thedarkduscher** [comment]
When removing `v_TexCoord = a_Uv;` from [sprite.v.glsl](https://gist.github.com/thedarkduscher/b176b832364535b38ecb9098699dcdcb#file-sprite-v-glsl) it doesn't crash anymore. When I add something like `vec2 test = a_Uv;" the next shader (or so) crashes again.

**Comment by kvark** [comment]
Are you having one of the buffers mapped by any chance?

> `GL_INVALID_OPERATION` is generated if a non-zero buffer object name is bound to an enabled array or the element array and the buffer object's data store is currently mapped. 

Also, this statement needs more info:
> When I add something like vec2 test = a_Uv; the next shader (or so) crashes again.

What shader are you adding this to? What's the next shader that comes after? Could you provide an `apitrace` for this as well?

**Comment by kvark** [comment]
It would really help to get https://github.com/gfx-rs/gfx/issues/596 implemented for cases like this, assuming the extension is supported on that OSX.

**Comment by thedarkduscher** [comment]
As far as I know we're not mapping any buffers, we're just passing the VertexBuffer with the PSO Data and update the Constant Buffer using `encoder.update_constant_buffer(...);`.

I've replaced `v_TexCoord = a_Uv;` with `vec2 test = a_Uv;` in `sprite.v.glsl` to see if it has something to do with v_TexCoord (which it apparently has not). We're just drawing a single Sprite and afterwards we're drawing a single quad with the Simple Mesh.

So, here's the working one:
```
#version 150 core

in vec3 a_Pos;
in vec2 a_Uv;

uniform b_Proj {
    mat4 u_Model;
    mat4 u_View;
    mat4 u_Proj;
};

out vec2 v_TexCoord;

void main() {
    v_TexCoord = vec2(0.0, 0.0);
    gl_Position = u_Proj * u_View * u_Model * vec4(a_Pos, 1.0);
}
```
[trace8.txt](https://github.com/gfx-rs/gfx/files/517982/trace8.txt)

And this is crashing:
```
#version 150 core

in vec3 a_Pos;
in vec2 a_Uv;

uniform b_Proj {
    mat4 u_Model;
    mat4 u_View;
    mat4 u_Proj;
};

out vec2 v_TexCoord;

void main() {
    vec2 test = a_Uv;
    v_TexCoord = vec2(0.0, 0.0);
    gl_Position = u_Proj * u_View * u_Model * vec4(a_Pos, 1.0);
}
```
[trace9.txt](https://github.com/gfx-rs/gfx/files/517983/trace9.txt)

**Comment by kvark** [comment]
Thank you for the info! I've got an idea:
So GLSL considers `a_Uv` used when you add this line to the shader. It also reports `a_Uv` being the first attribute, and `a_Pos` being the second one, so it effectively changes the positions of `a_Pos` binding between shaders.
So with the first shader we have attrib[0] = a_Uv, attrib[1] = a_Pos. When we switch to the second shader we get attrib[0] = a_Pos. Since we don't ever disable vertex attributes, we are effectively telling GL to send the same data to both attrib[0] and attrib[1] (even though the latter is not used). Perhaps, this is confusing the hell out of OSX driver.

Proposal to fix: call `gl.DisableVertexAttrib` on all unused slots. I'll make a PR shortly for you to test.

**Comment by kvark** [comment]
@thedarkduscher would you be able to test if #1063 fixes it for you?

**Comment by thedarkduscher** [comment]
Sure!

**Comment by thedarkduscher** [comment]
Works perfect :) 
BTW thanks for your fast help, I really appreciate your active support!

**Comment by kvark** [comment]
Awesome! It's quite handy that you are working on `master` for fixes like this :)
