### ISSUE TITLE
Support TriangleFan

### ISSUE THREAD

**Issue by mathstuf** [gfx-rs/gfx#1067]
I see that 33ea864100149266fdf7c4ef73d6b2c7ef094108 removed the `TriangleFan` primitive. Unfortunately, the commit is light on details. Is there a backend which does not support it?

**Comment by fkaa** [comment]
They are removed in (most) modern APIs (DX >=10, Metal). OpenGL and Vulkan still have it though. See [here](http://gamedev.stackexchange.com/a/35564) for more details

**Comment by mathstuf** [comment]
Ah, that makes sense, thanks.
