### ISSUE TITLE
Geometry shaders do not work and often crash the program

### ISSUE THREAD

**Issue by Diggsey** [gfx-rs/gfx#1069]
The program will randomly alternate between crashing or just failing to apply the geometry shader.

Backtrace + shader source + rust source:
https://gist.github.com/Diggsey/4c5f761cd19a5dd22f93d95a4e4e3603

Replacing `ShaderSet::Geometry(vs, gs, ps)` with `ShaderSet::Simple(vs, ps)` will result in the program working reliably.

**Comment by sectopod** [comment]
Hi @Diggsey !
I reproduced your problem and found a trivial mistype on our end, which is now fixed.
Would you mind doing a cargo override to use the latest gfx-rs from master?

**Comment by Diggsey** [comment]
Great, it's all working fine now!

**Comment by kvark** [comment]
It would be pretty sweet to have a GS-featuring example here. Either by modifying one of ours (there is quite a few already, getting more difficult to support if adding more for each feature), or introducing a new one.

**Comment by Diggsey** [comment]
I'd be happy to adapt my code into a simple multicoloured particle example (using a GS to expand points to quads) - not exactly the most advanced use of GS though.

**Comment by kvark** [comment]
@Diggsey I like the idea of particle-GS-featuring example!

Originally, I thought about something that loads up an OBJ (we don't have examples for that yet) and generates/draws it's normals using the geometry shader.
