### ISSUE TITLE
60fps limit?

### ISSUE THREAD

**Issue by mathstuf** [gfx-rs/gfx#1071]
I'm seeing my fps limited to 60fps during the `encode.flush(device)` step (with the GL backend); is there a way to remove that restriction?

**Comment by msiglreith** [comment]
Have you disabled vsync on window creation?
(gfx's `Application` enables it)

**Comment by mathstuf** [comment]
I'm not using `gfx::Application` (using SDL2 instead).

**Comment by mathstuf** [comment]
That is, I don't explicitly enable it; it is probably implicit somewhere, but I don't see a place to configure it.

**Comment by kvark** [comment]
This is probably what you are looking for: https://wiki.libsdl.org/SDL_GL_SetSwapInterval

**Comment by mathstuf** [comment]
It is already set to `0` and if I comment the `encoder.flush(device)` line, it is no longer limited to 60fps, (even with no draw commands inserted into it).

**Comment by kvark** [comment]
How many FPS are you getting if you don't call `encoder.flush` doesn't matter, since you get nothing on screen. gfx-rs core/render modules are completely unaware of your swap chain, which is responsible for vsync, and which is controlled by SDL only.
Care to show the source?

**Comment by mathstuf** [comment]
If I comment it out, I get either 0 or 1ms per loop (SDL's timer resolution).

Yeah, I'll upload the source tonight.

**Comment by mathstuf** [comment]
Hmm. I guess it could be optimizing out the swap if no commands were given…

**Comment by kvark** [comment]
Is this still a problem? Please re-open if true.

**Comment by mathstuf** [comment]
Yeah, I'm still seeing this. The code is [here](https://github.com/mathstuf/abagames-gunroar/tree/rust) and the loop is in [this directory](https://github.com/mathstuf/rust-abagames-util/tree/master/src/sdl), `mainloop.rs` and `video.rs` for the flush calls.

**Comment by mathstuf** [comment]
It appears I do not have permission to reopen.

**Comment by kvark** [comment]
I got the game running after a few tweaks. Where do you see the FPS?

**Comment by mathstuf** [comment]
Ah, sorry. Just pushed by FPS output hunk to [this branch](https://github.com/mathstuf/rust-abagames-util/tree/fps-output).

**Comment by mathstuf** [comment]
Out of curiosity, what tweaks were required?

**Comment by mathstuf** [comment]
Ah, found the missing `error_chain` import.

**Comment by kvark** [comment]
I had to tweak the path to utils as well as the external crate define for `error_chain`.
I can repro now and see that I'm also limited to 60 fps. Here is what I see in the capture:

`glXSwapIntervalMESA(interval = 0) = 0`, meaning the successful return. Although, the spec says it's not actually guaranteed to disable vsync:
> glXSwapIntervalMESA specifies the minimum number of video frame periods per buffer swap.

So basically the implementation is free to ignore value 0 and pretend that nothing happened...

The whole issue seems to be SDL/driver related, since we do issue the proper calls (as indicated in the capture).

**Comment by mathstuf** [comment]
OK, thanks for the info. I'll try and see if I can't try it out on another machine with a different video card.

**Comment by umurgdk** [comment]
@mathstuf if you're running on linux try running the application as: `vblank_mode=0 target/.../yourapp` `vblank_mode=0` environment variable disables the vsync for me.

**Comment by mathstuf** [comment]
Ah, thanks, I'll use that.

I see I never said my original goal: I'm porting a game from D to Rust and the D code runs at 90+ fps. I'm interested in the relative speed of the Rust code (and the better pipelined OpenGL code too) and 60 fps lock kind of defeats the purpose there :) . The workaround is sufficient for me.
