### ISSUE TITLE
Bump crates.io version

### ISSUE THREAD

**Issue by ozkriff** [gfx-rs/gfx#1082]
Looks like https://github.com/gfx-rs/gfx/issues/1070 is fixed in master branch.

**Comment by kvark** [comment]
Should I un-yank 0.12.2 then?

**Comment by ozkriff** [comment]
0.12.2 works fine for me on stable & nightly (1c448574b 2016-11-28) right now on local machine.

It fails on Travis (https://travis-ci.org/ozkriff/zoc/jobs/172933507) because of [this](https://www.reddit.com/r/rust/comments/5fjf7o/psa_cargo_nightly_on_linux_cant_fetch_the_index/) but I don't think it's important.

**Comment by kvark** [comment]
0.12.2 is [unyanked](https://crates.io/crates/gfx/0.12.2)
thanks for confirmation!
