### ISSUE TITLE
Consider handling or detecting padding/alignment issues for UBOs in GLSL

### ISSUE THREAD

**Issue by Jragonmiris** [gfx-rs/gfx#1083]
This is likely non-trivial, but I was just trying to diagnose an issue in this program:

https://gist.github.com/Jragonmiris/840195b04ea3695a7fb6df22bb6715ca

After a lot of debugging work, I found that the issue, of course, ends up being that in a GLSL shader, a `mat3` in a uniform block must be sent over as a `mat4`, something I forgot about because I usually work in 3D so it rarely comes up. So `[[f32; 3]; 3]` is just plain incorrect and leads to seemingly baffling issues like identity matrices not acting like identities.

See: https://www.opengl.org/wiki/Talk:Uniform_Buffer_Object

Given Rust's focus on safety, it may be worth it, where possible, to detect this. Possibly throwing a flag if non-4x4 matrices appear in a ConstantBuffer, though that may raise issues with other backends (I don't know if D3D requires such a thing).

I'm not sure if this *can* reasonably be handled, but I think if some way of detecting this *is* possible it would be helpful to users, especially newbies who don't have my shader debugging skills.

**Comment by Jragonmiris** [comment]
Closed because it looks like ATM, gfx may not be able to handle mat3s in uniform blocks at all.

**Comment by kvark** [comment]
@Jragonmiris please note that we already detect the invalid offsets inside uniform buffers, so if you add mat3s support, it should be handled nicely automatically.
