### ISSUE TITLE
An API for determining backend type

### ISSUE THREAD

**Issue by snuk182** [gfx-rs/gfx#1084]
I'm extending my [drawing backend for the Nuklear GUI library](https://github.com/snuk182/nuklear-backend-gfx) by adding the support for the graphic backends other than OpenGL. It has no backend-dependent code, except one place - the shaders. Unfortunately I could not find a way neither to automate per-backend shader loading in gfx (like in gfx_app) nor to get the backend type I'm currently in, to install the correct shader set. Although I can implement an external backend flag (similar to [this](https://github.com/gfx-rs/gfx/blob/master/src/shade.rs)), I'd still like to have this ability as a general purpose API.

**Comment by kvark** [comment]
Problem here is conceptual. GFX render/core are backend-agnostic, so having any kind of API in them exposing that a device is GL or D3D11 is a leaky abstraction. This is precisely why currently only `gfx_app` has the enum for backends, and knows about their differences, and chooses the apropriate shaders. That is why, if you want that kind of API and you aren't using `gfx_app`, you'll need to manage this yourself, probably by something that creates those specific backends in the first place.

**Comment by snuk182** [comment]
Ok then I'm closing it for now...
