### ISSUE TITLE
Update crates.io version of DX environment

### ISSUE THREAD

**Issue by snuk182** [gfx-rs/gfx#1085]
Current crates.io version of `gfx_window_dxgi` is 0.3.0. It does not have the `Window::poll_events()` method, which exists for git version 0.4.0. Maybe `gfx_device_dx11` also should be updated.

**Comment by kvark** [comment]
Thanks for filing the issue! Please feel free to submit a PR.

**Comment by snuk182** [comment]
It's not a code changing task, unfortunately - I cannot fix it on my own :cry:

**Comment by sectopod** [comment]
https://crates.io/crates/gfx_window_dxgi/0.4.0
