### ISSUE TITLE
Bump crates.io version of gfx_core

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1090]
The current version of `gfx_core` on crates.io is [0.4.0](https://crates.io/crates/gfx_core), but gfx 0.12.2 actually has as dependency [`gfx_core = 0.5`](https://github.com/gfx-rs/gfx/blob/master/src/render/Cargo.toml#L35).

Cargo will also pull the 0.4 version when creating a new application:
```
[[package]]
name = "gfx"
version = "0.12.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "draw_state 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "gfx_core 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.6 (registry+https://github.com/rust-lang/crates.io-index)",
]
```
This causes errors when trying to build the flowmap example in a separate project with the following dependencies:
```
[dependencies]
gfx = "0.12.2"
gfx_app = "0.3.0"
```

```Rust
error[E0432]: unresolved import `gfx::texture`
  --> main.rs:60:9
   |
60 |     use gfx::texture as t;
   |         ^^^^^^^^^^^^^^^^^ no `texture` in the root

error: no method named `create_texture_immutable_u8` found for type `&mut F` in the current scope
  --> main.rs:64:29
   |
64 |     let (_, view) = factory.create_texture_immutable_u8::<Rgba8>(kind, &[&img]).unwrap();
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0560]: struct `gfx_app::shade::Source<'_>` has no field named `msl_11`
  --> main.rs:82:13
   |
82 |             msl_11:   include_bytes!("shader/flowmap_vertex.metal"),
   |             ^^^^^^^ field does not exist - did you mean `hlsl_41`?

error[E0560]: struct `gfx_app::shade::Source<'_>` has no field named `msl_11`
  --> main.rs:89:13
   |
89 |             msl_11:   include_bytes!("shader/flowmap_frag.metal"),
   |             ^^^^^^^ field does not exist - did you mean `hlsl_41`?

error: aborting due to 3 previous errors
```
The first 2 errors are caused by the old version of gfx_core, the other due to changes to gfx_app on master branch.

**Comment by kvark** [comment]
You are mistaken. gfx-0.12.2 would not be successfully published if it depended on an unpublished gfx_core-0.5. Have a look here - https://crates.io/crates/gfx/0.12.2

Dependencies:
 - draw_state ^0.6
 - gfx_core ^0.4
 - log ^0.3

The link to `Cargo.toml` you posted is for *master* branch, while 0.12.2 is published from [v0.12 branch](https://github.com/gfx-rs/gfx/blob/v0.12/src/render/Cargo.toml#L35).

> This causes errors when trying to build the flowmap example in a separate project with the following dependencies

Yes, because you are trying to build an example from *master* branch using v0.12 dependencies.

**Comment by msiglreith** [comment]
Thanks for clearing it up! I wasn't aware of the version branches, now this actually makes sense 👍

**Comment by kvark** [comment]
No worries! We should probably describe this somewhere in README/docs.
