### ISSUE TITLE
Provide a write-only slice

### ISSUE THREAD

**Issue by snuk182** [gfx-rs/gfx#1096]
Currently we have 'gfx::mapping::Reader' for a readonly slice features, and a `gfx::mapping::RWer` for read and write slice features. While there is also a `gfx::mapping::Writer`, it does not provide slice write access, only the index-wise setter. Need something to fill this gap.

**Comment by snuk182** [comment]
Functionally it was fixed in https://github.com/gfx-rs/gfx/issues/1098 , but in an straightforward way of allowing `&mut [T]` support with a warning restriction of using it for reading, since Rust does not have any plans for write-only slices (yet?).

**Comment by kvark** [comment]
Ok, thanks @snuk182 ! It's up to you to either leave it open for more work or close.
