### ISSUE TITLE
Persistent mapping on D3D11

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1098]
D3D11 doesn't appear to support it. cc @Bastacyclop

**Comment by Bastacyclop** [comment]
@kvark Do you mean our backend, that would be expected since nobody did it yet (#1020), or D3D11 itself ? If D3D11 only supports temporary mapping we could do the same thing I did when the OpenGL capabilities do not include persistent mapping. Instead of synchronising the accesses to the persistent mapping we simply map/unmap the temporary mapping (the user API doesn't change). The question might be: is this solution good enough ?

**Comment by Bastacyclop** [comment]
To be more precise, whenever the user wants to access the mapping we ensure that it is mapped by checking a boolean and calling `Map` if necessary. Whenever the GPU needs access to the mapping we ensure that it is unmapped by checking the same boolean and calling `Unmap` if necessary.

**Comment by Bastacyclop** [comment]
This makes me consider entirely moving the mapping `Option<Fence>` management from core to the backends.

**Comment by snuk182** [comment]
Does this mean we should mimic the Persistent Buffers in DX11 with, say, [this](https://gamedev.stackexchange.com/questions/15651/mapping-a-vertex-buffer-in-directx11)?

**Comment by Bastacyclop** [comment]
That's what I would do, yes (without looking into the details of your link). We may also want to avoid explicitly saying to the user that the mapping is "persistent" since it might fall back to temporary mapping and that could be confusing.

**Comment by snuk182** [comment]
Then would not it be more clear to name it not Persistent, but Mappable ?

**Comment by kvark** [comment]
Sounds good! looks like you are on the right track :)

**Comment by snuk182** [comment]
Crap. The [buffer mapping api](https://retep998.github.io/doc/winapi/d3d11/struct.ID3D11DeviceContext.html#method.Map) attached to the DeviceContext, which is a part of Device. How can I get it in a Factory?

**Comment by Bastacyclop** [comment]
@snuk182 I hope we have not been working on the same parts :p

**Comment by snuk182** [comment]
Please go ahead. I never worked with D3D so just playing around.

**Comment by Bastacyclop** [comment]
I simply made the PR above, I never worked with D3D either and I won't have access to a Windows environment for a while.

**Comment by snuk182** [comment]
Ok then I gonna torture my copy of gfx a bit.

**Comment by snuk182** [comment]
[from here](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476457%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)
> If you call Map on a deferred context, you can only pass D3D11_MAP_WRITE_DISCARD, D3D11_MAP_WRITE_NO_OVERWRITE, or both to the MapType parameter. Other D3D11_MAP-typed values are not supported for a deferred context. 

Just checked it - indeed I cannot ask for READ_WRITE access. Are there ways I can access the non-deferred context?

**Comment by Bastacyclop** [comment]
I think you would need [this device](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/lib.rs#L162) instead of [this one](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/lib.rs#L405)

**Comment by snuk182** [comment]
Well I just took one returned by [GetImmediateContext](https://retep998.github.io/doc/winapi/d3d11/struct.ID3D11Device.html#method.GetImmediateContext) cause the original context is in the Device, which I cannot (?) access from the Factory

**Comment by Bastacyclop** [comment]
I want to point out something about the mapping `Mutex` locks. There are [holes](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L758) [between](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L776) [those](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L827) in my OpenGL implementation during the submission process. With the single-thread accesses in OpenGL this is fine (the user can't acquire the lock in between), but with multi-thread accesses the user might acquire the lock in between. I believe we must not allow this and keep the lock until the submission process is completly done with the mapping (for OpenGL too, for consistency ?).

**Comment by snuk182** [comment]
Sounds reasonable. Will ask for a mentoring on that after I prepare the general functionality.

**Comment by snuk182** [comment]
Did not find the buffer unmapping code in GL. While DX11 [requires to explicitly unmap the buffer before drawing](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476485(v=vs.85).aspx), I need to place it somewhere. Where I should do this?
(I suggest the `Drop` for `Writer`/`RWer`)

**Comment by kvark** [comment]
I think it's [here](https://github.com/gfx-rs/gfx/blob/688991d8cd7e4d98f14b7562e4a68c730805bd17/src/core/src/mapping.rs#L70):
```rust
impl<R: Resources> Drop for RawInner<R> {
    fn drop(&mut self) {
        self.buffer.was_unmapped();
    }
}
```

**Comment by Bastacyclop** [comment]
We unmap the buffers [before drawing](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L748) and [during cleanup](https://github.com/gfx-rs/gfx/blob/1a13b5b1edbaed620ca83fc6e966ac78c4c31eee/src/backend/gl/src/lib.rs#L916). We map the buffers [before user access](https://github.com/gfx-rs/gfx/blob/1a13b5b1edbaed620ca83fc6e966ac78c4c31eee/src/backend/gl/src/factory.rs#L536).

**Comment by snuk182** [comment]
Why we can't unmap the buffer on `Drop` of the `Reader` / `Writer` / `RWer` ? This would simplify the code and unsure the `map` & `unmap` will be called on the same thread (as long as these structs are not `Send + Sync`)

**Comment by Bastacyclop** [comment]
This is inherited from my persistent mapping implementation, where the mapping is flushed before gpu read. It also delays the `map`/`unmap` calls until really necessary, which could avoid some of them ?

If you were to unmap the buffer on `Drop`, you would still need to check during submission that the buffer is not currenlty mapped, so I don't think that it would simplify the code that much unless you find a better way to solve this.

However, if you do need to ensure that `map` and `unmap` will be called on the same thread this makes the `Drop` solution much more appropriate indeed. I guess you could do that for DX11 only and leave OpenGL as-is. Although this might be bad for consistency, so OpenGL could do the same, but then should the persistent mappings do the same too, and be flushed on `Drop` ?

**Comment by snuk182** [comment]
I definitely don't plan to change a thing in GL, unless I'm asked to change the general API. Will start with the existing approach with `ensure_(un)mapped` and see what will happen.

**Comment by snuk182** [comment]
https://github.com/snuk182/gfx/commit/f57e94ed2404600ac339775a12811fbfd171060f

**Comment by Bastacyclop** [comment]
@snuk182 Is `Device` or `Deferred` used by default ? Seems like you did not call `before_submit` in the `Deferred` submit.

**Comment by snuk182** [comment]
Thanks @Bastacyclop , now the instancing example works 😃 
However it looks like the API should be rethinked again as DX allows only dynamic buffers being mappable, with write access only. With having both Mappable and Dynamic this means the GL version of Dynamic is sorta useless.

**Comment by Bastacyclop** [comment]
The plan was to use Dynamic buffers (with gfx terms, this is not the same as DX dynamic buffers) with `update_buffer` calls. While Mappable buffers should be ... mappable :p. I personnally don't see any contradiction in using a DX dynamic buffer to implement a gfx Mappable buffer.
I think it would be nice to document the fact that Mappable read accesses are not supported by the DX11 backend though (in the backend README ?).
