### ISSUE TITLE
CI test SDL window

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1106]
Was disabled with #1091 due to incompatibility with container based CI. We might at least try to test it with AppVeyor, or find a way to disable sudo requirement for SDL2 on Travis.

**Comment by icefoxen** [comment]
With sudo access it's fairly easy to build SDL2 on Travis, if that's something you're willing to consider.  See https://github.com/ggez/ggez/blob/master/.travis.yml for an example.

**Comment by kvark** [comment]
We used to test it with `sudo`, and we removed that test when we got rid of `sudo` in order to make the builds faster. This bug is about finding a way to test SDL without `sudo`.

**Comment by lxnt** [comment]
https://github.com/gfx-rs/gfx/pull/1190 fixes that, but depends on PPA urls not changing. Since they didn't in last three years I guess this will work until Travis rolls out Trusty containers.

**Comment by GabrielMajeri** [comment]
Does this issue still exist after the latest `gfx_hal` changes? If so, what would be left to work on it?
