### ISSUE TITLE
Bitshifting overflow while loading texture

### ISSUE THREAD

**Issue by mechaxl** [gfx-rs/gfx#1115]
I get this error while trying to load a texture:

    thread 'main' panicked at 'attempt to shift right with overflow', /gfx_core-0.4.0/src/tex.rs:205

It looks like it's coming from this line:

https://github.com/gfx-rs/gfx/blob/master/src/core/src/texture.rs#L272

Specifically, the `level` argument gets set to 16 at some point, and `w`/`h`/`d` are `u16`, which triggers a bitshifting overflow.

What's odd is that this only happens for debug mode with `cargo run`. Using `cargo run --release` makes everything work just fine. Doing some debugging showed that in release mode, `level` is always 0.

This is on Mac OSX with the OpenGL backend.

**Comment by kvark** [comment]
Thanks for the report!
This one is simple. We need to check if `level` is higher or equal than the bit size of `Size` type and treat it specifically in order to avoid that bitshift.

**Comment by kvark** [comment]
Fixed in `gfx_core-0.5.1`
