### ISSUE TITLE
Make API elegant

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1124]
Follow this link and see how our basic API building blocks can be improved based on the guidelines:
https://scribbles.pascalhertleif.de/elegant-apis-in-rust.html

We got *some* stuff right:
  - no strings
  - module full of constants
  - some of the `From`/`Into`
  - “de-generization” technique to address the compile times (yay!)
  - the `Ext` extension traits

But there is still a lot more to take care of. And even though polishing the API is a bit too early until it's stabilized, it would be great to have someone looking into it now.

**Comment by Bastacyclop** [comment]
I guess it is related to #1036.

**Comment by kvark** [comment]
Not a goal any more. Could make sense for wgpu-rs, but should be filed separately.
