### ISSUE TITLE
Travis is green with errors

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1127]
Travis is [green with errors](https://travis-ci.org/gfx-rs/gfx/jobs/190336743#L493). I think this is because of the `;` command chaining in [.travis.yml](https://github.com/gfx-rs/gfx/blob/14706a41c0f3c2b2800a67bedf1118bbcae91ee2/.travis.yml#L51) ?

**Comment by kvark** [comment]
Not seeing any errors any more, and #1185 has landed, closing.
