### ISSUE TITLE
Rerandomize instancing example data on event

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1134]
Follow up on #1129

**Comment by GabrielMajeri** [comment]
The `instancing` example doesn't exist anymore, is it still possible to work on this issue?

**Comment by Bastacyclop** [comment]
@GabrielMajeri I guess not, unless you want to work on the `pre-ll` branch (https://github.com/gfx-rs/gfx/tree/pre-ll/examples/instancing). Is it still maintained or used?

**Comment by kvark** [comment]
Used but not maintained, let's close it.
