### ISSUE TITLE
Crash with an empty vertex buffer

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1136]
> if you call `factory.create_vertex_buffer_with_slice(&[], &[] as &[u16])`, `encoder.flush(&mut device)` will panic afterwards
> the panic is 'Error after executing command BindProgram(0): InvalidValue'

**Comment by Anttonii** [comment]
Did some digging around and the problem seems to caused by the fact that the program is attempting to store data into a 0-sized vertex buffer which results in invalid value error.

More information here: https://www.khronos.org/opengl/wiki/GLAPI/glBufferStorage

> GL_INVALID_VALUE is generated if size​ is less than or equal to zero.

**Comment by kvark** [comment]
I'm not convinced that we should support the empty buffers/textures at all.
I think the `Factory` can just return an error for this case.
