### ISSUE TITLE
Use winapi::uuidof()

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1142]
Available in v0.3. cc @retep998

**Comment by retep998** [comment]
@vitvakatu It's not abandoned. It's just waiting for winapi 0.3 to come out. Basically it allows code to wrap COM types in a safer interface because the uuid of the interface is now associated with the type. It's also cleaner than referring to arbitrary constants.

**Comment by vitvakatu** [comment]
@retep998 great! Carry on then, sorry for inconvenience 😄

**Comment by kvark** [comment]
We could use it to replace things like `d3d12::IID_ID3D12CommandSignature`
