### ISSUE TITLE
IndexBuffer does not support mappability

### ISSUE THREAD

**Issue by snuk182** [gfx-rs/gfx#1145]
OpenGL, gfx-0.14.
https://github.com/snuk182/nuklear-backend-gfx
https://github.com/snuk182/nuklear-test/tree/gfx0.13
If we use Upload buffer to stream index data into, it is not unmapped before actual draw calls, which results in a crash:
`thread 'main' panicked at 'Error InvalidOperation executing command: DrawIndexed(4, 5123, RawOffset(0x0), 174, 0, None)', C:\Users\plyhuns\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.13.0\src\lib.rs:753`

`GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to an enabled array or the element array and the buffer object's data store is currently mapped.`

This is because only PSO-data-based buffers go through the data binding mechanism which serves all the `ensure_(un)mapped` calls. Should adapt this to the `IndexBuffer` from a `Slice` as well.

Also we cannot override this by putting IndexBuffer into a pipe:
> the trait bound `gfx::IndexBuffer<u16>: gfx::pso::DataLink<'a>` is not satisfied [E0277]

**Comment by Bastacyclop** [comment]
Right, maybe this can be done during [encoding](https://github.com/gfx-rs/gfx/blob/1690f20fa89e182f83219adca90eaa0e8ef17913/src/render/src/encoder.rs#L315) ? Otherwise could be part of #1058.

**Comment by snuk182** [comment]
AFAIK in order to use generalized mapping stuff the buffer should still have some PSO-related information , like `AccessInfo`, so encoder itself hardly helps.

**Comment by Bastacyclop** [comment]
The encoder [owns](https://github.com/gfx-rs/gfx/blob/1690f20fa89e182f83219adca90eaa0e8ef17913/src/render/src/encoder.rs#L147) `AccessInfo`, the PSOs are simply filling it. I already used this for [buffer copies](https://github.com/gfx-rs/gfx/blob/1690f20fa89e182f83219adca90eaa0e8ef17913/src/render/src/encoder.rs#L217) who are not part of any PSO. Maybe `AccessInfo` should be extracted from the pso module into the encoder module for example.

**Comment by snuk182** [comment]
Makes sense. However then if https://github.com/gfx-rs/gfx/issues/1058 comes real, the encoder code fixing current ticket (if any) should be removed.

**Comment by kvark** [comment]
Thanks for the report @snuk182 !
FYI, #1058 is not something that I'm 100% convinced we should be doing, it's open for discussion.
