### ISSUE TITLE
How to define a pub pipeline with gfx_defines?

### ISSUE THREAD

**Issue by FlyingPhil** [gfx-rs/gfx#1148]
Suppose we have the following code:
``` rust
gfx_defines!{  
    vertex Vertex {  
        pos: [f32; 2] = "a_Pos",  
        color: [f32; 3] = "a_Color",  
    }  
    pipeline pipe {  
        vbuf: gfx::VertexBuffer<Vertex> = (),  
        out: gfx::RenderTarget<gfx::format::Rgba8> = "Target0",  
    }  
}
```

Is it possible to define Vertex and pipe as public types to use in functions in other files/modules?

**Comment by Bastacyclop** [comment]
@FlyingPhil They should be public already ?

**Comment by FlyingPhil** [comment]
@Bastacyclop Ohhh.. One should not trust the rust/atom autocomplete.. I'm sorry for the inconvenience :smile:

**Comment by Bastacyclop** [comment]
no problem :)
