### ISSUE TITLE
Add `Factory::create_texture_dynamic_u8`

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#1155]
Example: https://github.com/PistonDevelopers/gfx_texture/pull/94/files#diff-b4aea3e418ccdb71239b96952d9cddb6R136

An easy function creating a texture for dynamic usage.

**Comment by kvark** [comment]
Why do you want a dynamic `u8` texture? My understanding is - the `_u8` suffix was added just to support texture loading from raw data. What is the use-case of loading a dynamic texture from disk?

**Comment by bvssvni** [comment]
To update a texture from an `RgbaImage` (it derefs to `&[u8]`).

**Comment by kvark** [comment]
Ah right, hmm.

**Comment by Bastacyclop** [comment]
Using a `Data` texture and an `Upload` for staging seems more appropriate for this use-case. However texture staging is not implemented yet.

**Comment by GabrielMajeri** [comment]
I think this issue can be closed. For those using `wgpu-rs`, equivalent functionality is already implemented.
