### ISSUE TITLE
Metal shader libraries

### ISSUE THREAD

**Issue by JohnColanduoni** [gfx-rs/gfx#1168]
Metal can load shaders at runtime in one of two formats: shader source or precompiled libraries (.metallib). Either way an MTLLibrary object is created, which is able to expose multiple functions by name. 

Because core only allows construction of VertexShader/PixelShader structs though a single method in the Factory trait, the Metal backend can only load shaders from source, and requires the shader function to have a specific name (vert for vertex, frag for fragment). This forces you to have at most one vertex and one fragment shader in each file, and even then the shader ends up being compiled twice at runtime.

I'm happy to do the work for this, but unfortunately this change cannot be entirely confined to the Metal backend because the VertexShader/PixelShader structures' internals are private. Would it be acceptable to make them public, or at least provide a doc(hidden) function to construct them inside the backend?

**Comment by kvark** [comment]
One option here is to have some methods on `gfx_device_metal::Factory` to create shaders from precompiled libraries and/or specify the entry points. Either way, I can see how you'd need the VertexShader/PixelShader constructors exposed to the backends, so it is acceptable.
