### ISSUE TITLE
Z-buffer fighting on some Android devices

### ISSUE THREAD

**Issue by shmutalov** [gfx-rs/gfx#1188]
I have a Z-buffer fighting issue on my android device with following project:
https://github.com/ozkriff/zoc

I am building andorid app with `cargo apk`

+ Tried to change depth buffer size from 8 to 24 bits, no success:
+ Tried to change zNear and zFar values, no success: https://github.com/ozkriff/zoc/blob/11f04354e/src/camera.rs#L19-L20

Fog position: https://github.com/ozkriff/zoc/blob/11f04354e/src/tactical_screen.rs#L366

Fog offset `0.02`:

![Screenshot 1](http://i.imgur.com/h6a3YQI.png)

Fog offset `0.5`:

![Screenshot 2](http://i.imgur.com/1YR5Vta.png)

**Device:** Letv Le 1s, Andoid 6.0, Opengl ES 3.1, MTK6795

**Pixel format:**
```rust
fn new_window_builder() -> glutin::WindowBuilder<'static> {
    let gl_version = GlRequest::GlThenGles {
        opengles_version: (3, 1),
        opengl_version: (2, 1),
    };
    glutin::WindowBuilder::new()
        .with_title("Zone of Control".to_string())
        .with_pixel_format(24, 8)
	.with_depth_buffer(24)
	.with_stencil_buffer(8)
        .with_gl(gl_version)
}

...

let (window, device, mut factory, main_color, main_depth)
            = gfx_glutin::init(new_window_builder());
			
println!("{:?}", window.get_pixel_format());
```

**Result:**
```
PixelFormat { 
  hardware_accelerated: true, 
  color_bits: 24, 
  alpha_bits: 8, 
  depth_bits: 24, 
  stencil_bits: 8, 
  stereoscopy: false, 
  double_buffer: true, 
  multisampling: None, srgb: false 
}
```

Prebuilt apk for test: https://drive.google.com/open?id=0B2AoR3-Umz1PNC1jcXM3M29MOEU

**Comment by kvark** [comment]
Thanks for filing the issue and collecting all that information!
It would be most useful to have some sort of a GL capture from that phone, either with `apitrace` or Android's native tools.

We could also try out some more experiments to see where the problem is:
  - force the depth function to always pass
  - use [depth offset](https://docs.rs/gfx/0.14.0/gfx/state/struct.Offset.html) instead of modifying the world Z

**Comment by shmutalov** [comment]
Issue was fixed by changing `mediump` shader precision to `highp`:

https://github.com/ozkriff/zoc_assets/blob/master/shader/pre_gles.glsl#L3-L4

```glsl
precision mediump float;
precision mediump int;
```

To:

```glsl
precision highp float;
precision highp int;
```

Results:
![Screenshot 1](http://i.imgur.com/oOD6Yhq.jpg)

![Screenshot 2](http://i.imgur.com/tUCu3Oc.jpg)
