### ISSUE TITLE
Window creation examples for SDL and GLFW

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1199]
> Basic examples can be found at https://github.com/icefoxen/gfx/tree/master/examples/triangle-glfw and https://github.com/icefoxen/gfx/tree/master/examples/triangle-sdl

cc @icefoxen

**Comment by icefoxen** [comment]
See, now I'm going to have to eat my words about "keeping those up to date is trivial", since they're not up to date...  XD

**Comment by kellpossible** [comment]
and an example with glutin too?

**Comment by alexheretic** [comment]
#1271 provides an sdl window example, run with `(cd src/window/sdl && cargo run --example window)`

**Comment by kvark** [comment]
Fixed by #1258 and #1271
Thanks everyone!
