### ISSUE TITLE
Link to arcsynthesis on OpenGL state machine is dead

### ISSUE THREAD

**Issue by burtonageo** [gfx-rs/gfx#1213]
The [link](http://www.arcsynthesis.org/gltut/Basics/Intro%20What%20is%20OpenGL.html#d0e887) on the Readme about binding and unbinding objects leads to a parked domain website.

**Comment by ama0** [comment]
I think you can close this issue, @kvark. #1240 fixed it.

**Comment by kvark** [comment]
Thanks @ama0 !
