### ISSUE TITLE
[ll] Resource destruction

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1216]
*Part of the lower level core abstraction rewrite #1102*

## Motivation
We want to minimize API overhead for our core library. At the moment we track resources via reference counted handles in `core`. In contrast, `corell` API directly works with the raw `R::*` structs. Some backends (e.g Vulkan) have explicit `vkDestroy*` functions, which require an handle to the device.
d3d11/12 solves this by internal reference counting.

## 1st Approach (Explicit destruction)
In order to destruct resources the API will expose `destroy_*` functions, which need to be explicitly called.

**Pros**: Doesn't require to store the device handle in each resource.
**Cons**: Requires the user to explicitly take track of the it's resources and avoid duplicated destruction.

## 2nd Approach (Lifetime wrapper)
We use wrapper structs `ResourceObject<'a, R>` for the resources `R::*` to have an associated lifetime. Resources now can't outlive the creating factory.

**Pros**: We only need to store the 'bare' device handle in the resources for destruction.
**Cons**: Requires all Factory methods to use `&self` instead of `&mut self`, else we won't be able to reborrow the factory for creating new resources.

## 3rd Approach (RAII)
The most intuitive way for user would be RAII, resources will be destructed once the handle drops.

**Pros**: Safe and easy to use
**Cons**: Requires to keep track of the underlying device handle via reference counting to avoid the resource outliving the device.

cc @kvark

**Comment by kvark** [comment]
I'm strongly in favour of 1st approach - explicit destruction. One of the core benefits of the new core API that I'm looking to get is zero overhead for the most demanding applications.

Not sure how the 2nd will solve the problem, perhaps you need to explain it more.

**Comment by msiglreith** [comment]
Sounds reasonable.
Regarding the 2nd approach I tried to create a small code snippet to show the underlying idea:
https://is.gd/c6zdFR
Motivation for this approach was to avoid the reference counting costs and try to couple resource lifetime to the factory/device lifetime.

**Comment by minecrawler** [comment]
I do not like the first one, because it is Rust we use and Rust takes care of memory stuff for us. It just feels like a step back to C/C++ (though gfx is abstracting over something which was initially defined with those languages in mind). In my opinion, the third approach would be the correct one to guarantee lifetimes and memory safety on the user side.

**Comment by Bastacyclop** [comment]
@minecrawler The third approach will still be used for the higher level `gfx` package. The whole point of this lower level `gfx_core` API is to be able to bypass the overhead of the higher level one, so the third approach would be a step back and a mistake in my opinion.
I find the second approach interesting but it seems hard to do correctly so that it does not induce any overhead elsewhere and remains flexible enough.
Here is an attempt to make it work with `&mut self` Factory methods: https://is.gd/JvmPau

**Comment by DaseinPhaos** [comment]
+1 for lifetime wrapper. It might be hard to get right but I think once done correctly it can surely outperform the alternatives.

@msiglreith 
> Cons: Requires all Factory methods to use &self instead of &mut self, else we won't be able to reborrow the factory for creating new resources.

If we take the wrapper approach, why should any methods of `Factory` be marked as `&mut self` anyway?

**Comment by kvark** [comment]
@DaseinPhaos wouldn't it prevent moving the resource handles to different threads? That would be a show stopper.

**Comment by msiglreith** [comment]
> If we take the wrapper approach, why should any methods of Factory be marked as &mut self anyway?

Some backends need to change some inner fields atm (e.g current d3d11 backend), so I assumed it might be nicer to use mutable borrow here.

The lifetime approach requires scoped threads afaik.

**Comment by JohnColanduoni** [comment]
A small suggestion: why not add a Drop implementation for the resource handles that merely logs an error, and then prevent the destructor from running if you call the appropriate destory_* function (via mem::forget)? This way if you leak resources it at least won't be silent.

**Comment by msiglreith** [comment]
@JohnColanduoni Sounds reasonable, good idea! I added it on my TODO list for the ll branch. But I won't tackle it until the factory changes.

**Comment by kvark** [comment]
@JohnColanduoni that's what I call "poor man's linear typing" ;)

**Comment by msiglreith** [comment]
We settled with explicit destructors for vulkan portability sake.
The mentioned error logging on `Drop` can be considered for the validation layer #1426
