### ISSUE TITLE
[ll] [RFC] Resource binding

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1219]
_Part of the lower level core abstraction rewrite #1102_

Resource Binding
====================

Pipelines require access to resources in the shader stages. Each pipeline has an interface/layout for the different resources.
Resources can be constant buffers, textures, samplers, push constants, ...

# Overview (bindless APIs)
## Vulkan
In Vulkan resources are grouped together as `DescriptorSet`s, which define the layout of the pipeline. A descriptor is a lightweight handle to an buffer or image view. Views allow shaders to operate on the underlying objects and give access to a subrange of their memory with associated meta information.
To give a shader access to a resource, a view for the resource needs to be created first and a descriptor set matching the pipeline layout.
Descriptors are then written into the set, containing the view and the descriptor type (access type for the shader).

References:
https://developer.nvidia.com/vulkan-shader-resource-binding
https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html

## Directx 12
Pipelines have a root signature, consisting of references to descriptor tables (range in a descriptor heap), push constants and inline resources. In d3d12 we can differ between CPU and GPU descriptors. CPU descriptors are returned on view creation. GPU descriptors have to be allocated on a descriptor heap and CPU descriptors can be written into GPU descriptors. There can only be bound 1 Srv/Cbv/Uav descriptor heap and 1 sampler heap at the same time.

References:
https://msdn.microsoft.com/en-us/library/windows/desktop/dn899206(v=vs.85).aspx
https://software.intel.com/en-us/articles/introduction-to-resource-binding-in-microsoft-directx-12

# Draft proposal
The descriptor table approach from d3d12 is powerful and quite straightforward, but hard and inefficient to emulate via descriptor sets. Therefore we will have to follow vulkan's concept of descriptor sets here.

Both APIs share the view concept, which we can build upon. d3d12 stores views inside CPU descriptor heaps (to be symmetric to GPU descriptors..), but we can hide them internally in the `Factory`.
Our current factory API in core fits the model quite well and we can take it over.

Root Signatures are bound to 64*4bytes at maximum. (Descriptor tables: 4bytes, Root Constants: 4bytes, Root Descriptor: 4bytes, static sampler: 0)

Still, an open topic is descriptor creation and organization in heaps/pool.
 - As mentioned above, d3d12 only allows two descriptor heaps bound. Changing a heap inside a command buffer requires a flush, but across command buffer boundaries it's basically free (verify?).
 - DescriptorPools for set creation can't be accessed in parallel (vulkan)

Therefore, the current approach would be differ between 2 kinds of descriptor sets (srv_cbv_uav and samplers) to support d3d12. Descriptors are allocated from heaps by creating non-thread safe set allocators from an heap. Restrict resource binding to only allow descriptor sets from one heap of each kind.

# Draft API
```Rust
pub struct Resources {
    type ShaderResourceView;
    type ConstantBufferView;
    type UnorderedAccessView;

    type DescriptorHeap;
    type DescriptorSetPool;
    type DescriptorSet;
}

pub enum DescriptorHeapType {
    SrvCbvUav,
    Sampler,
}

pub trait Factory<R> {
    fn view_buffer_as_shader_resource(&mut self) -> R::ShaderResourceView;
    fn view_image_as_shader_resource(&mut self) -> R::ShaderResourceView;
    ...

    fn create_descriptor_heap(&mut self, ty: DescriptorHeapType, size: usize) -> R::DescriptorHeap;
    fn create_descriptor_set_allocator(&mut self, heap: &R::DescriptorHeap, max_sets: usize, descriptor_pools: &[PoolDesc]) -> R::DescriptorSetPool;
    fn create_descriptor_sets(&mut self, set_allocator: &mut R::DescriptorSetPool, set_layouts: &[DescriptorSetLayout]) -> Vec<R::DescriptorSet>;

    (missing writes and copies)
}

pub trait CommandBuffer<R> {
    fn bind_descriptor_heaps(srv_cbv_uav: Option<&R::DescriptorHeap>, samplers: Option<&R::DescriptorHeap>);
    fn bind_descriptor_sets(sets: &[&R::DescriptorSet]);
}
```

## Descriptor types
Vulkan associates the resource binding points with an usage type, matching the shader interface.
We probably need to specify them in the pipeline layout.

 - Sampler
 - Combined Image Sampler
 - Sampled Image
 - Storage Image
 - Uniform Texel Buffer (read-only)
 - Storage Texel Buffer (write, atomics)
 - Constant Buffer (read-only) (vk: Uniform Buffer)
 - Storage Buffer (read-write)
 - Uniform Buffer Dynamic
 - Storage Buffer Dynamic
 - Input Attachment

# Drawbacks
Becomes quite verbose for the user, especially the difference between Heaps and SetAllocators. And the reasoning to do so might not be totally clear.

# Unresolved questions
 - Compatibility with Metal and other backends
 - Handling different resource binding tiers (tier 1 == legacy APIs?)

**Comment by kvark** [comment]
Thanks for doing all the research and making this RFC! It really sets an example to all of us, great job! I generally agree with the direction you set, just trying to clarify some points below:

> There can only be bound 1 Srv/Cbv/Uav descriptor heap and 1 sampler heap at the same time.

That's new to me. Where does it say you can only have a single descriptor heap for each of this group? I can only see the limitation that samplers can't be mixed with other stuff.

> `fn create_descriptor_set_allocator`

Any reason this is `_allocator` and not a `_pool`? Looks a bit inconsistent.

> Becomes quite verbose for the user, especially the difference between Heaps and SetAllocators. And the reasoning to do so might not be totally clear.

Yes, and I hope this is fine, given that `gfx_render` is supposed to hide the complexity and make it safer to use.

> Compatibility with Metal and other backends

It appears to me that backends without explicit descriptor sets are going to be fairly easy to emulate, but I haven't tried doing that yet. At least that's our assumption for the Obsidian API.

**Comment by msiglreith** [comment]
>That's new to me. Where does it say you can only have a single descriptor heap for each of this group? I can only see the limitation that samplers can't be mixed with other stuff.

According to the MSDN documentation (first section) https://msdn.microsoft.com/de-de/library/windows/desktop/dn899210(v=vs.85).aspx:
> When descriptor heaps are set (using ID3D12GraphicsCommandList::SetDescriptorHeaps), all the heaps being used are set in a single call (and all previously set heaps are unset by the call). At most one heap of each type listed above can be set in the call.

I remember reading about this restriction multiple times.


> Any reason this is _allocator and not a _pool? Looks a bit inconsistent.

True, we have CommandPools so we should stick to the pool term!

Thanks for reviewing and providing great feedback!

**Comment by kvark** [comment]
@msiglreith thanks for the link!
I see now where my misunderstanding comes from. We do indeed have to have only 2 different active heaps, but I was thinking about descriptor sets. For those, the only limitation is basically that you can't have samplers mixed up with anything else, given that this would require the set to use both heaps at once.

**Comment by msiglreith** [comment]
Feedback after first implementation steps:

-  `DescriptorSetLayout`s are now backend resources instead of plain structs. They are also passed on pipeline layout creation.
- `DescriptorSetPool` will allocate a contiguous piece of descriptors from the heap. Users will be responsible for avoiding overlaps. (Easier to implement for dx12) The range is described by an offset and the number of descriptor defined in the descriptor pools.
```Rust
fn create_descriptor_set_pool(&mut self, heap: &native::DescriptorHeap, max_sets: usize, offset: usize, descriptor_pools: &[f::DescriptorPoolDesc]) -> native::DescriptorSetPool;
```

- I'm thinking of splitting `ShaderResourceView` and `UnorderedAccessView` into `ShaderResourceImageView`/`ShaderResourceBufferView` and `UnorderedAccessImageView`/`UnorderedAccessBufferView`.  Vulkan seems to care more about for which type of resource we create a view (buffer or image), whereas d3d12 differs between read-only vs read-write. Feedback regarding this is highly appreciated!

**Comment by msiglreith** [comment]
I think we resolved the issue by focusing on vulkan portability.
Individual backend specific bissues which might come up should be addressed in separate issues.
