### ISSUE TITLE
[ll] Vulkan portable implementation FFI

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1226]
If #1102 brings us to a Vulkan-like API of the `gfx_core`, there is one interesting option to explore - create a C FFI layer that with Vulkan-like header (or better - an actual one from upstream) that would work with our core library.

This would allow any application targeting Vulkan to work on a variety of platforms, and will be solidly backed by our Rust implementation. Essentially, the [Angle](https://github.com/google/angle) of the new era, taking on MoltenVK at the same time. The future has many use of such a layer ;)

Another absolutely crazy extension of this path is a possible use of `vulkano` as a high-level layer instead of `gfx_render`. It can just be an alternative, but convergence is great!

**Comment by Bastacyclop** [comment]
Wouldn't this need shader support too ?

**Comment by kvark** [comment]
Yes, via existing SPIRV-Cross library

**Comment by kvark** [comment]
It is happening in https://github.com/kvark/portability
