### ISSUE TITLE
Serde integration

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1229]
Example:
```rust
#[cfg_attrib(feature="serialize", derive(Serialize, Deserialize))]
```
cc @ebkalderon @msiglreith

**Comment by ebkalderon** [comment]
@kvark I think you meant `#[cfg_attr(...)]`. 😉 I am currently preparing two pull requests, one for `draw_state` and one for `gfx_core`.

**Comment by ebkalderon** [comment]
Okay, took a bit longer than I expected, but the PR for draw_state is now ready! (gfx-rs/draw_state#42)
