### ISSUE TITLE
[GL] Persistent mapping warning

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1237]
> apitrace: warning: glBufferStorage: MAP_NOTIFY_EXPLICIT_BIT_VMWX set w/o MAP_PERSISTENT_BIT

**Comment by Bastacyclop** [comment]
@kvark I [made some prints](https://github.com/gfx-rs/gfx/compare/master...Bastacyclop:mapwarn) after looking at [some](https://github.com/apitrace/apitrace/blob/b024c85d2487d2dc48b0713cc980b2011d92d110/wrappers/gltrace.py#L609) apitrace [stuff](https://github.com/apitrace/apitrace/blob/b024c85d2487d2dc48b0713cc980b2011d92d110/docs/VMWX_map_buffer_debug.txt#L48), I don't think that we are setting `MAP_NOTIFY_EXPLICIT_BIT_VMWX` anywhere so this might be an apitrace [bug](https://github.com/apitrace/apitrace/commit/34d047c48c89aa5f7310e48f3ec326c3ff40598c).

**Comment by kvark** [comment]
Aha, great, thanks for investigating!
