### ISSUE TITLE
Glutin updated to 0.8

### ISSUE THREAD

**Issue by keringar** [gfx-rs/gfx#1247]
Glutin has updated to 0.8 about 16 hours ago, and it changes how windows are created. Instead of each window controlling it's own event loop, you now create a separate event loop and pass it into the window when it's first created. It apparently fixes some issues on macos, ( https://github.com/tomaka/winit/pull/132 ), so we should try and update the glutin backend soonish. See https://github.com/tomaka/winit/pull/126 for additional information

**Comment by ebkalderon** [comment]
@keringar Sweet, I've been waiting for `glutin` to adopt the new `winit` API for a while now. Nice to hear it's finally landed!

**Comment by ishitatsuyuki** [comment]
We will need to update all examples, but the old fashion `poll_events()` method exists on `EventLoop` quite similar to before.

**Comment by kvark** [comment]
This has just been done in #1251, closing
