### ISSUE TITLE
Use cargo workspaces

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1248]
https://doc.rust-lang.org/beta/book/second-edition/ch14-03-cargo-workspaces.html

Benefits:
  - more idiomatic
  - re-uses the same "target" folder - faster publishing, cleaner
  - magnificent `cargo test --all` to test everything at once

TODO:
  - add `[workspace]` to the root cargo toml
  - adjust `.gitignore` to only care about the `/target` (as opposed to any `target`)
  - simplify Travis script to use `test --all`

**Comment by torkleyy** [comment]
Plus a `workspace` key is needed in every crate's `Cargo.toml`.

I would also suggest converting `gfx_app` into a workspace member, which is clearer IMO.

**Comment by kvark** [comment]
@torkleyy right. With an ability to build everything in a workspace, we no longer strictly need a project like `gfx_app` to depend on everything. It would be great to move it out of root, to avoid confusion.

**Comment by ama0** [comment]
I'm currently looking into it. Don't hold your breath though. :)

> Plus a `workspace` key is needed in every crate's `Cargo.toml`.

If I understand it correctly, this isn't the case. See:  [1525-cargo-workspace.md#implicit-relations](https://github.com/rust-lang/rfcs/blob/master/text/1525-cargo-workspace.md#implicit-relations)
>The package.workspace can be omitted if it would only contain ../ (or some repetition of it). That is, if the root of a workspace is hierarchically the first Cargo.toml with [workspace] above a crate in the filesystem, then that crate can omit the package.workspace key.

Another thing that may become an issue for people using [cargo-graph](https://github.com/kbknapp/cargo-graph) is an incorrect `[root]` in `Cargo.lock`. See [Incorrect [root] in Cargo.lock when using workspaces #3203](https://github.com/rust-lang/cargo/issues/3203)
But this shouldn't affect gfx-rs in any way.

**Comment by torkleyy** [comment]
@ama0 Oops, sorry for the useless note then. Thought it would be necessary, thanks for pointing this out.

**Comment by ama0** [comment]
> TODO:
>
> *  adjust .gitignore to only care about the /target (as opposed to any target)

This conflicts with the current goal to have simple window examples in all window providers. `window_sdl` currently has one and running this example from `/src/window/sdl` creates a target folder _in_ `/src/window/sdl`. Therefore I think it would be better to leave the current "ignore all target folders" entry in `.gitignore`.

**Comment by xtian** [comment]
@kvark I think this can be closed since it was addressed by #1417

**Comment by kvark** [comment]
@xtian indeed!
