### ISSUE TITLE
Design the high-level drawing layer above gfx-rs

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#125]
As we are getting settled with the scope (see #108), we should start thinking about the layer above gfx-rs. I hope to see it as a separate projects in our gfx-rs organization, where this issue is the ideas hub for the initial design.

Here is what I expect this layer to do:
- Define a concept of `Material`. For starters, we can just use `gfx::ShaderBundle` for it.
- Define a spatial system: world space, connections, and hierarchies. This would probably lock it to a particular math library (e.g. [cgmath-rs](https://github.com/bjz/cgmath-rs))
- Define a concept of `DrawList`
- Automatically [re-order](http://realtimecollisiondetection.net/blog/?p=86) calls inside each draw list

**Comment by kvark** [comment]
Nominating [gfx_scene](https://github.com/kvark/gfx_scene) for this role.

**Comment by bvssvni** [comment]
I've looked over the gfx_scene source and it looks promising.

**Comment by kvark** [comment]
The ecosystem has been expanded to include [gfx_pipeline](https://github.com/kvark/gfx_pipeline), `claymore_scene`, and `claymore_load` (sub-crates of [claymore](https://github.com/kvark/claymore)). It is now as high as we could ever be:
```rust
let pipeline = gfx_pipeline::forward::Pipeline::new(...);
let scene = claymore_load::scene(...);
...
pipeline.render(&scene, ...);
```

Please evaluate these libraries at some time to see if they can fit the role. I'm pretty much done with the general architecture, so I'll be focusing more on the game itself, hopefully.

**Comment by kvark** [comment]
[gfx_scene](https://github.com/gfx-rs/gfx_scene) has been transferred

**Comment by kvark** [comment]
Closing because of the following great libraries:
  - [Amethyst](https://github.com/amethyst/amethyst)
  - [GGEZ](https://github.com/ggez/ggez)
  - [ThreeRS](https://github.com/kvark/three-rs)
