### ISSUE TITLE
Release tracking

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1261]
We need a solid way to:
  1. Track what git revisions are getting published
  2. Be able to patch older versions (at least the last one).

The problem comes from the fact we have multiple crates in the same repo. It would be great to inspect (or ask around?) other repositories that followed the same structure to see how they approach releases.

Current solution is rather weak. We keep development in the `master` branch and for every minor release we keep a separate branch (e.g. `v0.15`). Problem is - "release" here is highly ambiguous. It's typical to update `gfx_core`, which forces all dependencies to have version bumps, and the version we take for the branch is from `gfx` itself. Now, how do we handle the case when the core is unchanged and just one of the crates got bumped? E.g. recently we published the new `gfx_window_glutin`, and now I'm considering updating `gfx` itself without touching the core.

I know that servo libraries get a habit of assigning tags to published versions. The git tags become Github releases automatically. It doesn't seem right for us to follow the suit, since we can release various sub-parts and not necessarily update the whole thing...

Ideas? Proposals?

**Comment by minecrawler** [comment]
Ideas:

- Use GitFlow: Every push to master should result in a new version (tag)
- Put different projects into different repositories; GitHub wasn't made for the kind of project management you try to use. You can use GitHub Projects to track milestones and issues across repositories
- Use git submodules to pull in other repositories locally

**Comment by OvermindDL1** [comment]
Yeah I'd say different git project for each different published package myself.  Or GitFlow otherwise.

**Comment by GabrielMajeri** [comment]
How would this issue change taking into consideration the new `gfx_hal`-based architecture? I'm guessing the version of the back ends is closely tied to HAL's version.

**Comment by kvark** [comment]
That's what we are doing, yes. We are also trying *not to* release a breaking version of a backend outside of gfx-hal upgrade cycle. I think that's working so far, let's close this.
