### ISSUE TITLE
Can't run Cube example on my device, requesting a little help.

### ISSUE THREAD

**Issue by bjadamson** [gfx-rs/gfx#1275]
Hi there!

I tried loading the GFX cube example code on my machine today, but I'm unable to get past a panic() on my machine. The panic is from this line here:

https://github.com/gfx-rs/gfx/blob/master/src/window/glutin/src/lib.rs#L102-L113

The complete backtrace:

> benjamin@benjamin-HP-Compaq-8200-Elite-SFF-PC  ~/github/cserver   master  RUST_BACKTRACE=1 gdb target/debug/cserver
> GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
> Copyright (C) 2014 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from target/debug/cserver...done.
> warning: Missing auto-load scripts referenced in section .debug_gdb_scripts
> of file /home/benjamin/github/cserver/target/debug/cserver
> Use `info auto-load python-scripts [REGEXP]' to list them.
> (gdb) r
> Starting program: /home/benjamin/github/cserver/target/debug/cserver 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', /checkout/src/libcore/result.rs:859
> stack backtrace:
>    0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
>              at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1: std::sys_common::backtrace::_print
>              at /checkout/src/libstd/sys_common/backtrace.rs:71
>    2: std::panicking::default_hook::{{closure}}
>              at /checkout/src/libstd/sys_common/backtrace.rs:60
>              at /checkout/src/libstd/panicking.rs:355
>    3: std::panicking::default_hook
>              at /checkout/src/libstd/panicking.rs:371
>    4: std::panicking::rust_panic_with_hook
>              at /checkout/src/libstd/panicking.rs:549
>    5: std::panicking::begin_panic
>              at /checkout/src/libstd/panicking.rs:511
>    6: std::panicking::begin_panic_fmt
>              at /checkout/src/libstd/panicking.rs:495
>    7: rust_begin_unwind
>              at /checkout/src/libstd/panicking.rs:471
>    8: core::panicking::panic_fmt
>              at /checkout/src/libcore/panicking.rs:69
>    9: core::result::unwrap_failed
>              at /checkout/src/libcore/macros.rs:29
>   10: <core::result::Result<T, E>>::unwrap
>              at /checkout/src/libcore/result.rs:737
>   11: gfx_window_glutin::init_raw
>              at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.15.0/src/lib.rs:101
>   12: gfx_window_glutin::init
>              at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_window_glutin-0.15.0/src/lib.rs:53
>   13: gfx_app::launch_gl3
>              at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_app-0.5.0/src/lib.rs:125
>   14: gfx_app::Application::launch_default
>              at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_app-0.5.0/src/lib.rs:365
>   15: gfx_app::Application::launch_simple
>              at /home/benjamin/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_app-0.5.0/src/lib.rs:361
>   16: cserver::main
>              at ./src/main.rs:158
>   17: std::panicking::try::do_call
>              at /checkout/src/libstd/panicking.rs:454
>   18: __rust_maybe_catch_panic
>              at /checkout/src/libpanic_unwind/lib.rs:98
>   19: std::rt::lang_start
>              at /checkout/src/libstd/panicking.rs:433
>              at /checkout/src/libstd/panic.rs:361
>              at /checkout/src/libstd/rt.rs:57
>   20: main
>   21: __libc_start_main
>   22: <unknown>
> [Inferior 1 (process 15099) exited with code 0145]

I queried my machine for GL support, [the full output can be found here](https://pastebin.com/X6ZvHT1K), but the important bits (I think, still noob to OpenGL) are:

> OpenGL version string: 3.0 Mesa 10.1.3
> OpenGL shading language version string: 1.30

[My C++ project works on this machine](https://github.com/bjadamson/BoomHS), I'm hoping to be able to switch away from C++ because I confused myself at some point in the architecture and I'm hoping Rust can help me from getting into the same situation. The C++ project during compilation prepends this string (R"(#version 300 es)";) to all the shaders [here](https://github.com/bjadamson/BoomHS/blob/release/tools/main_shaderloader.cxx#L88), but I don't think that the GLSL version has anything to do with being unable to create the OpenGL context. I'm not sure yet.

So I'll finally get to my question, do you think it is *correct* to have the unwrap() call where it is, or should a result be propagated up?

Do you have any idea why the opengl context isn't able to be created? From what I can tell from the output above, I believe my machine should be able to support creating an opengl context up to version 3, so I'm unsure why I can't create the context.

How would you go about debugging this further? Thanks in advance!!

**Comment by msiglreith** [comment]
Hey!
All examples (excluding the triangle) are launched with the following opengl context settings
https://github.com/gfx-rs/gfx/blob/master/src/lib.rs#L119-L122
Your system seems to support only GL3.0 and GL3.1, so you could try to adjust the opengl settings for the examples. Another quick check would be running the triangle example which should work without changes imo.

(I would also like to note that `Application` is not required for writing own code using gfx-rs, only for the examples)

**Comment by bjadamson** [comment]
Thank you for your response!

I did indeed try the triangle example upon waking up this morning. It failed, but it should should be possible for me to fix it I think.

`     Running `target/debug/examples/triangle`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Program(Vertex(CompilationFailed("0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES\n")))', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

One thing that surprises me is that I'm getting this error, even when there are 1.20 versions of the shaders. I'll see what changes I can make to try and get it to use the 1.20 version of the shaders. Maybe this expected?

**Comment by GabrielMajeri** [comment]
I'm guessing this issue is amplified now that the GLSL shaders in the examples use `#version 450`.

Are the `gfx_hal` examples intended to work on older OpenGL versions?

**Comment by kvark** [comment]
This is from the old gfx, which we no longer support, closing.

> Are the gfx_hal examples intended to work on older OpenGL versions?

Our target is OpenGL ES 3.0 (and OpenGL desktop 2.1 + extensions)
