### ISSUE TITLE
Tiny typo in docs for IndexBuffer

### ISSUE THREAD

**Issue by ucarion** [gfx-rs/gfx#1283]
In [the docs for `IndexBuffer`](https://docs.rs/gfx/0.16.0/gfx/enum.IndexBuffer.html), there's a part that reads:

> Do note that the `Slice`' start and end restrictions still apply for this variant.

There should be an "s" after the apostrophe. I would make a PR to fix this, but my editor removes trailing whitespace on save, so it's a bit annoying for me to make the minimal diff to fix this.

**Comment by torkleyy** [comment]
Which editor are you using? Anyways, I'll fix in 5 hours.

**Comment by kvark** [comment]
@ucarion please file a PR anyway, if you can
