### ISSUE TITLE
Replace cgmath bindings by `mint`

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1290]
https://github.com/kvark/mint

cc @ebkalderon 

Also need to cleanup the dependencies. I.e. instead of having this in the root Cargo.toml:
```toml
cgmath-types = ["gfx/cgmath-types", "gfx_core/cgmath-types"]
```
We could just have this:
```toml
mint = "gfx/mint"
```
Which would then require "gfx_core/mint" internally.

**Comment by vitvakatu** [comment]
I'm going to do it

**Comment by kvark** [comment]
Hopefully, https://github.com/brendanzab/cgmath/pull/418 is accepted and a new version is published before we publish new gfx-rs, or otherwise Amethyst folks may be a little angry. Also see https://github.com/amethyst/amethyst/issues/236.
