### ISSUE TITLE
[ll] Backend Generics

### ISSUE THREAD

**Issue by JohnColanduoni** [gfx-rs/gfx#1291]
Currently it is pretty difficult to create generics over backends when using corell:

- Neither Adapter nor Backend require that their CommandQueue associated types use the same Resources as them. Adding that constraint is also not simple, because CommandQueue<R=Self::Resources> doesn't immediately propagate to the command buffer associated types so they must be separately constrained.
- RenderPassInlineEncoder and RenderPassSecondaryEncoder's lifetime parameters make their inclusion in any Backend trait very difficult, because you then need to make that Backend trait have 4 lifetime parameters which then infects any trait or structure you try to make generic over the Backend trait.

I think the best way to handle this is to extend the techniques we use for other traits in corell to these:

- Make CommandQueue take Resources as a generic parameter like CommandBuffer does.
- Make RenderPassInlineEncoder/RenderPassSecondaryEncoder structs with references to the command buffer, RenderPass, and FrameBuffer with appropriate lifetimes that contains a backend-specific type inside, to which the structs proxy all of the calls (like Encoder does).

If this sounds good I'd be happy to implement it :smile:

**Comment by msiglreith** [comment]
Highly agree! Noticed this issue also while fiddling with `render`. I have something similar cooking on my experimentale [branch](https://github.com/gfx-rs/gfx/compare/ll...msiglreith:pr_asteria_05) and wanted to do a PR for the `ll` integration branch but couldn't test it on my dektop so far.

My current approach was based on re-introducing the [`Backend`](https://github.com/msiglreith/gfx/blob/pr_asteria_06/src/core/src/lib.rs#L228-L239) trait, which defines the types .
Replacing most of the associated types with a generic `B: Backend` works quite well so far.
How does this sound?

**Comment by JohnColanduoni** [comment]
Yeah that sounds perfect! I'm playing around with turning RenderPassI*Encoder into structs to work around the lifetimes, the rest of the API seems pretty generic-friendly so far.
