### ISSUE TITLE
SDL2 rendering: Error InvalidOperation executing command: BindVao

### ISSUE THREAD

**Issue by rhaps0dy** [gfx-rs/gfx#1319]
Hello,

I am trying to run icefoxen's [Triangle SDL](https://github.com/icefoxen/gfx/blob/master/examples/triangle-sdl/main.rs) example, with minor modifications to match the current release (here is the diff):
``` patch
47c47
<         gfx_window_sdl::init(&mut builder);
---
>         gfx_window_sdl::init::<ColorFormat, DepthFormat>(builder).unwrap();
50,51c50,52
<     let pso = factory.create_pipeline_simple(include_bytes!("shader/triangle_150.glslv"),
<                                 include_bytes!("shader/triangle_150.glslf"),
---
>     let pso = factory
>         .create_pipeline_simple(include_bytes!("shader/triangle_120.glslv"),
>                                 include_bytes!("shader/triangle_120.glslf"),

```

I am using SDL and I changed the shader version to 120 to be able to use GFX in WebGL. However, even when compiling to native (I'm on OS X), I get:

`thread 'main' panicked at 'Error InvalidOperation executing command: BindVao'`

which #1126 is supposed to solve.

Thank you for your help. If you wish maybe I can contribute something back like SDL or WebGL examples once I get this working.

**Comment by kvark** [comment]
Thanks for filing the issue!
I think #1126 is not relevant here.

We are missing a check for VAO support in the GL backend: https://github.com/gfx-rs/gfx/blob/190728a711cb1a0da8a747ea795275b10f9b0d8d/src/backend/gl/src/lib.rs#L516

The backend should have a flag in its private capabilities and check for it, similar to how `self.share.private_caps.frame_buffer_supported` is handled. This is a relatively easy task, if you want to take a stab at it.

**Comment by rhaps0dy** [comment]
There is already one of these flags: `private_caps.array_buffer_supported` corresponds to `GL_ARB_vertex_array_object`. I've been able to remove the error by wrapping the body of `Command::BindVao` with a check for this property being true. However I'm not sure this will create the correct behaviour in all cases. Is it OK to just skipping binding the VAO?

**Comment by kvark** [comment]
Yes, let's do that
