### ISSUE TITLE
Winit version conflict in gfx_window_metal.

### ISSUE THREAD

**Issue by dkushner** [gfx-rs/gfx#1341]
With the following dependencies:

```
winit = "0.6.0"
gfx = "0.16"
gfx_core = "0.7.1"
glutin = "0.8.0"
gfx_device_gl = "0.14.1"
gfx_window_glutin = "0.16.0"
gfx_window_metal = "0.2.0"
```

I get the following errors at compiltion:

```
error[E0308]: mismatched types
  --> src/core/application.rs:47:109
   |
47 |                 let (window, mut device, mut factory, color) = gfx_window_metal::init::<gfx::format::Rgba8>(winit_builder);
   |                                                                                                             ^^^^^^^^^^^^^ expected struct `winit::WindowBuilder`, found a different struct `winit::WindowBuilder`
   |
   = note: expected type `winit::WindowBuilder` (struct `winit::WindowBuilder`)
              found type `winit::WindowBuilder` (struct `winit::WindowBuilder`)
note: Perhaps two different versions of crate `winit` are being used?
  --> src/core/application.rs:47:109
   |
47 |                 let (window, mut device, mut factory, color) = gfx_window_metal::init::<gfx::format::Rgba8>(winit_builder);
   |                                                                                                             ^^^^^^^^^^^^^
```

It looks like `gfx_window_metal` was built against `winit@0.6`. Did a patch version break compatibility or am I screwing up the dependencies somehow?

**Comment by kvark** [comment]
> Did a patch version break compatibility

No, there is no compatibility breakage here from gfx-rs side. It's just some of our windowing backends refer to different `winit` versions from the others.

> am I screwing up the dependencies somehow?

No, you are doing it correctly.

What's missing is another minor bump of `gfx_window_metal` to 0.3.0 so that it depends on `winit`-0.6

**Comment by kvark** [comment]
I can't publish the new version at the moment, maybe @fkaa or @JohnColanduoni could?

**Comment by dkushner** [comment]
Ah, awesome. Thanks for confirmation on that, @kvark. Will stand by.

**Comment by kvark** [comment]
Please use gfx_window_metal 0.3
It fails on nightly due to cocoa, which we need to update at some point, but stable should work.
