### ISSUE TITLE
Update cocoa dependencies

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1348]
This should make Travis happy again.

**Comment by brendanzab** [comment]
This is probably blocked on tomaka/glutin#901, as winit also needs to be updated.

**Comment by alexheretic** [comment]
I looked at this briefly after my PR, despite not being a mac dev. Looks like metal-rs still requires cacoa 0.5, and hasn't been updated in a little while. With winit/glutin updated I think that is the last blocker dependency

**Comment by kvark** [comment]
@alexheretic right, sorry about that!
Blocked on https://github.com/gfx-rs/metal-rs/pull/4
