### ISSUE TITLE
[ll][d3d12] Buffer to Image copy alignment

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1352]
D3D12 appears to impose harsh alignment restrictions on buffer/image copies: 512 for the copy chunk, 256 for each row of texture.

I tried to work around the second limitation by copying each row independently but still faced the first one that doesn't seem to be avoidable.

I believe the most reasonable (and painless) way to proceed would be to expose the alignment limitations by the backend capabilities, check for them at run-time, and respect those all the way through our CPU stack that does the actual uploading. Thus, for example, `image` crate would need a parameter specifying what alignment per row it needs to keep (cc @bvssvni ).

Note: this is a blocker for pretty much anything, including our `trianglell` example.
cc @msiglreith

**Comment by JohnColanduoni** [comment]
I think this maps to VkPhysicalDeviceLimits.optimalBufferCopyOffsetAlignment/optimalBufferCopyRowPitchAlignment. Perhaps we could turn those into minimums in our analogue of VkPhysicalDeviceLimits?

**Comment by kvark** [comment]
@JohnColanduoni that's what I was thinking as well. Filed an issue to Vulkan WG, let's see if we can upstream this restriction.

**Comment by kvark** [comment]
@Kangz
> The placed footprint in D3D12 force an alignment of 512 for the offset from the start of the buffer. We have found that it is possible to work around this by sometimes doing two copies instead of one (for 2D textures).

**Comment by kvark** [comment]
Resolution is - expose the limits and enforce them. Not much else we can do here.
Note: working around D3D12 limitation doesn't address the whole problem, and doesn't respect Vulkan's optimal offset either, so I don't find it much useful.
