### ISSUE TITLE
[ll] Mapping size/offset semantics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1353]
Currently, `write_mapping` gets the `offset` and `size` parameters in `T` units. This appears slightly inconsistent with other `Factory` methods (e.g. `create_buffer`) that work with bytes. I believe that even though we technically can treat the buffer as typed, given the `T` knowledge, we should be consistent with our `offset` and `size`, and treat them in bytes.

@msiglreith thoughts?

**Comment by msiglreith** [comment]
I've seen it in the your d3d12 PR and it sounds reasonable to me. Might even be necessary due to possible(?) alignment requirements.
