### ISSUE TITLE
Examples rendered off-center or not all

### ISSUE THREAD

**Issue by robbieh** [gfx-rs/gfx#1358]
I've been working between my desktop and laptop but had strange issues. After testing I found the examples work fine on the desktop, but are either off-centered or missing on the laptop. Binaries compiled on the desktop will fail once transferred to the laptop. Where can I go to begin to figure out what is causing the difference?

**Comment by vitvakatu** [comment]
Hello, @robbieh thanks for filling in issue. First of all, can you provide basic information about your system? Are you using Linux or Windows? (or maybe Mac?). Can you provide screenshots for off-centered examples? Did you see any errors in console when trying to run examples?

**Comment by kvark** [comment]
I'd guess that the laptop has HiDPI screen, and our gfx_app doesn't handle yet gracefully.

**Comment by robbieh** [comment]
The two systems in question are both Linux. The (misbehaving) laptop is Ubuntu 16, the desktop Debian Sid. Yes, it is a HiDPI screen. I have a screenshot but github is rejecting it, so I'll try that again later. In the meantime, imagine the cube example if the cube rendered centered on the top right corner of the window. There are no errors in the console. It runs fine, but just doesn't render correctly.

HiDPI was something I suspected. Looks like maybe the source of the hidpi_factor is winit? [](https://github.com/tomaka/winit/blob/master/src/platform/linux/x11/window.rs#L776)

**Comment by robbieh** [comment]
Here's the screenshot.

![screenshot](https://user-images.githubusercontent.com/2595315/27979961-e7c9877e-6347-11e7-817e-0a2ce7ec0a94.jpg)

Possibly relevant output from xdpyinfo:
```

screen #0:
  dimensions:    3200x1800 pixels (300x169 millimeters)
  resolution:    271x271 dots per inch
  depths (7):    24, 1, 4, 8, 15, 16, 32
  root window id:    0xf6
  depth of root window:    24 planes
  number of colormaps:    minimum 1, maximum 1
  default colormap:    0x22
  default number of colormap cells:    256
  preallocated pixels:    black 0, white 16777215
  options:    backing-store WHEN MAPPED, save-unders NO

```

I've been looking, but haven't tracked down what's happening yet.

**Comment by evolarium** [comment]
This is due to [this issue in glutin](https://github.com/tomaka/glutin/issues/903).

**Comment by francesca64** [comment]
Proper HiDPI support in winit is coming quite soon: tomaka/winit#548

**Comment by kvark** [comment]
Closing as pre-ll is deprecated. Please re-open if this is still a concern.
