### ISSUE TITLE
triangle_fan support removed?

### ISSUE THREAD

**Issue by bjadamson** [gfx-rs/gfx#1361]
Hi, I am working on switching a game I have been working on from C++ to Rust. In doing so, I went to implement a shortcut for rendering cubes based on this paper:
http://www.cs.umd.edu/projects/gvil/papers/av_ts.pdf

Essentially you can submit the entire cube to opengl (or whatever backend) with one trianglestrip, instead of multiple triangles (or triangle strips).

The three steps are:

1. Order the vertices in a certain order. For me in my C++ game, since I built my cube's by following the vertices from-to-back counterclockwise, I need to order my vertices in the order: [2, 3, 6, 7, 1, 0, 4, 5]

2. Setup the following indice ordering:
[3, 2, 6, 7, 4, 2, 0, 3, 1, 6, 5, 4, 1, 0]

3. Submit the vertices from step 1 using the indices from step 2 to opengl or whatever backend using the TRIANGLFAN setting.

For me using c++ code this works no problem!
https://github.com/bjadamson/BoomHS/blob/release/include/opengl/gfx_to_opengl.hpp#L358-L382
https://github.com/bjadamson/BoomHS/blob/release/include/opengl/gfx_to_opengl.hpp#L339-L342
https://raw.githubusercontent.com/bjadamson/BoomHS/release/screenshots/early_shapes.png

So I went to implement this in rust using gfx, couldn't get the cube to render correctly. Later I think I narrowed down my issue. The default PSO created by the factory assumes you want the vertices to be interpreted as triangles. For my use case, I need the vertex's to be interpreted as triangle fan's. I  believe I am not seeing the cube render (using the same trick) because I am not using the TRIANGLEFAN vertex setting.

I tracked down that back in this commit from @sectopod that support for TRIANGLE_FAN is removed
https://github.com/gfx-rs/gfx/commit/33ea864100149266fdf7c4ef73d6b2c7ef094108

Before this commit, it seems TRIANGLE_FAN was supported (but it is unclear to what level, since it was removed after all).

My question is, was there a reason support for trianglefan was removed with this commit? If so, do you know what needs to be done to add support back in for trianglefan?

Thanks a bunch, so far programming with gfx is way easier than using opengl directly in C++!

**Comment by kvark** [comment]
Hello @bjadamson !

> Essentially you can submit the entire cube to opengl (or whatever backend) with one trianglestrip, instead of multiple triangles (or triangle strips).

This is certainly neat, but it shouldn't ever be a performance concern. The difference between fetching 14 indices (for triangle strip/fan) versus 24 (for triangle list) is nothing, really. And if you do happen to submit a billion of them for rendering, instancing is the answer.

> I tracked down that back in this commit from @sectopod that support for TRIANGLE_FAN is removed
33ea864
> My question is, was there a reason support for trianglefan was removed with this commit?

Simply because it's not supported by DX11, the backend for which @sectopod was working on. If we could emulate it for cheap, we'd probably go for it, but there seem to be no straightforward way to do it.

> If so, do you know what needs to be done to add support back in for trianglefan?

I'm afraid it's a lost cause. You can try using the strips instead of fan, but I'd simply recommend focusing on more rewarding optimizations.

**Comment by bjadamson** [comment]
Hi, thanks for your response. Quick question before I head off to bed, for the sake of discussion, what would your thoughts be to adding back support for TRIANGLEFAN, but in the DX11 backend, just panic!() if they application is ever using TRIANGLEFAN inside the DX11 backend.

Say, somewhere like [here.](https://github.com/gfx-rs/gfx/blob/33ea864100149266fdf7c4ef73d6b2c7ef094108/src/backend/dx11/src/factory.rs#L214)

I don't expect this to be a viable solution, just wondering your thoughts on such a path.

Thanks again!

**Comment by bjadamson** [comment]
Whoops, I read my code wrong. It uses triangle strips, not triangle fans! Doh! I think we can close this is you want

**Comment by kvark** [comment]
hah, ok:)
I'd like to see a strong case for triangle fans before considering to `panic!()` on them.
Typically, DirectX doesn't have stuff that is either badly supported by the HW, or not useful, so I rely on their reasoning.
