### ISSUE TITLE
Set up the PR gatekeeper bot

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1363]
@homu has left us, so we need a replacement
[specs](https://github.com/slide-rs/specs) uses [bors](https://bors-app.herokuapp.com/), and we can follow, unless somewhat has a better candidate?

cc @torkleyy

**Comment by torkleyy** [comment]
I like bors, because it's simple and responds pretty fast. I don't remember another alternative from my research for Specs (except the ones we'd have to host ourselves).

**Comment by msiglreith** [comment]
`bors-ng` seems to be our best (only?) replacement besides self-hosting, or getting access to `bors-servo` (or something similar).

Therefore I would be in favor of adding `bors-ng` 
<sub>(until we find a bot with a nicer looking icon)</sub>

**Comment by torkleyy** [comment]
This kinda sounds like bors-ng wouldn't good, but the only option. I don't think that is true, because it has all the important features, so I don't see a reason for not using it. 

I do however agree that the avatar could look nicer, but really, that's absolutely insignificant IMO.

**Comment by msiglreith** [comment]
@torkleyy Sorry, wasn't intended to sound like I'm against bors-ng. It seems to offer all functionality we need and is more future-proof compared to homu based approaches (active development). You also seem to have a positive experience from using it in the slide-rs project so another plus.

Icon and other aesthetical stuff (e.g message formatting) are highly subjective. Even though I care about them to some degree, but it's nothing blocking for me as functionality has priority here.

**Comment by torkleyy** [comment]
Alright, let's add it then ;) @kvark would have to do that, because only owners have the permission to do so. Don't forget to add the current members as reviewers :wink:

**Comment by kvark** [comment]
@torkleyy 
> This kinda sounds like bors-ng wouldn't good, but the only option. I don't think that is true, because it has all the important features, so I don't see a reason for not using it.

It does, and yet I see it as a downgrade from homu. Homu was just a user bot, with all the rules of regular users applied to it, so it was sort of predictable. Bors is a Github application, it's just scary.
