### ISSUE TITLE
Allocating heap memory for low level DX12 backend fails

### ISSUE THREAD

**Issue by ConorLPBoyle** [gfx-rs/gfx#1379]
When attempting to compile and run the trianglell example on Windows 10 64 bit MSVC with the default DX12 backend, the program panics at runtime with the following message:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-2147024809`', src\backend\dx12ll\src\factory.rs:215:8
```
The [create_heap function](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12ll/src/factory.rs#L215) asserts that
```
assert_eq!(winapi::S_OK, unsafe {
            self.inner.CreateHeap(&desc, &dxguid::IID_ID3D12Heap, &mut heap)
        });
```
Commenting this out, the example simply fails to run without providing a backtrace.
```
error: process didn't exit successfully: `target\debug\examples\trianglell.exe` (exit code: 2173)
```
The example works fine compiled with with `--features vulkan`.

**Comment by kvark** [comment]
Interesting! We don't require that much memory for the heaps, so I wonder why it fails.

It'd be great to see the [DebugView](https://technet.microsoft.com/en-us/sysinternals/debugview.aspx) output from this crash. Debug runtime should have a cleaner error message than just the code.

**Comment by ConorLPBoyle** [comment]
Alright, this should be more helpful.
`
[12408] D3D12 ERROR: ID3D12Device::CreateHeap: D3D12_HEAP_FLAGS has invalid flag combinations set. The following flags may not all be set simultaneously. Exactly one must be left unset, or all may be left unset when the adapter supports D3D12_RESOURCE_HEAP_TIER_2 or creating a heap in conjunction with D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER: D3D12_FEATURE_DATA_D3D12_OPTIONS::ResourceHeapTier = D3D12_RESOURCE_HEAP_TIER_1, D3D12_HEAP_FLAG_SHARED_CROSS_ADAPTER = 0, D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES = 0, D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES = 0, and D3D12_HEAP_FLAG_DENY_BUFFERS = 0. [ STATE_CREATION ERROR #631: CREATEHEAP_INVALIDMISCFLAGS]
`

**Comment by kvark** [comment]
Interesting, thanks for the info!
I'm not sure why I'm not seeing this on my Win10 machine.
Would you want to try making a patch?

**Comment by ConorLPBoyle** [comment]
I'll see what I can do.

[The docs](https://msdn.microsoft.com/en-us/library/windows/desktop/dn986743(v=vs.85).aspx) state that there are multiple heap allocation tiers in DX12: Tier 1 supports allocation of heaps with resources of either buffer, regular texture, or Render target/depth stencil texture types, while tier 2 heaps allow resource allocation from any category. Evidently, my GeForce GTX 1050 only supports tier 1.

**Comment by ConorLPBoyle** [comment]
The problem was exactly this. DX12 devices with Tier 1 resource heap support (or: [every NVIDIA card from Kepler to Pascal!](https://developer.nvidia.com/dx12-dos-and-donts)) require heap types to be declared in the flags, but create_heap only currently passes D3D12_HEAP_FLAGS(0) to the heap descriptor. 

So modifying the trianglell example and adding a custom create_heap_flagged function, I got it running the following way:
```
let bufferheapflags = winapi::D3D12_HEAP_FLAGS(0) | winapi::D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES | winapi::D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES;
let textureheapflags = winapi::D3D12_HEAP_FLAGS(0) | winapi::D3D12_HEAP_FLAG_DENY_RT_DS_TEXTURES | D3D12_HEAP_FLAG_DENY_BUFFERS;
let rendertextureheapflags = winapi::D3D12_HEAP_FLAGS(0) | winapi::D3D12_HEAP_FLAG_DENY_NON_RT_DS_TEXTURES | D3D12_HEAP_FLAG_DENY_BUFFERS; //unused

...

let heap = factory.create_heap_flagged(upload_heap, 1024, bufferheapflags);
...
let image_upload_heap = factory.create_heap_flagged(upload_heap, upload_size, bufferheapflags);
...
let image_heap = factory.create_heap_flagged(device_heap, image_req.size, textureheapflags);

```

The best course of action in my view would be to expose separate create_texture_heap(), create_render_texture_heap() and create_buffer_heap() functions which simply map to create_heap() in the vulkan factory.rs.

**Comment by kvark** [comment]
I don't understand how Vulkan efficiently runs on that tier-1 hardware, given that the memory you allocate there doesn't have the type of resources specified in advance.

**Comment by ConorLPBoyle** [comment]
Well, it runs. I leave the rest to your discretion.
