### ISSUE TITLE
Support Min/Mag filter for samplers

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1404]
All backends should be able to support this. We only expose one filter method for both, minifaction and magnification. (https://docs.rs/gfx/0.16.1/gfx/texture/struct.SamplerInfo.html)

**Comment by kvark** [comment]
The idea is to have a single enum as opposed to 3 different enums. It doesn't mean that all min/mag/mip produced filters are the same.

Keeping this issue open because now that we are going low level, this abstraction (of having a single enum) can go up to `gfx_render`.

**Comment by lwiklendt** [comment]
For users coming from opengl, a way to get opengl-like nearest mag and bilinear min is to use FilterMethod::Mipmap with a mipmap.
