### ISSUE TITLE
[ll] Command Buffer Rework

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1416]
_This is part of the intergration process and the low level API development._
# Summary
[summary]: #summary

Rework the current `Buffer` to match the API exposed by the next-gen APIs (Vulkan, D3D12 and Metal). Including a strong-typed interface to ensure compatibilty with queues and pools (don't allow to submit compute commands to graphics queues!) 

# Motivation
[motivation]: #motivation

This rework is motivated by the on-going shift towards a low-level API. Allowing us provide a command buffer interface with minimal overhead. Additionally, provide currently lacking compute support.

> Note: Reworking the cmd buffers will affect large parts of the current core and render API, but we don't list all points which might require changes here, focusing only of the major parts/approach.

# Detailed design

We provide a `RawCommandBuffer` trait which needs to be implemented for each backend. It's functionality is similar to `vkCommandBuffer` and `ID3D12GraphicsCommandLists`. We noticed that the APIs only expose one command buffer type and don't differ between functionality. This allows us to provide safe shim-wrappers for our `RawCommandBuffer` which ensure a certain functionality.

## Strong-typed Command Buffer shims

```rust
pub struct ComputeCommandBuffer<'a, B: Backend>(pub(crate) &'a mut B::RawCommandBuffer)
where B::RawCommandBuffer: 'a;

impl<'a, B: Backend> Capability for ComputeCommandBuffer<'a, B> {
    type Capability = Compute;
}

impl<'a, B: Backend> ComputeCommandBuffer<'a, B> {
    /// Finish recording commands to the command buffers.
    ///
    /// The command buffer will be consumed and can't be modified further.
    /// The command pool must be reset to able to re-record commands.
    pub fn finish(mut self) -> Submit<B, Compute> {
        Submit::new(self.0.finish())
    }

    // Implement compute and transfer operations here, forwarding to raw command buffer calls.
}
```
These shims are similar to Metals Encoders but in contrast to them the user doesn't/can't switch between different encoders. This means that e.g `ComputeCommandBuffer` implements methods for compute and transfer operations.

## RawCommandBuffer

The `RawCommandBuffer` denotes _primary_ command buffers which can be submitted to queues.
It abstracts the command buffers of the different APIs, where we focus on the next-gen APIs. For GL the command buffers are implemented by storing command operations manually inside a Vec as currently implemented.

Incomplete interface:
```rust
pub trait RawCommandBuffer<B> {
    fn finish(&mut self) -> B::SubmitInfo;

    fn pipeline_barrier(&mut self, &[memory::MemoryBarrier], &[memory::BufferBarrier], &[memory::ImageBarrier]);
    fn clear_depth_stencil(&mut self, &B::DepthStencilView, Option<target::Depth>, Option<target::Stencil>);
    fn resolve_image(&mut self);
    fn bind_index_buffer(&mut self, IndexBufferView<B>);
    fn bind_vertex_buffers(&mut self, pso::VertexBufferSet<B>);
    fn set_viewports(&mut self, &[target::Rect]);
    fn set_scissors(&mut self, &[target::Rect]);
    fn set_ref_values(&mut self, state::RefValues);
    fn begin_renderpass(
        &mut self,
        render_pass: &B::RenderPass,
        frame_buffer: &B::FrameBuffer,
        render_area: target::Rect,
        clear_values: &[ClearValue],
        first_subpass: SubpassContents,
    );
    fn bind_graphics_pipeline(&mut self, &B::GraphicsPipeline);
    fn bind_graphics_descriptor_sets(&mut self, layout: &B::PipelineLayout, first_set: usize, sets: &[&B::DescriptorSet]);
    fn bind_compute_pipeline(&mut self, &B::ComputePipeline);
    fn dispatch(&mut self, u32, u32, u32);
    fn dispatch_indirect(&mut self, buffer: &B::Buffer, offset: u64);
    fn update_buffer(&mut self, buffer: &B::Buffer, data: &[u8], offset: usize);
    fn copy_buffer(&mut self, src: &B::Buffer, dst: &B::Buffer, regions: &[BufferCopy]);
    fn copy_image(&mut self, src: &B::Image, dst: &B::Image);
    fn copy_buffer_to_image(&mut self, src: &B::Buffer, dst: &B::Image, layout: texture::ImageLayout, regions: &[BufferImageCopy]);
    fn copy_image_to_buffer(&mut self, src: &B::Image, dst: &B::Buffer, layout: texture::ImageLayout, regions: &[BufferImageCopy]);
    fn draw(&mut self, start: VertexCount, count: VertexCount, instance: Option<InstanceParams>);
    fn draw_indexed(&mut self, start: VertexCount, count: VertexCount, base: VertexOffset, instance: Option<InstanceParams>);
    fn draw_indirect(&mut self, buffer: &B::Buffer, offset: u64, draw_count: u32, stride: u32);
    fn draw_indexed_indirect(&mut self, buffer: &B::Buffer, offset: u64, draw_count: u32, stride: u32);
}
```

The exact/complete interface is still WIP!
We orientate us on the Vulkan API, including RenderPass support via subpass encoders (inline and secondary). Subpass encoders will probably be safe encoder shims similar to the strong typed command buffers. 

 ## Device changes
The rework introduces a bunch of new resource types (`ComputePipeline`, `GraphicsPipeline`, `RenderPass`, `PipelineLayout`, ...) which are going to be added to the `Resources` trait and creation methods will be added to the device.

# Unresolved questions
* Bundles and Secondary command buffers are currently excluded from this rework, even though secondary cmd buffers are essential for effective multi-threading due to renderpass restrictions.

* Re-using of recorded command buffers hasn't been considered, but should be able to extend via changes to `Submit`.

* Current compatibilty matrix for the different APIs: (https://files.gitter.im/msiglreith/RglN/cmdbuffer.png)

* Support for `Event` synchronization primitives

**Comment by kvark** [comment]
Thanks for filing the design issue!
Unresolved questions:
  - bundles/secondary command buffers - needs a separate issue for discussion. This is going to be a hot topic...
  - re-using: problem is the lack of support on Metal. If we emulate recording of commands on Metal, then it opens the door for secondary command buffers there as well. But it's not going to be fast.
  - event synchronization is a superset of Direct3D 12 split barriers, so we probably want to expose the full event API like Vulkan.

**Comment by msiglreith** [comment]
Functions from vulkan which can be mapped easily to other backends:
* `BlitImage`: Unsupported by D3D12 and Metal
* `ClearColor`, `ClearDepthStencil`: Vulkan allows clearing on images directly, D3D12 only via RenderTargetViews and DepthStencilViews. Has the be emulated via RenderPasses in Metal afaik.
* `FillBuffer`: Vulkan allows to clear all buffers again, D3D12 exposes only UAV clearing.
* `UpdateBuffer` (In command buffer updates max 64k bytes) is not supported by D3D12 at least, which is soley built around staging buffers and map/unmap.

**Comment by kvark** [comment]
I tried to go through the issues:

##  `BlitImage`

Metal supports a limited set of blitting with `MTLBlitCommandEncoder`. Copying between textures doesn't have the destination size parameter, but it also doesn't specify anywhere that the destination has to have the same size... And given the dedicated `generateMipmaps` function, I assume that the destination slice is always covered in full?.. it's not clear.

Anyway, it sounds like we need a helper crate/module (possibly in gfx_render) that would proved a cross-API support for basic operations like blitting. This crate/module would then be used by the vulkan portability layer when targeting D3D12 or Metal.

## `ClearColor`, `ClearDepthStencil`, `FillBuffer`

These are hard. Main problem here is that Vulkan doesn't impose any requirements on the images being cleared, so we can't rely on `RenderTargetView` clears because an image may not be renderable in the first place... and forcing it to be renderable would mean potential performance sacrifices and layout transitions, which are highly undesirable.

I suggest not providing these in `gfx_core` API at all. For Vulkan Portability, we can have a feature flag specifying if these operations are supported, and it will be `false` on anything but Vulkan.

## `UpdateBuffer`

Oh, I didn't realize Vulkan provides in-line buffer updates with `vkCmdUpdateBuffer`. What's confusing to me is that a single call is limited to 0x10000 bytes, but there is no mention about the limitation applied to all updates for a recorded command buffer... Thus, it's not clear if we can just emulate this by packing a D3D12 command buffer with a 0x10000-sized Upload buffer at the lowest level. Need to consult with Vulkan folks.

**Comment by msiglreith** [comment]
* For `ClearColor` and `ClearDepthStencil` we currently aim to expose the D3D12 interface based on RenderTargetViews and DepthStencilViews

* In comparison to vulkan we don't allow resetting individual command buffers, only resetting a whole command pool as it's more efficient according to the vulkan specs. Additionally, we only allow to record command buffers one-by-one *per* command pool (note: that command pools are non-free threaded, therefore you usually have at least one pool/thread anyway). For vulkan portability we could further add unsafe functions to circumvent it if needed.

* Indirect execution requires a certain argument command description which is stored inside the description. Luckily these command structs seem to be similar for **all**(!) backends.
Besides that, we can think about extending indirect execution support after the ll integration is done: D3D12 supports indirect execution of other commands as well (besides draw and dispatch) (https://msdn.microsoft.com/de-de/library/windows/desktop/dn903925(v=vs.85).aspx).

**Comment by msiglreith** [comment]
Command buffers have been reworked in the `ll` branch and implementation is there for most of the backends. We went further towards vulkan's API. Individual features should be discussed in separate issues.
