### ISSUE TITLE
Should this be osx?

### ISSUE THREAD

**Issue by bjadamson** [gfx-rs/gfx#1424]
I was stumped by this, is this correct? The else seems like it would never be true.

https://github.com/gfx-rs/gfx/blob/9e9a3301342595c06ce6b5e4df67ae661dcadb49/scripts/travis-script.sh#L28

**Comment by kvark** [comment]
definitely a bug!

**Comment by bjadamson** [comment]
Ok, do you mind if I fix it in my other pull-request?

**Comment by kvark** [comment]
Yes, please. Thank you!

**Comment by bjadamson** [comment]
This can be closed now, it's been fixed.
