### ISSUE TITLE
Rebuild high level on top of LL

### ISSUE THREAD

**Issue by Bastacyclop** [gfx-rs/gfx#1466]
## 1 - Rebuild `gfx_render`

First, we need to rebuild `gfx_render` on top of the new low level core.
It will incorporate the old features from `gfx_core` and `gfx_render`:
- Resource handles
- Mapping tracking
- `Factory` and `Device`, with the new terminology `Device` and `Queue`
- `Encoder` will not be `Send` anymore and rely on pools
- `Slice`, see #1392
- Pipeline mecanisms, see #1429

## 2 - Split `gfx_app`

Then, we want our crates to have clearer identities as discussed in [gitter](https://gitter.im/gfx-rs/gfx?at=599370f7ee5c9a4c5fc4032c). That's why the old `gfx_app` will be split into three components:
- Utility code for the examples will live in the `examples` directory
- Utility code for the user will be moved into `gfx_render` (backend-agnostic)
- Backend selection will be the responsibility of a new `gfx_frontend` crate

## 3 - Improve

After these two steps, we will probably have a lot of polishing to do!

**Comment by msiglreith** [comment]
Thanks for taking a stab at this topic!
The mentioned points sound good so far.

Relevant discussion (but also partially outdated): #1281

**Comment by Bastacyclop** [comment]
Things to do after the first `render` implementation:
- [ ] Apply the conclusions of [this `Format` discussion](https://github.com/gfx-rs/gfx/pull/1476#discussion_r137530687).
- [ ] Clean it up and handle errors
- [ ] Write the documentation

**Comment by kvark** [comment]
This is somewhat addressed by [Rendy](https://github.com/rustgd/rendy) now
cc @omni-viral
