### ISSUE TITLE
Render video in window?

### ISSUE THREAD

**Issue by superlou** [gfx-rs/gfx#1485]
Is it possible to play a video as a texture or otherwise within some part of the window?

**Comment by msiglreith** [comment]
It's possible and has been done already afaik (https://github.com/unpatched/internet-broadcasting-service)
The basic idea would be to copy every frame into an upload buffer and copy it to the texture. The texture will be drawn with a simple fullscreen shader pipeline.

Starting points:
* Upload buffer creation and writing: https://github.com/gfx-rs/gfx/blob/v0.16/examples/instancing/main.rs#L118-L122
* Copy buffer to a texture (non-immutable!): https://github.com/gfx-rs/gfx/blob/v0.16/src/render/src/encoder.rs#L263
* `blend`, `flowmap` or other examples for setting up a pipeline to draw a texture to the screen.

Video encoding/decoding and other related operations are out of scope for `gfx-rs`!

**Comment by nical** [comment]
A preferable way to render a decoded video streams, when using hardware video decoding, is to use the GL_TEXTURE_EXTERNAL_OES target in GL or equivalents in other APIs and sample from decoded frames as "regular" textures.

**Comment by superlou** [comment]
Understood that encoding/decoding are outside the scope of gfx-rs.  That technique sounds reasonable, and I appreciate the examples.  Will do the naive copies and check if that's performant enough.  Thanks!
