### ISSUE TITLE
The case for draw_state

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1509]
Now that we are moving to LL the draw state becomes way more verbose. I can hardly think of Piston, for example, using the states we have in LL. Perhaps, Vulkano would want to share something?

Action item: check out Vulkano's states.

Options:
  1. move all LL states into draw_state
  2. detach from draw_state, keep all the states in `gfx::pso`
  3. wait till `gfx_render` is shaped up, perhaps it will need higher level states

**Comment by msiglreith** [comment]
I would propose something between 2 and 3:
Move some parts like `LogicOp` and maybe `DepthBias` into `draw_state`, while keeping `Rasterizer` as it's quite specific (e.g conservative rasterization option). Higher level states might be interesting for `render` which will not expose every low level feature and hopefully will be usable for other projects as well.

**Comment by kvark** [comment]
An important question to ask is how the other users of draw_state are doing?
Calling @bvssvni .
I somehow don't think Piston needs `LogicOp`...

I think the best course of action for now would be to:
  1. detach gfx-hal from draw_state. Less dependencies is good for a developing library.
  2. get more progress/vision on gfx-render
  3. re-evaluate draw_state with required changes afterwards

**Comment by davll** [comment]
> detach gfx-hal from draw_state. Less dependencies is good for a developing library.

I agree with you, because gfx-hal and piston might have different requirements and therefore draw_state will get conflicted during development.

**Comment by bvssvni** [comment]
@kvark We're not using "draw_state" anymore, but a custom one for Piston-Graphics.
