### ISSUE TITLE
Simple render target rendering example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1512]
We got multiple requests for a simpler render-to-target example.
One of the candidates for merging is https://github.com/pengowen123/gfx_render_cubemap
cc @pengowen123
opinions?

**Comment by pengowen123** [comment]
Should the example be specifically of a cubemap or just a simple offscreen render target example? The linked example renders a cubemap which requires a geometry shader and a special function for creating the cubemap. This could be useful to show how to use more complex features of gfx, but maybe it's too much.

**Comment by kvark** [comment]
@pengowen123 let's add your example as-is then, for now at least.

**Comment by kvark** [comment]
Fixed by #1514
