### ISSUE TITLE
[ll] dx12: Shader module creation from SPIR-V

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1538]
Create shader modules from SPIR-V shader binaries using SPIRV-Cross (and the Rust wrapper library).

Issues:
- [x] Patch descriptor sets due to heap limitations to match root signature layout
- [x] Add support for `register(.., space[N])` output in SPIRV-Cross with shader model >= 5.1
- [x] Adjust normalized device coordinate system to match with Vulkans (inverted y-axis). Either via shader or negating the viewport (requires extension)

**Comment by kvark** [comment]
Related but not immediately required - https://github.com/KhronosGroup/SPIRV-Cross/issues/293

**Comment by msiglreith** [comment]
Implemented in https://github.com/gfx-rs/gfx/pull/1546
