### ISSUE TITLE
Adapter features

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1553]
Vulkan requires enabling physical device / adapter features when creating a device (e.g depth clamping).
Easiest option would probably to query all features and enabling them, but this might come with some performance cost.

For the sake of vulkan portability we might just follow Vulkan here and force the user to set all wanted features at `Adapter::open`.

Relevant Vulkan specs section: https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#devsandqueues-physical-device-enumeration

**Comment by HeroesGrave** [comment]
It might make this a bit easier if we could categorize the features as follows:

- Features that gfx needs and should error if they aren't available.
- Features that gfx needs to provide certain functionality but it can work just fine without them if that functionality isn't used (eg: geometry shaders). These should probably be enabled if they're available, but not throw errors when they're not available unless the user tries to do something that needs them.
- Features that gfx doesn't care about but the user might want to use (eg: large points). These probably need to be user configured for the most part, but if they can be enabled without a performance cost then they probably should.
- Features that should always be disabled (I'm not sure if there are any).

**Comment by msiglreith** [comment]
Closed via https://github.com/gfx-rs/gfx/pull/1768
