### ISSUE TITLE
Dynamic Pipeline States

### ISSUE THREAD

**Issue by davll** [gfx-rs/gfx#1567]
There are several render states outside PSOs in Vulkan:

- set_line_width
- set_depth_bounds
- set_depth_bias
- set_stencil_compare_mask
- set_stencil_write_mask

However, the above states are inside PSOs in DX12, so it needs discussion to find out a mechanism to emulate dynamic states in DX12 backend.

## References:

- [Pipeline states investigation](https://github.com/gpuweb/gpuweb/issues/26)
- [d3d11's render state cache in ANGLE project](https://github.com/google/angle/blob/master/src/libANGLE/renderer/d3d/d3d11/RenderStateCache.h)
- [DX12 Pipeline State Cache Example](https://github.com/Microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12PipelineStateCache)

**Comment by kvark** [comment]
Note that stencil read/write masks are required for Dota to work, adding a blocker tag.

**Comment by grovesNL** [comment]
@kvark I can grab the read/write masks, most of the work is already in place from my last PR

**Comment by kvark** [comment]
thanks @grovesNL , that would be great!

**Comment by kvark** [comment]
Pretty sure these are addressed now.
