### ISSUE TITLE
Examples, bad path, still refer to "core"

### ISSUE THREAD

**Issue by paulirotta** [gfx-rs/gfx#1577]
Examples like "cargo run --bin triangle" fail with a bad path
Because this was refactored to "hal" recently? Sorry, I'm new here..

From examples/Cargo.toml
gfx_core = { path = "../src/core", version = "0.10" }

**Comment by vitvakatu** [comment]
Master is broken atm, you should use appropriate branch (`v0.16` for example) for stability.

**Comment by kvark** [comment]
@paulirotta see the following line in the readme:
>The current master branch is heavy WIP, please refer to pre-ll for the latest stable code/examples. It also has a more complete README ;)

Also see this link for more info: https://users.rust-lang.org/t/its-gfx-rs-all-the-way-down/13339
