### ISSUE TITLE
Command buffer reusability

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1588]
Currently, calling `CommandBuffer::finish()` gives you a `Submit`, which is then passed by value to `Submission::submit`. This effectively prevents us from re-using a command buffer. This limitation allows us to close the eyes on some of the rough portability aspects, e.g. that Metal doesn't support this directly. At the same time, it prevents us from using a number of important use-cases:
  - optimization by baking the static data into a command buffer
  - testing by re-invoking different configurations of command buffers

We need to start tackling this down, or at least thinking about this.

**Comment by AlphaModder** [comment]
I'm attempting to address this in #1712.

**Comment by kvark** [comment]
Fixed in #1712 
Thanks @AlphaModder !
