### ISSUE TITLE
Revise examples/README.md

### ISSUE THREAD

**Issue by blueridanus** [gfx-rs/gfx#1593]
On the readme file of the examples folder, 

> The examples are split across three directories, each pertaining to the GFX library they are using.
>1. examples/corell contains low level examples.
>2. examples/render shows how to use the render crate directly.
>3. examples/support shows how to utilize the support module, showing you how you can build an application using minimal setup.

the text references _examples/corell_, but this folder does not exist.

**Comment by blueridanus** [comment]
#1578

**Comment by leoschwarz** [comment]
Also running the examples as described doesn't seem to work for me (but maybe I'm also doing something wrong), most of them don't have a corresponding `Cargo.toml` file.

**Comment by kvark** [comment]
@leoschwarz the only examples expected to run (at this point) are those in `examples/hal` and `examples/render`
