### ISSUE TITLE
Metal Semaphores

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1597]
Semaphores are used in the following scenarios in Vulkan:
  1. Synchronizing different command queues
  2. Synchronizing rendering with the presentation engine (effectively, a hidden queue)
  3. Ordering command buffers within submissions

Metal exposes multiple command queues but without any means to synchronize between them. The target use case is having completely independent workloads done in parallel. This poses a problem of implementing `VkSemaphore` on Metal.

First decision that's going to partially address the problem is exposing a single command queue. This solves (1). Synchronizing with the presentation engine needs more investigation, but it doesn't appear that it would require much magic, so we should be good with (2) as well.

As for (3) - it comes down to the serialization problem of command buffers for submission. We just need to analyze the incoming dependency graph of command buffers within a single submission (where semaphores mark dependencies), and derive the actual Metal submission order from it. Since Vulkan requires no deadlocks posed by semaphores, there should be at least one way to order the command buffers.

**Comment by msiglreith** [comment]
:+1:
Exposing a single command queue let's us decouple command pools (and therefore buffers) from specific queues and allows us to couple them with queue families instead (as done in Vulkan) without trying to expose one family for each queue.

**Comment by JohnColanduoni** [comment]
@kvark I think the command buffer callback feature will be sufficient to synchronize with Swapchain if we continue to handle presentation manually, and we'll probably want to keep a `dispatch_semaphore_t` around (like it is in the current implementation) for this case.

**Comment by kvark** [comment]
I think this is done, at least within the context of a single queue.
