### ISSUE TITLE
SDL throwing BadMatch with proprietary Nvidia driver on Linux

### ISSUE THREAD

**Issue by magnonellie** [gfx-rs/gfx#1602]
Requesting a specific OpenGL version when using SDL and the proprietary Nvidia driver on Linux causes this error to be thrown:
```
Could not make GL context current: BadMatch (invalid parameter attributes)
```
Removing the lines setting the GL version solves the problem with Nvidia, but causes Intel to not be able to understand 3.2 shaders. The problem seems to also be solved for Nvidia when removing the following line from `gfx_window_sdl/lib.rs`:
```rust
attr.set_alpha_size(cf.0.get_alpha_stencil_bits());
```
This however causes my Intel machine to display colors incorrectly.

**Comment by torkleyy** [comment]
So at this point this is either some incompatibility gfx should handle or a bug in your driver I think.

**Comment by magnonellie** [comment]
I can see both of those options being the case. One thing speaking for it not being a driver problem is that examples with glutin and glfw work, not to mention that Portal 2 (which uses SDL) also works without problem.

**Comment by magnonellie** [comment]
I managed to fix it! Hooray! Well kinda. I found a stackoverflow question that mentioned that it works when the attributes are set before creating the window, which did indeed work. https://stackoverflow.com/questions/42013957/error-creating-opengl-context-with-sdl-badmatch
What's quite unfortunate though is that the current API doesn't allow for doing that.

**Comment by msiglreith** [comment]
Can this be closed?

**Comment by magnonellie** [comment]
I think so. I thought it would close automatically once my PR got merged, but I guess it didn't since it was merged to the pre-ll branch. I don't know if there are plans to keep SDL for ll, but this is definitely solved for pre-ll.

**Comment by msiglreith** [comment]
Great, thanks!
