### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by killkrt** [gfx-rs/gfx#1607]
Hi,

I've tried to build the project on Linux, but it failed due to a problem that seem to be related with macOS stuff:

```
> git clone https://github.com/gfx-rs/gfx
> cd gfx
> cargo build
...
   Compiling spirv_cross v0.3.1 (https://github.com/grovesNL/spirv_cross.git?branch=build-set-stdlib#5fc5ab87)
   Compiling metadeps v1.1.2
   Compiling x11-dl v2.15.0
   Compiling rand v0.3.17
   Compiling shared_library v0.1.7
   Compiling memchr v1.0.2
   Compiling num_cpus v1.7.0
   Compiling malloc_buf v0.0.6
error: native frameworks are only available on macOS targets

   Compiling syn v0.11.11
error: aborting due to previous error

error: Could not compile `core-foundation-sys`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

System info:
Linux kernel: 4.13.8-1-ARCH #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017 x86_64 GNU/Linux
rust stable: 1.21.0

**Comment by grovesNL** [comment]
Thanks for reporting this, I think this is the same issue as grovesNL/spirv_cross#33.

**Comment by kvark** [comment]
@grovesNL I don't think it's related.

Doing `cargo build` in the root folder is equivalent to `cargo build --all`, which goes and tries to build all the contained crates in the workspace, including OSX and Windows stuff.

Instead, you can either build a specific package you are interested in (e.g. `cd examples/hal/quad && cargo run --features vulkan`), or use `make` for generic all-around builds.
