### ISSUE TITLE
Customize texture views for type safety

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#161]
Currently, all the textures are given to the user as `TextureHandle` which bears no compile time (or even run-time) information about the kind of view that the texture is. This has implications:
- shader parameters: we are unable to ensure the types upon connecting parameter struct, the user is free to break the contract at any point later on
- render targets: we could enforce dimensionality match in compile time

Roughly, we could have it done with phantom types:

``` rust
pub struct TextureView<Dim, Type>(TextureHandle);
pub enum Dim2D {}
pub enum Dim3D {}
pub enum TypeFloat {}
pub enum TypeInt {}
...
fn create_texture_2D(...) -> TextureView<Dim2D, TypeFloat> {...}
```

It is unclear though how to separate dimensionality from the base type. For instance, render target doesn't care (yet) about the base type, it only needs a specific dimension. Texture creation as well cares (so far) only about the dimension. Thus, we can implement only the dimension first, and see how it goes.

**Comment by fkaa** [comment]
Would this be using [ARB_texture_view](https://www.opengl.org/registry/specs/ARB/texture_view.txt) when available or is the struct name unrelated?

**Comment by kvark** [comment]
@fkaa I haven't looked into this extension yet, though it does seem to be related.

**Comment by kvark** [comment]
We are using the `ARB_texture_view` now, but overall this issue is no longer needed, given the deprecation of pre-ll.
