### ISSUE TITLE
OSX: Bundle without access to RenderTarget still draws black onto screen

### ISSUE THREAD

**Issue by ucarion** [gfx-rs/gfx#1644]
I have a project doing shadow-volume-like stuff, which works correctly on Ubuntu:

https://github.com/ucarion/gfx-draping

(The screenshots in the README reflect what it looks like on my Ubuntu machine.)

However, on my Mac, there seems to be this bug where the bundle that's supposed to set up the depth stencil is also drawing black to the color target wherever the depth test passes. Here's a screenshot:

<img width="1792" alt="screenshot 2017-11-24 17 57 10" src="https://user-images.githubusercontent.com/2180153/33226370-f7d318a8-d140-11e7-88fb-71ca4800a836.png">

It seems like the stencil buffer is being set up as expected -- the polygon (the square with two holes in it) is getting draped onto the terrain correctly. But the surrounding black rectangular prism is the bug I'm talking about. In `src/lib.rs` can comment out the line that goes:

```rust
        bounding_box_bundle.encode(encoder);
```

To confirm that `polyhedron_bundle`, which doesn't even have "access" to any `RenderTargetView` (only a `DepthStencilView`), still manages to draw to the screen.

**Comment by kvark** [comment]
Not sure if this is still an issue? Please re-open otherwise.
