### ISSUE TITLE
Place of D3D11 in the new low-level world

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1651]
My original position was:
  - there is a superior D3D12 on Windows 10
  - there are still GL and Vulkan backends on Windows 7
  - thus, we don't need D3D11 backend in HAL

However, one important consideration has brought to my attention by @jrmuizel. If gfx-hal wants to be the basis of [WebRender](https://github.com/servo/webrender/), it can't be a regression for those users of Windows 7 platforms. Currently, WebRender is using D3D11 on Windows through [Angle](https://chromium.googlesource.com/angle/angle/+/master/README.md).

In light of this fact, I believe we should bump/revive the priority of getting D3D11 backend ported over to HAL. Hopefully, most of the code is already there, and we don't need any HAL API changes.

**Comment by msiglreith** [comment]
Slightly unrelated but what's the target GL(ES) version of WebRender?
We might need to expose more features for dx11 and lower OpenGL versions but this shouldn't affect the portability API. Some parts like memory mapping, in particular, are still a bit unclear. I don't know if there is a consensus from the portability WG so far?

**Comment by kvark** [comment]
@msiglreith currently, GL ES 3.0 is required.

> I don't know if there is a consensus from the portability WG so far?

The consensus of this group is that GL is not important for now, it is a secondary goal that shouldn't affect the trade-off and design decisions we make to reach D3D12 and Metal.

**Comment by JohnColanduoni** [comment]
DX11 is also valuable for supporting Intel integrated graphics. There’s a few (relatively recent) DX11-compatible  generations which don’t have Vulkan support on Windows for any version, even though they do on Linux >:(.

**Comment by DiThi** [comment]
It's also important for people that never updated the GPU driver, and the built in Microsoft ones don't have Vulkan or modern GL.

**Comment by DiThi** [comment]
Another reason D3D11 is interesting: Windows MR headsets which doesn't support DX12 yet. And I think OVR doesn't support Vulkan/DX12 either, but I'm not sure (GL is fine though).

**Comment by kvark** [comment]
This has happened, gfx-hal as a D3D11 backend that is tested by wgpu-rs.
