### ISSUE TITLE
Error type for update_descriptor_sets

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1674]
There is quite a bit of `panic!` dust over the backend implementations. This is undesirable. We should return errors instead, where it makes sense. `update_descriptor_sets` is one of those functions, where the error types can be standardized in HAL.

**Comment by AlphaModder** [comment]
As far as I can tell, there are no such errors possible? Under DX12 and Vulkan, none of the relevant functions produce an error code, and there are no panics or expects in our current implementation.
