### ISSUE TITLE
[pre-ll] [Mac] Bug in OpenGL backend

### ISSUE THREAD

**Issue by eldyer** [gfx-rs/gfx#1699]
On my Mac machine, all pre-ll examples result in a blank screen when using the GL backend. Metal is working fine.
I have no such problems with v0.16.

**Comment by kvark** [comment]
@eldyer hmm, could you check `glutin` examples from their latest code? I wonder if it's related to https://github.com/tomaka/glutin/pull/963

**Comment by eldyer** [comment]
@kvark Just checked latest glutin examples - no problems. Also I'm using current glutin master in my own project together with gfx 0.16, which works fine.

**Comment by eldyer** [comment]
@kvark, I think you're right! Current glutin examples from master don't work correctly. I also just get an empty window. (Just compared the output from the glutin examples on my windows machine, didn't recognize something is wrong before.)

**Comment by kvark** [comment]
Closing as pre-ll is deprecated
