### ISSUE TITLE
gl function was not loaded

### ISSUE THREAD

**Issue by PvdBerg1998** [gfx-rs/gfx#1711]
When running `cargo run --release` on nightly 1.24.0, my application (based on Piston-Window, so Gfx with OpenGL) crashes with the following error: `gl function was not loaded`. Possibly related to https://github.com/brendanzab/gl-rs/issues/443.

- Does not occur on the stable toolchain
- Does not occur on non release builds on nightly

Only tested on Windows 10.

**Comment by msiglreith** [comment]
Could you check with the examples in the latest `pre-ll` branch?
We encountered this issue already earlier (and hopefully fixed it!): https://github.com/brendanzab/gl-rs/issues/438

**Comment by brendanzab** [comment]
Another possibly correlated issue could be brendanzab/gl-rs#443 - alas I'm stabbing in the dark on it right now.

**Comment by brendanzab** [comment]
I'm guessing this is brendanzab/gl-rs#438 as opposed to brendanzab/gl-rs#443 based on it working on stable - would be great if you could test using the newer version of gl-rs.

**Comment by kvark** [comment]
Considering this fixed in gl-rs
