### ISSUE TITLE
metal: Implement memory (un)mapping

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1720]
With https://github.com/gfx-rs/gfx/pull/1718 the memory mapping API has been changed from resource based approach to a device memory based approach, which is unimplemented on Metal.

The implementation is non-trivial as it requires tracking of bound buffers and images.
The easiest case would be to check if the mapped range is inside an existing resource, allowing us to directly map the resource.
For other cases investigation is required.

**Comment by omni-viral** [comment]
#1741

**Comment by kvark** [comment]
Basic implementation has landed now, more complex logic to follow, but no need to hold the milestone any more. Thanks @omni-viral !
