### ISSUE TITLE
Modifying depth bounds

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1737]
Allow setting min/max depth bounds if supported the backend.

**Comment by msiglreith** [comment]
yes, dx12 requires a newer update, but I dont see how CreatePipelineState would help here, There is a depth bounds command though. GL exposes an extension for it, se we can optionally expose the depth bounds feature. For the moment a no-op/error is enough for all backends expect vulkan.

**Comment by jbatez** [comment]
It's not enough just to set the depth bounds; you need to enable the depth bounds test in the graphics pipeline state, and the pre-Creators Update `CreateGraphicsPipelineState` (as opposed to the newer, more flexible `CreatePipelineState`) doesn't provide the option. From the `OMSetDepthBounds` [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/mt492658(v=vs.85).aspx):

> To use depth-bounds testing, the application must use the new CreatePipelineState method to enable depth-bounds testing on the PSO and then can use this command list method to change the depth-bounds dynamically.

**Comment by msiglreith** [comment]
ugh, that sounds really annoying 😕 Apparently the new way of avoiding CreateGraphicsPipeline1/2/3/..
Thanks for mentioning, TIL.

**Comment by kvark** [comment]
@jbatez are you saying that depth bounds are basically not supported in dx12 prior to the Creators Update? We may need to take that into account for the VkPI (by either introducing a flag to disable support, or requiring that Dx12 version).

**Comment by kvark** [comment]
Sorry about hitting you with our jargon. VkPI stands short for Vulkan Portability Initiative, which drives our features/API requirements.
And you are correct, Vulkan does have it as a feature already (phew!) so we are good.
