### ISSUE TITLE
[meta] API Layering

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1739]
There are cases where we need to insert more logic between HAL API and the backends:
  - Validation (#1426)
  - Warden recording of all incoming workloads, to be able to save & replay later

Also see https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/7#issuecomment-357308614

**Comment by msiglreith** [comment]
At which place between those two layers? Should it be possible to provide backend specific layers? If not, I think we handle those cases by implementing a ` pub enum ValidationLayer<B: Backend> : Backend`.

**Comment by kvark** [comment]
> At which place between those two layers?

At HAL.

> Should it be possible to provide backend specific layers?

No, I don't think so.

> If not, I think we handle those cases by implementing a `pub enum ValidationLayer<B: Backend> : Backend`

`enum`  would imply pre-defined set of layers? I was thinking about an approach that would allow adding user layers, and also doing pass-through for methods/types that you don't want to hook/override.

**Comment by kvark** [comment]
I think we can omit this now. We don't have a strong case, and neither we have manpower to get that.
