### ISSUE TITLE
Compute on Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1743]
Are there any blockers now w.r.t. compute support?

https://github.com/KhronosGroup/SPIRV-Cross/pull/321 has been merged a while ago, plus we got https://github.com/gfx-rs/metal-rs/pull/22 . cc @grovesNL

**Comment by grovesNL** [comment]
To get initial support for Metal compute (i.e. enough to run the [HAL compute example)](https://github.com/gfx-rs/gfx/blob/master/examples/hal/compute/main.rs), we need to:

- [ ] Implement `StorageBuffer` fully (required for HAL example)
- [ ] Add compute pipeline state to `CommandBufferInner`
- [ ] Implement `create_compute_pipeline` (should code share with `create_graphics_pipeline`)
- [ ] Implement `bind_compute_descriptor_sets`
- [ ] Implement `dispatch` and `dispatch_indirect`

Part of this work is [already started in a branch I created a while ago](https://github.com/gfx-rs/gfx/commit/58666c7b1829303e2da4974abdca5171ba49c54d), but my implementation of `StorageBuffer` is incorrect (it was meant to be a temporary stub at the time).

I think the necessary types are already available in metal-rs (see [my compute example](https://github.com/gfx-rs/metal-rs/blob/master/examples/compute/main.rs) for usage), so nothing should be blocking us.
