### ISSUE TITLE
Framebuffer region dependencies 

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1747]
Allow defining subpass dependencies as framebuffer local. It's offering weaker ordering guarentees than global framebuffer dependencies, therefore we should be able to fallback for APIs not supporting it (e.g dx12).

**Comment by kvark** [comment]
Is there anything left to do here after #1858 ?

**Comment by msiglreith** [comment]
I think vulkan doesn't handle it so far, right?

**Comment by kvark** [comment]
we just pass it through, transmuting the flags
