### ISSUE TITLE
Equivalent to VK_WHOLE_SIZE

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1749]
Vulkan allows passing `VK_WHOLE_SIZE` (basically `-1`) as value. We could use an enum for handling this case.

**Comment by msiglreith** [comment]
Alternative over an enum: In most cases, we have offset + size, which we represent via a range. We could try to abstract the functions over `a..b` (`Range`) and `a..` (`RangeFrom`) covering most of the cases I guess.

**Comment by omni-viral** [comment]
You need something like [this](https://doc.rust-lang.org/std/collections/range/trait.RangeArgument.html)

**Comment by kvark** [comment]
I think it would most cleanly map to `..`. If that's impossible to expose cleanly atm, we may settle on `Option<Range<_>>`.

**Comment by msiglreith** [comment]
`VK_WHOLE_SIZE` in combination with an offset usually means, from offset to end.
I think we can expose a similar trait to `RangeArgument` and only implement it for the range types we support or even all.
