### ISSUE TITLE
hal: dx12 startup crash

### ISSUE THREAD

**Issue by Rhuagh** [gfx-rs/gfx#1756]
When I try running the quad example using the dx12 backend on my Windows machine with a GTX560 Ti, it crashes during startup.

dx12 debug runtime log attached.

[quad-dx12-rhuagh.LOG](https://github.com/gfx-rs/gfx/files/1653359/quad-dx12-rhuagh.LOG)

**Comment by kvark** [comment]
Looks fairly straightforward:
> [34496] D3D12 ERROR: ID3D12Device::CreatePlacedResource: A buffer resource cannot be created on a heap with the D3D12_HEAP_FLAG_DENY_BUFFERS flag. [ STATE_CREATION ERROR #638: CREATERESOURCEANDHEAP_INVALIDHEAPPROPERTIES]

**Comment by AlphaModder** [comment]
Yup, I have this same issue. Should be simple to solve.
