### ISSUE TITLE
Metal descriptor set binding problem

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1763]
There appears to be a fundamental problem with the way we currently bind descriptor sets in metal. The implementation checks the actual data in descriptor sets and issues Metal encoder `set_buffer/sampler/texture` commands to fill the state.

The problem is that the contents of descriptor sets can change between encoding that command buffer and actually submitting it. Wrench only issues `Device::update_descriptor_sets` call before the actual execution.

One obvious solution would be to defer the encoding up until the submission time. This would be quite unfortunate in terms of performance, and MoltenVK does this. Although, this is only needed when argument buffers are not supported, so the damage will fade away with time.

cc @JohnColanduoni @grovesNL @msiglreith

**Comment by msiglreith** [comment]
Could you add an example as I don't think that's an issue and more like a warden bug.

> The descriptor set contents bound by a call to vkCmdBindDescriptorSets may be consumed during
host execution of the command, or during shader execution of the resulting draws, or any time in
between. Thus, the contents must not be altered (overwritten by an update command, or freed)
between when the command is recorded and when the command completes executing on the queue.

Calling `bind_descriptor_sets` and **afterwards** updating the descriptor set is not valid and requires re-recording (reset). As noted above the actual time the descriptor set contents are consumed is implementation dependent. This constraint seems to be particularily included for devices without 'real' descriptor heaps/sets (a la Mantle).

**Comment by kvark** [comment]
Oh wow, TIL!
Gotta rethink the way Warden provides those sets then. Issue can be closed \o/

**Comment by msiglreith** [comment]
yay!
