### ISSUE TITLE
dx12: Shader loading error

### ISSUE THREAD

**Issue by zakorgy** [gfx-rs/gfx#1784]
Short info header:
- GFX version: revision: https://github.com/gfx-rs/gfx/tree/89f280e216a2d37c977a9a189b10da856ee9035c
- OS: Windows 10
- GPU: Intel Core i7-7700

When loading this vertex [shader](https://gist.github.com/zakorgy/c7958bf4d7ae3cd1595859c2bea4fadc) compiled to SPIR-V, we get this error:  "Combined image samplers have no default expression representation." This points here:
https://github.com/KhronosGroup/SPIRV-Cross/blob/ab3907e4b59b243e7391a71f5e962c1bb5ab8451/spirv_glsl.cpp#L2299
Easy way to reproduce this  with webrender from here: https://github.com/zakorgy/webrender/tree/dx12
with the `cargo run --example basic_hal` command.

**Comment by msiglreith** [comment]
We don't expose combined image samplers atm.
For dx12, I guess we need an interface in spirv-cross for specifying the space and binding on the dx12 texture and sampler resource interfaces (different space, same binding).

**Comment by msiglreith** [comment]
Ah, you already split the `sampler2D`. Then it's a SPIRV-Cross bug I believe, noticed a similar issue when using `textureSize`.

**Comment by kvark** [comment]
Do we know which sampler in particular it complains about?
Can we dump the SPIRV text form to see if it has the combined sampler?
If it does not, can we reproduce the error by running SPIRV-Cross manually to submit an upstream issue?
Thanks!

**Comment by msiglreith** [comment]
I filed on issue on SPIRV-Cross

**Comment by grovesNL** [comment]
KhronosGroup/SPIRV-Cross/issues/418 was fixed, and I published the updated bindings in https://crates.io/crates/spirv_cross/0.4.6 We should be fine to close this issue assuming it works.

**Comment by msiglreith** [comment]
Can this be closed @zakorgy ?

**Comment by zakorgy** [comment]
I think yes.
