### ISSUE TITLE
`hal::SubmissionResult` is nearly unused?

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/gfx#1815]
Was working on docs and realized that the `SubmissionResult` type is used in only one place, backend/dx11/src/lib.rs .  This seems odd; maybe some cleanup is possible?

**Comment by kvark** [comment]
DX11 codebase is not ported and neither it is CI-tested. Consider it sitting in the repo as a reference for future work only.

**Comment by icefoxen** [comment]
Okay, I'll document it as such then.
