### ISSUE TITLE
[API Design] [II] C-CASE: Casing issues 

### ISSUE THREAD

**Issue by mjadczak** [gfx-rs/gfx#1827]
Making a pass through the checklist in #1254. These are cases where I think the casing may be a little questionable:

- `gfx_hal::Backend::Swapchain` – this should be `SwapChain`, since [Vulkan resources](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain) seem to refer to this as a "swap chain" with two words, not a "swapchain". The Vulkan SDK code itself seems to call them "swapchains", so this is up for discussion.
- `gfx_hal::device::Device::create_swapchain` – should be `create_swap_chain` by same logic
- `gfx_hal::window:SwapchainConfig` – likewise
- `gfx_hal::window::Swapchain` – same
- `gfx_backend_dx12::window::Swapchain` – same
- `gfx_backend_empty::Swapchain` – same
- `gfx_backend_gl::window::glutin::Swapchain` – same
- `gfx_backend_gl::window::glutin::Surface::swapchain_formats` – same
- `gfx_backend_metal::window::Swapchain` – same
- `gfx_backend_vulkan::CommandQueue.swapchain_fn` – same
- `gfx_backend_vulkan::window::Swapchain` – same
- `gfx_hal::device::Device::destroy_renderpass` – should be `destory_render_pass`, as we have a `RenderPass` type and the matching create operation is `create_render_pass`.
- `gfx_hal::command::renderpass` – should be `render_pass`
- `gfx_hal::command::raw::begin_renderpass` – same
- `gfx_hal::command::raw::begin_renderpass_raw` – same
- `gfx_hal::command::raw::end_renderpass` – same
- `gfx_hal::window::Extent2d` – this one is really questionable given the casing guidelines. It seems super-weird to not have this be `Extent2D`, much more so than e.g. `Id` or `Uuid` or `Srgb` to me.
- `gfx_backend_vulkan::native::FrameBuffer` – should be `Framebuffer`, as it's consistently referred to as such elsewhere.

I have looked through all of `gfx_hal` and all of the backends, and these were the only things I could find. Once these are dealt with, we can probably check off this item in #1254.

**Comment by kvark** [comment]
@mjadczak thank you for taking the action on naming/casing issues!
- "Swapchain" - the official WSI extension uses a single word, e.g. `VkSwapchainKHR`, hence our current use is correct
- "RenderPass" - used as separate words, e. g. `VkRenderPass`, so we should definitely fix the remaining uses of `renderpass`  here
- "Framebuffer" - used as a single word, e.g. `VkFramebuffer`. We should fix the remaining case, although it's not exposed in the API so fairly minor 
- "Extent2d"  - we'll only switch to `Extent2D` if Rustc doesn't complain. I believe it doesn't like this by default.

Would you want to provide a PR?

**Comment by mjadczak** [comment]
Done: #1830 

`rustc` seemed to like `Extent2D` just fine so I made the change.
