### ISSUE TITLE
[API Design] [II] Get rid of unnamed parameters in traits

### ISSUE THREAD

**Issue by mjadczak** [gfx-rs/gfx#1829]
[Rust RFC 1685](https://github.com/rust-lang/rust/issues/41686) deprecates anonymous parameters in trait functions. These functions use anonymous parameters and descriptive parameter names should be added:

- `gfx_hal::adapter::PhysicalDevice`
  - `open`
  - `format_properties`
- `gfx_hal::queue::capability::Capability`
  - `supported_by`
- `gfx_backend_dx11::command::Parser`
  - `parse`
  - `update_buffer`
  - `update_texture`
- `gfx_hal::device::Device`
  - `free_memory`
  - `create_command_pool`
  - `destroy_command_pool`
  - `destroy_renderpass`
  - `destroy_pipeline_layout`
  - `destroy_graphics_pipeline`
  - `destroy_compute_pipeline`
  - `destroy_framebuffer`
  - `destroy_shader_module`
  - `create_buffer`
  - `get_buffer_requirements`
  - `bind_buffer_memory`
  - `destroy_buffer`
  - `create_buffer_view`
  - `destroy_buffer_view`
  - `create_image`
  - `get_image_requirements`
  - `bind_image_memory`
  - `destroy_image`
  - `create_image_view`
  - `destroy_image_view`
  - `create_sampler`
  - `destroy_sampler`
  - `destroy_descriptor_pool`
  - `destroy_descriptor_set_layout`
  -  `write_descriptor_sets`
  - `copy_descriptor_sets`
  - `map_memory`
  - `flush_mapped_memory_ranges`
  - `invalidate_mapped_memory_ranges`
  - `unmap_memory`
  - `destroy_semaphore`
  - `get_fence_status`
  - `destroy_fence`
  - `create_query_pool`
  - `destroy_query_pool`
- `gfx_hal::queue:RawCommandQueue`
  - `submit_raw`
- `gfx_hal::window::Surface`
  - `supports_queue_family`
  - `capabilities_and_formats`

**Comment by kvark** [comment]
Uh, I really liked this feature. But yeah, let's do it.
