### ISSUE TITLE
[API Design] [II] C-GETTER: Getter names should follow Rust conventions

### ISSUE THREAD

**Issue by mjadczak** [gfx-rs/gfx#1833]
See #1254.

These should all drop their `get_` prefix to comply with Rust conventions:
- `gfx_backend_dx11::device::Device.get_shader_model`
- `gfx_hal::adapter::PhysicalDevice`
  - `get_features`
  - `get_limits`
- `gfx_hal::device::Device`
  - `get_buffer_requirements`
  - `get_image_requirements`
  - `get_fence_status`
- `gfx_hal::image::AaMode.get_num_fragments`
- `gfx_hal::image::Kind`
  - `get_dimensions`
  - `get_level_dimensions`
  - `get_num_levels`
  - `get_num_slices`
  - `get_num_layers`
- `gfx_hal::window::Surface.get_kind`

Some of these might not be true "getters" in that they have to do some sort of computation. In that case the name without `get_` would still fit, or perhaps a name like `calculate_*` should be used.

These should be discussed, and perhaps changed to something more descriptive. According to the checklist, `get` should only be used as a name when "there is a single and obvious thing that could reasonably be gotten by a getter".
- `gfx_backend_dx11::command::DataBuffer.get`
- `gfx_backend_gl::queue::CommandQueue.get` and `get_raw`

**Comment by kvark** [comment]
I agree on those except for the `Device`, where `get` is not exactly a getter, it actually does some logic inside.

**Comment by mjadczak** [comment]
Are you talking about the three functions in `gfx_hal::device::Device`? I'm not sure what the convention is on functions which are not pure getters—we could stick with `get` or we could go to something like `obtain` or `calc`.

**Comment by kvark** [comment]
Yes, those. I think it's fine to leave them as get_xxx.
