### ISSUE TITLE
Fix subresource footprint calculation in D3D12

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1843]
@zakorgy wrote:
> When creating the D3D12_SUBRESOURCE_FOOTPRINT the height variable should take the buffer offset in account. Because if the offset is not zero, the debug layer shows an error, that we want to write more bytes than the buffer size.  A possible solution which worked for us, is to replace this [line](https://github.com/gfx-rs/gfx/blob/8d0ef5ba96bb4a2ecc5671975677323f11773dc5/src/backend/dx12/src/command.rs#L1296) with
```rust
let height = height as u32 - (region.buffer_offset as u32 / row_pitch);
```

**Comment by kvark** [comment]
@zakorgy  Looking at this some more, no longer seems as trivial. Do you have the exact validation error message saved somewhere?

**Comment by zakorgy** [comment]
@kvark here is the error message:
```
[248] D3D12 ERROR: ID3D12CommandList::CopyTextureRegion: The region specified by 
D3D12_TEXTURE_COPY_LOCATION:PlacedFootprint extends past the end of the buffer it is placed on.
The size required by PlacedFootprint is 16777216, as the fields of PlacedFootprint::Placement are as
follows: RowPitch is 16384, Height is 1024, and Format is R32G32B32A32_FLOAT. PlacedFootprint::Offset
is 16384, which requires the buffer to have 16793600 bytes; but the buffer only has 16777216 bytes.
[ RESOURCE_MANIPULATION ERROR #869: COPYTEXTUREREGION_INVALIDSRCPLACEMENT]
```
As you can see, the difference between the actual (16777216) and the expected (16793600) buffer size is the length of the RowPitch, which is equal with the Offset in this case.

**Comment by kvark** [comment]
@msiglreith so it looks like the `CopyTextureRegion` is really limited comparing to Vulkan's variant. In the latter, we could take a small buffer and copy the contents into a larger texture. In the former, we couldn't just place the footprint of the image into a smaller buffer...

**Comment by msiglreith** [comment]
@kvark Care to elaborate? I don't see any limitations beside offset alignment, pitch alignment and format compatibility, but I only really dealt with CopyBufferToImage so far.
As a quick overview how I currently implement it in rostkatze:
* offset aligned && pitch aligned: 1 copy, nothing fancy
* !offset aligned && pitch aligned: 2 copies following NXT
* !pitch aligned: Manually 'stitching' together the images by copy per row (possible optimization via compute shaders but limited due to UAV format support(?)). Data inheritance would also help here but seems to be UB with different formats.

**Comment by msiglreith** [comment]
> Is this texture -> aligned buffer copy followed by buffer -> buffer ? Where do we get the extra space for the temporary buffer?

No, it's rounding down the offset to the next aligned offset and adjusting the copy parameters accordingly depending on the pitch, resulting in either one or two CopyTextureRegion calls, copying two disjoint regions of the buffer into the texture. NXT's documentation visualizes it quite well: https://github.com/google/nxt-standalone/blob/master/src/backend/d3d12/TextureCopySplitter.cpp#L97-L170

> Each of those row by row copies would require the buffer offset alignment. How do you provide that? Going through a temporary buffer?

I don't use any temporary buffers. Manualy rounding down the offsets, setting a pitch and adjusting the src box accordingly allows to select subrows of the src buffer and copy them to image rows (might require two copies per image row). That involves quite some overhead indeed, but usually only necessary for low dimensional mipmaps.

AMD implements the whole copy stuff via compute shaders, but they don't provide the source for the shaders. Maybe I'm missing something but this seems to be only possible for a few formats with the UAV interface provided by D3D12?

**Comment by kvark** [comment]
Ok, I get it now, thanks for explanation @msiglreith !

> Maybe I'm missing something but this seems to be only possible for a few formats with the UAV interface provided by D3D12?

Where do you see the UAV limitation coming from? In terms of shaders, they could use [ByteAddressBuffer](https://msdn.microsoft.com/en-us/library/windows/desktop/ff471453(v=vs.85).aspx) and not care about the types.

**Comment by msiglreith** [comment]
> Where do you see the UAV limitation coming from? In terms of shaders, they could use ByteAddressBuffer and not care about the types.

https://msdn.microsoft.com/de-de/library/windows/desktop/ff471325(v=vs.85).aspx
To clarify the format limitations is for images.
