### ISSUE TITLE
Readme file: Documentation link broken

### ISSUE THREAD

**Issue by AveryGlitch** [gfx-rs/gfx#1844]
The `Documentation` link in the readme file is broken

**Comment by grovesNL** [comment]
This is a known issue for now (unfortunately) until the new crates are published

**Comment by jonathandturner** [comment]
This is still an issue, unfortunately, months later.  One temporary fix might be to point it the link to a different set of docs.

**Comment by grovesNL** [comment]
@jonathandturner We haven't completed documentation for the ongoing rewrite in master (ll) yet, so I'm not sure how valuable it is to link to other documentation at the moment. For example, if we link to pre-ll docs, they won't match master at all, so it could cause further confusion.

The [pre-ll](https://github.com/gfx-rs/gfx/tree/pre-ll) branch links to the [old docs](https://docs.rs/gfx/0.17.1/gfx/) correctly. Perhaps we should make the note about pre-ll in the README more noticeable, or simply remove the documentation link on master for now?

**Comment by jonathandturner** [comment]
Yeah, if master just doesn't have good docs quite yet, I'd probably just remove the broken link altogether.  Then, when they're ready, you could add it back.
