### ISSUE TITLE
`Factory::create_texture_immutable_u8()` does not check length of input

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/gfx#1895]
Short info header:
- GFX version: 0.17.1
- OS: Linux
- GPU: Any

`Factory::create_texture_immutable_u8()` actually segfaulted when I tried to pass it an input slice of a size different than what was described in the `Kind`.

This is pre-LL, so idk if we reeeeeeally care, but here it is.

**Comment by GabrielMajeri** [comment]
I think this can be closed since it's `pre-ll`
