### ISSUE TITLE
[dx12] buffer-image copy feedback

### ISSUE THREAD

**Issue by zakorgy** [gfx-rs/gfx#1905]
Short info header:
- OS: Windows
- GPU: Intel HD Graphics 630

I tried to run WebRender with the buffer-image copy changes on dx12 introduced in https://github.com/gfx-rs/gfx/pull/1893.
I found some values in the worst-case scenario branch, which I think are not in bytes and there is a missing multiplication with the `image.bytes_per_block`. Some of them causes [errors](https://gist.github.com/zakorgy/bfba86715b8ad02bf7b404c95c7ec22d).  I made a [gist](https://gist.github.com/zakorgy/eb19f031d286c39ddd8485e8248d4a0a) about my changes to fix these errors, but I'm not sure this is 100 % correct.

Also I found a strange behavior in the trivial case. If the `footprint_offset` value is greater than zero, e.g it points to the first position of the second line of the texture , it still copies things in the first line and overwrites it. Here are two images of renderdoc which shows the problem.
What we expect:
![expected](https://user-images.githubusercontent.com/11725775/38306617-6bd0c43a-3811-11e8-9aed-8307507396ff.PNG)
The result (the first row contains the second row, and the second row is empty):
![result](https://user-images.githubusercontent.com/11725775/38306622-71d4e00a-3811-11e8-8082-302f656bd535.PNG)

cc @kvark

**Comment by kvark** [comment]
@zakorgy note that my PR doesn't address the second issue you mentioned - about the trivial case. I double checked the code on our side and didn't find anything suspicious. Could you provide the repro instructions and/or share the RenderDoc captures posted?

**Comment by msiglreith** [comment]
> Also we have some suspicious warnings due to intersecting memory address ranges.

All expected. We alias a large chunk of heap for each DeviceMemory for mapping (not sure if legal tho..)
