### ISSUE TITLE
'undeclared identifier' in DX12 backend

### ISSUE THREAD

**Issue by callym** [gfx-rs/gfx#1916]
Short info header: I'm getting an 'undeclared identifier' when trying to compile with the DX12 backend, but not with the Vulkan backend.
- GFX version: master#b75b8f5
- OS: Windows 10 x64
- GPU: Nvidia 1060

The shader is
```glsl
#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(location = 0) in vec3 position;
layout(location = 1) in vec3 color;
layout(location = 2) in vec2 uv;

layout(set = 0, binding = 0) uniform Locals {
    mat4 proj_view;
};

layout(push_constant) uniform ModelLocals {
    mat4 model;
};

layout(location = 0) out vec3 v_color;
layout(location = 1) out vec2 v_uv;

void main() {
    v_color = color;
    v_uv = uv;
    gl_Position = proj_view * model * vec4(position, 1.0);
}
```

The error is:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Shader(CompilationFailed("D:\\programming\\opalite\\examples\\simple\\Shader@0x000001ADCB31E350(35,51-59): error X3004: undeclared identifier \'_37_model\'\n\u{0}"))', libcore\result.rs:945:5`

I think the error is because the push constant block, is this not supported in DX12 (yet?)?

**Comment by msiglreith** [comment]
> I think the error is because the push constant block, is this not supported in DX12 (yet?)?

It is/should be. [This](https://github.com/msiglreith/SPIRV-Cross/commit/c655cb6c49864809ad68c3fe537587f52cf71bde) should fix it but I need to test it first.

**Comment by msiglreith** [comment]
Submitted a fix to spirv-cross https://github.com/gfx-rs/gfx/issues/1916
If it goes through an update to the rust spirv-cross wrapper and a dx12 dependency bump will follow.

**Comment by callym** [comment]
That's great, thanks so much for looking into this so quickly :)
