### ISSUE TITLE
Device feature requests

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#1928]
We need a mechanism to request particular features of the supported ones for the device.
see https://github.com/szeged/webrender/issues/136#issuecomment-380745757

**Comment by LaylConway** [comment]
Just now hit against this problem while trying to convert my engine from ash to gfx-hal to give it a try. My engine by default uses BC1 textures, and `texture_compression_bc` technically needs to be enabled to use those. Luckily my development machine's drivers accept it either way, but a validation error still ends up happening.
