### ISSUE TITLE
Present method on swapchain should return Result

### ISSUE THREAD

**Issue by thorjelly** [gfx-rs/gfx#1933]
It should be expected that the "present" method can fail with ErrorOutOfDateKhr or perhaps SupOptimalKhr. Currently, the present method asserts that the operation is a success, causing a panic on error. These errors can and should be handled gracefully, by for example dropping the frame and rebuilding the swapchain. Therefore, the present method should return a Result, rather than assert success within its body. This is a pretty important improvement; even the current quad example panics by simply attempting to resize the window.

**Comment by msiglreith** [comment]
Closing this in favor of #1961 as it also includes results for acquire
