### ISSUE TITLE
Dynamic buffer descriptors

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1949]
Add support for dynamic uniform buffers and dynamic storage buffers.

Implementation:

* Vulkan: obvious
* DX12: Descriptor + Root constant for offset maybe? Separate root constant space for all dynamic descriptor offset and updated on BindDescriptorSet. Further limits the available place in the root signature (32 root constants, 8 descriptor sets (2 slots due to sampler separation),  8 + 4 root constants for dynamic, 3 root constants for workgroup size, 1 spare for now). Other ideas?
* Metal: No idea

Edit: Update dx12 root signature split up

**Comment by kvark** [comment]
The current status is - the feature is implemented and working well on Vulkan and Metal.
DX12/11 needs this covered as well, as it's blocking [rx](https://www.reddit.com/r/rust/comments/dauizc/rx_v020_released_a_modern_pixel_editor/f21psn6/) and potentially Amethyst from using the backend. See [code](https://github.com/gfx-rs/gfx/blob/543b521773a17f5f9d58a9ee3cc6a22b6442d1d7/src/backend/dx12/src/command.rs#L213).

**Comment by msiglreith** [comment]
Note: Using root descriptors for implementing it in DX12 should be the easier approach compared to the one outlined. It should occupy the same space in the root signature.

**Comment by msiglreith** [comment]
With the implementation of uniform buffers as root descriptors we end up with a root signature layout (64slots):
- 32 root constants -> 128bytes (Vulkan minimum)
- 8 descriptor tables for 4 descriptor sets (CBV/SRV/UAV and Sampler tables split)
- 8 root descriptors for dynamic uniform buffers -> 2x8 slots (Vulkan Minimum)

This leafs us with 8 slots for dynamic storage buffers, https://github.com/gfx-rs/gfx/issues/2604/ and https://github.com/gfx-rs/gfx/issues/2589

Root descriptors for SRV and UAV are different which would require us to know which resource type is used on the shader side. We don't have this information in the host side API (see https://github.com/gfx-rs/gfx/issues/2933).

In case we assume 4 slots for the https://github.com/gfx-rs/gfx/issues/2604/ and https://github.com/gfx-rs/gfx/issues/2589, we end up with 4 slots -> 2 root descriptors for storage buffers. As we would have to bind both SRV and UAV if we follow the approach used for descriptor tables, it would end up with 1 storage buffer max which would not fit the vulkan minimum.

As storage buffers are translated to the R/WByteAddressBuffers, we actually can make use of the descriptor table + push constant approach proposed initially. Therefore we only need one push constant for each storage buffer and we would fit in the limit. This requires a few changes to spirv-cross tho to properly offset the address buffers with the push constant value, along with injecting these in the shaders.
