### ISSUE TITLE
[dx12] Copy split assert on PBR IBL sample

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1957]
https://github.com/SaschaWillems/Vulkan/tree/master/examples/pbribl
The sample hits [this](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12/src/command.rs#L689) assert during copying a cube texture.

cc @kvark

**Comment by kvark** [comment]
looks like a legitimate bug / missing case for the copy split
do you have the exact parameters?

**Comment by kvark** [comment]
Perhaps, all we need there is to take a first multiple of `row_pitch_texels` that matches the expectation.
