### ISSUE TITLE
thread 'main' panicked at 'Error InvalidOperation executing command: BindProgram(0)' (pre-ll triangle example)

### ISSUE THREAD

**Issue by xzn** [gfx-rs/gfx#1958]
- GFX version:
pre-ll git 

- OS:
Windows

- GPU:
Intel UHD 620

Running the triangle example gives me the following error:
thread 'main' panicked at 'Error InvalidOperation executing command: BindProgram(0)', src\backend\gl\src\lib.rs:808:13

I also tried the cube example which works fine except when I try to resize the window:
ERROR 2018-04-21T09:46:57Z: gfx_window_dxgi: Resize failed with code 887A0001
ERROR 2018-04-21T09:46:57Z: gfx_app: Resize failed: The RTV cannot be changed due to the references to it existing
(should I open a separate issue for the cube example?)

**Comment by kvark** [comment]
@xzn why is this now closed?
