### ISSUE TITLE
[ll] Swapchain acquire_frame and present need to return Result

### ISSUE THREAD

**Issue by HybridEidolon** [gfx-rs/gfx#1961]
The Vulkan analog for the two trait functions `acquire_frame` and `present` on hal::Swapchain can result in errors. See [the vulkan spec for the WSI swapchain extension.](http://vulkan-spec-chunked.ahcox.com/ch29s06.html)

The return codes VK_ERROR_OUT_OF_DATE_KHR and VK_SUBOPTIMAL are critical for recognizing when a swapchain needs to be recreated; there can be a data race between the calls for `acquire_frame` and `present` in user code that would result in OUT_OF_DATE being returned on the latter, even if a window resize event from the host window system were handled to recreate the swapchain just before `acquire_frame`. _(On my GTX 1080 on Windows, it does not appear that nvidia's driver will ever yield VK_SUBOPTIMAL and gracefully fall back to scaling the swap image like DXGI does)._

User code both needs to be exposed to these error conditions and also handle them for full Vulkan transparency.

This is probably necessary for Vulkan Portability. In DXGI, Present can return a comparable error, but only when the device itself is lost; it silently handles swapchains of the wrong size (which is why you could resize the quad demo freely right now). In Metal, there are no errors at all from `present`. In GL, well, it depends on the windowing implementation.

**Comment by kvark** [comment]
Acquire part is addressed in #2345, present still needs to be fixed.

**Comment by kvark** [comment]
Present got addressed in #2502
