### ISSUE TITLE
dx12: PBR cubmap copy issues

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1963]
Small blue lines appear in the skybox in the image based textured PBR sample in dx12:
![unbenannt](https://user-images.githubusercontent.com/7253845/39128554-5b6ae14c-4708-11e8-8276-9936a086d193.png)
(left and right)
Most likely an issue during copy_buffer_to_image

cc @kvark

**Comment by kvark** [comment]
Share a GPU capture please? Sounds like we miss first/last (part of the) row in the slowest path.
