### ISSUE TITLE
[pre-ll/gl] Example for texture array usage

### ISSUE THREAD

**Issue by skemps** [gfx-rs/gfx#1993]
Is there any example or tutorial for using texture arays (gfx::texture::Kind::D2Array), like creating array, adding textures to it and drawing them with shader?

Short info header:
- GFX version: 0.17.1
- OS: Debian Stretch
- GPU: Nvidia 970gt

**Comment by kvark** [comment]
Here are some examples: https://github.com/search?p=1&q=%22Kind%3A%3AD2Array%22&type=Code&utf8=%E2%9C%93

**Comment by GabrielMajeri** [comment]
@kvark should this issue be updated to remove the `pre-ll` label and request a texture array example for the new API?

**Comment by kvark** [comment]
wgpu-rs has `shadow` example that uses texture arrays.
