### ISSUE TITLE
Explicit binding parameter for vertex bindings

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#1994]
Graphics pipeline creation interprets the index of the vertex binding in the array as binding index, which should be decoupled.

Fixes https://github.com/gfx-rs/portability/blob/master/libportability-gfx/src/impls.rs#L1571

**Comment by kvark** [comment]
Fixed by #2013
@jbatez FYI, Github doesn't recognize "Implements #xxx" pattern: https://help.github.com/articles/closing-issues-using-keywords/
