### ISSUE TITLE
Image layout queries and initialization

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2051]
Vulkan allows to specify the initial layout on image creation, which we don't have. There is also `vkGetImageSubresourceLayout` that we need to provide. It appears to be blocking the tests:
"dEQP-VK.draw.simple_draw.*

**Comment by omni-viral** [comment]
Should be reopened. Not fixed

**Comment by kvark** [comment]
> Vulkan allows to specify the initial layout on image creation, which we don't have.

That I figured we don't actually need just yet. Vulkan only allows PREINITIALIZED and UNINITIALIZED layouts there anyway, which are of limited use for us.

> vkGetImageSubresourceLayout

This has been done and tested by CTS.

**Comment by omni-viral** [comment]
Okee
