### ISSUE TITLE
What is the command used to generate the vert.spv and frag.spv files?

### ISSUE THREAD

**Issue by xMAC94x** [gfx-rs/gfx#2081]
https://github.com/gfx-rs/gfx/blob/master/examples/hal/quad/data/frag.spv

any information on this?

**Comment by kvark** [comment]
[glslang](https://github.com/KhronosGroup/glslang) with trivial parameters. We'll probably migrate to keeping only GLSL shaders in the examples and generating SPV from build scripts.

**Comment by xMAC94x** [comment]
ah okay i could reproduce it, thanks
