### ISSUE TITLE
dx12: TYPELESS format conversion

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2083]
> D3D12 ERROR: ID3D12Device::CreateRenderTargetView: The resource format (R16G16B16A16_FLOAT) and view format (R16G16B16A16_UINT) differ in float vs non-float component interpretation - this type of format casting is not supported. [ STATE_CREATION ERROR #38: CREATERENDERTARGETVIEW_INVALIDF

Apparently we need to convert formats into typeless variants on resource creation. Would be interesting to know if there is a drawback and if we need to do it for all type of resources.

**Comment by fkaa** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/mt426647(v=vs.85).aspx I think you need typeless or partially typed on the resource then you can use formats inside the format family for views?

> L : typeless format
> PCS : partially typed, castable and simple layout
> FCS : fully typed, castable and simple layout
> FNS : fully typed, non-castable and simple layout
> PCC : partially typed, castable and complex layout
> FCC : fully typed, castable and complex layout
> FNC : fully typed, non-castable and complex layout
> V : video format

**Comment by msiglreith** [comment]
yes, the `PCS\PCC` (alias _TYPELESS) formats. I wasn't aware that additionally cast between data types are forbidden which is quite irritating to me.
