### ISSUE TITLE
Add mirror clamped to edge filter

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2100]
Support the one time mirroring filter extension (VK_KHR_sampler_mirror_clamp_to_edge).
Named `D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE` in D3D12

**Comment by msiglreith** [comment]
Need to figure out first how to expose extensions in gfx

**Comment by caitp** [comment]
> Need to figure out first how to expose extensions in gfx

How about something like this? (Granted, I haven't really looked at the gfx codebase at all until a few hours ago).

This way, an application can request an abstract naming of extensions which vulkan/metal/dx12 can translate, ignore, or fail during device creation if they can't be supported.

1. encode abstract extensions via enum or bitfield

```rust
mod hal {
    enum Extension {
        SamplerMirrorOnce, // VK_KHR_sampler_mirror_clamp_to_edge,
        ..
    }
}
```

2. pass into PhysicalDevice::open() (either as a bitfield, or a vec/slice/iterator of enums)

```rust
fn open(
        &self,
        families: &[(&QueueFamily, &[hal::QueuePriority])],
        extensions: &[Extension],
    ) -> Result<hal::Gpu<Backend>, DeviceCreationError>
```

3. add some conv:: machinery to translate requested extensions into a pointer to a 'static str

```rust
pub enum ExtensionError {
    ImplicitlySupported, // Or return Option<&'static str>, whatever

    NotSupported, // PhysicalDevice can't do what's requested, HAL can try to find another that can?
}

pub fn map_ext(ext: Extension) -> Result<&'static str, ExtensionError> {
  map ext {
    Extension::SamplerMirrorOnce => Ok(extensions::VK_KHR_Sampler_mirror_clamp_to_edge),

    _ => Err(ExtensionError::NotSupported),
  }
}
```

---

A fancier version of this would integrate the builder pattern for PhysicalDevice opening, with methods that accept HAL abstractions for extensions, as well as backend-specific versions which could be used for testing, or adding backend support before HAL integration is ready, which would be better for developers of gfx-rs (by allowing the advancement of individual backend features without being blocked on support in other backends or the HAL) e.g.

```rust
backend_vulkan::PhysicalDevice::open()
    // testing some extension that doesn't exist in HAL --- doesn't require handling in other backends
    .with_vulkan_extensions(&["VK_KHR_sampler_mirror_clamp_to_edge"])

    // using extensions which are exposed in HAL, and are known about by all backends.
    .with_extensions(&[Extension::QuerySurfaceCapabilities]);
```

**Comment by caitp** [comment]
of course, making the abstract extension enums/bitfields isn’t very future-proof (would mean removing them or adding new ones is always a API breaking change) so there are downsides

**Comment by kvark** [comment]
@msiglreith I suggest just extending `Features`, just like #3170 does it.
Essentially, extensions are just features that weren't know by the time the spec was out.

**Comment by kvark** [comment]
I'm trying to cover our bases for releaing 0.5, will add a flag for this.
