### ISSUE TITLE
Specify LOD as float

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2101]
Our current encoding results in quantization errors causing a few CTS issues to fail on dx12.

**Comment by kvark** [comment]
Out of curiosity, what values do they use that are not 1/8 quantified?

**Comment by msiglreith** [comment]
I think it was `0.1` in the maxlod case. Fixed the CTS linear mipmap filter mode cases.

**Comment by msiglreith** [comment]
Guideline:
1. Remove the LOD wrapper and define a newtype for f32 (https://github.com/gfx-rs/gfx/blob/master/src/hal/src/image.rs#L432-L444)
2. Fix builds

Bonus points for running CTS before and afterwards but that requires a huge amount of time for setup :)
