### ISSUE TITLE
Implement BaseTyped for f64

### ISSUE THREAD

**Issue by SuperCuber** [gfx-rs/gfx#2106]
Short info header:
- GFX version: 0.17.1
- OS: Windows
- GPU: GTX Geforce 1060

# Issue
Is there a reason why `BaseTyped` isn't implemented for `f64`?

From my limited understanding of the code, adding it to [here](https://docs.rs/gfx_core/0.8.0/src/gfx_core/shade.rs.html#282) should do the trick?

There even is a spot for it in the enum...

**Comment by kvark** [comment]
No reason, PRs are welcome ;)

**Comment by Napokue** [comment]
Will look into it
