### ISSUE TITLE
Things that I think could be improved in gfx-rs

### ISSUE THREAD

**Issue by tomaka** [gfx-rs/gfx#216]
@kvark encouraged me to post a _mega-issue_ about things that I don't like with gfx-rs, so here it is.
# Documentation
- [x] More examples.
- [ ] Document the differences between `device`, `render` and `gfx` and what each of these crates is supposed to do. It took me some time to figure out that only `gfx` is supposed to be used.
- [ ] Not only document what a trait/enum is, but also where and how it should be used. For example if an object doesn't have a constructor (like `FrontEnd` or `DrawList`), it should be documented how to create one.
- [ ] Everything that shouldn't be used by the user must be either private or marked with `#[doc(hidden)]`. This includes `Handle` and `VertexFormat`.
- [ ] Document a little bit what a buffer, a surface, a frame buffer, etc. are. Don't assume that all `gfx-rs` users will be experts in 3D rendering.
- [ ] Document whether `[[f32, ..4], ..4]` is supposed to be row-major or column-major.
- [x] The `Frame` type is too confusing. The front end returns "the main frame", but frames can be created with `Frame::new()`. The docs say it's "the result of rendering", but I'd expect the pixel data to be in there if it was the case. What exactly _is_ a frame?
- [x] Same for `Mesh`.
- [x] I have never heard the `Shell` word before when talking about 3D rendering. This word is confusing.
# Safety
- [x] Remove all `type Foo = Bar` in favor of `struct Foo(Bar)`.
- [x] Remove all `delete_*` functions. RAII should handle everything.
- [x] Rust doesn't allow "empty" objects (eg. null pointers), so gfx-rx shouldn't allow empty textures or empty buffers either.
- [ ] Texture data format should be inferred using Rust's type system. For example if the user uploads some texture data whose type is `&[(f32, f32, f32)]` or `&[[f32, ..3]]`, you can infer that it has 3 `gl_float` components.
- [ ] Similarly, the type of the texture (1D, 2D, 3D) can be auto-detected depending on the function parameters. If the user passes a height of 1 and a depth of 1 to `create_texture`, then it's a 1D texture.
- [x] Why does `DrawList` have a `reset` method? The user should just create a new list instead of resetting it.
- [x] Index buffer are too difficult to use and too unsafe. Just like textures, the type of indices should be inferred from the rust type used in the buffer instead of requiring the user to pass a `U16` or `U32` enum value.
- [x] `create_frame_buffer` should not return a `u32`.
- [x] `Mesh` should contain the `BufferHandle` to ensure that the buffer is not destroyed as long as the mesh exists.
# Usability
- [x] Why is `connect_program` not part of the draw list? More often than not, you have a `matrix` uniform which must be updated at each frame. The fact that it's not part of the draw list makes draw list not reusable because you need to recreate a new `CustomShell` object at each frame.
- [ ] `ParamDirectory` should be much easier to create.

**Comment by kvark** [comment]
This becomes slightly obsolete, and a lot of points are already done. Lowering the priority.

**Comment by kvark** [comment]
Not planning on doing these changes in pre-ll
