### ISSUE TITLE
Very difficult to put state in a struct, due to type complexity

### ISSUE THREAD

**Issue by scottjmaddox** [gfx-rs/gfx#2162]
Short info header:
- GFX version: 0.17.1
- OS: MacOS
- GPU: Intel

I'm trying to stick all of the rendering state into a struct, but I'm finding very difficult to figure out the types of everything, due to all of the type complexity. The compiler helps a bit, but it won't fill in all the inferred details, and then I'm still left with code that won't compile because I'm missing some trait bounds... I don't have any specific recommendations, but I feel like there needs to be an easy way to stick the state in a struct.

**Comment by kvark** [comment]
@scottjmaddox indeed some of the knowledge is required to be able to store the types, and it takes a rough learning curve to get it (see http://gfx-rs.github.io/2016/01/22/pso.html).

**Comment by scottjmaddox** [comment]
@kvark, thanks for your quick response. I've since moved away from using `gfx`, so feel free to close this issue if you don't plan to fix it. However, I do think keeping type complexity in check is a reasonable goal. I suspect this could be achieved by using trait objects (i.e. indirection) more, though I have not investigated the possibility in depth.
