### ISSUE TITLE
Stale depth-stencil state in Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2209]
See https://github.com/szeged/webrender/issues/189#issuecomment-403082557
Looks like we aren't always updating the d/s state in Metal still. Need to run WebRender's Wrench/Metal on `reftests/filters/filter-saturate-red-1-ref.yaml` and see what comes in versus what comes out.

**Comment by dati91** [comment]
I print out the pipeline I'm submitting (bottom right console), and the capture shows the depth state before the draw call.
<img width="1440" alt="screen shot 2018-07-06 at 19 13 18" src="https://user-images.githubusercontent.com/2149430/42391843-f0652582-8150-11e8-81c9-96b4f46a57cd.png">

**Comment by kvark** [comment]
Can I repro? We see the same in Dota, and would be great to fix it if indeed the issue is on our side.

**Comment by dati91** [comment]
You can use the [same repo as before](https://github.com/dati91/webrender/tree/metal_debug) (with the debug enabled ofc). And run the `reftest reftests/filters/filter-saturate-red-1.yaml` and capture the first result, because the ref runs first and then the actual test. But I can see this error in the second test as well in the log.

**Comment by kvark** [comment]
I'm not able to capture this since we are hitting the "message sent to deallocated instance" here :( which is already filed to Apple.

**Comment by kvark** [comment]
Oh, actually, this is about `NSError`, which is fixed in metal-rs but not published yet.

**Comment by kvark** [comment]
I took a capture, and I do see the depth-stencil attachment. The load op = don't care and store op = store, which is sort of weird (are you sure you don't want to clear the depth here?), but other than that it seems alright. If the depth attachment doesn't make it there on your end (or I'm looking at the wrong thing?), please investigate further. E.g. check what happens when you create the framebuffer in the first place.

**Comment by dati91** [comment]
So it seems like the `framebuffer_inner` is set in `begin_render_pass`, but we call the `bind_graphics_pipeline` before that.
Also a note: if I comment out [this part](https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/command.rs#L2500), the test is passing.

**Comment by kvark** [comment]
Oh I see. So you bind the PSO first, it's depth-stencil gets discarded, and then you start a render pass, but the original depth-stencil state is already gone. So we erroneously `warn!` as well as erase the ds descriptor. We should instead hold on to it. I'll take it from here, thanks for investigating this!

**Comment by dati91** [comment]
Running the `text` reftests result in
```
REFTEST INFO | 37 passing, 1 failing

Reftests with unexpected results:
	reftests/text/shadow-grey-transparent.yaml == reftests/text/shadow-grey-ref.yaml
```
Where the failing test differs in `662` pixels. The test uses `fuzzy(1,653)` values and the windows/vulkan pixel difference is `497`.
So I guess we can call this an "expected fail".
