### ISSUE TITLE
Assert in range alloc not passing causes application to exit

### ISSUE THREAD

**Issue by Napokue** [gfx-rs/gfx#2228]
Short info header:
- GFX version: https://github.com/gfx-rs/gfx/commit/58b9f28779a7224c795b2f70b003acafc404aa6f
- OS: Windows
- GPU: NVIDIA GeForce GTX 1080

In the file backend/auxil/range_alloc.rs:33 the assert is not passing. This causes the application to exit.

Command used: `cargo run --bin compute --features dx12 1 2 3 4`
Error: `panicked at 'assertion failed: (left != right)`

**Comment by Napokue** [comment]
Looking into it

**Comment by kvark** [comment]
Fixes by #2234
