### ISSUE TITLE
Reduce debug logging overhead in release

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2237]
See https://github.com/rust-lang-nursery/log/issues/112
This is a bit of an obscure source of overhead that we need to fix. It affects everything!

**Comment by Benjamin-L** [comment]
Specifying this feature in the hal backends leads to some really hard to debug behavior when trying to get `info!` output from a binary crate that depended on `gfx-hal-backend-vulkan`. This is detailed [here](https://github.com/rust-lang-nursery/log/issues/309). Is there a possibility of either making it optional or working it out in such a way that crates depending on this can still use `log` normally?

**Comment by kvark** [comment]
@Benjamin-L can't this be trivially worked around by just building in debug instead of release? The features we use should only affect the latter.

**Comment by Benjamin-L** [comment]
No, since ideally, I want `info!` to output in the release build.

**Comment by kvark** [comment]
I'd be fine with just switching it to `info!` on release in HAL. I agree this isn't a solution in general, but it's an acceptable compromise we can get now.

**Comment by Benjamin-L** [comment]
Is just not touching the `max_level_*` features in a library not a reasonable option? I feel like the choice of compile-time max logging level for the entire binary should just be left up to users of a library. @KodrAus from the `log` project mentioned the idea of implementing a custom wrapper around all the expensive log calls that gets disabled on release builds. Effectively re-implementing the `max_level_*` features for the backend libraries in a non-global way.

**Comment by kvark** [comment]
Yeah, this sounds reasonable to me. Let's have the application/library deciding the log cutting. Would you want to make a PR removing the features from here?
