### ISSUE TITLE
Setting the viewport

### ISSUE THREAD

**Issue by tomc1998** [gfx-rs/gfx#2256]
Short info header:
- GFX version: 0.17
- OS: Ubuntu 16.04
- GPU: Intel HD 3000

I can't find any way to set the viewport. I'm writing a 2D game, and in response to the window being resized, I alter the current orthographic projection matrix to match the size of the window - but I can't change the viewport, so the graphics just get squished into one corner of the window and the rest of the window remains black.

In gfx_gl I found the Gl struct, which has the Gl::Viewport() method - however, I can't seem to find any way to get a Gl instance to call this method with!

Any suggestions? Thanks.

**Comment by tomc1998** [comment]
Okay, so for anyone else struggling to find this seemingly arcane bit of info:

If you're using glutin & GL as your backend (if not then godspeed), in the gfx_window_glutin crate there's a function called `update_views` >> https://docs.rs/gfx_window_glutin/0.11.0/gfx_window_glutin/fn.update_views.html

You need to call this with mutable reference to your color views, depth views, and your GL window. This will update the viewport to be the correct size!

My call ended up looking something like

```
gfx_window_glutin::update_views(window, &mut self.data.out_col, &mut self.data.out_depth);
```

Where in 'self' I have an 'data' field which is my pipeline data, and out_col is the color view for that pipeline data, and out_depth is the depth view.

Note, this seems to prevent vsync, so maybe only do this when you need to resize the viewport, rather than every frame?

**Comment by msiglreith** [comment]
Thanks for posting the solution.
Viewport is set automatically using the dimension of the bound render targets,

> Note, this seems to prevent vsync, so maybe only do this when you need to resize the viewport, rather than every frame?

Actually shouldn't affect it, as it's basically just updating the dimensions.

**Comment by tomc1998** [comment]
Odd, i'm currently measuring frame times - before I ever called `update_views`, the frame times were pretty consistently 16ms, I assumed because of some sort of vsync when swapping buffers. Afterwards, the frame times never got over 2ms, and it's only because of my manual frame limiting that the game ran at 60FPS still. Any ideas?

**Comment by msiglreith** [comment]
See https://docs.rs/glutin/0.17.0/glutin/struct.ContextBuilder.html#method.with_vsync
for enabling vsync on your glutin context
