### ISSUE TITLE
gfx_device_gl::create() panics without an OGL context

### ISSUE THREAD

**Issue by Yatekii** [gfx-rs/gfx#2261]
Short info header:
- GFX version: gfx: 0.17.1, gfx_device_gl: 0.15.3, gfx_core: 0.8.2, gfx_gl: 0.5.0
- OS: Linux, Windows
- GPU:  Intel UHD Graphics 620 (Linux), Gigabyte OC GTX970 (Windows) 

```rust
gfx_device_gl::create(epoxy::get_proc_addr);
```
will panic if no OGL context is activated. This shouldn't happen and maybe this should therefore return an `Option<T>`.

The error results from the `Info` struct in `gfx_gl_device` which apparently can't handle empty string (or whatever no context results in).

Best,
Yatekii

**Comment by samsartor** [comment]
It seems like the specific `create` function mentioned here no longer exists. There is `Instance::create` but it looks like a short-term hack to support `portability`.

**Comment by kvark** [comment]
@samsartor it's there - https://docs.rs/gfx_device_gl/0.16.1/gfx_device_gl/fn.create.html

**Comment by jpryne** [comment]
This appears to be fixed in the current build, yes? Close?
