### ISSUE TITLE
`bind_vertex_buffer` inside render pass on dx12

### ISSUE THREAD

**Issue by fu5ha** [gfx-rs/gfx#2280]
Short info header:
- GFX version: commit e8254cd
- OS: Windows 10
- GPU: Nvidia GTX 980 ti

Project:
https://gitlab.com/termhn/game/blob/new-renderer-indirect/voxygen/src/renderer.rs#L364

When using vulkan backend, performs as expected with each draw call having bound a new vertex buffer, producing a normal looking image:
![image](https://user-images.githubusercontent.com/887711/43364015-4608f1c2-92c6-11e8-8e7b-35f454e0f53c.png)

When using dx12 backend, only the final bound vertex buffer is bound for all of the draw calls, producing:
![image](https://user-images.githubusercontent.com/887711/43364005-236df608-92c6-11e8-9b64-e5f920fc1e08.png)

**Comment by jackmott** [comment]
I'm thinking of taking a look at this. @termhn is this still an issue and does your code link still point to the right spot?

**Comment by termhn** [comment]
I believe it is still an issue and the code has moved a few lines down:

https://gitlab.com/termhn/game/blob/new-renderer-indirect/voxygen/src/renderer.rs#L405

**Comment by jackmott** [comment]
Yeah after digging into it, I think this is beyond me at the moment. So @msiglreith if you want to take a stab at it, feel free, I'm not going to be touching it at least for a while.

**Comment by termhn** [comment]
Haha that’s exactly what I concluded for myself :) thanks for taking a look
anyway

**Comment by kvark** [comment]
@termhn is this a blocker for you?

**Comment by termhn** [comment]
@kvark No, it’s not. The larger “blocker” for me is gl backend functionality, but ultimately neither of them are really blocking atm, just somewhat inconvenient.
