### ISSUE TITLE
Metal: vkGetPhysicalDeviceSurfaceCapabilitiesKHR returns invalid currentExtent

### ISSUE THREAD

**Issue by zeux** [gfx-rs/gfx#2322]
The following code returns -1 for both width and height when used immediately after initializing the instance, device and creating the swap chain:

```
    VkSurfaceCapabilitiesKHR scaps;
    VK_CHECK(vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physicalDevice, wd.presentationSurface, &scaps));

    unsigned int width = scaps.currentExtent.width, height = scaps.currentExtent.height;
```

The call doesn't error and other fields of scaps seem reasonable.

**Comment by kvark** [comment]
Wait, I think this is up to spec:
> currentExtent is the current width and height of the surface, or the special value (0xFFFFFFFF,0xFFFFFFFF) indicating that the surface size will be determined by the extent of a swapchain targeting the surface.

**Comment by zeux** [comment]
Interesting. We haven't seen this on any other device, but I guess if it's up to spec we'd need to handle this. I'll look into this further.

**Comment by zeux** [comment]
I've read the spec - while this is technically accurate, the spec does define the behavior per-platform - and AFAICT the only platform where 0xFFFF_FFFF is valid is Wayland based on the spec.

Of course MVK isn't really specified in the official extension list, so this is somewhat murky - not clear if it's okay to return 0xFFFF_FFFF. It feels like it's more appropriate to return the current view size...

**Comment by kvark** [comment]
I don't see any blockers for us to return the actual size. Will get this sorted tonight.
