### ISSUE TITLE
Simplify the resize logic of Quad example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2326]
The resize logic is super generic currently. It takes into account the fact that swapchain may need a different format, which forces the pipeline states to be recreated, then render passes, framebuffers, etc - imposes a ton of headache. I don't think it's worth the complexity of the code. This is our first and simplest example, we can still have other examples showing a more complicated resize functionality. For the Quad, it should be sufficient to simply assert that the format PSO was created for is still supported.

**Comment by termhn** [comment]
Agreed, this was a source of a lot of confusion for me initially.

**Comment by ZeGentzy** [comment]
Wouldn't this mean just copying most of the things in `swapchain_stuff` out and into `main`? I hardly see how it would make it less complex. Also, we would still have to recreate the framebuffers because of the possible varying extent, or should we assert that too?

Instead, how about a better name for the function `swapchain_stuff` (someone else will have to come up with that better name however) and/or a comment explaining why we have to recreate all the stuff, as to minimize confusion?

**Comment by kvark** [comment]
> Wouldn't this mean just copying most of the things in swapchain_stuff out and into main

Yes. You can then go through the initialization code without jumping back and forth.

> Also, we would still have to recreate the framebuffers because of the possible varying extent, or should we assert that too?

I think framebuffers are the only thing that would need to be re-created.

**Comment by jackmott** [comment]
I'm taking a stab at this, first issue I run into is with `set_layout`:
```
error[E0382]: use of moved value: `set_layout`
   --> examples/quad/main.rs:622:42
    |
418 |         device.create_pipeline_layout(Some(set_layout), &[(pso::ShaderStageFlags::VERTEX, 0..8)]);
    |                                            ---------- value moved here
...
622 |     device.destroy_descriptor_set_layout(set_layout);
    |                                          ^^^^^^^^^^ value used here after move
    |
    = note: move occurs because `set_layout` has type `back::native::DescriptorSetLayout`, which does not implement the `Copy` trait
```

What would be the best approach to resolve this?

**Comment by kvark** [comment]
@jackmott awesome! :clap: 
> What would be the best approach to resolve this?

`create_pipeline_layout` doesn't actually need to own it, so you can pass `iter::once(&set_layout)` instead of `Some(set_layout)`

**Comment by jackmott** [comment]
@kvark   Was away for the weekend, taking a look again today.  To recreate the framebuffers do I also need to recreate frame_images?  Do I need to recreate the swapchain to do this?  I get borrow checker errors if I try to recreate the framebuffers with the existing backbuffer.

Sorry for the all the questions hopefully the rate will slow down as I get more familiar!

**Comment by kvark** [comment]
On resize, you have to recreate the swapchain. This means you'll have new images, and thus you have to re-create the framebuffers.

**Comment by jackmott** [comment]
thanks
