### ISSUE TITLE
[Feature Request] 2D Vector Graphics Supporting

### ISSUE THREAD

**Issue by tuxzz** [gfx-rs/gfx#2327]
````gfx-rs```` may add a set of 2D Vector Graphics API like ````Direct2D````/````OpenVG````/````Skia````/````Cairo````.

It's common to use a 2D Vector Graphics API in GUI Applications, 3D or 2D games.
It can be used to draw lines, shapes, or text, on screen or a off-screen surface. The off-screen surface may be passed to a shader and do some processing. 

````Direct2D```` have good API and performance but it's Windows only. ````Skia```` is cross platform and have a nice performance but it's hard to integrate with gfx.

It's takes really a lot of coding work if the 2D API isn't integrated with other parts, especially when the render target is a off-screen surface and there are various graphics backends.

**Comment by kvark** [comment]
@tuxzz I see it as a purely ecosystem question. There is no value in having the 2D graphics as a core feature of gfx-rs. It provides low-level access to GPU, and you should be able to build a 2D vector library on top of it. Speaking of which, to what extent does https://github.com/nical/lyon already cover that? cc @nical

**Comment by anderejd** [comment]
Another options which I'm personally looking forward to is being able to run webrender on top of gfx-rs. That will provide many useful 2d drawing primitives for building GUIs. I believe this is where one can follow the progress: https://github.com/szeged/webrender

@kvark Can you give an update on how that is coming along?

**Comment by kvark** [comment]
@anderejd WR is not an alternative to vector 2D graphics. WR itself needs a solution for this (currently leaving it to the client to figure out, while developing a `pathfinder`-based code path).

> @kvark Can you give an update on how that is coming along?

WR has reached the reftest coverage of non-gfx path, but there are a few (major) things to address before it is shippable (e.g. efficient texture uploading).

**Comment by nical** [comment]
@tuxzz I don't think gfx-rs is the right place to build a 2D rendering API, but if 2D rendering is something you want to work on and since it's a topic very close to my heart, let me know. I'm happy to bounce ideas around.
This is definitely something that could be built on top of gfx-rs (just like Direct2D is built on top of D3D11/12).

**Comment by nical** [comment]
Vulkan doesn't have vector graphics specific extensions as far as I know, but it gives you access to a lot of generic tools on the GPU that you can take advantage of to make a good vector graphics renderer.
I agree that there is a gap. It's a tough one to fill, but if you want to do something I'll try to help, especially if you are looking for interactive/game type things where I think that we can do better than D2D/Skia at the API/architectural level. Maybe a good start could be to create a repo somewhere and brainstorm some ideas (it's really out of scope for the gfx-rs folks).

**Comment by kvark** [comment]
Wow, an org plus RFC repo? Must be aiming pretty high with this :)
If somebody is jumping on that trait, maybe they could _just_ implement [Moz2D](https://wiki.mozilla.org/Platform/GFX/Moz2D) with gfx-hal? That could be helpful for Gecko.
As for this issue, it's been stated multiple times that it's out of scope, so I'm closing it.
