### ISSUE TITLE
make reftests fails on clear-image

### ISSUE THREAD

**Issue by jackmott** [gfx-rs/gfx#2358]
Short info header:
- GFX version:master
- OS:linux
- GPU:nvidia 1070

```
 Scene 'transfer':
                Test 'fill-last' ...    ran: PASS
                Test 'fill-first' ...   ran: PASS
                Test 'clear-image' ...  ran: FAIL [127, 127, 127, 127]
```

**Comment by kvark** [comment]
Looks like a precision error, since the expected values are 128 and we clear to 0.5. I guess we could be clearing to something like 0.5001 for confidence?
