### ISSUE TITLE
Support for buffer/texture memory mapping

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#236]
Following @eddyb [request](https://botbot.me/mozilla/rust-gamedev/msg/19925287/) and @nical [comment](https://github.com/gfx-rs/gfx-rs/issues/113#issuecomment-50419896), we need to provide the mapping ability for our GPU containers. RAII would be great.

**Comment by ishitatsuyuki** [comment]
There's some concerns with GL versions on buffer mapping. It seems the mapping system is implemented for the GL backend, but does it handle ES2 which has no mapping method or GL2 which doesn't accept `glMapBufferRange`?

**Comment by kvark** [comment]
I believe this is implemented now in a series of PRs by @Bastacyclop , finishing on the screenshot logic in the example in #1478
