### ISSUE TITLE
Refine specialization constants API

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2382]
#2381 makes them just ranges into raw `[u8]` data. This isn't very convenient.

One way to improve it could be to carry the data inside the specialization constant instead of storing it separately:
```rust
pub struct Specialization<V: Borrow<[u8]>> {
    /// Constant identifier in shader source.
    pub id: u32,
    /// Value to override specialization constant.
    pub value: V,
}
```
I made such an attempt in [this branch](https://github.com/kvark/gfx/commit/ca1e4bfa5a6e91174d9a041a83e79356a7ceccf7) but it appears to be adding a level of indirection that isn't very convenient for either portability or Vulkan backend.

Another direction of improvement would be adding a trait that allows conversion of primitive types (like `f32` or `u32`) to a specialization constant, because otherwise using them directly is very inconvenient.

**Comment by kvark** [comment]
I don't have any extra input on it, but given it's a potentially API breaking change, we need to resolve this somehow by 0.2.

**Comment by omni-viral** [comment]
Using `Borrow` trait for owned values isn't really nice for API. For instance, `&Vec<u8>` doesn't fit here.

**Comment by kvark** [comment]
@omni-viral we use `Borrow` everywhere else. Could you clarify on why `&Vec<u8>` isn't fitting?

**Comment by omni-viral** [comment]
`Vec<u8>` **does** implement `Borrow<[u8]>`
`&'a Vec<u8>` **does not** implement `Borrow<[u8]>`

**Comment by kvark** [comment]
@omni-viral oh, I see now what you are trying to say. `Borrow` trait for **owned** values isn't really nice. That's true, and that's why we are using `Deref<Borrow<..>>` everywhere, not owned borrow.

To be fair, in case of `Vec<u8>` you can just coerce it to a slice, and [it works](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=511df10f8ba22fb7c184977c5f57b8bd).

**Comment by omni-viral** [comment]
`AsRef` is implemented transitively for references.
But then `AsRef<[u8]>` is not implemented for `&[u8]`

Let me illustrate it with [this snippet](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5d6a5a66d1dd09eba1336487df639f4)

**Comment by omni-viral** [comment]
> Deref<Borrow<..>>

Never saw such bound in gfx-hal API?
