### ISSUE TITLE
Metal: Texture arrays with 1 layer don't work

### ISSUE THREAD

**Issue by zeux** [gfx-rs/gfx#2396]
It looks like Metal backend infers the type of the image at the call site of create_image, and considers images with 1 array layer 2D:

https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/device.rs#L2083-L2117

Unfortunately, this doesn't work with texture arrays with 1 layer. For these, the application needs to create an image with arrayLayers=1, and create an image view with viewType = VK_IMAGE_VIEW_TYPE_2D_ARRAY. In Metal, what should happen is that a MTLTextureType2DArray is created.

Failure to do this produces validation errors like this:

> validateFunctionArguments:3377: failed assertion `Fragment Function(main0): incorrect type of texture (MTLTextureType2D) bound at texture binding at index 1 (expect MTLTextureType2DArray) for NormalMap[0].'

These happen because the application creates an array shader view (VK_IMAGE_VIEW_TYPE_2D_ARRAY), the pipeline layout uses an array descriptor, the shader uses an array image, but Metal backend substitutes a 2D image instead.

There might not be a nice solution to this. I think MoltenVK delays the creation of the image until the creation of the view and has to deal with several different possible ordering situations; it may also assume that an image view is created before the data is uploaded to the image?

**Comment by kvark** [comment]
Thanks for filing the issue and expression your investigation notes!
I think we'll force the backing texture to have 2D array type if `VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT` was provided. One can always create regular 2D views from an array, but not the other way around.

**Comment by zeux** [comment]
The spec says that this flag doesn't work for 2D images unfortunately:

> If flags contains VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT, imageType must be VK_IMAGE_TYPE_3D

**Comment by kvark** [comment]
Oops, I missed that bit. Can't we always create a 2D array texture then, just in case?

**Comment by zeux** [comment]
Actually... am I off base here? I realized that the validation error was related to another issue that was misleading me. It looks like gfx-rs creates a texture view for a Vulkan image view, and that seems like it correctly creates 2D array view for a 2D texture in this case? Let me double check this but I feel like maybe the issue was a red herring. https://developer.apple.com/documentation/metal/mtltexture/1515409-newtextureviewwithpixelformat?language=objc seems to suggest you can reinterpret between 2D and 2D arrays in both directions.

**Comment by kvark** [comment]
Uh, I instantly assumed Metal doesn't allow you to have an array view out of a non-array texture. cc @msiglreith Thanks for clarifying this, looking forward for more info.

**Comment by zeux** [comment]
I've double checked this and I believe gfx-rs is working correctly here. The validation issue was a red herring that was related to some Vulkan-on-macOS-packaging on our end (shaders were stale I think). We've seen something sort of similar on MoltenVK so I jumped to conclusions, sorry about that. I'll close this.
