### ISSUE TITLE
another test scenario: XENIA

### ISSUE THREAD

**Issue by Rastafabisch** [gfx-rs/gfx#2405]
After you already successfully got RPCS3 and dolphin running (btw: are those Vulkan enabled implementations available for download?) the next emulation hurdle you might want to take might be the XENIA XBox360 emulator which on it's websites states that there won't be macOS support unless vulkan would be available. It's available here: http://xenia.jp

I really admire your work and am following the process as the projects compatibility keeps growing.

**Comment by kvark** [comment]
Thanks for your support @Rastafabisch !

We've already reached out to Xenia devs in https://github.com/xenia-project/xenia/issues/596 and discussed the first blockers. The first one got filed on both sides as https://github.com/xenia-project/xenia/issues/1213 and https://github.com/gfx-rs/portability/issues/140

If we discover more specific issues, we should make them:
  - in this repository, if they are about technical bits/implementation
  - in [gfx-portability repository](https://github.com/gfx-rs/portability), if they are about C wrapper or target Vulkan applications

With this in mind, I'm going to close this issue. In the meantime, you might want to check https://github.com/gfx-rs/portability/issues/125 for the big picture. You are also welcome to continue discussion and/or file more specific issues.

> btw: are those Vulkan enabled implementations available for download

You can try out packaged releases from https://github.com/gfx-rs/portability/releases. The way to do this is typically just defining `VK_ICD_FILENAMES=<path_to_portability.json>` for a program that was linked properly against Vulkan SDK.
