### ISSUE TITLE
Source Code Locations

### ISSUE THREAD

**Issue by JonErikDSuero** [gfx-rs/gfx#2410]
(This is not really an Issue.)

I cannot find the open source repositories for `gfx_core`, and other crates. The only place I can see the source code is in the documentation:
e.g. https://docs.rs/gfx/0.17.1/src/gfx/factory.rs.html#102-293

Could anyone please point me to the location of the source code? I'm looking specifically for the `gfx::traits::FactoryExt::link_program`.

Thank you!

**Comment by msiglreith** [comment]
Hi @JonErikDSuero 
the crates are located here: https://github.com/gfx-rs/gfx/tree/pre-ll/src (crate for each subfolder)
That's the `pre-ll` branch for the 'old' API which is currently hosted on crates.io and docs.rs
See the corresponding release branches if you want to target a specific version

The linked factory.rs is located in `render/factory.rs` (`render` is the high level crate for `core`, where the `Ext` traits are defined).

**Comment by JonErikDSuero** [comment]
@msiglreith Ah! I finally understood the comment in README. Thank you!
