### ISSUE TITLE
Small leak in Swapchain::present when using gfx-backend-metal

### ISSUE THREAD

**Issue by mtak-** [gfx-rs/gfx#2412]
Short info header:
- GFX version: ll
- OS: macos
- GPU: Radeon Pro 455 2048 MB

Running essentially this code: https://github.com/grovesNL/gfx-hal-tutorial/blob/master/src/15_hello_triangle.rs

Every frame leaks a few bytes. I tried wrapping the `present` call in a `autoreleasepool` and the leak went away. Instruments points to `queue.raw.new_command_buffer()` as the source of the persistent bytes.

**Comment by kvark** [comment]
Thanks for the issue! The little block of code inside `present` that gets a command buffer and commits it - needs to be wrapped into an autorelease pool.

**Comment by kvark** [comment]
Fixed by #2411
