### ISSUE TITLE
quad example flickers during resize on macos/ios using metal backend

### ISSUE THREAD

**Issue by mtak-** [gfx-rs/gfx#2414]
Short info header:
- GFX version: master (14789bb04f192a19587cf40004addf8f0c62d50f)
- OS: iOS/macos
- GPU: Radeon Pro 455 2048 MB, and A11 Bionic (iOS)

This is what @kvark had to say about it
> macos swapchain handing is pretty hacky, but it would be nice to make it work as if it's not hacky:)
> for the quad example, first need to check if we report the OutOfDate swapchain so that the quad example keeps re-creating it
> and then verify that the re-creation doesn't causes flicker

**Comment by mtak-** [comment]
A related problem is that OSX enters an inner event loop during resize https://github.com/tomaka/winit/issues/459, causing multiple resize events to happen before `poll_events` returns. Moving the swapchain recreation/present logic into `poll_events` predictably makes the flicker more noticeable.

`Swapchain::present` doesn't currently ever return an error with metal. Adding this code to `CommandQueue::present` shows no errors even tho there's still a flicker. FWIW this is much more noticeable on iOS than macos.
```rust
command_buffer.wait_until_completed(); 
println!("command buffer status: {:?}", command_buffer.status() as u32);
assert!(command_buffer.status() as u32 != metal::MTLCommandBufferStatus::Error as u32);
assert!(unsafe { let x: *mut () = msg_send![command_buffer, error]; x as usize == 0});
```
That error checking also makes `present` synchronous, which seems undesirable.

I'm too much of a vulkan newb to say for sure, but I think this is a gfx-backend-metal or winit bug instead of a `quad` bug.

**Comment by kvark** [comment]
@mtak- how do you resize the window on iOS? O_o

> Swapchain::present doesn't currently ever return an error with metal. 

We could replace this code to return an error:
```rust
            if let Ok(drawable) = swapchain.borrow().take_drawable(index) {
                command_buffer.present_drawable(&drawable);
            }
```

> A related problem is that OSX enters an inner event loop during resize

This is quite annoying on our side :(

**Comment by mtak-** [comment]
@kvark turn the device 90 degrees :P.

I made a pull request to change that to return an error, but that fixes nothing as far as i can tell.

Maybe this code in window.rs `build_swapchain` is related. Still poking at it
```rust
// when resizing, this trick frees up the currently shown frame
// HACK: the has_swapchain is unfortunate, and might not be
//       correct in all cases.
drawable.present();
None
```

**Comment by kvark** [comment]
Indeed, that's nicely spotted!
yes, we present so that the textures from the previous swapchain are not shown any more.
We could technically copy the contents from an old texture to the new one (and clear the new one) before doing this present, I think that would help.
