### ISSUE TITLE
Quad example thinks window is 1x1 pixel when using Vulkan backend under Wayland

### ISSUE THREAD

**Issue by hexaglow** [gfx-rs/gfx#2421]
Short info header:
- GFX version: Commit `a449dc5`
- OS: Fedora 28 (using Wayland)
- GPU: Intel UHD 620

When using the Vulkan backend, the drawn area is only 1x1 pixel in size when running the quad example. This issue does not occur when using the GL backend. The window is the 'correct' size, I can tell because the titlebar is the right width and the resize grab handles appear in the right places. However the window is almost totally transparent apart from a single pixel in the upper-left corner.

Whenever I resize the window the following message is printed in the console output:

    SwapchainConfig { present_mode: Fifo, format: Bgra8Srgb, extent: Extent2D { width: 1, height: 1 }, image_count: 4, image_layers: 1, image_usage: COLOR_ATTACHMENT }

**Comment by hexaglow** [comment]
I have just re-tested this under X and it works fine. So this issue only applies to Wayland.

Also of note: I am getting correct resize events under both X and Wayland, e.g.

    resized to LogicalSize { width: 905.0, height: 768.0 }

but the `extent` of the `SwapchainConfig` always reads (0, 0) under Wayland

**Comment by msiglreith** [comment]
Thanks for reporting. That's purely an issue of the quad sample. Wayland allows us to specify the swapchain size arbitrarily and actually has no current size. Atm we just use the minimum then. We should rather take the expected window size and clamp it to fit the swapchain extent limits.
