### ISSUE TITLE
Appears to be no way to copy a texture to CPU memory

### ISSUE THREAD

**Issue by Vurich** [gfx-rs/gfx#2423]
I want to add the ability to save screenshots/record videos to my rendering engine (it's aimed at generative art so saving screenshots is a core feature). I can render to a texture but there doesn't seem to be any way to use `glReadPixels` or a related function to copy from a texture to a local buffer. I do not know enough about OpenGL to implement this myself (I used to use raw OpenGL but I only ever did simple stuff), but some quick Googling showed up `glReadPixels` and `glReadPixel`, neither of which appear in `gfx` at all.

I don't know whether I'm just missing a way to load information back from the GPU or whether it's just not implemented.

**Comment by kvark** [comment]
@Vurich there is an issue template here for a reason. In particular, you need to specify what version of gfx-rs you are using.
For 0.17, you may want to look at the `gamma` example that has a [screenshot](https://github.com/gfx-rs/gfx/blob/29d6f8aab6203bb460c3f2e867fa01c826d7af65/examples/gamma/main.rs#L129) function.

**Comment by Vurich** [comment]
Thanks, it looks like the `Reader` type was the missing piece that I was looking for. Apologies for not using the template.

**Comment by kvark** [comment]
Awesome, I suppose it's resolved then.
