### ISSUE TITLE
Unify error types

### ISSUE THREAD

**Issue by ntgraff** [gfx-rs/gfx#2436]
Currently, there are multiple error types, some using the failure crate, and some implementing the Error trait. I propose that all types implement Error and to remove the failure crate. or make every error type the failure crate type. This may be a rookie question, but if it is already mostly using the Error trait, why keep the failure dependency and not use the standard library way?

**Comment by bjadamson** [comment]
Someday this may offer a better alternative:
https://internals.rust-lang.org/t/pre-rfc-anonymous-variant-types/8707/70

Even if this RFC is never passed anonymous unions in general would be another possible solution.

**Comment by omni-viral** [comment]
For error handling anonymous enums that remove duplicates would be much better. Otherwise you won't be able to use `?` on error type in function that return anonymous enum with that type
