### ISSUE TITLE
Handle extensions and Vulkan API changes

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/gfx#2456]
As mentioned in https://github.com/gfx-rs/gfx/issues/2100#issuecomment-394102730 and partially in #1928, we need a way to handle the version of Vulkan and extensions HAL matches. Like #1928 we need a way to enable features, but more generally we need a way to handle `pNext` for extensions and support extensions which have been incorporated into Vulkan core for a particular spec version.

**Comment by kvark** [comment]
@omni-viral I don't think we need to have the backends diverging in the extensions *they know about* (not necessarily support). So we can have a benefit of knowing all the new extension enum variants and types at the type system level, and we can just expand gfx-hal to accept this extra information with a big warning saying that one has to check for the supported features and opt into some when instantiating an adapter.

**Comment by omni-viral** [comment]
@kvark so what exactly you propose?

**Comment by kvark** [comment]
@omni-viral just grow our structures/enums/types with the new extensions we are aware of.

**Comment by omni-viral** [comment]
@kvark How backends will report which extension is supported? Would backends just panic if struct from unsupported extension is used? Should we implement next-chain like structure for extensions or just add more fields to structures introducing breaking change each time?

**Comment by grovesNL** [comment]
In general, for enums we expect to grow, we could use `non_exhaustive` to avoid breaking changes.

Backends already list supported features on the adapter (`hal::Features`) so we would continue to expand that (or split it if we expect to run out of bitflags). For conditionally enabled struct fields it seems like it would be fine to accept `Option` (requiring `None` if the feature isn't supported).

Although if we do need to support `pNext` chains, we could have a non-exhaustive `FeatureStruct` enum with all known variants, and the caller would pass `&[FeatureStruct]` based on supported features. Then we can `Err` if an unsupported `FeatureStruct` was passed.

**Comment by kvark** [comment]
The reason Vulkan has extensions is to test new functionality provided by IHVs *without* affecting the core spec. Once an extension is tried out and approved, it becomes a part of the core spec.

Our situation is different. We don't have independent graphics backend developers who want to try out new stuff, as far as I'm aware. And we have Semver-tracked APIs. Once we decide to add a new piece of functionality, we just add it to the code, with appropriate limits, features, and new entry points.

If it breaks the API, so be it - we'll bump the version accordingly. If somebody needs to depend on it, we make a release. This is a standard workflow of Rust libraries, there is nothing new that needs to be invented here with regards to Vulkan extensions.

If the goal is to make the APIs more robust to such changes, there are general Rust techniques to do so:
  - don't have structures fully public, instead provide accessor methods that could be extended
  - `non_exhausive` enums for things like `Format`
  - pile up a number of breaking changes before publishing

That being said, I think this issue can be closed.

**Comment by omni-viral** [comment]
@kvark would that mean that gfx-hal will not have support for anything Vulkan provides until it goes into core spec?
No raytracing in near future?

**Comment by kvark** [comment]
@omni-viral no, that's not what I mean.
gfx-hal doesn't need to be restricted to Vulkan core. Raytracing can be done today in some form.

What I'm saying is that Vulkan extensions are needed because of the way Vulkan is developed, and our project has different workflow, organization, and doesn't have to reflect the extension model.

If we need something, we just add an implementation for it.

**Comment by grovesNL** [comment]
Sounds good to me. I think the explanation here is pretty good, and should be a good reference for now if there are any questions about how extensions are handled (we should probably move some of these points to the wiki later)
