### ISSUE TITLE
Refactor value name of ChannelType for consistency

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2458]
```rust
pub enum ChannelType {
    /// Unsigned normalized.
    Unorm,
    /// Signed normalized.
    Inorm,
    /// Unsigned integer.
    Uint,
    /// Signed integer.
    Int,
    /// Unsigned floating-point.
    Ufloat,
    /// Signed floating-point.
    Float,
    /// Unsigned scaled integer.
    Uscaled,
    /// Signed scaled integer.
    Iscaled,
    /// Unsigned normalized, SRGB non-linear encoded.
    Srgb,
}
```

Should they remove prefix *I* for those **Signed** value because `Float` and `Int` are not consistent with `Unorm` and `Inorm`? For example just let `Inorm` be `Norm`.

https://github.com/gfx-rs/gfx/blob/bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7/src/hal/src/format.rs#L195

**Comment by kvark** [comment]
I think we should actually go the *other* way: make all the I/U (or even S/U) consistent across types, i.e. `Int -> Sint`. That would be closer to Vulkan and also kinda make sense.

**Comment by Michael-Lfx** [comment]
Ok. I will submit a PR for that later.
