### ISSUE TITLE
There appears to be an erronous dev-dependency in hal

### ISSUE THREAD

**Issue by eugene2k** [gfx-rs/gfx#2466]
https://github.com/gfx-rs/gfx/blob/f288599e34e536ee406edd3cab81589ab29dc784/src/hal/Cargo.toml#L28-L29

**Comment by kvark** [comment]
The empty backend is hooked up here in order for doctests to compile, e.g. https://github.com/gfx-rs/gfx/blob/f288599e34e536ee406edd3cab81589ab29dc784/src/hal/src/window.rs#L25

**Comment by eugene2k** [comment]
ah, that makes sense! It looked like a circular dependency with `empty` depending on `hal` and `hal` on `empty`
