### ISSUE TITLE
Macros require explicit `use gfx;` in Rust 2018

### ISSUE THREAD

**Issue by gralpli** [gfx-rs/gfx#2474]
This is only a small thing and I'm not sure if it's worth an issue, but it took me a while to figure out how to make my code compile. I'm also a beginner with _gfx-rs_.

Rust 2018 got rid of `extern crate` and made some changes to how paths are interpreted in `use`-statements. From a submodule and by default, you can't access `gfx` via `use super::gfx;` anymore, but this is what some macros (like `gfx_pipeline!`) are trying which results in a compiler error. You have to explicitly `use gfx;` in the top-level-module to make the compiler happy which I think shouldn't be needed.

Try this with Rust 2018:

```rust
use gfx; // shouldn't be necessary
use gfx::*;

gfx_defines! {
    vertex Vertex {
        pos: [f32; 2] = "a_Pos",
        color: [f32; 3] = "a_Color",
    }

    pipeline Pipeline {
        vbuf: VertexBuffer<Vertex> = (),
        out: RenderTarget<gfx::format::Srgba8> = "Target0",
    }
}

fn main() { }
```

**Comment by GabrielMajeri** [comment]
This issue is about the `pre-ll` API, which is no longer updated. The new `gfx-hal` [macros](https://docs.rs/gfx-hal/0.5.3/gfx_hal/macro.spec_const_list.html) properly refer to the `hal` crate without requiring `use gfx`
