### ISSUE TITLE
How to use feature auto-capture

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2479]
I find it that `auto-capture` is using `MTLCaptureManager` which supports Capture GPU Frame of Xcode. How to use it when running Dota2 due to no launching from Xcode?

**Comment by kvark** [comment]
@Michael-Lfx you can only use it *when* running from XCode. Also, it doesn't make sense for Dota - frame boundaries trigger capture automatically. It's useful for workloads that are either compute or don't present frame, mostly Vulkan CTS. Here are instructions on how to set up XCode to run anything external, I have all the things set up this way (Dota, Vulkan CTS, Filament, etc):

![xcode-capture](https://user-images.githubusercontent.com/107301/48951515-d0692d80-ef0c-11e8-8b57-16a01c0b2274.png)
ode.

**Comment by Michael-Lfx** [comment]
I think it's better to make it as a wiki page for new latecomers.

**Comment by kvark** [comment]
I think it'd be good to have this sort of documentation to be a part of the repo, e.g. by existing in the backend Readme, or even as comments in Cargo.toml.

**Comment by Michael-Lfx** [comment]
Another proposal: leaving a fine-configured project/workspace in examples to save time.

**Comment by Michael-Lfx** [comment]
Unfortunately I failed to make Capture GPU Frame work because no matter quad or colour-uniform they crashed ASAP when Build & Run is pressed. 
![2281543485351_ pic_hd](https://user-images.githubusercontent.com/9588926/49214024-aa59f680-f400-11e8-8369-e4b3186a5414.jpg)
<img width="530" alt="image" src="https://user-images.githubusercontent.com/9588926/49214061-c2ca1100-f400-11e8-9f5a-0868d19acc77.png">
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/9588926/49214783-52bc8a80-f402-11e8-99e8-f5eef1e18462.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/9588926/49214799-5c45f280-f402-11e8-9300-24c8093bb1d5.png">
<img width="896" alt="image" src="https://user-images.githubusercontent.com/9588926/49214833-6bc53b80-f402-11e8-846a-8cb40ff669ea.png">

With or without "Main Thread Checker" quad crashed anyway. My codebase is `6fa48b1209ee19b98abb10c0feecff9acbf44b29` which log is Merge #2484.

My os is macOS 10.14 and macOS 10.13.5. Both of them(iMac 5k 2015 later and macbook Pro 2015 mid) crash at the same location.

Help, please. @kvark @grovesNL
