### ISSUE TITLE
Y coordinate inversion requirement of glsl coordinate system to SPIR

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2480]
Is it required to invert the y coordinates of vertex shader when using glsl 450 shaders then converting to SPIR data and then feed them to hal + metal + vulkan backend?

**Comment by kvark** [comment]
Yes. If your shaders are written for GL and you need to run them through Vulkan or gfx-rs, you've got to do this Y inversion somewhere. Preferably, at shader conversion time.

**Comment by Michael-Lfx** [comment]
The log of examples/colour-uniform indicates that SPIR-Cross will add Y-axis for Metal. So it confuses me with you previous answer because I see no magic about Y inversion in their shader. Is the SPIRV-Cross crate is modified by @grovesNL to handle Metal case specially?

Here is the log.

```
DEBUG 2018-11-26T13:36:08Z: gfx_backend_metal::device: SPIRV-Cross generated shader:
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

constant float scale_tmp [[function_constant(0)]];
constant float scale = is_function_constant_defined(scale_tmp) ? scale_tmp : 1.2000000476837158203125;

struct main0_out
{
    float2 v_uv [[user(locn0)]];
    float4 gl_Position [[position]];
};

struct main0_in
{
    float2 a_pos [[attribute(0)]];
    float2 a_uv [[attribute(1)]];
};

vertex main0_out main0(main0_in in [[stage_in]])
{
    main0_out out = {};
    out.v_uv = in.a_uv;
    out.gl_Position = float4(in.a_pos * scale, 0.0, 1.0);
    out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
    return out;
}
```

**Comment by Michael-Lfx** [comment]
> spirv_cross has an `invert_y` boolean in each of GLSL/HLSL/MSL `CompilerVertexOptions`, which adds a transformation to invert the y-axis.
> 
> You can see this line added in the shader above:
> 
> ```c++
> out.gl_Position.y = -(out.gl_Position.y);    // Invert Y-axis for Metal
> ```

What about Depth Range adjust for Metal? Is clip-space related to  Depth Range conversion?

https://github.com/KhronosGroup/SPIRV-Cross/blob/510e1475c67eb6ceffbf3f189242e7bd7e130c80/spirv_msl.cpp#L3528-3530

**Comment by grovesNL** [comment]
@Michael-Lfx yes, that handles the depth conversion. In spirv_cross the option is called `transform_clip_space`. I'm not sure but I don't think we apply it in gfx yet.

**Comment by Michael-Lfx** [comment]
> @Michael-Lfx yes, that handles the depth conversion. In spirv_cross the option is called `transform_clip_space`. I'm not sure but I don't think we apply it in gfx yet.

Thanks. Then back to the original question: should I add anti-conversion for glsl 450 which will runs on gfx finally to neutralize the effect from spir-cross?

**Comment by kvark** [comment]
@Michael-Lfx You appear to be mixing up two different things here, hence getting confused by my answer (or I'm just being confused myself). Your question was about GLSL->SPIRV. Typically GLSL is written for GL, which has different rendering space from Vulkan, hence you'd need to adjust for it (with whatever *you* are using for GLSL->SPIRV), and that's precisely what I said. gfx-rs doesn't care that much, our API accepts SPIR-V and cares most about SPIRV->Anything. And this is where we pass appropriate flags to spirv-cross.

**Comment by kvark** [comment]
I believe this is resolved. Please re-open otherwise.
