### ISSUE TITLE
Depth range conversion requirement of glsl coordinate system to SPIR

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2481]
Same background as #2480 . Should we add something like `gl_Position.z = (gl_Position.z + gl_Position.w) / 2.0;` in the end of vertex shader to make it right for Vulkan and Metal?

**Comment by kvark** [comment]
Yes.

**Comment by kvark** [comment]
I believe this is resolved. Please re-open otherwise.
