### ISSUE TITLE
missing docs about hardcode value of buffer_alignment of metal

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2482]
As #2024 is considering compute shader case. How about rendering? Now `buffer_alignment` hardcodes to 256 or 64 based on what strategy. Is that some docs to explain it?
https://github.com/gfx-rs/gfx/blob/84104892d44f1e8245dc53698a72d006435f3722/src/backend/metal/src/device.rs#L427

**Comment by kvark** [comment]
All of those fields in `PrivateCapabilities` are derived from Metal feature set tables: https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf

That is to say, these values aren't hidden, they are exposed via our HAL limits: https://github.com/gfx-rs/gfx/blob/84104892d44f1e8245dc53698a72d006435f3722/src/backend/metal/src/device.rs#L604-L608

So I don't think this requires any extra documentation. Users are expected to obey the exposed limits, and that's about it.

**Comment by Michael-Lfx** [comment]
Got it. Thank you kvark. I owe you a lunch.
