### ISSUE TITLE
No image_barrier and pipeline_barrier is ok for Metal

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2486]
https://github.com/gfx-rs/gfx/blob/6fa48b1209ee19b98abb10c0feecff9acbf44b29/examples/colour-uniform/main.rs#L1211-1221

Block like above can be removed and works fine when running on macOS. Should they be marked with target_os feature?

**Comment by kvark** [comment]
The fact that *some* backends can ignore *some* instructions/state is their *implementation detail* (much like a Vulkan driver can ignore those). The application code doesn't need to know about that, it should target Vulkan semantics.

Things will change with BAL #2249 , but today the situation is clear.

**Comment by Michael-Lfx** [comment]
Got it. Thank you.
