### ISSUE TITLE
Add shader reflection

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2496]
There are lots of code used to create `PiplineState` and `DescriptorSetLayout` inside `examples/`. IIRC, both Vulkan and Metal supports shader reflection. I think it can help to reduce those scary PipelineState init code. Is it reasonable to add inside gfx-hal or framework based on it like wgpu or game engine, etc.?

**Comment by omni-viral** [comment]
How Vulkan supports shader reflection? Is there a function to query info from shader module?

**Comment by msiglreith** [comment]
Relection would be provided via SPIRV analysis, which is IMO out of scope of gfx-hal.
You might want to look at [`spirv-reflect`](https://github.com/gwihlidal/spirv-reflect-rs) which provide such utility.

**Comment by kvark** [comment]
I think this is clearly out of scope here. There are tools to work with SPIR-V, we don't stand in the way of using them.
