### ISSUE TITLE
Question about depth

### ISSUE THREAD

**Issue by Merlotec** [gfx-rs/gfx#2498]
I'm having rouble getting depth testing to work properly. When I use a tutorial example, any vertex outside certain z values is not rendered at all. I have tried changing the depth range in the pso::Viewport struct and using set_depth_bounds() using the command buffer, but to no avail. What is the best way to set up depth so that all the vertices are rendered no matter what their z values are?

**Comment by msiglreith** [comment]
You can use depth clamping to enable the graphics driver to move all vertices into the far or near plane if they are out of bounds. This gates by a feature (https://github.com/gfx-rs/gfx/blob/master/src/hal/src/lib.rs#L127) and enabled in the rasterizer (https://github.com/gfx-rs/gfx/blob/master/src/hal/src/pso/graphics.rs#L214). But usually this is controlled via the near and far paramters of the projection matrix ([`cgmath sample`](https://github.com/msiglreith/gfx_ocean/blob/master/src/main.rs#L111) or [`nalgebra-glm sample`](https://github.com/msiglreith/grr/blob/master/examples/pbr/pbr.rs#L403))

Else you can debug it via tools like renderdoc to see the vertex positions after the vertex shader to check that everything is applied correctly. Additionally, visually confirm the depth values in the depth buffer and double-check the depth state of the bound pipeline.
