### ISSUE TITLE
Rename repo to gfx-hal?

### ISSUE THREAD

**Issue by crlf0710** [gfx-rs/gfx#2540]
Half seriously.

**Comment by kvark** [comment]
Nah, gfx-rs is a project that has multiple crates, not just gfx-hal.

**Comment by Lokathor** [comment]
This repo is only going to be gfx-hal going forward though, right?

You could name it gfx-hal and then split off a gfx repo that hosts the pre-ll code and such. Might be a lot of churn, I guess it depends on how much you want to let pre-ll keep going, or replace it's backend with a gfx-hal backend and have it be the "higher level" version and keep going with 0.18 and all

**Comment by kvark** [comment]
@Lokathor There isn't much value in this churn *at this point*. We have long decided `pre-ll` to be in maintenance mode, for at least as long as needed to get wgpu-rs usable.
