### ISSUE TITLE
Problem presenting swap_chain with Metal backend [Metal]

### ISSUE THREAD

**Issue by HackerWithoutACause** [gfx-rs/gfx#2541]
Short info header: Problem presenting swap_chain with Metal backend
- GFX version: main head
- OS: MacOS Sierra 10.12.6 (16G1710)
- GPU: EVGA GeForce GTX 750 Ti 1024 MB

Another thing to note about my system is that it is running on non apple hardware (Hackintosh) and using a NVIDIA Web Driver.

When running the Quad example `swap_chain.present_nosemaphores` will return an error, causing the swap-chain to be remade each loop. If I instead of recreating the swap-chain when `swap_chain.present_nosemaphores` returns an error and instead panic, the debugger shows that `swap_chain.present_nosemaphores` gets called successfully approx. 4 before it fails. The debugger also show that the error appears to be traced back to line `1786` of `command.rs`, `let drawable = swapchain.borrow().take_drawable(index)?;`

To check if this was a problem with my Metal installation I ran the `Hello Triangle` provided by Apple and it worked fine.

**Comment by kvark** [comment]
Interesting, thanks for filing the bug! Could you share the full code for us to reproduce?

**Comment by HackerWithoutACause** [comment]
It's the same as the quad example except line `725` was changed to `swap_chain.present_nosemaphores(&mut queue_group.queues[0], frame).unwrap();` instead of
```
if let Err(_) = swap_chain.present_nosemaphores(&mut queue_group.queues[0], frame) {
    recreate_swapchain = true;
}
```

**Comment by kvark** [comment]
Can you confirm if the quad example doesn't work for you? Just to make sure.

**Comment by HackerWithoutACause** [comment]
The unmodified program compiles fine and opens a window, but no texture is displayed and repeatedly prints
```SwapchainConfig { present_mode: Fifo, composite_alpha: Inherit, format: Bgra8Srgb, extent: Extent2D { width: 1024, height: 768 }, image_count: 2, image_layers: 1, image_usage: COLOR_ATTACHMENT }```

**Comment by kvark** [comment]
That might happen if the `CAMetalLayer` loses its underlying frame queue each frame, e.g. if it's in the background or invisible. This one is going to be tricky to resolve without being able to reproduce here... If you want to take a look yourself, it would be much appreciated!

**Comment by HackerWithoutACause** [comment]
I don't know if this helps, but I've been looking at when `present_nosemaphores` fails and it seems that `acquire_image` returned a different index then the one that is said to be the next frame from `SurfaceInner::next_frame`.

**Comment by HackerWithoutACause** [comment]
I updated to High Sierra and that fixed the issue.
