### ISSUE TITLE
`push_graphics_constants`/`push_compute_constants` offset parameter is inconsistent across different backends

### ISSUE THREAD

**Issue by aleksijuvani** [gfx-rs/gfx#2552]
Here's something that I just ran into.. The Metal backend expects the offset passed to `push_graphics_constants`/`push_compute_constants` [be in bytes](https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/command.rs#L506-L507), but the Vulkan backend [expects it to be a multiple of 4 bytes (the size of u32).](https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/command.rs#L958) This causes user code to break across the different backends.

I'm not sure what the DirectX 12 backend expects in this regard. Could someone familiar with that backend check it out? I'd do it myself, but I'm having problems getting my code to run on that particular backend..

**Comment by kvark** [comment]
Good find! Let's fix the Vulkan backend then. Care to file a PR?

**Comment by aleksijuvani** [comment]
Sure, give me a second. Is the DirectX 12 backend consistent with Metal's behaviour, or do we need to fix the DirectX 12 backend as well?
