### ISSUE TITLE
Improve usability of SwapchainConfig

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/gfx#2561]
Similar to the [with_mode](https://docs.rs/gfx-hal/0.1.0/gfx_hal/window/struct.SwapchainConfig.html#method.with_mode) method, it would be very nice to have `with_alpha` for setting the `composite_alpha` field in a builder style

**Comment by grovesNL** [comment]
I think there are a couple issues we should try to address here related to `SwapchainConfig` usability:
- we should add all the missing `with_` functions (there's already a comment `// TODO: depth-only, stencil-only, swapchain size, present modes, etc.`), which might make this the preferred way to create a `SwapchainConfig` anyway
- documentation for `from_caps` doesn't state which defaults it assumes, and users might not be aware of the consequences (especially with regards to surface compatibility)

**Comment by kvark** [comment]
Looks like this can be landed without API breakage, removing as blocker.
