### ISSUE TITLE
Secondary command buffer support on Metal

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2564]
Supporting SCBs is required to run Angle on VkPI. cc @null77

**Comment by kvark** [comment]
Found a major complication: when we are recording an SCB that is meant to be run from a render pass and inherit its state, we don't know at all what render targets the pass has. Current recording facilities operate with a requirement that everything is here to run.

**Comment by omni-viral** [comment]
@kvark but when you begin SCB you provide render pass and framebuffer references.

**Comment by kvark** [comment]
Oh, that'd fix that ;) missed it somehow yesterday, will take another look now. Thanks!

**Comment by null77** [comment]
Awesome! Thanks Dzitry. I will let you know when I get the patch to load Vulkan via the MVK extension ready.

**Comment by kvark** [comment]
@null77 fwiw, the new gfx-portability release includes this: https://github.com/gfx-rs/portability/releases/tag/0.4
