### ISSUE TITLE
Clarification regarding device.wait_idle()

### ISSUE THREAD

**Issue by bgourlie** [gfx-rs/gfx#2570]
I'm looking at the at the documentation for [device.wait_idle()](https://docs.rs/gfx-hal/0.1.0/gfx_hal/device/trait.Device.html#tymethod.wait_idle) which states the following:

>Wait for all queues associated with this device to idle.
>
>Host access to all queues needs to be **externally** sycnhronized!

Regarding the comment about synchronization: Is this a warning that `wait_idle()` isn't appropriate for host synchronization? Or is it sufficient and this comment is just emphasizing the fact?

**Comment by msiglreith** [comment]
It's meant that you should not submit or do other operations on a queue on thread and call `wait_idle` in parallel on another one.
External synchronization means accessing object handles in parallel requires locks. See the Vulkan specification for more details.
