### ISSUE TITLE
Occasional incorrect use of Range

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/gfx#2571]
The [Range](https://doc.rust-lang.org/core/ops/struct.Range.html) struct is _exclusive_ while [RangeInclusive](https://doc.rust-lang.org/core/ops/struct.RangeInclusive.html) is naturally the _inclusive_ version. There are some parts of the system that use `Range` to provide inclusive values. This is a semantic error that can lead to very confused programmers down the line.

Specifically, with [SurfaceCapabilities](https://docs.rs/gfx-hal/0.1.0/gfx_hal/window/struct.SurfaceCapabilities.html) on win32 Vulkan and DX12:
* `extents`: Range<Extent2D>
* `image_count`: Range<SwapImageIndex>

(Possibly other places in the library, I'm very new here obviously.)

Now this isn't quite as simple as switching from `Range` to `RangeInclusive`, because the `RangeInclusive` carries an extra `Option<bool>` field for whatever obscure iteration based reason. So it throws extra overhead into the pile if we use `RangeInclusive`. It's probably better to just use tuples (really) and document that they're inclusive at both ends.

**Comment by rileylyman** [comment]
Is it a concern that changing `Range` to `(u32, u32)`, for example, could break a lot of user code? Would it be better to change how other parts of the library's code uses these fields? For example, instead of `surface_caps.image_count = start..end` we write `surface_caps.image_count = start..(end + 1)`.

**Comment by Lokathor** [comment]
0.2 will probably have a whole bunch of minor breaks in general. It's probably better to just do the break, because the `Range` type doesn't super fit in the first place. Using `Range` means that plain description things that we'd want to just be `Copy` don't end up being `Copy`, which is annoying.

**Comment by rileylyman** [comment]
Ok, I can try changing them to tuples.

**Comment by kvark** [comment]
My vote would be to use `RangeInclusive` where appropriate. Ranges have strong semantics (that is better than a comment on a tuple) and good ergonomics. The only downside is that they aren't `Copy`, but this is most of the time easy to work with (please show me cases where it's not the case).

**Comment by Lokathor** [comment]
It's more annoying than anything else. You have to put `clone` all over the place, which freaks people out because they think you're doing some expensive thing when you're not.

**Comment by memoryruins** [comment]
`Clone` does not always imply expensive, and there are other reasons to avoid implementing `Copy`, whether or not its the correct choice on ranges. Although clone can stand out in code, it is less alarming when aware of the type. It is useful that ranges already have documented semantics.

To make available in this thread, some various sizes of ranges:
```
size_of::<Range<u8>>() = 2
size_of::<RangeInclusive<u8>>() = 3

size_of::<Range<u16>>() = 4
size_of::<RangeInclusive<u16>>() = 6

size_of::<Range<u32>>() = 8
size_of::<RangeInclusive<u32>>() = 12

size_of::<Range<u64>>() = 16
size_of::<RangeInclusive<u64>>() = 24

size_of::<Range<u128>>() = 32
size_of::<RangeInclusive<u128>>() = 40
```

**Comment by kvark** [comment]
@Lokathor can you link to the code for example? One that freaks people out, preferably :)
@memoryruins thanks for mentioning the size differences of `RangeInclusive`. Out of my head, I don't think we'll use them for any hot spots.

**Comment by kvark** [comment]
I think for the nearest future we at least need to fix the backends so that the semantics is consistent (and non-inclusive). Therefore, it's not a blocker for 0.2.

**Comment by rukai** [comment]
I've started work on this.
Is there anything other than the fields on SurfaceCapabilities I should be adressing?

**Comment by rukai** [comment]
By going through `rg Range` I have confirmed that every other use of range to describe linear values is following the correct semantics, except for these ranges I'm not sure of:
*    `ImageBlit.src_bounds/dst_bounds`
*    `SamplerInfo.lod_range`
*    `fn set_depth_bounds`
*    `SpecializationConstant.range`
*    `pso::graphics::Viewport.depth`
*    `BakedStates.depth_bounds`

There are however lots of cases where Range is used to convey something non-linear.
e.g. `gfx_hal::pass::Attachment.layouts`
These should probably be changed to individual start and end values as they reduce the users in faith in regular uses of Range to follow the correct semantics.
What are peoples thoughts on this?

**Comment by kvark** [comment]
> There are however lots of cases where Range is used to convey something non-linear.
e.g. gfx_hal::pass::Attachment.layouts
These should probably be changed to individual start and end values as they reduce the users in faith in regular uses of Range to follow the correct semantics.

That would make sense. We should not use `Range` for non-linear things.
