### ISSUE TITLE
We need a way to query the maximum amount of push const space

### ISSUE THREAD

**Issue by Lokathor** [gfx-rs/gfx#2587]
[VkPhysicalDeviceLimits](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkPhysicalDeviceLimits.html) has a `maxPushConstantsSize` field, but this doesn't appear to be exposed anywhere within the gfx-hal API.

The spec gives you 128 bytes minimum, but most cards have more than that available

**Comment by msiglreith** [comment]
Relevant PR https://github.com/gfx-rs/gfx/pull/2201

**Comment by kvark** [comment]
Fixed by #2698
