### ISSUE TITLE
Use gl.VERSION to infer device_type? 

### ISSUE THREAD

**Issue by jackmott** [gfx-rs/gfx#2593]
Short info header:
- GFX version:master
- OS:all
- GPU:all

Could we use the string provided by gl.VERSION to infer the device_type instead of always returning `DiscreteGpu`.  We should be able to infer correctly a high % of the time by just inspect for the presence of nvidia, intel, or amd in the version string.  If we collected some of the common cases here we could get a heuristic possibly.

Relevant code would be here:
https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L274

Failing this, should we add an unknown type for cases where we have no idea?

**Comment by kvark** [comment]
If GL doesn't have any other way to discover this, then the proposed method could be our last resort.

**Comment by jackmott** [comment]
This shows all the info we can get. https://www.khronos.org/opengl/wiki/OpenGL_Context#Context_information_queries   So version, vendor, renderer.  We can either compile a list of common cases and do a heuristic or add an “unknown” option.  I’m happy to do a pr for whatever the team thinks is the best approach

**Comment by kvark** [comment]
Please do. This is going to be a solid improvement over the current state ;)

**Comment by jackmott** [comment]
So intel is making some discrete cards soon:
https://www.tomshardware.com/news/intel-discrete-gpu-2020-raja,37289.html

This may make the whole inference idea no good.  Would the gfx team rather just return Other for gl every time? Or add an Unknown type?
