### ISSUE TITLE
Add featured interface for creating Image and ImageView from CoreVideo created Texture

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2608]
As written in title I have to support instance of `CVMetalTextureRef *` created by `CVMetalTextureCacheCreateTextureFromImage` because camera and hardware decoder return `CVImageBufferRef`. The CV function is faster than the path that `CVImageBufferRef` -> staging buffer -> image due to no memory copy operations. 
Is it ok to add some featured interfaces within metal backend to address it? cc @kvark

**Comment by kvark** [comment]
Absolutely!

**Comment by Michael-Lfx** [comment]
```c
CV_EXPORT CVReturn CVMetalTextureCacheCreate(
					CFAllocatorRef CV_NULLABLE allocator,
					CFDictionaryRef CV_NULLABLE cacheAttributes,
					id <MTLDevice> CV_NONNULL metalDevice,
					CFDictionaryRef CV_NULLABLE textureAttributes,
					CV_RETURNS_RETAINED_PARAMETER CVMetalTextureCacheRef CV_NULLABLE * CV_NONNULL cacheOut ) API_AVAILABLE(macosx(10.11), ios(8.0), tvos(9.0)) __WATCHOS_PROHIBITED;
```

As the above shows the `CVMetalTextureCacheCreate()` requires `id <MTLDevice>` but both `pub struct PhysicalDevice` and `pub struct Device` make its device field public inside crate. **Should I make it public to the outside caller?** cc @kvark 

Here's the definition.

```rust
struct Shared {
    device: Mutex<metal::Device>,
    queue: Mutex<command::QueueInner>,
    service_pipes: internal::ServicePipes,
    disabilities: PrivateDisabilities,
    private_caps: PrivateCapabilities,
    visibility: VisibilityShared,
}

pub struct PhysicalDevice {
    pub(crate) shared: Arc<Shared>,
    memory_types: Vec<hal::MemoryType>,
}

pub struct Device {
    pub(crate) shared: Arc<Shared>,
    memory_types: Vec<hal::MemoryType>,
    pub online_recording: OnlineRecording,
}
```

**Comment by kvark** [comment]
Exposing `MTLDevice` isn't solving the problem: you'd still need to get `B::Image` on the output. I think we just need a `pub fn create_image_from_cv_buffer(..) -> Image` function added to `impl Device` in the metal backend.

**Comment by Michael-Lfx** [comment]
> Exposing `MTLDevice` isn't solving the problem: you'd still need to get `B::Image` on the output. I think we just need a `pub fn create_image_from_cv_buffer(..) -> Image` function added to `impl Device` in the metal backend.

It brings two more questions:
- Where do you store the `CVMetalTextureCacheRef` created by `CVMetalTextureCacheCreate(…)` then passing to `CVMetalTextureCacheCreateTextureFromImage(…CVMetalTextureCacheRef...)`?
- When do you call the `CVMetalTextureCacheFlush(...)` if we store it inside metal backend? 

I am still unfamiliar with the gfx codebase and need more help to do it.

**Comment by kvark** [comment]
I don't know a bit about `CoreVideo`, so you might need to help me here :)
Roughly, speaking, I thought we can add a variant to `ImageLike` here: https://github.com/gfx-rs/gfx/blob/f7e4c3fa5cb4e300ea34542c0c917a6a732a8e9d/src/backend/metal/src/native.rs#L290

Then we'd call `CVMetalTextureCacheFlush` if appropriate in one of the `match` spots for that enum.
