### ISSUE TITLE
dx12: mat4 as attribute doesn't work

### ISSUE THREAD

**Issue by termhn** [gfx-rs/gfx#2612]
According to Vulkan spec, when an attribute is of type `mat4`, it will treat the next 3 attribute locations as part of the same attribute (see table 20.2 here https://vulkan.lunarg.com/doc/view/1.0.33.0/linux/vkspec.chunked/ch20s01.html)

On Vulkan this works as expected, on DX12 it doesn't. It's possible this is actually a spirv-cross bug and not a gfx bug, but it seemed like the translation worked as intended...

Example that reproduces the issue here: https://github.com/termhn/learn-gfx-hal/blob/matrix-attribute-bug/examples/instanced_drawing.rs also, it works as intended on dx12 as well if we manually use 4 vec4 attributes and then combine them like here: https://github.com/termhn/learn-gfx-hal/blob/instancing/examples/instanced_drawing.rs

Short info header:
- GFX version: hal 0.1
- OS: windows 10 latest
- GPU: gtx 980ti

**Comment by msiglreith** [comment]
Thanks for reporting.
Closing as duplicate, see https://github.com/gfx-rs/gfx/issues/2612
