### ISSUE TITLE
dx12: Unitialized vertex buffer conflict with remappings

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2614]
`warden`tests fail due to the remapping we use in dx12 which currently conflicts with the binding logic for vertex buffers. Some vertex buffers may be uninitialized when first binding them on pipeline binds. This will result in `'attempt to subtract with overflow'` in case remapping appears as the offset is usually != 0.

**Comment by kvark** [comment]
This is now basically a blocker for wgpu-rs. We need to have this fixed and published as a patch to 0.1
