### ISSUE TITLE
[release] Release 0.18 of pre-ll?

### ISSUE THREAD

**Issue by norru** [gfx-rs/gfx#2617]
I am maintaining a library (gfx-gtk) which depends on a recent (nov18) feature which was added to the pre-ll branch.

At the moment I'm relying on the following deps for development

```
gfx = { git="https://github.com/gfx-rs/gfx.git", rev="56be7773b6c62a5e243a6481a632374370ee33fe" }
gfx_device_gl = { git="https://github.com/gfx-rs/gfx.git", rev="56be7773b6c62a5e243a6481a632374370ee33fe" }
```

I would like to make a new release on `crates.io` of gfx-gtk but `cargo publish` doesn't like git dependencies (it requires dependent crates to be available on `crates.io`).

Would it be possible to consider a release of `gfx` and `gfx_device_*` with the current `pre-ll` head?

**Comment by kvark** [comment]
I assume the feature missing here is tessellation+geometry shader support, which is breaking the API and thus needs to have a version bump.
Earlier, I wanted to do some minor API tweaks before 0.18, but now I think we are just going to proceed after #2197 is merged.

**Comment by norru** [comment]
Yes, that is my understanding, as well.

**Comment by termhn** [comment]
I think this can be closed now?

**Comment by norru** [comment]
Just found the lib on `crates.io`. Thanks!
