### ISSUE TITLE
Archive deprecated repositories

### ISSUE THREAD

**Issue by erlend-sh** [gfx-rs/gfx#2625]
These 5 repos can be [archived](
https://help.github.com/articles/archiving-a-github-repository/):

- https://github.com/gfx-rs/draw_state
- https://github.com/gfx-rs/gfx_macros
- https://github.com/gfx-rs/gfx_scene (can be unarchived if it becomes active again)
- https://github.com/gfx-rs/gfx-memory
- https://github.com/gfx-rs/gfx-render

**Comment by kvark** [comment]
draw_state is still used by pre-ll. gfx-memory may be used by wgpu-rs
Others are indeed good to archive, I'll do that now.
