### ISSUE TITLE
DXGI_ERROR_INVALID_CALL on D3D12 backend Instance::create(_, _)

### ISSUE THREAD

**Issue by CryZe** [gfx-rs/gfx#2630]
When creating an instance of the D3D12 backend I'm getting the following error:
```
[2019-02-16][17:31:38][gfx_backend_dx12][ERROR] Failed on dxgi factory creation: -2005270527
```
This error code is 0x887A0001 / DXGI_ERROR_INVALID_CALL and is described as
```
The application provided invalid parameter data; this must be debugged and fixed before the application is released.
```

- GFX version: latest master (c16898e327b9f007cf3a3e2c04a9afd1b3e79d0a)
- OS: Windows 10
- GPU: Nvidia GTX 1080 Ti

**Comment by kvark** [comment]
@CryZe Do the examples work for you? What is the code you are running that triggers it?

**Comment by CryZe** [comment]
Considering Instance::create(_, _) is the first call into gfx and the error in there is the first thing, I don't think nothing else matters too much. I can try it in a small reproduction without everything else around it though.

**Comment by kvark** [comment]
Does this happen in Debug as well for you? And please confirm if it affects the examples.

**Comment by CryZe** [comment]
I will test it. The thing is this happens on someone else's PC that was trying out my project, so I need to contact them with these builds, which kind of slows down figuring this out.

**Comment by kvark** [comment]
Oh I see, that's unfortunate!
The biggest help to fix this would be getting the DX12 debug output (i.e with MS DbgView) out of that machine. It typically has human-readable explanations for DX12/DXGI errors.

**Comment by CryZe** [comment]
Okay, so even this fails:
```rust
use gfx_backend_dx12::Instance;
use std::io::prelude::*;

fn main() {
    fern::Dispatch::new()
        .format(|out, message, record| {
            out.finish(format_args!(
                "{}[{}][{}] {}",
                chrono::Local::now().format("[%Y-%m-%d %H:%M:%S]"),
                record.target(),
                record.level(),
                message
            ))
        })
        .level(log::LevelFilter::Trace)
        .chain(fern::log_file("log.txt").unwrap())
        .apply()
        .unwrap();

    #[cfg(debug_assertions)]
    log::info!("Starting in Debug Mode...");
    #[cfg(not(debug_assertions))]
    log::info!("Starting in Release Mode...");

    log::info!("Creating instance...");
    let _instance = Instance::create("Foo", 1);
    log::info!("Possibly created instance?");
    println!("Hello, world!");
    std::io::stdin().read_exact(&mut [0]).unwrap();
}
```
with
```
[2019-02-18 19:20:23][gfx_dx12_bug][INFO] Starting in Debug Mode...
[2019-02-18 19:20:23][gfx_dx12_bug][INFO] Creating instance...
[2019-02-18 19:20:23][gfx_backend_dx12][ERROR] Failed on dxgi factory creation: -2005270527
[2019-02-18 19:20:23][gfx_dx12_bug][INFO] Possibly created instance?
```
in both debug and release.

**Comment by CryZe** [comment]
How do you use DbgView for debugging this?

**Comment by CryZe** [comment]
> This function accepts a flag indicating whether DXGIDebug.dll is loaded. 
I believe the D3D11_CREATE_DEVICE_DEBUG is not supposed to be passed if you didn't load the DXGIDebug.dll before. The example code Microsoft provides only conditionally passes that flag too.

**Comment by CryZe** [comment]
Alright, I just confirmed that this indeed fixes the bug. 
Running this:
```rust
    let mut debug_controller: *mut winapi::um::d3d12sdklayers::ID3D12Debug = std::ptr::null_mut();
    let hr = unsafe {
        winapi::um::d3d12::D3D12GetDebugInterface(
            &winapi::um::d3d12sdklayers::ID3D12Debug::uuidof(),
            &mut debug_controller as *mut *mut _ as *mut *mut _,
        )
    };

    if !winerror::SUCCEEDED(hr) {
        log::error!("Failed on getting d3d12 debug interface: {:08x?}", hr);
    } else {
        log::info!("Succeeded with getting d3d12 debug interface");
    }

    let mut queue = d3d12::WeakPtr::<dxgidebug::IDXGIInfoQueue>::null();
    let hr = unsafe {
        dxgi1_3::DXGIGetDebugInterface1(0, &dxgidebug::IDXGIInfoQueue::uuidof(), queue.mut_void())
    };

    let flags = if !winerror::SUCCEEDED(hr) {
        log::error!("Failed on getting dxgi debug interface: {:08x?}", hr);
        0
    } else {
        log::info!("Succeeded with getting dxgi debug interface");
        dxgi1_3::DXGI_CREATE_FACTORY_DEBUG
    };

    let mut dxgi_factory = d3d12::WeakPtr::<dxgi1_4::IDXGIFactory4>::null();
    let hr = unsafe {
        dxgi1_3::CreateDXGIFactory2(
            flags,
            &dxgi1_4::IDXGIFactory4::uuidof(),
            dxgi_factory.mut_void(),
        )
    };

    if !winerror::SUCCEEDED(hr) {
        log::error!("Failed on dxgi factory creation: {:08x?}", hr);
    } else {
        log::info!("Succeeded with dxgi factory creation");
    }
```
results in
```
[2019-02-18 20:15:38][gfx_dx12_bug][ERROR] Failed on getting d3d12 debug interface: 887a002d
[2019-02-18 20:15:38][gfx_dx12_bug][ERROR] Failed on getting dxgi debug interface: 887a002d
[2019-02-18 20:15:38][gfx_dx12_bug][INFO] Succeeded with dxgi factory creation
```
with the two error codes being:
DXGI_ERROR_SDK_COMPONENT_MISSING
`The operation depends on an SDK component that is missing or mismatched.`

And then conditionally not providing the debug flag makes the dxgi factory creation succeed. So this confirms my suspicion that the DirectX 12 backend hasn't been sufficiently tested without the debugging SDK components installed.

**Comment by kvark** [comment]
Wow, great investigation, thank you!
Sounds like a fix is an extra check during instance creation to avoid passing that debug flag? Would you want to submit a PR?
