### ISSUE TITLE
dx12: command buffer lifecycle

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2668]
Some parts of the vulkan cmd buffer lifecycle are not implemented correctly (e.g reset -> begin)

**Comment by kvark** [comment]
This is an implementation detail of dx12 backend, thus not a blocker for 0.2 release.

**Comment by kvark** [comment]
The way to test this would be: run [wgpu-rs](https://github.com/gfx-rs/wgpu-rs) examples on dx12 and inspect the debug output (by either launching from Visual Studio or hooking up MS DebugView).
