### ISSUE TITLE
Support negative viewport dimensions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2676]
Vulkan maintenance1 extension allows to have the negative viewport dimensions. The idea is to unite the rendering space with DX12 and Metal by inverting Y this way.

We currently have the Vulkan to Metal adjustment done by SPIRV-Cross here:
https://github.com/gfx-rs/gfx/blob/8e3864bce2f21fb39676ab068b3bf2651a4db4f4/src/backend/metal/src/device.rs#L1002

I don't know if this affects DX12 yet, and it's not clear to me how to support this properly, but we can surely look at MoltenVK for some inspiration. Meanwhile, https://github.com/DiligentGraphics/DiligentCore uses this and is unable to render anything. It turns out that on Metal setting the negative viewport means nothing gets through.

**Comment by kvark** [comment]
Actually, I'm wrong here. The negative viewports are supported just fine. We just end up setting the scissor to 1x1.

**Comment by msiglreith** [comment]
For single viewports it's quite simple to treat it as additional dynamic parameter and rebuild a pipeline accordingly (+ or -).
Once we have geometry shaders and multi viewports support it can get ugly quite quickly (2^16 combinations vs bitmask?)
