### ISSUE TITLE
[pre-ll] Claim constant buffer support for WebGL2

### ISSUE THREAD

**Issue by tangmi** [gfx-rs/gfx#2726]
Short info header:
- GFX version: `gfx 0.18.0`
- OS: Emscripten on Windows 10

Hi all, in the GL backend there's an override to the `constant_buffer_supported` flag that ensures `false` if we're compiling for emscripten. However, I believe that WebGL2 supports uniforms buffers and I'm wondering if this override is needed anymore (ES 3.0 should capture WebGL2 and reject WebGL1, I think)?

https://github.com/gfx-rs/gfx/blob/b621055de09c84e72255edda11559e8e0af6742f/src/backend/gl/src/info.rs#L299-L302

Thanks for your time!

**Comment by kvark** [comment]
Would be good to check up with @grovesNL . It might be that I was hacking this through for emscripten and not bother... So definitely likely to be a thing to fix :)

**Comment by tangmi** [comment]
I've created a PR doing the change, but am happy to wait for a response form @grovesNL.

**Comment by grovesNL** [comment]
Yeah, this sounds correct to me! :+1:

**Comment by tangmi** [comment]
Thanks! I'll close this as the PR was merged!
