### ISSUE TITLE
[pre-ll] Initialize Device and Factory from existing context

### ISSUE THREAD

**Issue by tangmi** [gfx-rs/gfx#2727]
Short info header:
- GFX version: `gfx 0.18.0`

I'm wondering how receptive we'd be to adding functions to create a Device and Factory from existing backend-specific contexts, similar to how the hal DX11 backend has a `new` function that takes an existing `ID3D11DeviceContext`:

https://github.com/gfx-rs/gfx/blob/fcc3806aba14e4c0f54adb51dd34057e192800d3/src/backend/dx11/src/device.rs#L68-L72

I imagine for all backends, it will be adding a backend-specific method to the Device type. For DX11 I imagine it involves just passing the immediate context in and for GL there might not need to be any work done (just need to be careful to call the creation on a gl thread?).

The use case for this is to allow non-`gfx`/`winit` entrypoints to call my `gfx` code as a library.

Cheers!

**Comment by kvark** [comment]
That would be fine by me. If you are the first (and only to date) client of that potential API, would you mind providing the PR with the version that works for you?

**Comment by tangmi** [comment]
@kvark The PR was merged, so I'm going to close this out. I'm also using the new `create_from_existing` to make a headless (i.e. swapchain-less) instance of GFX for testing.
