### ISSUE TITLE
Update Winit dependency

### ISSUE THREAD

**Issue by AlterionX** [gfx-rs/gfx#2743]
Short info header:
- GFX version: 0.1.0
- OS: Linux
- GPU: GTX 1060

I got a winit version mismatch while compiling my code (winit 0.19.1 vs winit 0.18.1). I fixed it by downgrading winit in my Cargo.toml, but would we get a version bump on the dependencies?

**Comment by Michael-Lfx** [comment]
I think it's alright to do it. BTW what's new about 0.19.1?

**Comment by AlterionX** [comment]
https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md

The top lists it out pretty nicely. But now that I look at the changelog, I guess a package upgrade would be a breaking change that needs gfx-hal to do a version bump as well?

**Comment by Abendstolz** [comment]
It's not as trivial as one might except as `glutin` also needs to be updated to a newer version (0.21 is the newest at the time of writing this) and there are quite a few changes.
