### ISSUE TITLE
GL backend panics when resizing the windows to 0 height

### ISSUE THREAD

**Issue by AregevDev** [gfx-rs/gfx#2777]
Short info header:
- GFX version: hal-2.0
- OS: Windows 10
- GPU: GeForce RTX 2070 with the latest game-ready driver

Running the quad example and resizing the window to 0 height will cause panic.
Log: https://pastebin.com/1VXzrMDR

Does not happen with any other backend nor on Linux

**Comment by cormac-obrien** [comment]
Attempting to use an FBO with any dimension equal to 0 is a [violation of the OpenGL spec](https://www.khronos.org/opengl/wiki/Framebuffer_Object#Framebuffer_Completeness):

>Using an incomplete FBO is an error. [...] If an image is attached, it must adhere to the following rules:
> - The image has a non-zero width and height
> - [...]

It looks like it would also violate the Vulkan spec:

> ### Valid Usage [of VkFramebufferCreateInfo]
> - `width` **must** be greater than `0`.
> - `height` **must** be greater than `0`.
> [...]

In GL's case, though, it's not illegal until you attempt to actually use it. Would it make sense to have this be a universal bound and just add a check to `gfx_backend_gl::Device::create_framebuffer`? Regardless, we might want to add this to the docs for `create_framebuffer`.
