### ISSUE TITLE
Support Events

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2804]
`Event` object is probably the largest concept we are missing from Vulkan, and we still need it:
  - as an associated type of `Backend` trait
  - as a few `Device` and `CommandBuffer` functions dealing with these objects

The first (and most important) step would be exposing these APIs, having them implemented on Vulkan only for now and leaving `unimplemented!()` elsewhere.

**Comment by Michael-Lfx** [comment]
iOS 12 also provide Metal Event API. Are they the same functionality as Vulkan?

**Comment by kvark** [comment]
I haven't looked at them yet, but we'll surely try to take advantage of them down the road. This is blocked on having the API exposed (this issue!) to begin with.

**Comment by Michael-Lfx** [comment]
- [MTLEvent](https://developer.apple.com/documentation/metal/mtlevent)
- [MTLFence](https://developer.apple.com/documentation/metal/mtlfence)
