### ISSUE TITLE
Where are Cube example?

### ISSUE THREAD

**Issue by DuckerMan** [gfx-rs/gfx#2805]
There was a cube example

**Comment by kvark** [comment]
As the library got rewritten with low-level API (gfx-hal), there is no more a cube example. You can find the code and examples for the old library in [v0.18 branch](https://github.com/gfx-rs/gfx/tree/v0.18).

The closest successor to the old API is [wgpu-rs](https://github.com/gfx-rs/wgpu-rs), which has a few examples.

**Comment by DuckerMan** [comment]
Press F to pay respect for cube
