### ISSUE TITLE
Hook up debug GL driver messaging

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2826]
See https://github.com/servo/webrender/blob/2afa27199d4d5b0180dd7629e35e9113a33074ec/webrender/src/renderer.rs#L2119

Whenever we check for GL error (in debug), if we detect one, we should ask the driver for debug messages and print them out.

**Comment by cormac-obrien** [comment]
Do we want to register a callback for this or just use the driver message log? The [wiki page on debug output](https://www.khronos.org/opengl/wiki/Debug_Output#Logging) suggests the former:

> **Warning**: `GL_MAX_DEBUG_LOGGED_MESSAGES` is allowed to be as few as one, so it would be unwise to rely on logging without at least verifying that the message log is of reasonable length. So it's more reliable to build your own log.

FWIW, I haven't turned up any GL implementation with this limitation.

**Comment by kvark** [comment]
Registering a callback is preferred, as you noted, and would be in line with what our Vulkan backend is doing. I'd be happy to have at least something at this point to help figuring out the GL errors.
