### ISSUE TITLE
Upgrade Vulkan backend to Rust2018

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2827]

**Comment by mcr431** [comment]
First time contributing to gfx -- I ran Cargo's built in upgrader and added the edition to Cargo.toml as per (https://doc.rust-lang.org/stable/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html). 

Everything builds but was wondering if there are any test suites or standard procedures for testing an upgrading like this. Should I just make sure the demos work with vulkan still?
