### ISSUE TITLE
[pre-ll] Add support for shader images (UAV objects)

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#284]
GL [specification](http://www.opengl.org/registry/specs/ARB/shader_image_load_store.txt), available on GL-4.2 and DX-11. This is needed for advanced shader model 5.0 techniques, such as forward+ rendering.

**Comment by dylanede** [comment]
What's the status of this now?

**Comment by kvark** [comment]
@dylanede are you looking into using it?
We haven't made any progress on this front.

**Comment by dylanede** [comment]
Well, I'm looking into eventually helping adding support for it, when I have the time. I've got some project ideas that depend upon this.

**Comment by kvark** [comment]
I believe we've had support UAVs for a long time by now.
