### ISSUE TITLE
gl: buffer role change

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/gfx#2844]
We have it as internal private capability, but I don't remember why and currently don't see why it has been added at all. As far as I know there is no such limitation.

**Comment by kvark** [comment]
Introduced in #1559, which I wrote and you reviewed ;)

**Comment by kyren** [comment]
PR for removing it and simplifying the logic in the gl backend: #2847

If we don't merge that PR we should at least do some of the other fixup in that PR besides removing `buffer_role_change`, but as per discussion the flag seems sensible to remove.
