### ISSUE TITLE
UBOs' sorting problem

### ISSUE THREAD

**Issue by skyvoid123** [gfx-rs/gfx#2845]
We have a vertex shader:
`
layout(binding = 0) uniform block {
	float f1;
};
`
Then, in the fragment shader, the layout binging's sorting is independent or behind the vertex shader's? 
E.g, the fragment shader should be
(1)
`
layout(binding = 0) uniform block {
	float f2;
};
`
or
(2)
`
layout(binding = 1) uniform block {
	float f2;
};
`
?
And, I found gfx's metal backend will hit the following function, if the fragment shader is written as (1).
![1](https://user-images.githubusercontent.com/21290096/59893769-93b4d480-9410-11e9-8bdb-105af76f753b.png)

@kvark @msiglreith @grovesNL

**Comment by kvark** [comment]
The binding model is defined for the *pipeline*, which means that all shader stages see sub-sets of the same thing. They don't see the same resource at *different* bindings, the only thing you can change between stages is visibility, e.g. you can have something visible to *only* vertex shaders, not the fragment ones.

So in your particular case, both shaders should be using "binding = 0"

**Comment by liufeipengkk1** [comment]
> The binding model is defined for the _pipeline_, which means that all shader stages see sub-sets of the same thing. They don't see the same resource at _different_ bindings, the only thing you can change between stages is visibility, e.g. you can have something visible to _only_ vertex shaders, not the fragment ones.
> 
> So in your particular case, both shaders should be using "binding = 0"

if we use binding 0 like :
```
//vertex shader
layout (binding = 0) uniform ubo1 {float a1;}
```
```
//fragment shader
layout (binding =0) uniform ubo2 {float a2;}
```
ubo1 and ubo2 are the same UniformBuffer?

**Comment by liufeipengkk1** [comment]
https://community.khronos.org/t/ubo-bindings-to-different-stages/6896 so. we cannot bind same position at same set position  in different stage in gfx  like vulkan?

**Comment by kvark** [comment]
> ubo1 and ubo2 are the same UniformBuffer?

yes, they will get the contents of the same buffer

> we cannot bind same position at same set position in different stage in gfx like vulkan?

I'm not sure how you make this conclusion from the link. You definitely can bind the same position to different stages in gfx-hal and Vulkan alike. When you describe a binding in the descriptor set layout, you provide the mask of shader stages: https://docs.rs/gfx-hal/0.2.1/gfx_hal/pso/struct.DescriptorSetLayoutBinding.html#structfield.stage_flags

**Comment by liufeipengkk1** [comment]
> > ubo1 and ubo2 are the same UniformBuffer?
> 
> yes, they will get the contents of the same buffer
> 
> > we cannot bind same position at same set position in different stage in gfx like vulkan?
> 
> I'm not sure how you make this conclusion from the link. You definitely can bind the same position to different stages in gfx-hal and Vulkan alike. When you describe a binding in the descriptor set layout, you provide the mask of shader stages: https://docs.rs/gfx-hal/0.2.1/gfx_hal/pso/struct.DescriptorSetLayoutBinding.html#structfield.stage_flags

thanks, got it.

**Comment by Michael-Lfx** [comment]
Could we avoid sorting if `if self.shared.private_caps.argument_buffers` is ready?

**Comment by kvark** [comment]
@Michael-Lfx we aren't sorting anything. Could you clarify?

**Comment by Michael-Lfx** [comment]
> @Michael-Lfx we aren't sorting anything. Could you clarify?

https://github.com/gfx-rs/gfx/blob/b25684a7e25f913583fd25f20f9c8b049ac78f54/src/backend/metal/src/device.rs#L1798-L1799

As shown above there are two `sort_by_key()` which confuse me.

**Comment by kvark** [comment]
This sorting is required by the Vulkan spec in order to match the `write_descriptor_sets` (which is vkUpdateDescriptorSets` in there), regardless of the argument buffer support. Do you see it showing up in profiles? I'd be surprised.
