### ISSUE TITLE
mtl: Avoid clear pending_subpasses and then append one by one

### ISSUE THREAD

**Issue by Michael-Lfx** [gfx-rs/gfx#2850]
https://github.com/gfx-rs/gfx/blob/2b58aafa0fc7b8ef78bb07386d8b38f1a22cc2fb/src/backend/metal/src/command.rs#L3210

https://github.com/gfx-rs/gfx/blob/2b58aafa0fc7b8ef78bb07386d8b38f1a22cc2fb/src/backend/metal/src/command.rs#L3286

Could we call `self.state.pending_subpasses.resize(render_pass.subpasses.len())` instead of `self.state.pending_subpasses.clear()` which then append elements one by one given that there are no early return inside the loop?

**Comment by kvark** [comment]
I don't quite understand what is the problem with `clear` that you are seeing? Supposing we replace clear() by resize(). Some elements are going to be left in the vector. We'd still then need to walk it and fill them up, which means the old contents get destructed/dropped. This is no different from dropping them all the once with clear() and then appending.
