### ISSUE TITLE
[gl] Describe backend internals

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2858]
See https://github.com/gfx-rs/gfx/pull/2857/files#diff-6e80d01aaeb75f01d28d8338b0a64797R2 for a rough start.
cc @grovesNL @ZeGentzy @kyren 

Doing this would help maintaining the backend in the long run.

**Comment by ZeGentzy** [comment]
Remaping: https://github.com/gfx-rs/gfx/pull/2663#discussion_r270650958

**Comment by kvark** [comment]
@ZeGentzy that would be great, yeah! Do you have a preference over commenting it at the top of the "lib.rs" like I did, on the corresponding types like `Memory` and `PipelineLayout`, or somewhere else?
