### ISSUE TITLE
Consider removing typed command buffers, pools and queues

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2862]
Anything on top of "raw" command types is not used by any backends, it's only for the user, and it doesn't help most important users either (rendy and wgpu-rs can't use those). So we should probably just remove those layers in favor of something like https://crates.io/crates/rendy-command
cc @omni-viral

**Comment by omni-viral** [comment]
I can't neither support nor discourage this proposition.
For someone those wrappers could be good enough. And I don't think they add much maintenance cost.

... IIRC, there was UB somewhere.

**Comment by kvark** [comment]
They have been actually requiring quite a bit of maintenance as we were reworking the raw model... Even today, I think compiler complains about some of the things we do in that typed layer and claims it to be deprecated, so there might be a point where it just stops to compile.

**Comment by kvark** [comment]
Here are the steps for accomplishing the task:
  1. Get familiar with how the subject types in gfx-hal are represented by raw and typed layers
  2. Evaluate, to what extent is this functionality intersecting with rendy-command
  3. Communicate back to us, make a more detailed proposal of removing the redundancy
  4. Remove the respective types from gfx-hal
  5. Rename the remaining raw types to drop the "Raw" prefix
  6. Get huge thanks and kudos from the community :)

**Comment by zakorgy** [comment]
@kvark it looks like we can transit to the raw types without any problem ( https://github.com/szeged/webrender/pull/301 ), so we can give the green light for this change.

**Comment by kvark** [comment]
It's still a big API change. Let's not rush it for hal-0.3 and instead let it bake in `master` before hal-0.4 is out.
