### ISSUE TITLE
Upgrade to winit 0.20.0

### ISSUE THREAD

**Issue by rukai** [gfx-rs/gfx#2874]
I opened this earlier https://github.com/gfx-rs/wgpu/issues/238
But it quickly became clear that gfx-hal is the first step here.

I've started working on this.

**Comment by kvark** [comment]
This has been requested on the forum: https://users.rust-lang.org/t/winit-0-20-the-state-of-windowing-in-rust-and-a-request-for-help/29485/31?u=kvark
cc @norru
