### ISSUE TITLE
Using both UBO and push_constant in shader on Metal

### ISSUE THREAD

**Issue by mvlabat** [gfx-rs/gfx#2913]
Short info header:
- GFX version: 0.2.1
- OS: MacOS
- GPU: Intel Iris Graphics 6100 1536 MB

I have the following shader I try to use in my project:
```glsl
#version 450

layout(std140, set = 0, binding = 0) uniform ViewArgs {
    uniform mat4 proj;
    uniform mat4 view;
} viewArgs;

layout(location = 0) in vec2 uv;
layout(location = 1) in vec3 position;

layout(push_constant) uniform PushConstants {
    vec2 translation;
    float scale;
    float health;
} pushConstants;
```
Here's the full version: (https://github.com/mvlabat/hello_amethyst/blob/e0d93fe98f83c97eb04b1bf32d604a4fc6c67285/resources/shaders/health_ui.vert)

When I run my project, gfx fails on compiling the shader with the following error:
> Error compiling the shader CompilationFailed("Compilation failed: \n\nprogram_source:36:133: error: \'buffer\' has a duplicate index \'0\'\nvertex main0_out main0(main0_in in [[stage_in]], constant ViewArgs& viewArgs [[buffer(0)]], constant PushConstants& pushConstants [[buffer(0)]])\n                                                                                                                                    ^\n")

With a very quick glance at `gfx-rs` code I assumed that's because gfx-rs always sets `0` binding index for push constants:
https://github.com/gfx-rs/gfx/blob/c547e0d6d376df78c1f87639b6b055e4197c7ecb/src/backend/metal/src/device.rs#L1049-L1060
Though as I'm a total noob in Vulkan and gfx-rs I might be wrong.

Here's my code where I write push constants, in case you can find it useful. It's amethyst though, I dunno if it can help you a lot...
https://github.com/mvlabat/hello_amethyst/blob/e0d93fe98f83c97eb04b1bf32d604a4fc6c67285/src/render_groups/health_ui.rs#L157

**Comment by kvark** [comment]
Have you updated the sample by any chance? Last time I recall, I couldn't even run it for reasons unrelated to gfx-hal, so it was not possible to reproduce the issue.

**Comment by mvlabat** [comment]
Sorry, the bug is in my application. Creating pipeline layout like that fixed the problem:
```
let push_constants = vec![(pso::ShaderStageFlags::VERTEX, 0..4), (pso::ShaderStageFlags::FRAGMENT, 0..4)];

    let pipeline_layout = unsafe {
        factory
            .device()
            .create_pipeline_layout(layouts, push_constants)
    }?;
```
