### ISSUE TITLE
DX12: MSAA has no effect

### ISSUE THREAD

**Issue by danaugrs** [gfx-rs/gfx#2936]
**gfx-hal 0.2.1 | Windows 10 | NVIDIA GeForce GTX 1070 Max-Q Design**

MSAA doesn't seem to have any effect on DX12.
See https://github.com/gfx-rs/wgpu-rs/issues/47#issuecomment-517453278 for context.

**Comment by Slyklaw** [comment]
Same on my Nvidia 1060, but it works correctly on my Radeon Vega.

**Comment by kvark** [comment]
Fixed by #3343
