### ISSUE TITLE
How to create surface from winit window with gfx-hal 0.3?

### ISSUE THREAD

**Issue by jeancf** [gfx-rs/gfx#2959]
Hello,

I am on gfx-hal with Vulkan backend running on linux X11 KDE. 
I am trying to upgrade my code from gfx-hal 0.1 to 0.3. I notice that
```
pub fn create_surface(&self, window: &Window) -> Surface
```
no longer exists. What is the new method of getting the surface from my winit window?
Thanks.

**Comment by rukai** [comment]
Maybe try checking the examples?

**Comment by aleksijuvani** [comment]
You'll need to enable the "winit" feature for the backend in your Cargo.toml. This used to be a default feature, but it is no longer enabled by default. Enabling this feature should allow you to pass `&Window` to `create_surface` like previously.

**Comment by jeancf** [comment]
Thanks you @aleksijuvani, it worked.
@rukai: it was far from self-explanatory based on the examples.
