### ISSUE TITLE
Implement Backend for Instance

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#2963]
It seems like we could have one less type exposed by the API if we just make `Instance` to be that object that implements the `hal::Backend` trait.

**Comment by yanchith** [comment]
I'd like to try this. Expect updates :)

**Comment by yanchith** [comment]
So, I think I've hit the first, and possibly only larger question for implementing this:

`hal::Backend` has some serious bounds: `'static + Sized + Eq + Clone + Hash + fmt::Debug + Any + Send + Sync`. Implementing these for the empty `enum Backend {}` was of course trivial, but it a bit more involved with the instances.

The question is, do we want to relax the bounds a bit (possibly causing internal and external breakage), or do we want to `Arc` the underlying raw instances?

In the vulkan backend, the raw instance is already wrapped in an `Arc`, which simplified implementing `Clone + Eq + Hash`, but as I continued into doing the same change for the metal backend, I found that I would need to add the `Arc` around `GfxManagedMetalLayerDelegate` to keep it's resource management correct, possibly causing overhead. Is this overhead something gfx can live with? 

Thanks!

**Comment by yanchith** [comment]
One more thing: the gl backend is experiencing a bit of a cfg hell, and this PR makes it worse. I think I could slap enough cfgs in there to make it work, but the price may be a bit high.

Originally, the `enum Backend {}` was just unconditionally available, but after moving the `Backend` trait to `Instance`, we must ensure that one of the 2 possible gl instances is available everywhere we want to use the Backend trait...

**Comment by kvark** [comment]
Thank you for taking a stab at this!
Seeing the issues you raised, I'm starting to think that maybe it's not the best idea to do it at all? When stuff depends on `B: Backend` we don't want to imply any relation/requirement about `Instance` in particular.

Do you think you could change the direction of this PR and just add `type Instance` to `Backend` with the corresponding `trait Instance` somewhere?
