### ISSUE TITLE
Update metal-rs dependency to fix leaks

### ISSUE THREAD

**Issue by seivan** [gfx-rs/gfx#2971]
There's a leak in published `metal-rs` `0.15.0`, patching against master branch fixes those. 
Related: https://github.com/gfx-rs/metal-rs/issues/95

Shouldn't have any issues working against master branch with regards to API breakages.

**Comment by kvark** [comment]
Most importantly, hal-0.3 branch of gfx-backend-metal needs to be updated

**Comment by seivan** [comment]
Fixed in https://github.com/gfx-rs/gfx/pull/2972

**Comment by seivan** [comment]
Sorry, only fixed in the backend, not the main crate. My bad.
PR https://github.com/gfx-rs/gfx/pull/2973
