### ISSUE TITLE
Doesn't work on MacOS Sierra

### ISSUE THREAD

**Issue by GooseDB** [gfx-rs/gfx#2976]
Short info header:
- GFX version:0.3.0
- OS: OSX 10.12.6
- GPU: Intel Iris Plus Graphics 640 1536 МБ

It draws just a white screen
feature=metal

https://imgur.com/a/uHli2AF

**Comment by grovesNL** [comment]
I think this is the same issue as #2563 (Metal on Sierra)

**Comment by kvark** [comment]
I believe this is fixed by #3049
