### ISSUE TITLE
gfx_backend_metal: Unable to render on macOS Mojave

### ISSUE THREAD

**Issue by mdunnio** [gfx-rs/gfx#2990]
Short info header:
- GFX version: 0.17.1
- OS: macOS Mojave 10.14.6
- GPU: Intel HD Graphics 4000 1536 MB

Other:
- gfx_core version: 0.8.3
- gfx-hal: 0.2.1
- gfx_backend_metal: 0.2.4

I’m receiving these warnings while trying to draw in a window:

```
[INFO][gfx_backend_metal::window] build_swapchain SwapchainConfig { present_mode: Fifo, composite_alpha: OPAQUE, format: Bgra8Srgb, extent: Extent2D { width: 500, height: 500 }, image_count: 3, image_layers: 1, image_usage: COLOR_ATTACHMENT }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Vertex, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Fragment, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Vertex, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[INFO][gfx_backend_metal::device] Entry point EntryPoint { name: "main", execution_model: Fragment, work_group_size: WorkGroupSize { x: 0, y: 0, z: 0 } }
[WARN][gfx_backend_metal::window] Swapchain drawables are changed, unable to wait for 0
[WARN][gfx_backend_metal::window] Failed to get the drawable of frame 0
[WARN][gfx_backend_metal::window] Swapchain drawables are changed, unable to wait for 1
[WARN][gfx_backend_metal::window] Failed to get the drawable of frame 1
[WARN][gfx_backend_metal::window] Swapchain drawables are changed, unable to wait for 2
[WARN][gfx_backend_metal::window] Failed to get the drawable of frame 2
[WARN][gfx_backend_metal::window] No frame is available
```

`[WARN][gfx_backend_metal::window] No frame is available` repeats forever.

Please let me know if I can get more information.

Thanks!

**Comment by kvark** [comment]
> GFX version: 0.17.1

that must be a mistake :)

> Please let me know if I can get more information.

what about our quad example from `master` branch? or the `colour-uniform` one? They currently use different swapchain models.

**Comment by mdunnio** [comment]
> that must be a mistake :)

When I grep my Cargo.lock file, I see this:

`gfx 0.17.1 (registry+https://github.com/rust-lang/crates.io-index),`

As far as I can tell, this is the version that `amethyst 0.12.0` brings in. Am I looking at the wrong package?

I’ll try giving the quad example a shot and see if I’m able to run it.  Thanks.

**Comment by mdunnio** [comment]
I was able to run both examples successfully. Perhaps this is an `amethyst` issue. Thanks for the help.

**Comment by kvark** [comment]
See the top of our README:
> PLEASE BE AWARE: this is home to the gfx-hal crate/API. The Old gfx Crate Is Now Deprecated.

If you see the old `gfx` in the lock file, I recommend investigating why it's there and reaching back to Amethyst team. It's definitely not expected to be used.

I'm going to close the issue as our examples work. Please feel free to re-open.

**Comment by sejr** [comment]
Hey all, would love to re-open this as I'm seeing it with a project I'm working on, via Amethyst. The window will open to a black screen that doesn't update unless I resize the window, then it seems to work okay. Meanwhile, `[WARN][gfx_backend_metal::window] No frame is available` repeats ad nauseam.

```toml
[[package]]
name = "gfx-backend-metal"
version = "0.3.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "arrayvec 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)",
 "bitflags 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "block 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)",
 "cocoa 0.19.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "copyless 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)",
 "core-graphics 0.17.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "foreign-types 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "gfx-hal 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "metal 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "objc 0.2.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "parking_lot 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "range-alloc 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "raw-window-handle 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "smallvec 0.6.13 (registry+https://github.com/rust-lang/crates.io-index)",
 "spirv_cross 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "storage-map 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "winit 0.19.5 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**Comment by kvark** [comment]
@sejr please move this comment to a new issue

**Comment by sejr** [comment]
@kvark done: #3195
