### ISSUE TITLE
Is there a description of gfx-hal differences from Vulkan?

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/gfx#2992]
People keep asking what exactly the differences between `gfx-hal` and Vulkan are.  Is there an authoritative list somewhere I can refer to?  Beyond simple rust-ification such as turning pointers into iterators and so on, is there a set of features that are added/unsupported, minor differences in how things are structured, etc?

Thanks in advance.

Short info header:
- GFX version: 0.3
- OS: n/a
- GPU: n/a

**Comment by kvark** [comment]
If only that was described somewhere, right?
https://github.com/gfx-rs/gfx/wiki/Deviations-from-Vulkan
😃

**Comment by icefoxen** [comment]
Awesome, thanks! Now I know!
