### ISSUE TITLE
[Doc Request] shaderc example in code or in markdown

### ISSUE THREAD

**Issue by BrandonDyer64** [gfx-rs/gfx#2999]
I think it would be worthwhile to include more information on how a developer using the gfx examples, namely `quad`, might use their own shader code.

In my opinion, this should be included either in the example Rust file itself, or as a continuation challenge in the examples readme.

### In the code

Change this:
```
let spirv = pso::read_spirv(Cursor::new(&include_bytes!("data/quad.frag.spv")[..])).unwrap();
unsafe { device.create_shader_module(&spirv) }.unwrap()
```
To this:
```
let source = fs::read_to_string("src/data/quad.frag").unwrap();
let binary_result = compiler.compile_into_spirv(&source[..], shaderc::ShaderKind::Fragment, "shader.glsl", "main", Some(&options)).unwrap();
unsafe { device.create_shader_module(binary_result.as_binary()) }.unwrap()
```
along with the code to create the compiler.

### In the readme

Add something like this to the readme in the examples folder:

```
## Compiling your own shaders
Now that you've gotten the examples running, you probably want to use your own shaders.
Have a look at [shaderc-rs](https://crates.io/crates/shaderc) to implement this programatically.
```

**Comment by kvark** [comment]
This is a bit controversial. Given no *good* way to generate SPIR-V, I don't think we should cover all the not-great ways. API accepts SPIR-V clearly, and we provide some examples to show that. We can leave the other details (about how to get SPIR-V) out of scope.

**Comment by BrandonDyer64** [comment]
If we do the readme version of this, we could tell them all of the different ways to do it, instead of just one. I just want to be able to steer a developer in the right direction. One my biggest troubles getting started with gfx was having no idea how to compile my own shaders, and having to mess with a compiler that didn't seem to work for anything other than Vulkan.

Maybe the readme could look something like this?

```
## Compiling your own shaders
Now that you've gotten the examples running, you probably want to use your own shaders.
Have a look at [shaderc-rs](https://crates.io/crates/shaderc), [glslang](https://github.com/KhronosGroup/glslang), or [glsl-to-spirv](https://crates.io/crates/glsl-to-spirv)<sup>deprecated</sup>.
```

**Comment by kvark** [comment]
@BrandonDyer64 that section looks good to me. Want to turn it into a PR?

**Comment by BrandonDyer64** [comment]
Yup! On it
