### ISSUE TITLE
Split `Surface::compatibility` into separate functions

### ISSUE THREAD

**Issue by grovesNL** [gfx-rs/gfx#3019]
Certain calls in `compatibility` can add a lot of overhead, especially during resizes with swapchain recreation. Specifically `get_physical_device_surface_formats` has been found to be slow with some drivers.

By splitting this into separate functions, we can allow applications to cache results if they'd like, or avoid calls if they're not needed (i.e. for a resize event maybe not all of this information is necessary).

**Comment by Osspial** [comment]
For some perspective on just how slow `get_physical_device_surface_formats` is: I did a Windows performance analysis on [`rx`](https://github.com/cloudhead/rx) with the Vulkan backend on my NVIDIA system, and calls to that function were taking up *over half the user code execution time* during resize operations.
