### ISSUE TITLE
Missing gfx-backend-empty when installing gfx-hal 0.3.1

### ISSUE THREAD

**Issue by Wojtechnology** [gfx-rs/gfx#3020]
I'm not sure what changed, but I recently tried to do a rebuild of my project, which depends on gfx-hal version 0.3.1, and I got this when building:

```
error[E0463]: can't find crate for `back`
  --> /Users/wojtekswiderski/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-hal-0.3.1/src/lib.rs:23:1
   |
23 | extern crate gfx_backend_empty as back;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `gfx-hal`.
```
I'm pretty sure this isn't a problem with my issue since I made a new project and got the same issue.

Short info header:
- GFX version: 0.3.1
- OS: Mac OSX 10.13
- GPU: NVIDIA GeForce GT 750M 2 GB

**Comment by kvark** [comment]
Interesting! This line is not in [hal/src/lib.rs](https://docs.rs/crate/gfx-hal/0.3.1/source/src/lib.rs):
> extern crate gfx_backend_empty as back;

So I'm not sure why it complains about gfx-hal failing to compile, specifically.

**Comment by kvark** [comment]
Ok, looks like we just forgot to publish gfx-backend-empty for 0.3.1
It's now public. Please re-open if you are still seeing the issue!

**Comment by Wojtechnology** [comment]
Still seeing this. It seems like it's specified as a dev-dependency which might be what's causing the issue.

**Comment by kvark** [comment]
Dev dependencies are only needed for testing and examples. What are you doing exactly?

**Comment by kvark** [comment]
I just tried bumping gfx-hal dependency to 0.3.1 in https://github.com/msiglreith/gfx_ocean/pull/15 and it works without issues. Looks like something is off on your side. Try deleting `Cargo.lock`?

Again, the line it shows in the error is only ever seen in an example within this repository. It has nothing to do with gfx-hal itself.

**Comment by Wojtechnology** [comment]
You're right. Must have been something to do with cargo reusing a cached version of the package. After I cleaned the folder containing the package, it now downloads. Thanks so much!
