### ISSUE TITLE
`create_pipeline_layout` should take push constant ranges in units of bytes

### ISSUE THREAD

**Issue by aleksijuvani** [gfx-rs/gfx#3021]
Currently `create_pipeline_layout` takes the push constant ranges in multiples of 4 bytes, i.e. the size of `u32`. This is inconsistent with `push_graphics_constants` and `push_compute_constants` which take the `offset` in bytes instead. In GLSL, the `offset` layout qualifier often used with push constants also takes bytes. This keeps tripping me up because it means that I have to divide the push constant range bounds by 4 in my head every time before passing them onto `create_pipeline_layout`.

I suppose there's an argument to be made that since `push_graphics_constants` and `push_compute_constants` take `&[u32]` for the data instead of `&[u8]`, all offsets should also be in terms of the size of `u32` instead of `u8`, but this is also inconsistent because the `push_graphics_constants` and `push_compute_constants` functions take the `offset` in bytes.

**Comment by aleksijuvani** [comment]
This is also inconsistent with Vulkan in which `vkCreatePipelineLayout` takes the push command ranges in units of bytes, and `vkCmdPushConstants` which takes the offset in units of bytes.

**Comment by kvark** [comment]
Also relevant - https://github.com/gfx-rs/portability/blob/9926fe07296bd4ca153c96c7a43bf2aea2c6059d/libportability-gfx/src/impls.rs#L2568

Let's align with Vulkan here to avoid confusion!
