### ISSUE TITLE
WebGL: INVALID_ENUM: getParameter: invalid parameter name

### ISSUE THREAD

**Issue by smasher816** [gfx-rs/gfx#3036]
Short info header:
- GFX version: da078cd6e4cc49f542310ce7a0ff12ba0a07b13a
- OS: Linux
- GPU: Intel i7-7700K (modesetting) / nvidia 980Ti (proprietary)

Attempting to run the "quad with WebGL/WebAssembly" example.

```
WebGL: INVALID_ENUM: getParameter: invalid parameter name
imports.wbg.__widl_f_get_parameter_WebGL2RenderingContext @ quad.js:571
web_sys::WebGl2RenderingContext::get_parameter::he13d0183ee1b8f87 @ wasm-0042b982-1184:1
<glow::web::Context as glow::Context>::get_parameter_i32::hce33eca485710fa8 @ wasm-0042b982-874:1
gfx_backend_gl::info::query_all::h162f0391f3e541c3 @ wasm-0042b982-261:1
gfx_backend_gl::PhysicalDevice::new_adapter::h207b7c3a8648bed4 @ wasm-0042b982-256:1
<gfx_backend_gl::window::web::Surface as gfx_hal::Instance>::enumerate_adapters::heedbf3af6469c799 @ wasm-0042b982-941:1
quad::main::h1494804617ce0d78 @ wasm-0042b982-237:1
wasm_main @ wasm-0042b982-1918:1
(anonymous) @ quad.js:1162
Promise.then (async)
init @ quad.js:1159
(anonymous) @ (index):12
a.onRuntimeInitialized @ spirv_cross_wrapper_glsl.js:36
b @ spirv_cross_wrapper_glsl.js:38
Z @ spirv_cross_wrapper_glsl.js:39
ua @ spirv_cross_wrapper_glsl.js:37
d @ spirv_cross_wrapper_glsl.js:20
e @ spirv_cross_wrapper_glsl.js:20
Promise.then (async)
e @ spirv_cross_wrapper_glsl.js:22
a.asm @ spirv_cross_wrapper_glsl.js:24
(anonymous) @ spirv_cross_wrapper_glsl.js:28
(anonymous) @ (index):10
load (async)
(anonymous) @ (index):9
quad.js:921 Vendor: "WebKit"
quad.js:921 Renderer: "WebKit WebGL"
quad.js:921 Version: 2.0
quad.js:921 Shading Language: 3.0
quad.js:921 Features: INSTANCE_RATE
quad.js:921 Legacy Features: DRAW_INSTANCED | DRAW_INDEXED_INSTANCED | VERTEX_BASE | CONSTANT_BUFFER | COPY_BUFFER | SAMPLER_OBJECTS | INSTANCED_ATTRIBUTE_BINDING
quad.js:924 Loaded Extensions:
```

```
quad.js:921 Memory types: [
    (
        MemoryType {
            properties: CPU_VISIBLE | CPU_CACHED,
            heap_index: 1,
        },
        Buffer(
            INDEX,
        ),
    ),
    (
        MemoryType {
            properties: CPU_VISIBLE | CPU_CACHED,
            heap_index: 1,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Buffer(
            INDEX,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Image,
    ),
]
```

```
quad.js:921 	Created frame buffer WebFramebufferKey(KeyData { idx: 1, version: 1 })
```

```
quad.js:243 panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://localhost:8000/quad.js:230:21)
    at console_error_panic_hook::hook::h33f326cb575e7248 (wasm-function[490]:0x8855e)
    at core::ops::function::Fn::call::h1a84e8ea8a42e605 (wasm-function[2042]:0xc1859)
    at std::panicking::rust_panic_with_hook::he430b5bca58aed0b (wasm-function[795]:0xa7d09)
    at std::panicking::continue_panic_fmt::h5382cb4bf506a95c (wasm-function[1160]:0xb82b9)
    at rust_begin_unwind (wasm-function[2035]:0xc180f)
    at core::panicking::panic_fmt::hd2f9751e01df4ba2 (wasm-function[1332]:0xbc3d1)
    at core::panicking::panic::h4a0ba0b7ae8acfd2 (wasm-function[1273]:0xbb0a6)
    at quad::main::h1494804617ce0d78 (wasm-function[237]:0x18f09)
    at wasm_main (wasm-function[1918]:0xc1268)
```

```
wasm-0042b982-2134:1 Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (wasm-function[2134]:0xc1bb1)
    at rust_panic (wasm-function[1557]:0xbef3b)
    at std::panicking::rust_panic_with_hook::he430b5bca58aed0b (wasm-function[795]:0xa7d30)
    at std::panicking::continue_panic_fmt::h5382cb4bf506a95c (wasm-function[1160]:0xb82b9)
    at rust_begin_unwind (wasm-function[2035]:0xc180f)
    at core::panicking::panic_fmt::hd2f9751e01df4ba2 (wasm-function[1332]:0xbc3d1)
    at core::panicking::panic::h4a0ba0b7ae8acfd2 (wasm-function[1273]:0xbb0a6)
    at quad::main::h1494804617ce0d78 (wasm-function[237]:0x18f09)
    at wasm_main (wasm-function[1918]:0xc1268)
    at http://localhost:8000/quad.js:1162:14
﻿```
```

-------

Snippet of the code for the first getParameter error
```
imports.wbg.__widl_f_get_parameter_WebGL2RenderingContext = function(arg0, arg1) {
        try {
            const ret = getObject(arg0).getParameter(arg1 >>> 0);
            return addHeapObject(ret);
        } catch (e) {
            handleError(e)
        }
    };
```

**Comment by demurgos** [comment]
I have a similar issue when following `examples/README.md` to render `quad` with WebGL. The error happens on both Firefox and Chrome.

I get the following warnings:

```
Error: WebGL warning: getParameter: pname: invalid enum value <enum 0x8c2b> quad.js:567:41
Error: WebGL warning: getParameter: pname: invalid enum value <enum 0x90df>
```

Then some logs about my device

<details>

```
Vendor: "Mozilla" quad.js:921:17
Renderer: "Mozilla" quad.js:921:17
Version: 2.0 quad.js:921:17
Shading Language: 3.0 quad.js:921:17
Features: INSTANCE_RATE quad.js:921:17
Legacy Features: DRAW_INSTANCED | DRAW_INDEXED_INSTANCED | VERTEX_BASE | CONSTANT_BUFFER | COPY_BUFFER | SAMPLER_OBJECTS | INSTANCED_ATTRIBUTE_BINDING quad.js:921:17
Loaded Extensions: quad.js:924:17
Memory types: [
    (
        MemoryType {
            properties: CPU_VISIBLE | CPU_CACHED,
            heap_index: 1,
        },
        Buffer(
            INDEX,
        ),
    ),
    (
        MemoryType {
            properties: CPU_VISIBLE | CPU_CACHED,
            heap_index: 1,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Buffer(
            INDEX,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Buffer(
            TRANSFER_SRC | TRANSFER_DST | UNIFORM_TEXEL | STORAGE_TEXEL | UNIFORM | STORAGE | VERTEX | INDIRECT,
        ),
    ),
    (
        MemoryType {
            properties: DEVICE_LOCAL,
            heap_index: 0,
        },
        Image,
    ),
] quad.js:921:17
	Created frame buffer WebFramebufferKey(KeyData { idx: 1, version: 1 })
```

</details>

And finally a panic with the following error:

```
panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@http://localhost:5000/quad.js:235:21
console_error_panic_hook::Error::new::he1fe1b4290c65397@http://localhost:5000/quad_bg.wasm:wasm-function[16555]:0x53dbf1
console_error_panic_hook::hook_impl::h471836e23a9eef3a@http://localhost:5000/quad_bg.wasm:wasm-function[2853]:0x330bec
console_error_panic_hook::hook::hf54704760872b4a4@http://localhost:5000/quad_bg.wasm:wasm-function[17891]:0x552378
core::ops::function::Fn::call::h75cc49e9abd3e0ac@http://localhost:5000/quad_bg.wasm:wasm-function[16686]:0x54002b
std::panicking::rust_panic_with_hook::hf721587d23a2327a@http://localhost:5000/quad_bg.wasm:wasm-function[4682]:0x3c1b7e
std::panicking::continue_panic_fmt::h278f146f56cb70e2@http://localhost:5000/quad_bg.wasm:wasm-function[10506]:0x4bccbd
rust_begin_unwind@http://localhost:5000/quad_bg.wasm:wasm-function[21736]:0x579426
core::panicking::panic_fmt::hf1ace737199033ee@http://localhost:5000/quad_bg.wasm:wasm-function[17070]:0x546082
core::panicking::panic::hdd2376bed10f76e5@http://localhost:5000/quad_bg.wasm:wasm-function[11917]:0x4e0b82
core::option::Option<T>::unwrap::h552c458ff8716523@http://localhost:5000/quad_bg.wasm:wasm-function[7994]:0x46d370
quad::Renderer<B>::new::hf20ac9ea305ff6dd@http://localhost:5000/quad_bg.wasm:wasm-function[235]:0x2ff6c
quad::main::h1494804617ce0d78@http://localhost:5000/quad_bg.wasm:wasm-function[404]:0x146c05
quad::wasm_main::h96b38bccde67cea0@http://localhost:5000/quad_bg.wasm:wasm-function[20235]:0x56e8b8
wasm_main@http://localhost:5000/quad_bg.wasm:wasm-function[19148]:0x5633af
init/<@http://localhost:5000/quad.js:1162:14


quad.js:232:17
    __wbg_error_4bb6c2a97407129a http://localhost:5000/quad.js:232
    hd98d7beb64e1cc27 http://localhost:5000/quad_bg.wasm:4519250
    h471836e23a9eef3a http://localhost:5000/quad_bg.wasm:3345611
    hf54704760872b4a4 http://localhost:5000/quad_bg.wasm:5579640
    h75cc49e9abd3e0ac http://localhost:5000/quad_bg.wasm:5505067
    hf721587d23a2327a http://localhost:5000/quad_bg.wasm:3939198
    h278f146f56cb70e2 http://localhost:5000/quad_bg.wasm:4967613
    rust_begin_unwind http://localhost:5000/quad_bg.wasm:5739558
    hf1ace737199033ee http://localhost:5000/quad_bg.wasm:5529730
    hdd2376bed10f76e5 http://localhost:5000/quad_bg.wasm:5114754
    h552c458ff8716523 http://localhost:5000/quad_bg.wasm:4641648
    hf20ac9ea305ff6dd http://localhost:5000/quad_bg.wasm:196460
    h1494804617ce0d78 http://localhost:5000/quad_bg.wasm:1338373
    h96b38bccde67cea0 http://localhost:5000/quad_bg.wasm:5695672
    wasm_main http://localhost:5000/quad_bg.wasm:5649327
    init http://localhost:5000/quad.js:1162
RuntimeError: unreachable executed quad_bg.wasm:5739881:1
```

Here are my system information.

Short info header:
- GFX version: fb762601e28ad0da2f4a9e004e970e6928eb83f3
- OS: Linux
- GPU: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) 

  Firefox info from `about:support`:

  | Feature | Value |
  | ------- | ------- |
  | Vendor ID | 0x8086 |
  | Device ID | 0x591b |
  | Driver Vendor | mesa/i965 |
  | Driver Version | 19.1.7.0 |
  | RAM | 3072MB |

  Extra info:
  <details>

  | Feature | Value |
  | ------- | ------- |
  | WebGL 1 Driver WSI Info | GLX 1.4 GLX_VENDOR(client): Mesa Project and SGI GLX_VENDOR(server): SGI Extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync  |
  | WebGL 1 Driver Renderer | Intel Open Source Technology Center -- Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)  |
  | WebGL 1 Driver Version | 3.0 Mesa 19.1.7 |
  | WebGL 1 Driver Extensions | GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_APPLE_object_purgeable GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_INTEL_performance_query GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_fragment_shader_interlock GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_EXT_shader_samples_identical GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_NV_fragment_shader_interlock GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_KHR_parallel_shader_compile GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_sRGB_R8 GL_INTEL_shader_atomic_float_minmax GL_NV_compute_shader_derivatives |
  | WebGL 1 Extensions | ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_disjoint_timer_query EXT_float_blend EXT_frag_depth EXT_shader_texture_lod EXT_sRGB EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context |
  | WebGL 2 Driver WSI Info | GLX 1.4 GLX_VENDOR(client): Mesa Project and SGI GLX_VENDOR(server): SGI Extensions: GLX_ARB_create_context GLX_ARB_create_context_no_error GLX_ARB_create_context_profile GLX_ARB_create_context_robustness GLX_ARB_fbconfig_float GLX_ARB_framebuffer_sRGB GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_buffer_age GLX_EXT_create_context_es2_profile GLX_EXT_create_context_es_profile GLX_EXT_fbconfig_packed_float GLX_EXT_framebuffer_sRGB GLX_EXT_import_context GLX_EXT_texture_from_pixmap GLX_EXT_visual_info GLX_EXT_visual_rating GLX_INTEL_swap_event GLX_MESA_copy_sub_buffer GLX_MESA_query_renderer GLX_MESA_swap_control GLX_OML_swap_method GLX_OML_sync_control GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group GLX_SGI_make_current_read GLX_SGI_swap_control GLX_SGI_video_sync |
  | WebGL 2 Driver Renderer | Intel Open Source Technology Center -- Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2) |
  | WebGL 2 Driver Version | 4.5 (Core Profile) Mesa 19.1.7 |
  | WebGL 2 Driver Extensions | GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_depth_clamp_separate GL_AMD_draw_buffers_blend GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_object_purgeable GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_framebuffer_fetch GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_multimode_draw_arrays GL_INTEL_conservative_rasterization GL_INTEL_performance_query GL_INTEL_shader_atomic_float_minmax GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fragment_shader_interlock GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc |
  | WebGL 2 Extensions | EXT_color_buffer_float EXT_disjoint_timer_query EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic OES_texture_float_linear WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context |
  | Window Protocol | x11 |
  
  </details>

**Comment by grovesNL** [comment]
Thanks for reporting this!

There's a chance we might have already fixed this upstream in a new version of [glow](https://github.com/grovesNL/glow), I can take a look.

**Comment by demurgos** [comment]
I tried to link the latest `glow` version but there was some breaking changes so the compilation failed. I'll wait for you to update it then. Thank you very much for looking into this.

As another datapoint, I still have the same behavior when switching to my discreate GPU: (nVidia GeForce GTX 1050/PCIe/SSE2, driver 435.21.0.0).
