### ISSUE TITLE
Piston game loop example with FirstPerson camera

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#305]
As an idea, we can draw a normal-mapped sphere there, so that camera rotation would make sense.
cc @bvssvni

**Comment by Bastacyclop** [comment]
@kvark I'm closing this: gfx examples are not piston examples.

**Comment by kvark** [comment]
That would be an integration example. I think whoever is higher level should provide those. In this case, Piston seems higher.

**Comment by Bastacyclop** [comment]
Yes, I think linking to piston as a project using gfx like you did in the README is enough.
