### ISSUE TITLE
ShaderStageFlags::ALL does not match vulkan definition

### ISSUE THREAD

**Issue by icefoxen** [gfx-rs/gfx#3079]
Short info header:
- GFX version: 0.4.0
- OS: Linux Ubuntu 18.04
- GPU: NVidia GTX 1060, Vulkan backend.

`ShaderStageFlags::ALL` is defined as `GRAPHICS.bits | COMPUTE.bits` here: https://github.com/gfx-rs/gfx/blob/5ad5cfea6e20ab73851a4f75e2ce3b92ac0a39dd/src/hal/src/pso/mod.rs#L95 
But, the Vulkan spec explicitly says it must be 0x7FFF_FFFF : https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkShaderStageFlagBits .  Presumably they want it to be "all" for realsies, always, no matter what extensions may get added in the future.  I'm not yet sure whether this value gets fed directly into the Vulkan backend without conversion but I'm getting validation errors that *look* related so I'm betting it is.

**Comment by icefoxen** [comment]
Confirmed the value is sent straight to Vulkan, the conversion to Vulkan types is defined here: https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/conv.rs#L174-L176  and used here: https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/command.rs#L942

**Comment by kvark** [comment]
Please post the validation errors for completeness. That one sounds like something we could release in a patch.

**Comment by icefoxen** [comment]
Turns out the validation errors were due to something else.  Sigh!  Still technically maybe-not-correct though.

**Comment by omni-viral** [comment]
IIRC this special value exists so you can specify **all stages that are valid in the context**
