### ISSUE TITLE
internal error: entered unreachable code

### ISSUE THREAD

**Issue by KuSpa** [gfx-rs/gfx#3103]
Short info header:
- GFX version: 0.2.3
- OS: ubuntu  linux 18.04.3 4.15.0-70-generic
- GPU: gtx 980 ti
- GPU Driver: nvidia-driver-390

i'm using amethyst 0.13, which is using 0.2.3. and upon starting i get the error mentioned in the title. 
The error happens in `device::bind_image_memory`( https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/device.rs#L1486 in the current version i guess?). printing the (i guess^^) vulkan error gives: `Unable to enumerate adapters: ERROR_INITIALIZATION_FAILED`

it only happens in 5% of the starts, when i create excatly 3 player gameobjects... having 1,2 or more than 3  works, may be only correlation tho

**Comment by kvark** [comment]
> Unable to enumerate adapters: ERROR_INITIALIZATION_FAILED

Do simple Vulkan apps work for you, like `vkcube`?

**Comment by KuSpa** [comment]
@kvark  yes it does. my stuff sometimes as well, i changed the issue text accordingly

**Comment by kvark** [comment]
Could you try running our examples from master? gfx-hal version 0.2.3 is pretty old at this point.

**Comment by KuSpa** [comment]
sorry for the delay. the example works like a charm. guess its the old version then :/
