### ISSUE TITLE
How to best approach headless rendering

### ISSUE THREAD

**Issue by chinedufn** [gfx-rs/gfx#3107]
Hey!

I'm new to both Vulkan and gfx-hal coming from more of an OpenGL background - so forgive any misguided questions.

I'd like to use gfx-hal to render headlessly to an image as part of a test suite for my game that I'm planning to port to gfx-hal.

I've started by typing out the quad example to get a feel for the API - that was very helpful - thank you!

Now after poking around for a bit I see that `gfx-backend-gl::Headless` can be used for headless rendering.

Great! So I tried to plug that into the quad example (my goal is to figure out how to get the quad example rendering to an image file instead of a window - then I should be good from there for my use case.) but I'm seeing that in `impl hal::Instance<B> for Headless` the `create_surface` method is unimplemented.

First question - is there a reason that that is unimplemented - or is that just something that hasn't happened yet? Do you have a sense of what would be needed to make it happen? If it's beginner friendly I'd be interested in contributing if you could provide some guidance and direction of where to start and what to do.

From there I started to think about how I could just ditch the `Surface` entirely and render to an image using that headless context.

It was at that point I opened this issue so that while I look around someone here might see it and point me in the right direction.

What’s the easiest way to headlessly render and read the pixels back?

Cheers!

---

_side thought: being able to run headless tests in CI and be 95% confident that your application will work across all of your targets assuming that you trust gfx-hal is super appealing - so I wonder if there should eventually be some dedicated docs on headless rendering. Just a quick thought_

**Comment by kvark** [comment]
gfx-hal/Vulkan API is not tied to a "head" like OpenGL is. You start with an `Instance`, and then you can work your way to rendering to an image without considering any of the `Surface`/`Swapchain` stuff.
The GL backend tries to hack around that, it's by any means representing the canonical approach.

**Comment by chinedufn** [comment]
Ahh ok thanks. So regardless of it I’m using the metal or vulkan or dx12 backend I should be able to go from an instance to a byte slice of pixels just fine?

Alright cool - I’ll give that a try - thanks!

**Comment by kvark** [comment]
Absolutely! Just ignore all the `Surface` and `Swapchain` stuff if you are headless.

**Comment by chinedufn** [comment]
Ok so my plan is

1. Don't call `present_surface` and remove all of the other `Surface` and `Swapchain` stuff like you described

2. When creating a framebuffer, Use [create_image](https://docs.rs/gfx-hal/0.4.1/gfx_hal/device/trait.Device.html#tymethod.create_image) and [create_image_view](https://docs.rs/gfx-hal/0.4.1/gfx_hal/device/trait.Device.html#tymethod.create_image_view) to create the `ImageView` for my framebuffer. Then submit it like the `quad` example does now

3. I believe that after calling `submit` my `ImageView` will have the pixel data? If so - here's a problem I foresee:

Metal's `ImageView` has `pub (crate)` visibility https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/native.rs#L390-L393 and I don't see any APIs for accessing it from outside of the crate.

Given this - would that mean that it isn't currently possible to get the pixel data from the metal backend while rendering headlessly? Or am I overlooking something (I haven't tried any of the above yet - plan to take a look tonight) ?

Thanks!

**Comment by chinedufn** [comment]
Similarly - the Vulkan `ImageView` https://github.com/gfx-rs/gfx/blob/master/src/backend/vulkan/src/native.rs#L54-L60 fields only have crate visibility.

I'd like to use `Metal` when developing locally and `Vulkan` in CI - so currently trying to figure out how to best get the pixel data out of the `ImageView`'s - assuming that is the correct approach here.

If this is already possible and I'm missing something - sorry! Otherwise - I'd be happy to contribute any changes necessary to make this possible if you can point me in the right direction.

Cheers!

**Comment by kvark** [comment]
@chinedufn are you attempting to invest into learning Vulkan/gfx-hal in order to achieve the goals? 

If you don't know what you are doing, perhaps you would be better off with higher level libraries. For example, wgpu-rs has an example doing exactly what you are looking for: https://github.com/gfx-rs/wgpu-rs/blob/master/examples/capture/main.rs 

More to the point, you aren't supposed to use any fields of `ImageView` or other structs associated from the backend. Once you scheduled some rendering into an image (that the image view is pointing at), you'd need to schedule a copy from this image into a buffer that is CPU-visible.

Closest source that uses gfx-hal directly that I know is our Warden test suite, which is purely headless: https://github.com/gfx-rs/gfx/blob/99e3ee35adddf28b30e47247a10905b6fd375a66/src/warden/src/gpu.rs#L1539

**Comment by chinedufn** [comment]
So the larger goal here is to port my WebGL engine to Vulkan / gfx-hal. I'd rather learn, use and understand Vulkan/gfx-hal than use a higher level library. It'll be slower in the short term but I'm very interested in the long term advantages of truly understanding my graphics pipeline - especially when building on top of Rust which generally makes it pretty easy to organize complex code/concepts over time if you understand them.

As a start to this goal I'm experimenting with taking very small pieces of the engine and implementing them with gfx-hal with test coverage - to see how it feels / performs / etc.

Also - starting off at the gfx-hal level is a lot more fun for me (;

---

I'll read over that wgpu-rs implementation and warden and use that as a guide for getting headless rendering working.

Sorry for the trouble - I'll poke around myself from here - thanks for pointing me in the right direction!

**Comment by kvark** [comment]
Please don't hesitate to talk to us at https://gitter.im/gfx-rs/gfx or https://gitter.im/gfx-rs/webgpu , and good luck!
