### ISSUE TITLE
Match shader samplers type against user-provided texture/sampler pair

### ISSUE THREAD

**Issue by sectopod** [gfx-rs/gfx#311]
Need more safety here! Optimally, we'd like to match at the time user sets up the parameter, not at the draw call itself. This affects MSAA #308. AFAIK, the current approach is to have draw calls unfailable.

**Comment by bvssvni** [comment]
Will this allow changing texture filter at drawing? In the Piston 2D back-ends we would like to choose between linear and nearest filter using the same program.

**Comment by kvark** [comment]
This issue is only about safety checks, not new abilities. Changing the filter mode at drawing is, of course, allowed (see [my other response](https://github.com/PistonDevelopers/gfx_graphics/issues/272#issuecomment-162395962)).

**Comment by kvark** [comment]
Not happening in pre-ll
