### ISSUE TITLE
Fix Warden to work without timer queries

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3126]
Currently, Warden can't be used for reftesting and benchmarking on many platforms because it assumes the support for time queries. We need to make it more flexible. This will open the road to enable it on Travis for CI headless.

In order to repro, either run `make reftests` if you are not on Windows, or specifically `cd src/warden && cargo run --bin reftest --features gl -- ci` if you are on Windows.

**Comment by bzm3r** [comment]
How difficult is it to expose the timestamp query capability of the DX12 API through gfx-hal. I have used it for [piet-dx12](https://github.com/bzm3r/piet-dx12/blob/929e8fd42de649b6eebe899f917cd54bed95cc32/src/gpu.rs#L801) but do not know what the challenges will be in exposing it through the `write_timestamp` methods provided by gfx-hal. 

Second, would the alternative to timestamp querying be `std::time::Instant`, as is done here: https://github.com/bzm3r/transpose-timing-tests/blob/5561d919b5d9e5079d98d03e3085c5a193caf732/src/gpu.rs#L299 ?

**Comment by kvark** [comment]
I think D3D12 time queries are going to be straightforward to port, see https://docs.microsoft.com/en-us/windows/win32/direct3d12/queries

`std::time::Instant` is not an alternative since it measures CPU time, while we are interested in GPU time here.
