### ISSUE TITLE
Features for read-only storage descriptors

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3164]
Knowing if something is read-only is a good way for us to do less work. Both direct users of gfx-rs and wgpu *do* know that, and would like to communicate it to us. However, Vulkan Portability doesn't know about that and would like us to operate in the blind.

I wonder if we can support this by having a "READONLY_STORAGE" feature that VkPI will not enable.

Another way to address this would be having a "PORTABILITY" feature - this has the benefit of the "default" being more restricted and closer to WebGPU.

We could also consider refactoring the descriptor types to add:
  - read-only image storage
  - comparison samplers

**Comment by msiglreith** [comment]
Sounds reasonable to me. Exposing an additional access flag might help as well for dx12

**Comment by kvark** [comment]
@msiglreith hmm, as I implemented this, I realized that maybe this was a bad idea. We can easily have `read-only` always treated as supported. gfx-portability would just not use it at all ever.
