### ISSUE TITLE
Released version of `gfx-backend-dx12` not in repository?

### ISSUE THREAD

**Issue by hannobraun** [gfx-rs/gfx#3171]
The latest version of `gfx-backend-dx12` release on crates.io is, as of this writing, version 0.4.3: https://crates.io/crates/gfx-backend-dx12

While the version in this repository is version 0.4.0: https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12/Cargo.toml#L3

Seems like something is amiss. Is it possible that the most recent releases are stuck in the local repository of whoever published them?

**Comment by hannobraun** [comment]
Same issue with `gfx-backend-vulkan`. Released version is 0.4.2, version in repository is 0.4.0.

**Comment by grovesNL** [comment]
Hi, the source for all version 0.4.x releases is located under the `hal-0.4` branch: https://github.com/gfx-rs/gfx/tree/hal-0.4 (we could bump the versions on `master` to match, but `master` is always ahead of those version numbers so it's a bit misleading anyway)

**Comment by hannobraun** [comment]
Ah thank you, that makes total sense, I didn't think to look for a release branch.
