### ISSUE TITLE
Extras library

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3177]
Using bits of Rendy introduces some unfortunate friction, e.g. timeline of https://github.com/amethyst/rendy/pull/269
Perhaps, we should just start a `gfx-extras` crate with libraries for descriptor and memory management?

**Comment by GabrielMajeri** [comment]
We now have a `gfx-extras` crate. Is this issue still relevant?

**Comment by kvark** [comment]
Indeed, this was resolved!
