### ISSUE TITLE
Unbound image subresources

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3200]
We should remove the use of `Range` in `image::SubresourceLayers` and `image::SubresourceRange`, and instead pass count of layers/mipmaps as `Option<NonZero>`.  This would correspond to `VK_REMAINING_ARRAY_LAYERS` and `VK_REMAINING_MIP_LEVELS` in vulkan. We could also take this opportunity to refine the terms used for fields and comments.

**Comment by hgallagher1993** [comment]
Hi, just to let you know I've started working on this :+1:

**Comment by kvark** [comment]
@hgallagher1993 I assume the issue is up for grabs again

**Comment by hgallagher1993** [comment]
@kvark I did completely forget about it but I started looking into this again about 2 weeks ago (it's how I found #3319 😄), I was using the reftests just to make sure everything was compiling and working so with that fix merged I plan on working on this again today. I mostly have this finished from a couple of months ago so it shouldn't take me too long I don't think.

**Comment by kvark** [comment]
Oh that's wonderful news! looking forward to it - this is our last blocker, pretty much.

**Comment by kvark** [comment]
@hgallagher1993 did you get anywhere with this?

**Comment by hgallagher1993** [comment]
@kvark sorry for the late reply I was traveling to my home country all day yesterday. I had actually pretty much finished this I think but running `cargo run --bin quad --features dx12` on Windows leads to 20 compile errors (unrelated to my changes) so before creating the merge request for this I was going to look into fixing them as well just so I could have everything compiling properly

**Comment by hgallagher1993** [comment]
@kvark created the issue for the compile failures here #3334
