### ISSUE TITLE
Use inplace_it in Vulkan for alloca

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3201]
We have this performance issue in Vulkan backend that gfx-rs API is based on iterators, and Ash expects slices, so we need some extremely lightweight way of producing a slice, sometimes without knowing anything about the number of elements. Basically, we want `alloca`, but it's not available in Rust.

However there is a simple crate that does something similar - https://github.com/NotIntMan/inplace_it . We should try it out and see if we can remove all the heap allocations from hot paths of the Vulkan backend, and possibly in other backends too.

**Comment by khodzha** [comment]
doesnt it require knowing number of elements upfront? and that requires walking iterator twice, is that acceptable?

https://docs.rs/inplace_it/0.3.0/inplace_it/fn.inplace_or_alloc_array.html

**Comment by kvark** [comment]
Good point! Problem with walking twice is that an iterator may not necessarily be clonable, i.e. it can have side effects...
How do you feel about changing the relevant gfx-hal API signatures to require `ExactSizeIterator` instead of a regular iterator? That would give us the size.

**Comment by khodzha** [comment]
> How do you feel

i dont have much experience with graphics so i have no opinions on this, `ExactSizeIterator` works for me :+1:

**Comment by kvark** [comment]
@khodzha would you want to try making this API change? This could be interesting experience. I think there are other opportunities in backends to take advantage of the size, so it would be an all-around win.

**Comment by khodzha** [comment]
yeah i can do that
