### ISSUE TITLE
GL depth buffer not being cleared

### ISSUE THREAD

**Issue by chemicstry** [gfx-rs/gfx#3202]
Short info header:
- GFX version: 0.5.0
- OS: Windows 10
- GPU: GTX 1070

When `glDepthMask` is set to false, clears do not work on depth buffer. This happens when last rendered item on the pipeline was transparent and `depth.write` was set to false. This prevents next frame from clearing the depth buffer. This does not happen on vulkan and depth buffer is cleared correctly.

I guess the easy fix is to just set depth mask to true in https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/queue.rs#L530 before clear? Restoring previous value is not neccessary as render pass will set it anyway

**Comment by kvark** [comment]
Yes, that would be a nice little patch. Thank you for reporting! Please consider making a PR:)
