### ISSUE TITLE
Out of bounds array access when passing a buffer name with a length >= 64

### ISSUE THREAD

**Issue by HalfVoxel** [gfx-rs/gfx#3213]
Passing a label name (for e.g. a buffer) with a length greater or equal to 64 will cause the code to try to write to an index outside the length of the array. This is fine in debug mode when bounds checks are enabled, but in release mode this will cause undefined behaviour.

I'm not sure what should happen in this case, either it could silently truncate the string to 64 characters or it could panic.

https://github.com/gfx-rs/gfx/blob/deeb135553dccbc654ce105c042aa07b4cdbdd23/src/backend/vulkan/src/device.rs#L2284

**Comment by kvark** [comment]
@HalfVoxel this is just wrong. It needs to copy the right amount of data, so that there is room for the sentinel. Would you want to make a patch?

**Comment by HalfVoxel** [comment]
I could probably do that.
Also, is this method supposed to be thread safe? If it is, I should probably also make it not use a static buffer which is shared between all threads.

**Comment by kvark** [comment]
Yes, it needs to be thread safe. Therefore, a static buffer can't be used here.

**Comment by HalfVoxel** [comment]
I created a pull request.
I tried to maintain the non-allocating common case for small strings, even though it does add a bit of complexity. This method is probably relatively hot though, so it makes sense to me.
