### ISSUE TITLE
Remove slice from Batch and add .draw_slice

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#322]
The draw method could use `mesh.as_slice()` by default.

This will make it simpler to render a part of the mesh without having to mutate the batch state.

**Comment by kvark** [comment]
This might help the ergonomics of hand-written code snippets only, it doesn't help any non-trivial stuff. Be sides, but we should be aware of the exponential growth of `draw()` methods. I'm leaning towards negative here. Any votes from @bjz , @cmr , @csherratt ?

**Comment by bjz** [comment]
I'm not sure - I'll have to look after work.

**Comment by bjz** [comment]
What do you mean by 'hand written code snippets'?

**Comment by kvark** [comment]
@bjz I mean code where you manually draw something concrete, as the opposite to generic code that generates/loads and renders something. What I meant is: for the most cases you need indices, hence you need the slice.
