### ISSUE TITLE
gfx-backend-gl does not respect pso::GraphicsPipelineDesc::baked_states

### ISSUE THREAD

**Issue by tyleo** [gfx-rs/gfx#3257]
Short info header:
- GFX version: 0.5
- OS: Windows 10
- GPU: Nvidia GeForce GTX 1082

I'm doing some experiments with cross-platform rendering using gfx-hal.

I have a program which renders a simple triangle using a vertex buffer. I'm creating a new `pso::GraphicsPipelineDesc` every time I resize the window. The `pso::GraphicsPipelineDesc` gets a `pso::BakedStates` with the correct `viewport` and `scissor` confirmed with a couple of `println!()`s.

This appears to resize correctly on all platforms except OpenGL. On OpenGL I only see the correct behavior if I do the following while recording my `CommandBuffer`:
```rust
command_buffer.set_viewports(0, &[viewport.clone()]);
command_buffer.set_scissors(0, &[viewport.rect.clone()]);
```

A quick look through the gfx code shows that the `pso::GraphicsPipelineDesc::baked_states` are not used by OpenGL, requiring this extra step.

I can easily work around this and I'm not sure that its a bug. Nonetheless, I thought I'd bring it up here so it is at least documented if anyone else encounters this issue.

**Comment by kvark** [comment]
Thank you for filing! GL backend is missing quite a bit of functionality, and isn't tested as well.
Baked states is one of the things we need.
