### ISSUE TITLE
Avoid heap allocations in GraphicsPipelineDesc

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3259]
It currently has a lot of `Vec` arguments. This should be unnecessary.

**Comment by khodzha** [comment]
@kvark could you elaborate if you are talking about `PrimitiveAssembler` (which has `buffers` and `attributes` vecs) argument here?

**Comment by kvark** [comment]
@khodzha there wasn't `PrimitiveAssembler` at the time the bug was written. Today I can confirm that all the `Vec`s we want to eliminate are inside `PrimitiveAssembler`, so you are right.
