### ISSUE TITLE
vulkan on windows doesn't find any adapters on backend surface

### ISSUE THREAD

**Issue by torresguilherme** [gfx-rs/gfx#3273]
Short info header:
- GFX version: gfx-hal 0.5.0 with vulkan backend (version 0.5.1). Also relevant: i'm using winit for the window instance (tried with version 0.20 and 0.22.2)
- OS: Windows 10
- GPU: NVidia GeForce 635M

vulkan doesn't find any adapters on windows 10 in the current configuration.

error: `thread 'main' panicked at 'removal index (is 0) should be < len (is 0)', src\liballoc\vec.rs:1057:13`

tracing back with a debugger, i found the error to be in the following lines:

```
    // create backend
    let (instance, surface, adapter) = {
        let instance = backend::Instance::create(name, 1).expect("Backend not supported");

        let surface = unsafe {
            instance
                .create_surface(&window.window_instance)
                .expect("Failed to create surface for window")
        };

        let adapter = instance.enumerate_adapters().remove(0); // panic in this line

        (instance, surface, adapter)
    };
```

my code pretty much follows [mistodon's triangle tutorial](https://github.com/mistodon/gfx-hal-tutorials/blob/master/doc/part-1-triangle.adoc) by the book.

any help i can get here is appreciated

**Comment by kvark** [comment]
Looking at https://www.techpowerup.com/gpu-specs/geforce-gt-635m.c2232, it looks like your HW just doesn't support Vulkan.

**Comment by torresguilherme** [comment]
thanks for the response.
also, [this test](https://github.com/skeeto/vulkan-test) reported me a thumbs up. and i'm pretty sure i did some stuff with vulkano on it last year.
also, an "adapter" to abstract the physical device is not a thing in the vulkan C api as far as i'm concerned...

**Comment by kvark** [comment]
The test you linked to only tries to create a Vulkan instance, which is a matter of having Vulkan drivers but not necessarily Vulkan support by the hardware. In the gfx-hal code you posted `backend::Instance::create` also succeeds just fine.

If you can run Ash or Vulkano, that would be good to know. Could you double-check? gfx-rs also uses Ash in the Vulkan backend.

>  an "adapter" to abstract the physical device is not a thing in the vulkan C api as far as i'm concerned

Yep, and gfx-rs is not exactly Vulkan C API either. That would be [gfx-portability](https://github.com/gfx-rs/portability).

**Comment by torresguilherme** [comment]
by the way, i just thought of something... when i ran vulkano on it, i may or not have used the intel chip and not the nvidia discrete card. but i guess that shouldn't matter since the outcome of my gfx-hal code is the same log regardless.

anyway i'll report back soon for sure :)

**Comment by torresguilherme** [comment]
i just tested the vulkano triangle example and it panicked. "incompatible driver". that does say something.

and since my anecdotal evidence from last year doesn't really tell a lot, we can settle at that, i guess. this shouldn't be a gfx-rs issue at least.
