### ISSUE TITLE
How to use gfx-rs correctly and what about GLFW and Vulkan?

### ISSUE THREAD

**Issue by MarioSieg** [gfx-rs/gfx#3288]
Hello everyone,

I've recently switched from C++ to Rust for game development. I'm recreating my engine and so far I'm pretty happy with Rust and it's wonderful community. Back in C++ I used bgfx https://github.com/bkaradzic/bgfx as a rendering abstraction library. Now I want to use gfx-rs. But I'm a little confused:  at the docs https://docs.rs/gfx/0.18.2/gfx/ they write about Factory and Device in the crate gfx. But at the gfx examples (in this repo) they never use them. They also always use "hal" instead of "gfx" so what up with that? What is the current correct way to use this library? Also I've seen gfx-window-glfw uses an OpenGL Device - but is it still possible to use Vulkan then?

Thanks in advance and sorry for this dump question!

Best Regards,
Mario

**Comment by kvark** [comment]
Hi!

You are looking at the wrong crate. Check out the readme, it has links to [gfx-hal crate](https://crates.io/crates/gfx-hal) as well as a [section](http://kvark.github.io/tech/arguments/2020/06/30/technical-discussions.html) explaning what `gfx` crate was.

Another thing is - published version is not the same as the `master` version, the latter is always a bit ahead, so examples would have slightly different code too. If you are looking for the example code for the last published version, you need to see the [hal-0.5 branch](https://github.com/gfx-rs/gfx/tree/hal-0.5/examples).

Finally, if you are used to `bgfx`, I recommend looking at https://github.com/gfx-rs/wgpu-rs instead. gfx-hal is extremely low level and unsafe, it would be a difficult thing to grasp right off the bat.

**Comment by MarioSieg** [comment]
Hey,
I apologize for that - didn't see it!
I know gfx-hal is low level but I recently started to learn Vulkan so it's okay.
Just by the way to you know any examples with gfx-hal wich are using 3D meshes? Like a cube or triangle example? I wasn't able to find any!

Thank you,
Mario

**Comment by kvark** [comment]
@MarioSieg the most complex example using gfx-hal *directly* is https://github.com/gfx-rs/gfx-ocean
Other things go through wgpu-rs or Rendy, e.g. https://github.com/termhn/rendy-pbr
