### ISSUE TITLE
Vulkan backend: acquire_image unwraps option, panics if no swapchain

### ISSUE THREAD

**Issue by btrepp** [gfx-rs/gfx#3295]
Short info header:
- GFX version: gfx-hal = "0.5.2"
                      gfx-backend-vulkan = "0.5.8"
- OS: windows 10
- GPU:  Rx Vega 64

From
https://github.com/gfx-rs/gfx/blob/f9bd1e11f2616beb3b95645914e1803b1bdc9b22/src/backend/vulkan/src/window.rs#L503

It looks like acquire_image unwraps the swapchain. If call it before a swapchain is initialized you get a panic. The function signature is a result type, so it might be better to return an error about the swapchain not being configured?

> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.8\src\window.rs:503:19
> stack backtrace:
>    0: backtrace::backtrace::trace_unsynchronized
>              at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
>    1: std::sys_common::backtrace::_print_fmt
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:78
>    2: std::sys_common::backtrace::_print::{{impl}}::fmt
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:59
>    3: core::fmt::write
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\fmt\mod.rs:1069
>    4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\io\mod.rs:1504
>    5: std::sys_common::backtrace::_print
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:62
>    6: std::sys_common::backtrace::print
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\sys_common\backtrace.rs:49
>    7: std::panicking::default_hook::{{closure}}
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:198
>    8: std::panicking::default_hook
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:218
>    9: std::panicking::rust_panic_with_hook
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:511
>   10: std::panicking::begin_panic_handler
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:419
>   11: core::panicking::panic_fmt
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:111
>   12: core::panicking::panic
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libcore\panicking.rs:54
>   13: core::option::Option<mut gfx_backend_vulkan::window::SurfaceSwapchain*>::unwrap<mut gfx_backend_vulkan::window::SurfaceSwapchain*>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\macros\mod.rs:34
>   14: gfx_backend_vulkan::window::{{impl}}::acquire_image
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-backend-vulkan-0.5.8\src\window.rs:503
>   15: diengine::gfx::device::Renderer<gfx_backend_vulkan::Backend>::render<gfx_backend_vulkan::Backend>
>              at .\src\gfx\device.rs:47
>   16: diengine::main::{{closure}}
>              at .\src\main.rs:38
>   17: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<(),closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:200
>   18: alloc::boxed::{{impl}}::call_mut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*),FnMut<(winit::event::Event<()>, mut winit::event_loop::ControlFlow*)>>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\liballoc\boxed.rs:1015
>   19: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:239
>   20: std::panic::{{impl}}::call_once<(),closure-0>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
>   21: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,()>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
>   22: winit::platform_impl::platform::window::TASKBAR_LIST::__getit
>   23: std::panicking::try<(),std::panic::AssertUnwindSafe<closure-0>>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
>   24: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
>   25: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),(),closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
>   26: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::call_event_handler<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:233
>   27: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::send_event<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:208
>   28: winit::platform_impl::platform::event_loop::SubclassInput<()>::send_event<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:90
>   29: winit::platform_impl::platform::event_loop::public_window_callback::{{closure}}<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:819
>   30: core::ops::function::FnOnce::call_once<closure-0,()>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\ops\function.rs:232
>   31: std::panic::{{impl}}::call_once<isize,closure-0>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:318
>   32: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:331
>   33: std::panicking::try::do_catch<std::panic::AssertUnwindSafe<closure-0>,isize>
>   34: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panicking.rs:274
>   35: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\panic.rs:394
>   36: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<()>::catch_unwind<(),isize,closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop\runner.rs:150
>   37: winit::platform_impl::platform::event_loop::public_window_callback<()>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:1893
>   38: DefSubclassProc
>   39: DefSubclassProc
>   40: CallWindowProcW
>   41: DispatchMessageW
>   42: IsWindowVisible
>   43: KiUserCallbackDispatcher
>   44: NtUserDispatchMessage
>   45: DispatchMessageW
>   46: winit::platform_impl::platform::event_loop::EventLoop<()>::run_return<(),closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:215
>   47: winit::platform_impl::platform::event_loop::EventLoop<()>::run<(),closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\platform_impl\windows\event_loop.rs:185
>   48: winit::event_loop::EventLoop<()>::run<(),closure-0>
>              at C:\Users\Beau\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.22.2\src\event_loop.rs:149
>   49: diengine::main
>              at .\src\main.rs:23
>   50: std::rt::lang_start::{{closure}}<()>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
>   51: std::rt::lang_start_internal::{{closure}}
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:52
>   52: std::panicking::try::do_call
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:331
>   53: std::panicking::try
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panicking.rs:274
>   54: std::panic::catch_unwind
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\panic.rs:394
>   55: std::rt::lang_start_internal
>              at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\/src\libstd\rt.rs:51
>   56: std::rt::lang_start<()>
>              at C:\Users\Beau\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
>   57: main
>   58: invoke_main
>              at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
>   59: __scrt_common_main_seh
>              at d:\agent\_work\5\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
>   60: BaseThreadInitThunk
>   61: RtlUserThreadStart
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> error: process didn't exit successfully: `target\debug\diengine.exe` (exit code: 101)

**Comment by kvark** [comment]
The story about returning result types has a lot of baggage in gfx, but in general the idea we want to follow is: results are for things that the user can *not* anticipate. Like, out of memory, or, in this case, window moved to a different monitor. Results in gfx-rs are *not* for errors that the user makes in using the API. In this case, it's clearly a user error, so we technically can behave totally nuts (unsafe/UB) in such cases, and panicking is the best outcome.
