### ISSUE TITLE
Change Requirements::memort_type_bits to u32

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3298]
That would match Vulkan. There is no need for it to be `u64`, really.

**Comment by khodzha** [comment]
@kvark could you clarify, you want this https://github.com/gfx-rs/gfx/blob/dafb4e8ea6ef675b8c980025be8504681b66e216/src/hal/src/memory.rs#L102 changed to u32? 

is it ok to change this
https://github.com/gfx-rs/gfx/blob/dafb4e8ea6ef675b8c980025be8504681b66e216/src/backend/gl/src/lib.rs#L329 and this
https://github.com/gfx-rs/gfx/blob/dafb4e8ea6ef675b8c980025be8504681b66e216/src/backend/gl/src/lib.rs#L350 to u32 too?

**Comment by kvark** [comment]
yes, all of them. Ideally, we can make a typedef `type MemoryTypeMask = u32` and use it in those places
