### ISSUE TITLE
Investigate using Vulkan api version 1.1+

### ISSUE THREAD

**Issue by Wumpf** [gfx-rs/gfx#3302]
Currently the Vulkan backend is hardcoded to use version 1.0.0. Changing it to use the newest available version is easy:
```
        let api_version_default = vk::make_version(1, 0, 0);
        let api_version = entry
            .try_enumerate_instance_version()
            .unwrap_or(Some(api_version_default))
            .unwrap_or(api_version_default);
        trace!(
            "Using Vulkan api version {}.{}.{}",
            vk::version_major(api_version),
            vk::version_minor(api_version),
            vk::version_patch(api_version)
        );
```
(and pass this to `vk::ApplicationInfo`)

However, it is currently unknown if this would break any existing API: Many inputs to the gfx-hal api are just passed on to Vulkan as-is. Need to map out changes to Vulkan core in 1.1/1.2/.. and figure out if anything could behave differently in newer versions.

**Comment by tangmi** [comment]
Possibly relevant (from LunarG):
- [Vulkan-SDK-Version-Compatibility_4_20.pdf](https://www.lunarg.com/wp-content/uploads/2020/03/Vulkan-SDK-Version-Compatibility_4_20.pdf): Says that that minor versions of Vulkan are backwards compatible and that there are some extra steps required in 1.1 for context creation.
- [1.1-Compatibility-Statement_05_18.pdf](https://www.lunarg.com/wp-content/uploads/2018/05/1.1-Compatibility-Statement_05_18.pdf): Basically says the same thing, but specific for a 1.0 to 1.1 migration.

It seems like upgrading to 1.1+ will be pretty straightforward. When we implement features like descriptor indexing or ray tracing, we may need to be careful to conditionally light them up in the Vulkan backends based on the SDK version as well as the feature availability (although my driver will happily report ray tracing is available on a 1.0 device...).
