### ISSUE TITLE
Fill in Limits Required by Wgpu

### ISSUE THREAD

**Issue by cwfitzgerald** [gfx-rs/gfx#3308]
Now that wgpu has support for limits, the various gfx-hal backends need to make sure they are filling in at least all the limits required by wgpu. As of right now we max the limits with the default to force a minimum, but this isn't accurate to the hardware.

There is a decent amount of research that has to go into figuring out the exact values for all the backends as some backends (like dx12) some things don't have limits like vulkan does.

**Comment by kvark** [comment]
I just realized that this issue doesn't actually tell which limits are missing.

**Comment by cwfitzgerald** [comment]
So at this point, both DX11 and DX12 are updated, so unless you think metal needs more work, we can close this, at least until GL is re-enabled.
