### ISSUE TITLE
Use ExactSizeIterator bound in command encoding methods

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3309]
As a follow-up to https://github.com/gfx-rs/gfx/pull/3307 we'd want to put `ExactSizeIterator` bound on the methods that are called often, methods of `trait CommandBuffer`.
cc @khodzha

**Comment by khodzha** [comment]
i found only `wait_events` and `execute_commands` are collecting into `Vec`s and not into `SmallVec`s

do you want only those to be bounded? :thinking:

**Comment by kvark** [comment]
`SmallVec` there is still risky, I'd ideally want to replace the uses of `SmallVec` with `inplace_it` or `ArrayVec`, maybe even removing `smallvec` completely from the dependencies. The concern about `SmallVec` is having a threshold. Once you cross it, there is a performance cliff. For example for the `blit_image` we have a capacity of 4. Once the user blits 5 regions, and it's perf-critical code, they hit a performance pitfall.

`SmallVec` is good when there is a "natural" cut-off. For example, if something has a "typically one, but sometimes many" semantics, it works. But if there is no "natural" cut-off point, then `SmallVec` is not a good fit.

If it's possible to enforce a compile-time maximum, `ArrayVec` is good. For example, we can define `MAX_DESCRIPTOR_SETS: usize = 16` and cap the limits to it. So that we can use `ArrayVec[_; MAX_DESCRIPTOR_SETS]` for anything related.

In all other places (e.g. copy regions, or barriers), we don't have either the maximum, or a natural cut-off, so `inplace_it` works best.

**Comment by kvark** [comment]
Also, regardless of what Vulkan backend will use to back them, we need to add the `ExactSizeIterator` for the API, to allow future optimizations in all backends.
