### ISSUE TITLE
Build errs  for gfx_hal crate with rust 1.45

### ISSUE THREAD

**Issue by frankieD3** [gfx-rs/gfx#3321]
Short info header:
- GFX version: 1.53
- OS: window
- GPU: N/A

Get the following errors with 1.45 rust:
```
:: C:/users/fdemi/OneDrive/Documents/Development/.cargo\registry\src\github.com-1ecc6299db9ec823\gfx-hal-0.5.3\src\command\mod.rs:136:15
    |
136 |     unsafe fn pipeline_barrier<'a, T>(
    |               ---------------- the trait cannot be made into an object because method `pipeline_barrier` has generic type parameters
...
152 |     unsafe fn clear_image<T>(
    |               ----------- the trait cannot be made into an object because method `clear_image` has generic type parameters
...
164 |     unsafe fn clear_attachments<T, U>(&mut self, clears: T, rects: U)
    |               ----------------- the trait cannot be made into an object because method `clear_attachments` has generic type parameters
...
173 |     unsafe fn resolve_image<T>(
    |               ------------- the trait cannot be made into an object because method `resolve_image` has generic type parameters
...
186 |     unsafe fn blit_image<T>(
    |               ---------- the trait cannot be made into an object because method `blit_image` has generic type parameters
...
217 |     unsafe fn bind_vertex_buffers<I, T>(&mut self, first_binding: pso::BufferIndex, buffers: I)
    |               ------------------- the trait cannot be made into an object because method `bind_vertex_buffers` has generic type parameters

and more lines
...
```
If I revert back to 1.44 it build correctly.

Frank

**Comment by kvark** [comment]
Does the error say *where* we are trying to make the trait into an object?

**Comment by frankieD3** [comment]
I  have been forgetting how everything gets built. I have been working on porting to recent crates and version of rust, learning_gfx_hal . Part of my learning experience with Rust. I believe that the compiler is attempting to create functions for a deceleration:
`
#[cfg(feature = "dx12")]
use gfx_backend_dx12 as back;
#[cfg(feature = "metal")]
use gfx_backend_metal as back;
#[cfg(feature = "vulkan")]
use gfx_backend_vulkan as back;

command_buffers: Vec<CommandBuffer<back::Backend >>,
    command_pool: ManuallyDrop<dyn CommandPool<back::Backend>>,
`
The compiler attempts with 1.45 to create the trait suitable for the last two lines above and attempts to build the traits.  However probably more to the point 
those 2 lines create their own errs: 
the size for value of type  "  each type above" cannot be know at compile time. 

I am working out how to work how to declare those types that satisfy current levels of crates and rust. There has been a lot of change since the learning_gfx_hal tutorial.

I am interested in updating the tutorial but need to figure out how to reach the correct people so I get it right.

Frank

**Comment by kvark** [comment]
Alright, so it looks like the failing entity here is the tutorial, not gfx-hal itself.
