### ISSUE TITLE
Expose IMAGE_CUBE_ARRAY feature

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3324]
This is needed for `wgpu`. On Metal, it requires iOS 11+, see https://developer.apple.com/documentation/metal/mtltexturetype/mtltexturetypecubearray?language=objc

**Comment by zakorgy** [comment]
I think this was adressed in https://github.com/gfx-rs/gfx/commit/4a95ec7f8015f1c8781712849080a9c14cd7d9a1#diff-869ac7455848098462f60a2653891c381c147fc4ce300a5b9b58f1fdca130251R851
