### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [gfx-rs/gfx#3352]
Is it possible to update examples ?
Now the winit is not defined anymore in GL backend, can it possible to continue to use it ?

A simple 
```
cargo run --example quad --feature gl
```
returns:
`thread 'main' panicked at 'not implemented', /Users/marco/dev/mediaio/gfx/src/backend/gl/src/window/dummy.rs:20:9`

**Comment by kvark** [comment]
GL is temporarily disabled currently. It's not a problem with examples. Keep an eye on #3340
