### ISSUE TITLE
[Question] gfx-hal or ash

### ISSUE THREAD

**Issue by discosultan** [gfx-rs/gfx#3365]
I know that I will only be using the Vulkan backend. Are there any benefits to using gfx-hal instead of ash directly in that case?

**Comment by kvark** [comment]
How are you going to run on platforms that do not have Vulkan? All macOS, iOS, Windows with Intel broadwell/haswell and lower?

**Comment by discosultan** [comment]
That is not a concern because I intend to run only on my machine where I know Vulkan to always be available.

**Comment by kvark** [comment]
Technically, you'd be having gfx-backend-vulkan between your app and Ash serving no direct benefit. So at first sight, it seems that going with Ash directly makes more sense.

There are network effects though. For example, with gfx-rs you'd be able to use https://github.com/gfx-rs/gfx-extras for automatic memory and descriptor allocation.
