### ISSUE TITLE
Default values for push constants in D3D12

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3374]
In D3D12, push constants are part of the root signature, which is associated with the pipeline layout. Therefore, values always flow from the root signature into the shader, not the other way around. If we want to use the default value and not require the user to always provide some, we should be reading it from the shader. Here are rough steps:
  1. when creating a pipeline, read the default values for push constants, match them against the pipeline layout, and store them somewhere in the pipeline
  2. in [flush_user_data](https://github.com/gfx-rs/gfx/blob/08d6110b6843ab01f314dc6f440e24e48945b096/src/backend/dx12/src/command.rs#L278), if a constant doesn't have a value in the `user_data`, we need to get it from the current pipeline.

Ideally, we need to rehash the understanding about how the default values work in Vulkan...

**Comment by msiglreith** [comment]
Is this about specialization constants? Would be news to me that there are default values for push constants in SPIR-V

**Comment by kvark** [comment]
You are right, I mixed things up. I was talking about this line:
```
layout(constant_id = 0) const float scale = 1.2f;
```
It is a specialization constant.
I got confused because the example specifies the push constant ranges.

Anyway, need more of a fresh head when I'm hacking stuff. Thank you for correction!
