### ISSUE TITLE
Multiple frames in flight

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3404]
We need to support this sequence: Acquire(1) , Acquire(2), Present(1), Present(2).
It's supported on Vulkan and Metal now. However, there is a problem with D3D, and it's blocking Dota2 on DX12 experiment:
> D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandLists: A command list, which writes to a swapchain back buffer, may only be executed when that back buffer is the back buffer that will be presented during the next call to Present*. Such a back buffer is also referred to as the "current back buffer". Swap Chain: 0x00000112B7BF9F60:'Unnamed Object' - Current Back Buffer Buffer: 0x00000112B7BE9060:'Unnamed ID3D12Resource Object' - Attempted Write Buffer: 0x00000112B7A0FD90:'Unnamed ID3D12Resource Object' [ STATE_SETTING ERROR #907: EXECUTECOMMANDLISTS_WRONGSWAPCHAINBUFFERREFERENCE]

As far as I see, in DXGI, you can only do `GetCurrentBackBufferIndex()` followed by `Present()`. It appears to me that there is now way to do either of these:
  - select which image you are presenting
  - get next index of the backbuffer instead of the current one

**Comment by msiglreith** [comment]
Right now I see two options:
A: Virtualize the swapchain images with an hidden transfer operation on present (performance overhead)
B: Limit the range of min/max images by setting both equal. This should allow the application to only acquire 1 frame at the time without infinite blocking.

**Comment by kvark** [comment]
I tried reporting that we only support 1 image - Dota hangs on `SwapBuffers`. Not sure yet if we are doing anything wrong.
Tried reporting only 2 - Dota still tries to acquire both (d'oh!). It's possible that it only does that at start, I'm not sure.

I was thinking maybe there is also another crazy choice:
C: whenever we detect that another frame is acquired, create an extra DXGI swapchain on the same surface.

**Comment by kvark** [comment]
Fixed in #3424 by the following hack: if we are acquiring a second/third/etc frame, we consider the `(GetCurrentBackBufferIndex() + N) % count` to be the index. If it ends up being different during `present()`, we issue an `OutOfDate` error. Experiments show that this works though :tada:
