### ISSUE TITLE
Memory leak in the examples with DX12 backend

### ISSUE THREAD

**Issue by yzsolt** [gfx-rs/gfx#3505]
The `quad` example leaks memory heavily (10-20 MB/sec, depending on the framerate) if modified slightly to render continously. `wgpu-rs` examples are also leaking now that `wgpu-rs` is using `gfx` master (https://github.com/gfx-rs/wgpu/issues/1059).

The leak was introduced by https://github.com/gfx-rs/gfx/pull/3393

The amount of leaked memory doesn't seem to change if the window is resized, so it's probably not a texture leak. Maybe it's command buffer allocation related?

- GFX version: master starting from ee90ac192f97f98813e1cbd03f87f3f7cffec89c
- OS: Windows 10
- GPU: all

**Comment by yzsolt** [comment]
Seems like adding an `allocator.reset();` before returning it here: https://github.com/gfx-rs/gfx/blob/9c18ad3951968f277be510a3d1b30e8ad677e84e/src/backend/dx12/src/pool.rs#L26 fixes the leak. Not sure if it's a proper fix though.

**Comment by kvark** [comment]
It seems like a proper fix. Thank you for filing the issue and investigating! Could you make that small PR, please?

**Comment by yzsolt** [comment]
Turns out it's not that simple... While it fixes `gfx/quad`, the `wgpu/water` example fails with the following:
```
D3D12 ERROR: ID3D12CommandQueue::ExecuteCommandList: The command allocator was reset after the command list was recorded. [ EXECUTION ERROR #541: COMMAND_ALLOCATOR_RESET]
```
Since command buffers borrow their allocator from the shared pool only for their recording session, it's possible that we try to reset the allocator here while it still "owns" another command buffer which has been recorded but has not been executed yet on the GPU.

I've hacked together some command buffer → command allocator ownership tracking and reset the allocator based on that, which seems to be working, but needs some cleanup before publishing.

**Comment by kvark** [comment]
Yeah, sounds like you got it right. Looking forward to review that cleaned up patch!

**Comment by yzsolt** [comment]
After digging around a little more, I think that we'll need some tweaks in `wgpu` too to fix the leaks there.

Let's see: the main problem is that we currently never reset the DX12 command allocators. This alone can be fixed by iteraring and resetting the shared pool's allocators in DX12 backend's `CommandPool::reset` (which is currently dummy). It's safe to do, since this method's precondition is that the allocated buffers must not be in use. This also means that no ownership tracking needed on `gfx`'s side, the user is responsible to match this requirement.

By doing this, calling `CommandPool::reset` basically becomes mandatory for `gfx` users, but the problem is that `wgpu`currently never calls it and I haven't found a good place to do so. [According to NVidia](https://developer.nvidia.com/dx12-dos-and-donts#allocs) some double-buffering mechanism could help, keeping a set of command pool+lists for the previous submitted frame and another for recording the current frame (~queue submission).

Anyway, this is `wgpu`'s problem, so if this explanation seems plausible, I'll prepare the `gfx` patch which closes this issue and I will open a new one in `wgpu`.

**Comment by kvark** [comment]
Hmm, can we still try to make it so DX12 backend doesn't require the command pool reset? That would be a deviation from Vulkan semantics.
For example, if we have some tracking to know, for a given allocator, if the associated command buffers have all finished execution, we could `reset` the allocator.
We could have some sort of a "reset" area for allocators that reached a certain threshold (e.g. of the number of command buffers they recorded), so that they aren't grabbed for new command lists until they are fully done and reset.
