### ISSUE TITLE
Failed to run mesh-shading example

### ISSUE THREAD

**Issue by Lowentwickler** [gfx-rs/gfx#3512]
Short info header:
- GFX version: master
- OS: Darwin Kernel Version 20.1.0 x86_64
- GPU: Intel(R) Iris(TM) Plus Graphics

```
RUST_BACKTRACE=1 cargo run --release --bin mesh-shading --features metal
    Finished release [optimized] target(s) in 0.11s
     Running `/Users/elias/Projects/gfx/target/release/mesh-shading`
AdapterInfo { name: "Intel(R) Iris(TM) Plus Graphics", vendor: 0, device: 0, device_type: IntegratedGpu }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MissingFeature', examples/mesh-shading/main.rs:219:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_none_failed
   3: mesh_shading::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by cwfitzgerald** [comment]
As far as I'm aware, metal has no support for mesh shaders, neither does the underlying intel hardware, so it makes sence that it cannot run mesh shaders.

**Comment by kvark** [comment]
RIght, mesh shaders are currently only supported by Vulkan backend on limited platforms. The error reported by the example is appropriate.

**Comment by Lowentwickler** [comment]
If it is known and fails in the right place, maybe some explained `panic!` instead of the `Result::unwrap()` on an `Err` would make more sense.

**Comment by kvark** [comment]
Sure, a better error message would be nice there!
