### ISSUE TITLE
Replace GL's x11 dependency by hand-written code

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3519]
We don't need much from the x11 library. Maybe it's an overkill to hook it up, and we can get away with something that we just hack in?

**Comment by Systemcluster** [comment]
Was this supposed to be closed by #3520?

**Comment by kvark** [comment]
https://github.com/gfx-rs/gfx/pull/3520/commits/84f98481dbb77c6ba63f3277562879c3255f8542 was a part of that PR, yes
