### ISSUE TITLE
Implement more backends

### ISSUE THREAD

**Issue by brendanzab** [gfx-rs/gfx#352]
A metabug for tracking our status on various device backends
- [x] [OpenGL](http://www.opengl.org/)
- [x] [OpenGL ES 2.x/3.x](http://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_2.0)
- [x] [Direct3D 11](http://msdn.microsoft.com/directx) - #89
- [ ] Direct3D 12
- [ ] ~~[Mantle](http://www.amd.com/mantle)~~
- [x] [Metal](https://developer.apple.com/metal) - #890
- [ ] [GNM](http://en.wikipedia.org/wiki/GNM_%28API%29) (might not be possible due to NDA)
- [x] [Vulkan](https://www.khronos.org/vulkan) - #629

**Comment by csherratt** [comment]
[mantle spec](http://www.amd.com/Documents/Mantle-Programming-Guide-and-API-Reference.pdf) is now public.

**Comment by cmr** [comment]
The spec is missing a lot of values and the SDK will never be made public. I see no point adding a Mantle backend (as opposed to Vulkan)

**Comment by csherratt** [comment]
@cmr, I agree, between `DX12` and `Vulkan` there is not much reason for us to look at `Mantle`.

**Comment by tomaka** [comment]
If I was you, I'd still try implementing it.
The differences between Mantle and Vulkan look minimal, and by implementing Mantle you will anticipate the problems you will face with Vulkan.

**Comment by kvark** [comment]
@tomaka this would be great, if only we had resources/volunteers to try it out

**Comment by kvark** [comment]
wow, can't believe we got have of this list

**Comment by kvark** [comment]
With LL approaching, I believe this issue can be closed. The list of supported backends will be maintained in README instead.
