### ISSUE TITLE
Failed to run custom build command for `khronos-egl v2.1.1`

### ISSUE THREAD

**Issue by anthonyarusso** [gfx-rs/gfx#3534]
##Context
I am a novice with Linux and Cargo alike. I am currently running commands from ChromeOS's "Crostini" Debian 10 (Buster) container.

I am aware that [Vulkan support on Crostini](https://bugs.chromium.org/p/chromium/issues/detail?id=996591) is WIP, but was lead to believe WGPU would function properly if it targets an OpenGL backend.

---
###OS and CPU Info
ChromeOS Version 86.0.4240.198 (Official Build) (64-bit)
Linux 5.4.58-07649-ge120df5deade x86_64
Debian GNU/Linux 10 (buster)
[10th Gen Intel Core i3](https://ark.intel.com/content/www/us/en/ark/products/196451/intel-core-i3-10110u-processor-4m-cache-up-to-4-10-ghz.html)

###OpenGL / Mesa Info
OpenGL vendor string: Red Hat
OpenGL renderer string: virgl
OpenGL core profile version string: 4.3 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.1 Mesa 19.2.8
OpenGL shading language version string: 1.40
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

###Cargo Info
Installed all Cargo packages related to WGPU today.

##The Problem
Attempted to execute `cargo run --example cube` and was met with the following error:
[wgpu_error.txt](https://github.com/gfx-rs/wgpu-rs/files/5648010/wgpu_error.txt)

##Attempted solutions
Installed Vulkan packages (only to later realize Crostini lacks support):
`sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils`

Attempted to further update OpenGL / Mesa Packages. I believe I have the Debian Buster-Backports packages installed and up-to-date.

Attempted to set the `WGPU_BACKEND` environment variable listed in the [README](https://github.com/gfx-rs/wgpu-rs#how-to-run-examples) to `gl`.

I was unable to find such an environment variable by running `printenv | grep "WGPU"` or similar commands. Am I wrong to assume these are Bash environment variables? If not, where can I locate and change these?

Any help is appreciated. Please let me know if there is any more information you would like.

**Comment by kvark** [comment]
@anthonyarusso thank you, this is very helpful! I have an idea on how to fix that, but obviously I don't have a machine that complains in the same way as yours.
