### ISSUE TITLE
Graphics card is chosen depending on monitor

### ISSUE THREAD

**Issue by JQTechnologies** [gfx-rs/gfx#3613]
Short info header:
- GFX version: 0.5.2 and the one that amethyst 0.15.3 uses (I think 0.4.1?)
- OS: Windows 10
- GPU: gtx 1050ti and integrated graphics card from i7-7700HQ

Hey! So as in the title, the graphics card of choice seems to be selected by on which monitor is positioned window (and which graphics card monitor uses).
I think this shouldn't be the case and user should be able to choose it (there is special menu on atleast my laptop, when right clicking executable, where I can choose on which graphics card window is running. When I choose running on dedicated graphics, window is like for a split second running on it and immediately changing to integrated graphics, from what I've seen in task manager).

**Comment by attackgoat** [comment]
I'm assuming that your code selects an adapter using a method similar to [the example code](https://github.com/gfx-rs/gfx/blob/00285817af676e091ac886b927e9e5e292f22a03/examples/quad/main.rs#L130).

If that's the case you might need to expand the logic, here is [an example](https://github.com/attackgoat/screen-13/blob/56cf4c3a12ab0fab7a9758599228b75041577a7d/src/gpu/mod.rs#L203) or [another](https://github.com/amethyst/rendy/blob/b811def00c6825f303f407f83fbf09c5ad39e451/factory/src/factory.rs#L1210).

**Comment by kvark** [comment]
Yep, gfx-hal doesn't choose an adapter for your, it's all in your control. Closing on that note, but please free to continue discussion and/or reopen!

**Comment by JQTechnologies** [comment]
Oh, Ok then, thanks for anwsers! Well, this means that I will need to open this issue on Amethyst, because I've got same problem using it.

**Comment by JQTechnologies** [comment]
Oh w8, second example is from amethyst, interesting since I've got same problem while using it

**Comment by JQTechnologies** [comment]
I will try to add code from examples to my code, I will reopen issue if it doesn't fix it

**Comment by JQTechnologies** [comment]
Yep, same issue still occurs.

**Comment by kvark** [comment]
> I don't see the option for reopening issue

Weird and unfortunate. We do want anybody to be able to re-open. I'll do this now.

>Yep, same issue still occurs.

Strictly speaking, it's not bug. Examples pick an adapter that can natively present to the window they run on. So if different screens are connected to different adapters, moving the window between screens would change the preferred adapter. This is totally fine for the examples.

So this issue then could be reopened on the basis of an enhancement request to the examples: let's have some more elaborate adapter selection logic demonstrated.

**Comment by JQTechnologies** [comment]
Issue fixed! Problem was solved after I updated drivers for Intel GPU. And sorry for misconception, I think that before not even Intel GPU was used, maybe CPU (?). I haven't read task manager properly.
