### ISSUE TITLE
Needed of release build type

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [gfx-rs/gfx#3643]
Short info header:
- GFX version: master - 0.7
- OS: Web

Do you have detail about [that check](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/lib.rs#L220) that not allow build debug version of the library.
We have some other bug on web, and it can be useful to allow it to found more details about it.

Thank you,
Marc-Antoine

**Comment by kvark** [comment]
What do you mean by `not allow build debug version of the library`?  We build in debug all the time.
The check is just calling `glError`, which is slow, so we don't want to do this in release.

**Comment by MarcAntoine-Arnaud** [comment]
It's linked to https://github.com/gfx-rs/wgpu-rs/issues/741
From Wgpu-rs, it returns a panic as @vincentFTS mentioned it.

Or does it comes from somewhere else that the backend is not well configured ?

**Comment by kvark** [comment]
The checking code is not a problem here, it just shows us that there is a problem. The real problem is in the GL backend logic is trying to use an invalid enumerant. Anyhow, that issue is there, I'm going to move it to gfx repo and close this one.
