### ISSUE TITLE
[Wasm/WebGL] Hello-triangle panics at adapter creation.

### ISSUE THREAD

**Issue by VincentFTS** [gfx-rs/gfx#3644]
On wasm/WebGL, the hello-triangle panics at adapter creation.
I’m using wgpu-rs 0.7

**Comment by Gordon-F** [comment]
The main problem here that the version checker thinks that `WebGL 2.0` == `OpenGL ES 3.2` (or other ES version). I can make a PR with custom custom `PartialEq` and `PartialOrd` impl for `Version` or we can rework capabilities checking for WebGL.

**Comment by kvark** [comment]
WebGL2 should correspond to OpenGL ES 3.0, in which case we don't need a special implementation, I think

**Comment by Gordon-F** [comment]
@kvark Technically yes, but not in the current code.

For example, the this check is `true` for `wasm` code, which is wrong:
```rust
if info.is_supported(&[Core(4, 3), Es(3, 2), Ext("GL_ARB_compute_shader")]) {
}
```
https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/info.rs#L402

**Comment by kvark** [comment]
Why is this check `true`? it requires Es(3,2), which WASM target doesn't have

**Comment by Gordon-F** [comment]
@kvark Sorry, I didn't provide complete information. Let me explain. 

Let's see what `is_supported` do:
```rust
pub fn is_supported(&self, requirements: &[Requirement]) -> bool {
        use self::Requirement::*;
        requirements.iter().any(|r| match *r {
            Core(major, minor) => self.is_version_supported(major, minor),
            Es(major, minor) => self.is_embedded_version_supported(major, minor),
            Ext(extension) => self.is_extension_supported(extension),
        })
    }
```

Add extra logs to `is_embedded_version_supported` ([original version](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/info.rs#L316)):
```rust
pub fn is_embedded_version_supported(&self, major: u32, minor: u32) -> bool {
        let is_embedded_version_supported = self.version.is_embedded
            && self.version >= Version::new(major, minor, None, String::from(""));
        log::debug!(
            "is_embedded_version_supported = {}. Check version = {}.{}. Current version = {}.{}",
            is_embedded_version_supported,
            major,
            minor,
            self.version.major,
            self.version.minor
        );

        is_embedded_version_supported
    }
```

Run `wgpu` `hello-triangle` example:
```log
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.1. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.2. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.2. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 2.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.0. Current version = 2.0
hello-triangle.js:1182 is_embedded_version_supported = true. Check version = 3.1. Current version = 2.0
```

As we can see `is_embedded_version_supported` always `true` for WebGL.

Add custom PartialEq and PartialOrd impl for [Version](https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/info.rs#L8):
```rust
impl PartialEq for Version {
    fn eq(&self, other: &Self) -> bool {
        self.is_embedded == other.is_embedded && self.major == other.major && self.minor == other.minor
    }
}

impl PartialOrd for Version {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        if self.major == other.major && self.minor == self.minor {
            Some(Ordering::Equal)
        } else if self.major > other.major {
            Some(Ordering::Greater)
        } else if self.major < other.major {
            Some(Ordering::Less)
        } else if self.major == other.major && self.minor > other.minor {
            Some(Ordering::Greater)
        } else if self.major == other.major && self.minor < other.minor {
            Some(Ordering::Less)
        } else {
            None
        }
    }
}
```

All works fine:
<img width="1632" alt="webgl_triangle" src="https://user-images.githubusercontent.com/3227317/108254743-76e41d80-716c-11eb-8b8b-e3063632f4ff.png">

**Comment by kvark** [comment]
Do we know why the comparison is turning true, exactly? The derived `PartialOrd` should compare the major then minor versions (see [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=42dc2a4235da409a82d1805d4c863ca7)), there shouldn't be need to custom-derive it.

**Comment by Gordon-F** [comment]
Ohhh I think all simple. `is_embedded_version_supported` should be:

```rust
pub fn is_embedded_version_supported(&self, major: u32, minor: u32) -> bool {
        self.version.is_embedded && self.version >= Version::new_embedded(major, minor, None, String::from(""))
    }
```

We should check embedded version only with embedded version, because first bool `is_embedded` in `Version` struct.

See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a3e3683037443b2d90b92cc5e98bb759).

**Comment by kvark** [comment]
That makes sense, yeah!

**Comment by VincentFTS** [comment]
Could this land on 0.7 branch ?

**Comment by kvark** [comment]
@VincentFTS the GL backend has a lot of rough edges right now. This blocker is resolved, but others are still there, so even if you *could* use wgpu-0.7 for generating WebGL, you should heavily consider `master` branch instead.
We'll try to release a patch to gfx-backend-gl, fwiw.

**Comment by kvark** [comment]
Thanks to @Gordon-F quick followup, you can now get the fix by doing `cargo update -p gfx-backend-gl`
