### ISSUE TITLE
Vulkan backend requires imageless_framebuffers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3648]
Likely regressed by #3624 or #3625
User output:
```
[0.205856 DEBUG]()(no module): Requesting extensions: [
    "VK_KHR_swapchain",
    "VK_KHR_maintenance1",
    "VK_KHR_maintenance2",
    "VK_KHR_maintenance3",
    "VK_KHR_imageless_framebuffer",
    "VK_EXT_sampler_filter_minmax",
    "VK_AMD_negative_viewport_height",
]
```
Driver output:
> [0.195898 WARN]()(no module): Unsupported extension requested: VK_KHR_imageless_framebuffer
[0.196419 WARN]()(no module): Unsupported extension requested: VK_KHR_image_format_list
[0.199571 WARN]()(no module): Unsupported extension requested: VK_KHR_maintenance3

> thread 'main' panicked at 'failed to create gfx-hal device: Requested extension is missing', C:\Users\Franz\.cargo\git\checkouts\wgpu-53e70f8674b08dd4\b1b44ca\wgpu-core\src\instance.rs:460:26

**Comment by francesco-cattoglio** [comment]
Here is the output of my `vulkaninfo`:
[vulkaninfo.txt](https://github.com/gfx-rs/gfx/files/6017656/vulkaninfo.txt)
