### ISSUE TITLE
GL backend fails on wayland

### ISSUE THREAD

**Issue by dlunch** [gfx-rs/gfx#3671]
Short info header:
- GFX version: gfx-backend-gl 0.7.1
- OS: Arch Linux
- GPU: AMD RX 6900 XT

GL backend on wayland fails with following error log:
`WARN  gfx_backend_gl::window::egl    > Error in create_pbuffer_surface: BadMatch`

It seems that pbuffer is not supported on wayland mesa driver(https://lists.freedesktop.org/archives/wayland-devel/2012-April/002928.html, https://bugs.freedesktop.org/show_bug.cgi?id=105995)

**Comment by kvark** [comment]
Thank you for filing!
We aren't using PBuffer for anything useful.
I imagine Wayland platforms support surface-less contexts, so we can just check for this and not create anything.
cc @Gordon-F

**Comment by kvark** [comment]
Should be fixed by #3676
