### ISSUE TITLE
Enable VK_KHR_storage_buffer_storage_class on VK-1.0

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#3700]
This is required for the next Naga update, see https://github.com/gfx-rs/naga/pull/612

**Comment by Gordon-F** [comment]
Is `SPIR-V 1.3` required `Vulkan 1.1` ?

Based on  [Android distribution dashboard](https://developer.android.com/about/dashboards) this requirement drops 22.0% of Vulkan based devices. Also based on [gpuinfo.org](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_storage_buffer_storage_class&platform=android&option=not) information `VK_KHR_storage_buffer_storage_class` not supported on 23.7% devices.

**Comment by kvark** [comment]
yes, Vulkan 1.1 requires SPIR-V 1.4.
I'm told that pretty much everything under the sun either supports the extension, or Vulkan 1.1

**Comment by Gordon-F** [comment]
> I'm told that pretty much everything under the sun either supports the extension, or Vulkan 1.1

Maybe my point looked too scary (drops 23% of Android devices), but after I open my link again I realized that only 19 devices don't support `VK_KHR_storage_buffer_storage_class` 😄 

Is this an urgent task? Can I try to solve it?

**Comment by kvark** [comment]
Please do!
This is a little bit urgent in a sense that it's going to block the *next* naga train (gfx-19), which we aren't doing yet.
We haven't fully got `gfx-18` arriving to wgpu-rs yet, even.
