### ISSUE TITLE
Dx12 backend fails to enumerate adapters while running in the Visual Studio graphics debugger

### ISSUE THREAD

**Issue by Imberflur** [gfx-rs/gfx#3710]
Short info header:
- GFX version: d002952029facee7aafd52c94230057df6dd298f
- OS: Windows 10
- GPU: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx, 2600 Mhz, 2 Core(s), 4 Logical Processor(s)
--------
Error logged when requesting an adapter on the dx12 while running in the Visual Studio graphics debugger:
![image](https://user-images.githubusercontent.com/2002109/113366866-74a6de80-9328-11eb-88bf-95e333693253.png)
```
 ERROR gfx_backend_dx12: Failed enumerating adapters: 0x80004005
```

**Comment by cwfitzgerald** [comment]
Does DX11 work while running the debugger?

**Comment by Imberflur** [comment]
> 
> 
> Does DX11 work while running the debugger?

It does appear to select an adapter! Looks like it has other issues afterwards though: `PanicInfo: panicked at 'not implemented', D:\veloren\gfx\src\backend\dx11\src\device.rs:771:18`

**Comment by cwfitzgerald** [comment]
The next thing to test is if running the dx12 examples works. If they don't, there's nothing we can't do anything about.

**Comment by kvark** [comment]
Looks like E_FAIL coming internally.

**Comment by Imberflur** [comment]
I tested out this sample: <https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HelloWorld/src/HelloTriangle>. And it also failed only when running in the graphics debugger:
![image](https://user-images.githubusercontent.com/2002109/113497301-c4280e80-94d0-11eb-9aa7-0f0fafef6ede.png)

Interestingly, I got a little informational note this time:
![image](https://user-images.githubusercontent.com/2002109/113497318-e0c44680-94d0-11eb-8900-7536b2f11769.png)
which links to <https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/visual-studio-graphics-diagnostics-directx-12?view=vs-2019>

I would say we can close this issue since it appears to no longer be supported?
