### ISSUE TITLE
MTLGPUFamilyMac1 is deprecated

### ISSUE THREAD

**Issue by nullhook** [gfx-rs/gfx#3797]
[lib.rs](https://github.com/gfx-rs/gfx/blob/master/src/backend/metal/src/lib.rs#L1086) uses MTLGPUFamilyMac1 to detect support for binary archives. however, it's deprecated. should use MTLGPUFamilyMac2 instead.

<img width="1145" alt="image" src="https://github.com/gfx-rs/gfx/assets/8665427/1ff56cf7-9d87-422a-95fa-edb280356475">

additionally, i don't see a check for GPUFamilyCommon type. is that intentional?

**Comment by cwfitzgerald** [comment]
Hello! gfx-hal is deprecated. If you're interested in fixing this, we will accept PRs, but we aren't actively maintaining it anymore
