### ISSUE TITLE
Implement half-floats

### ISSUE THREAD

**Issue by cmr** [gfx-rs/gfx#422]
See https://www.opengl.org/registry/specs/ARB/half_float_pixel.txt

**Comment by Sixstring982** [comment]
Anybody working on this? I'd like to give it a shot.

**Comment by fkaa** [comment]
@Sixstring982 go for it!

@kvark while we're at it, is there anything we can do to promote half floats in vertex formats? Using `u16` and `mem::transmute`ing would probably work, but doesn't look very nice.

**Comment by kvark** [comment]
@fkaa current `format` module has `F16` type, but it doesn't do anything... We can put logic into it for f16<->f32 conversion.

**Comment by Sixstring982** [comment]
Looks like f16 was at one point being considered as a native type: https://internals.rust-lang.org/t/adding-minifloats-f24-f16-f8-as-native-types/2367/13

I think f32<->f16 conversions are probably OK for most circumstances, even though IEEE 754 16-bit floats would act differently.

**Comment by kvark** [comment]
I'd love some native f16 support.

**Comment by Sixstring982** [comment]
Alright, I built some half floats. So far they can be converted to and from any of the other numeric primitives. Is that all we need, or should I implement Add, Mul, etc. for them?

**Comment by kvark** [comment]
@Sixstring982 that should be fine. I assume if people want any real computation with them on CPU side they can convert to/from `f32`. Is your code big? Do you think you'd be able to just put it into our `gfx_core::format::F16` implementation, or as a separate crate?

**Comment by kvark** [comment]
@fkaa rendering-wise our GL backend already supports `GL_HALF_FLOAT` just fine. At least for vertex attributes and texture formats, that is.

**Comment by Sixstring982** [comment]
I have about 300 lines. It could probably be in its own crate.

**Comment by kvark** [comment]
@Sixstring982 yeah, that's rather big
We could depend on it as a feature.

**Comment by kvark** [comment]
I believe this is exposed in gfx-hal
