### ISSUE TITLE
Implement buffer copying

### ISSUE THREAD

**Issue by cmr** [gfx-rs/gfx#423]
See https://www.opengl.org/registry/specs/ARB/copy_buffer.txt

**Comment by Bastacyclop** [comment]
@kvark I think me and @Androcas will simply add the following methods:
```rust
command::Buffer::copy_buffer(src: R::Buffer, dst: R::Buffer,
                             src_offset_bytes: usize, dst_offset_bytes: usize,
                             size_bytes: usize);

Encoder::copy_buffer(src: handle::Buffer, dst: handle::Buffer,
                     src_offset: usize, dst_offset: usize,
                     size: usize) -> Result<(), CopyError>;
```
Using [glCopyBufferSubData](https://www.opengl.org/sdk/docs/man/html/glCopyBufferSubData.xhtml) for OpenGL, [vkCmdCopyBuffer](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#vkCmdCopyBuffer) for Vulkan (we won't handle synchronization) and [DeviceContext::CopySubresourceRegion](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476394(v=vs.85).aspx) for D3D11.

**Comment by kvark** [comment]
@Bastacyclop sounds good!
