### ISSUE TITLE
"gfx by example" docs

### ISSUE THREAD

**Issue by brendanzab** [gfx-rs/gfx#455]
There is a nice site for the Metal API called "[Metal By Example](http://metalbyexample.com/)". It would be nice to create some docs similar to that. Perhaps we could look at @sebcrozet's awesome [ncollide](http://ncollide.org/) docs for inspiration too.

**Comment by Bastacyclop** [comment]
related to #942

**Comment by kvark** [comment]
No longer needed: pre-ll is fading away, and for ll there is a ton of Vulkan examples out there.
