### ISSUE TITLE
Document typedefs used in the corresponding functions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#528]
We have typedefs like these:

``` rust
/// Number of bits per component
pub type Bits = u8;
/// Number of MSAA samples
pub type NumSamples = u8;
/// Number of EQAA fragments
pub type NumFragments = u8;
```

They end up as `u8` in the documentation. We need to take that into account by explaining their meaning when they are used. Like here:

``` rust
 /// Unsigned integer format with a given number of bits per component.
Unsigned(Components, Bits, ::attrib::IntSubType),
```

Alternatively, we may evaluate stronger types. Obviously, the ergonomics may suffer.

**Comment by bjz** [comment]
This seems like a Rustdoc issue :/

**Comment by kvark** [comment]
Not going to be fixed
