### ISSUE TITLE
Rewrite README with a focus on shiny things

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#542]
Our [README](https://github.com/gfx-rs/gfx-rs/blob/master/README.md) tries to be everything at the moment:
  - why we are building it
  - our goals and non-goals
  - our crate hierarchy
  - building instructions

It is long to the point of almost being boring. Here is the rough outline of the new design I propose:
  1. Short-sentenced definition with links to:
    - Travis, Gitter, Waffle.io (unchanged)
    - documentation
    - why/goals/non-goals wiki (same-ish content, moved to a separate file)
    - crate hierarchy and architecture notes (maybe link to my presentation slides and video?)
  2. Big fat screenshot from Snowmew (with a link) - the one with lighting and shadows on the Sponza scene
  3. Getting started notes

It will be smaller, more focused, and hopefully more attractive.
Thoughts? Suggestions?

**Comment by bjz** [comment]
:+1:

**Comment by kvark** [comment]
Thanks @fkaa for fixing this in 7cf57a07e00ac90a1832f2747ab2a63e1f3d5457 !
