### ISSUE TITLE
Head-less tests

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#583]
I recall an attempt to get this working long time in the past. We need to try again, especially since Glium already shows how it could be done.

**Comment by bjz** [comment]
Can we break this down into smaller steps?

**Comment by kvark** [comment]
I didn't look into this, so I'm not sure what steps it would take. Perhaps, @cmr remembers something?

**Comment by kvark** [comment]
I believe, from the perspective of #1410 this issue comes down to proper support of `Headless` glutin context, which would allow us to run the test harness on CI.

**Comment by kvark** [comment]
This happened in  #1731
