### ISSUE TITLE
Utilize the borrow checker to improve resource operations safety

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#584]
@tomaka shared on IRC:

> 12:12  tomaka  kvark: I'll explain the "uses & and &mut to avoid invalid operations" here
> 12:12   tomaka  kvark: for example if you take a buffer
> 12:13   tomaka  reading the buffer, writing the buffer, using the buffer to draw, all take a "&Buffer"
> 12:13   tomaka  but mapping the buffer or using it as a target for transform feedback takes a "&mut Buffer"
> 12:13   tomaka  because OpenGL allows no other operation to take place on a buffer while it is mapped
> 12:13   tomaka  and no other operation while it is used for transform feedback
> 12:14   tomaka  so Rust's borrow checker helps enforcing these restrictions in OpenGL

**Comment by Bastacyclop** [comment]
This would be really nice, but how is it supposed to work with the current handle system ? Which parts of gfx would suffer most if resource ownership wasn't shared anymore ?

**Comment by Bastacyclop** [comment]
@kvark If feasible, this would reduce performance overhead by removing the whole `Arc<Mutex<>>` stuff for memory mapping. I think it would also simplify partial resource management, we could split a buffer into slices (and map them independantly for example). I could try to experiment with the idea in my spare time to see how it goes.

**Comment by kvark** [comment]
@Bastacyclop I don't think it's feasible now, given our construction of command buffers is independent of their execution. Unless you have something on your mind to experiment with, I suggest closing the issue.

**Comment by kvark** [comment]
this is a cool concept, but it hasn't happened in pre-ll
