### ISSUE TITLE
More runtime checks

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#591]
A good list from @tomaka :
-    I checked the minimum GL version of every single OpenGL call, and glium checks whether the backend supports it first
-    Checking that the values of depth_range is between 0 and 1
-    Checking that the dimensions of the viewport and the scissor box are inferior to MAX_VIEWPORT_DIMS
-    Checking that the number of framebuffer attachments are inferior to MAX_DRAW_BUFFERS
-    Checking that all framebuffer attachments have the same dimensions, because this is required by EXT_framebuffer_objects
-    Checking that there's a depth buffer before drawing with a depth test
-    Checking the types of attributes, uniform values, and fragment output
-    Checking for missing uniforms or attributes
-    Checking if we're out of memory when creating a buffer
-    Checking the alignment of elements when uploading a buffer
-    Checking that the backend supports the requested format when creating a texture
-    Checking that the format of the client data is compatible with the requested texture format
-    Checking the layout of uniform blocks
-    Checking that the requested anisotropic filtering level is inferior to MAX_TEXTURE_MAX_ANISOTROPY
-    Checking that the program has tessellation shaders when you draw with patches

**Comment by bvssvni** [comment]
Wouldn't this slow down the application?

Is it possible to run these checks at startup?

**Comment by kvark** [comment]
@bvssvni we are already doing many of them. I don't think the performance is going to be the problem, because a typical complexity for the checks is `O(1)`, and the heavier ones we do at init time (e.g. matching uniforms - as opposed to glium's rendering time).

Generally speaking, a trade of one or two comparison per graphics operation in exchange for increased safety net - definitely worth it. The GL version checks are probably very well predicted by the CPU's branch predictor. We shouldn't skip any of these, especially since we can do them more efficiently than glium :P

On a side note, it looks like @lynks-- just faced the texture size limitation, which is a part of this list.

**Comment by kvark** [comment]
Mostly done. Any remaining issues to be filed separately.
