### ISSUE TITLE
Add lifetime parameter to `Resources` for associated types

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#614]
https://github.com/PistonDevelopers/gfx_graphics/blob/master/src/back_end.rs#L198-L208

```
pub struct GfxGraphics<'a, R, C, O>
    where R: gfx::Resources + 'a,
          C: gfx::CommandBuffer<R> + 'a,
          O: gfx::Output<R> + 'a,
          R::Buffer: 'a,
          R::ArrayBuffer: 'a,
          R::Shader: 'a,
          R::Program: 'a,
          R::FrameBuffer: 'a,
          R::Surface: 'a,
          R::Texture: 'a,
          R::Sampler: 'a
{
   ...
}
```

The compiler doesn't know that the associated types outlives `Resources` in every context they are used, and these constraints must be added even if they are never referred to anywhere. By adding a lifetime input parameter to `Resources<'a>` this can be annotated directly on the trait.

**Comment by bvssvni** [comment]
Hmm... this might propagate upward to add a lifetype parameter to `Device`.

**Comment by bvssvni** [comment]
This could be:

```Rust
pub struct GfxGraphics<'a, D>
    where
        D: 'a + gfx::Device<'a>
{
   ...
}
```

**Comment by kvark** [comment]
@bvssvni I certainly agree this looks bizarre. What it not clear to me though is why `GfxGraphics` is the only place I've seen that had to constraint all the lifetimes. Perhaps, there is an easy way to refactor `GfxGraphics` that solves it?

**Comment by kvark** [comment]
Not happened in pre-ll
