### ISSUE TITLE
Add Vulkan back-end

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#629]
Relates to #352 

~~Vulcan specs are yet to be released, but~~ the architecture [overview](https://www.khronos.org/vulkan) looks very promising. Or, as @csherratt said:
> From 35,000 feet vulkan and gfx look like a match made in heaven. The problem is vulkan can only be viewed from 35,000 feet.

In terms of rendering commands, they expose command buffers and show a [diagram](https://www.khronos.org/assets/uploads/apis/2015-vk-image-4.png) that is very similar to what I drawn a while ago for the [presentation](https://github.com/kvark/slides/raw/master/GFX_RustTorontoMeetup.pdf). VRAM and resource management is still an open question (not limited to Vulcan), but overall I expect Vulcan backend to be much lighter and more efficient than OpenGL one.

Links:
- PowerVR samples [ported](http://blog.imgtec.com/powervr/trying-out-the-new-vulkan-graphics-api-on-powervr-gpus)
- https://github.com/SaschaWillems/Vulkan

**Comment by Kagami** [comment]
It's out! :)
