### ISSUE TITLE
Mesh trait

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#640]
Turning `Mesh` into a trait would provide several benefits:
- can be implemented automatically for `Buffer<T>`, where `T: VertexFormat`, since our buffer info has the size, so we can use it as the number of vertices
- allows mesh proxies without re-allocation of attributes on the heap. For example, an instanced mesh can be a proxy of the per-vertex mesh and per-instance mesh data.

**Comment by bvssvni** [comment]
Heck yeah. This sounds like a good idea.

**Comment by bjz** [comment]
Would it be possible to implement it for `Vec`?

**Comment by kvark** [comment]
Not sure about `Vec`, actually. A `Mesh` will need to return some attributes, which point to buffers. Thus, it will not be able to create/update buffers on the fly with `Vec`.
