### ISSUE TITLE
Find better names for the core concepts

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#698]
`Device`: the same HW device (video card, GPU) can support multiple APIs. Conceptually, `Device` was meant to be an API backend originally. Later on, it lost all the resource management and became just a thing executing command buffers, for which `Device` is not the worst name. Candidates:
- `GraphicsDevice`
  - (+) less changes, i.e. local variable names could still be `device`.
  - (-) confusing with regards to Metal `MTLDevice`, which it is not
- `GraphicsQueue`
  - (+) consistent with Metal/Vulkan, AFAIK
  - (-) it might be a queue on the driver side, but from our point of view it's a sink. Whatever goes in is executed from our perspective.

_Note_: regardless of the `Device` rename, all the `gfx_device_*` crates should be renamed to `gfx_backend_*`.

`Renderer`: not actually rendering anything, but fills up the command buffer. Candidates:
- `GraphicsEncoder`
  - (+) consistent with Metal
- split the resource management aside and deprecate this one in favor of `Stream`

_Note 2_: The prefix `Graphics` here is to indicate the graphics work. When we introduce compute shaders, they have nothing to do with batches or graphics queues. They will need their own queue & encoder.

`Stream`: not actually streaming much, but rather queuing stuff, same as `Renderer`, but with a given target. Candidates:
- `RenderTo`/`EncodeTo`
  - (+) shows that it's derived from `Renderer`/`Encoder`

`Batch`: not related to actual "batching" of anything. As it turned out, `gfx_scene` still uses a bigger structure as a unit of sorting/rendering. Candidates:
- `Unit`
- `Object`
- `DrawCall`
- `PipelineStateObject` (#815)

Please suggest your candidate names!
cc @csherratt @fkaa @bvssvni @cmr

**Comment by bvssvni** [comment]
:+1:

**Comment by fkaa** [comment]
Agree with the `Device -> Backend` for repos. I think `Device` terminology is pretty analogous with the hardware definition. The only difference between gfx's `Device` and Metal's `MTLDevice` right now as I see it is that gfx has decoupled resource creation. The flow of operations in Metal from how i understand it goes like this:
```
MTLDevice <- MTLCommandQueue <- MTLCommandBuffer(s) <- MTL*Encoder(s)
```
where the device is responsible for executing the queue of command buffers, which in turn are created by encoders. I think if we can find an existing API which uses a consistent terminology and fits gfx's model we should just adopt it. OpenGL can be ruled out I think, as it doesn't even have the notion of command buffers. Mantle naming sounds very similar to Metal. Mantle also distinguishes between compute commands and more universal ones (`GR_QUEUE_COMPUTE` and `GR_QUEUE_UNIVERSAL` respectively). Personally I think Mantle naming is the most applicable to gfx, being the base for Vulkan.

So my initial thoughts:

From | To
------------ | -------------
`Device` | `Device`
`Renderer` | `*Encoder`
`Stream` | Unsure, does `RenderPass` cover this or is it too high level?
`Batch` | Unsure, `RenderParams` could imply that the contained data is tied to the draw call
`Output` | `RenderTarget`
`Plane` | `RenderTargetAttachment`

**Note**: This is just my first impression with all these terms actually, so I might be oversimplifying some areas. In general I think I prefer verbose names rather than short and generic ones, where you have to look up in the docs/source exactly what it's used for.

Some excerpts I found relevant/interesting from the Mantle PDF:
![model](https://cloud.githubusercontent.com/assets/768574/8047417/594ca8ea-0e45-11e5-87e0-0e95afd5e4fc.png)
![screen shot 2015-06-09 at 01 04 27](https://cloud.githubusercontent.com/assets/768574/8047426/6aeb49bc-0e45-11e5-8643-e4e347d55ecc.png)

**Comment by csherratt** [comment]
I have been thinking that maybe the `Stream` should be removed altogether. It might work better as a set of utility functions then as a `object` that needs to be manipulated.

```rust
renderer.with_output(output, |stream| {
  stream.draw(my_wonderful_batch);
  // implicit flush at scope close.
});
```

**Comment by kvark** [comment]
@fkaa thanks for great input! I'll make a proper answer later on.
@csherratt you are missing the associated types. That's the main selling point of `Stream` that it only needs `R` and hides everything else as a detail.

**Comment by kvark** [comment]
@fkaa 
> Personally I think Mantle naming is the most applicable to gfx, being the base for Vulkan

+1

> `MTLDevice <- MTLCommandQueue <- MTLCommandBuffer(s) <- MTL*Encoder(s)`

This is correct, but with one major note: `Queue -> Device` link is not something we control:
> When the GPU is ready, it picks the next available command buffer from the queue and executes it.

So from our perspective, `Queue` *is* what executes/consumes the command buffers, as I mentioned initially.

> Unsure, does `RenderPass` cover this or is it too high level?

I don't see `RenderPass` in Mantle docs, so I assume you are referring to Metal her. It looks to me that MTL `RenderPass` is our `Output`. The `CommandEncoder` is created with a pass as the parameter in [this example](http://metalbyexample.com/up-and-running-2/), which means they don't have our `Renderer` (and maybe neither should we) but go straight to `Stream`.

**Comment by fkaa** [comment]
#### Here be text
Okay, so making another review of names etc.. Watched an interesting [video](http://realm.io/news/3d-graphics-metal-swift/) by Warren Moore and got some more clarification on how Metal worked and how it could be applied to `gfx`. A lot of my suggestions might not make sense, but I'm just writing down some thoughts I have right now.

#### Descriptors
So a big part of object creation in Metal is described by *descriptors*. Descriptors are essentially bags of properties which are used in every operation which returns a handle which can be described from client-side. This isn't that big of a deal on its own, but it's applied *everywhere* in Metal (there's even a `MTLRenderPipelineColorAttachmentDescriptor`! phew).

Most of this pattern already exists in `gfx` but not everywhere, and not uniformly named, from what I could tell. So most of the stuff that would have to change would be to move things like argument parameters to factory methods into their own `Descriptor` struct.

#### Pipeline
A lot of the concepts in `gfx` are "hidden" under generic terms, like streams and batches (for good reasons, re: type parameters, iirc). Personally I think that using their names directly such as `CommandQueue` and `CommandBuffer` would make `gfx` more approachable to new users.

Some *very* rough psuedo-code, some stuff may not fit together:
```rust
let (device, factory) = ...;
let queue: CommandQueue = factory.create_cmd_queue();

let vertex_buf: Buffer = ...;
let vertex_desc = from_macro_struct(&magic_struct); // ?
let vertex_fmt = factory.create_vertex_format(&vertex_desc);

// the shader program + vertex format (vao) + framebuffer stuff
let pipeline_desc = RenderPipelineDescriptor {
    program: from_magic_function(),
    vertex_layout: vertex_fmt,
    colors: ..., // list of color attachments
    depth_format: None,
    stencil_format: None
};
let pipeline = factory.create_pipeline_state(&pipeline_desc);

loop {
    // short-lived command buffer, everything is re-drawn each frame
    let buf: CommandBuffer = factory.create_cmd_buf(&queue);

    // encoders serialize commands into the command buffers
    let encoder_desc = RenderEncoderDescriptor {
        color: ...,
        depth: ...,
        stencil: ...,
    };
    let encoder: RenderEncoder = factory.create_encoder(&buf, &encoder_desc);

    
    encoder.set_pipeline(&pipeline);
    // shader attribute handled from here
    encoder.set_vertex_buffer(&vertex_buf, offset, attribute);
    encoder.draw_primitives(TriangleFan, start, count);
    // finishes encoding
    encoder.end();

    // commit the command buffer for submission
    buf.commit();

    swap_buffers();
}
```

**Comment by kvark** [comment]
@fkaa thanks! that'd be quite useful!
Note that our `*Info` things are pretty much the descriptors, and they are used consistently, we just may need to have more of these types.

**Comment by kvark** [comment]
`difficulty: easy` tag here is a joke. Should be `difficulty: near impossible`

**Comment by kvark** [comment]
Ok, last major piece of this issue: `gfx::Device` -> `gfx::Queue`.
It matches `ID3D12CommandQueue`, `MTLCommandQueue` and `vkQueue`.

**Comment by Binero** [comment]
I would have to agree with @eugene2k that `CommandQueue` might be more descriptive. Furthermore, it might also be worth having `CommandQueue` be a trait, and then have for every back end the specific implementations be named `GraphicsCQ` and `ComputeCQ`. I know Rust doesn't like abbreviations, but `GraphicsCommandQueue` and `ComputeCommandQueue` might just be a little bit over the top.

**Comment by msiglreith** [comment]
Alongside our new low level core we adopted the terminology of the next gen APIs.

Remaining issues are renaming of `Factory` into `Device` and find a new name for the `Device` wrapper struct (containing the current factory, queues and memory heaps).

Possible alternatives: `ActiveAdapter` (by @kvark) or we could also just call it `Gpu`.
