### ISSUE TITLE
Create a core library

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#703]
Thinking of the future I would like to have a core library that contains only the things needed for writing a back-end, such that we could experiment with multiple designs without blocking another. This will also make it easier to release newer versions of Gfx that uses the same core library as older versions, meaning that if some code only depends on the core it does not have to break with major versions.

**Comment by kvark** [comment]
The `device` module is everything you need to write a back-end.

> such that we could experiment with multiple designs without blocking another

What stops us currently from experimenting with multiple designs exactly?

Please keep in mind that @cmr is supposedly working on a library that may replace all the device stuff in `gfx`.

**Comment by bvssvni** [comment]
Oh, interesting.

**Comment by kvark** [comment]
Search for `ugpu` [here](https://gitter.im/gfx-rs/gfx-rs/archives/2015/03/08)

**Comment by bvssvni** [comment]
@kvark Thanks!

**Comment by sectopod** [comment]
I figured I'd do this as a part of the grand overhaul. Need it badly to help with compile times.
