### ISSUE TITLE
Consider Glium backend

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#709]
Unlikely to be possible, just something to keep an eye on.
cc @tomaka

**Comment by tomaka** [comment]
I totally lost track of the internal design of gfx, but I think this is possible.
I'm not opposed to adding low-level things in glium (unsafe or not).

**Comment by kvark** [comment]
@tomaka thanks, sounds promising :) It would be rather useless if not for the high-level stuff that I'm doing, which I'd like Glium users to have access to as well.

**Comment by tomaka** [comment]
What I mean is that gfx is already converting high-level things into low-level things. So in order to write a glium backend, glium may have to have to accept more low-level things.

**Comment by bvssvni** [comment]
I am curious about the overhead of converting the draw state. Piston-Graphics needs this for glium_graphics so we could use it as a test case to see whether a Glium back-end is a good idea?

**Comment by kvark** [comment]
@bvssvni that would be a great start!

**Comment by Binero** [comment]
Isn't a Glium back-end quite redundant, given that every platform Glium supports, is automatically supported by OpenGL? Seems like a lot of effort for no benefits. 

If it means replacing the OpenGL back-end with Glium, then it's a completely different story of course.

**Comment by msiglreith** [comment]
I don't think this is an option/reasonable anymore due to our new low level direction.
