### ISSUE TITLE
Single-threaded compile-time configuration

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#721]
We could have a `cfg(single)` switch, effectively working around #636. For single-threaded, we'd use regular `Rc` instead of custom `Arc`.

cc @csherratt @cmr

**Comment by csherratt** [comment]
[Rc `is_unique` is still not stable.](https://doc.rust-lang.org/std/rc/fn.is_unique.html). So, we are blocked on that unless we want to make `cfg(single)` change the internal Arc.

**Comment by kvark** [comment]
Not happened in pre-ll
