### ISSUE TITLE
Move custom Arc to separate library

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#724]
https://github.com/gfx-rs/gfx-rs/pull/720 added a custom Arc to use `is_unique` in stable Rust.

It is possible that the same factory pattern that Gfx uses is needed elsewhere, so it might be an idea to move the `Arc` to a separate library.

**Comment by kvark** [comment]
I'd like to see at least one more project needing this.

**Comment by csherratt** [comment]
I don't have a problem with this. That being said, it the `Arc` trait were to move to an external crate I think it would make sense to include the entire `std::sync::Arc`. There is quite a few features that are still unstable, like `Weak` that people are bound to want.

**Comment by kvark** [comment]
@csherratt hmm, I'm not a big fan of making more libraries without an explicit need for this. I don't think anyone needs `Weak` currently with `gfx` resources, and by the time they need it - we might as well use a stabilized `Arc`. Besides, there are talks about `Weak` being unsafe and all, so it's future is moot.

**Comment by kvark** [comment]
I think we are no longer using a custom `Arc`, closing.
