### ISSUE TITLE
Organization governing policy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#726]
We need to come up with a policy of accepting/rejecting projects (or new gfx examples) under gfx-rs organization. What are the requirements, what is the process of adoption, etc.

For instance, there has been #125 waiting for some sort of decision. Recently, `gfx_text` also appeared with an intention be a part of gfx.

Requirements in progress:
- all core members must approve the design
- must be used by at least one core member
- must not depend too much on outside projects
- must be Apache 2.0 licensed

Calling for @gfx-rs/owners to join!

Edit: @bvssvni explained we need to provide the motivation for each of the requirements, and helped to define it (kudos!). Here it is:
- contributors come and go, but things get evolving nevertheless. Code needs to be supported constantly, and this responsibility is often left on the core developers. That is why, we need to approve the design and at least partially use a new project ourselves (dogfooding).
- GFX is a complex project that started as a hardware abstraction. It requires some level of understanding and experience in order to follow the ideas and concepts of the development. That is why, we can't accept every project or contributor in the team. We've got to keep the scope narrow in order to sustain the quality level of our work.

**Comment by csherratt** [comment]
> must depend too much on outside projects

Should that be mustn’t? Or am I missing the meaning.

We should also require that it be Apache 2.0 licensed. Just to make sure anyone using any component of `gfx` can assume it has the same terms.

**Comment by kvark** [comment]
@csherratt thanks, I modified the list w.r.t. your notes.

**Comment by kvark** [comment]
Core members come and go similarly to contributors. I will make these decisions with help of active members. No explicit policy is needed now.
