### ISSUE TITLE
Use EXT_framebuffer_object

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#731]
Everything supports it, so we could use it when ARB version is not available, instead of panicking.

**Comment by fkaa** [comment]
Does that mean that framebuffer attachments will be forced to have equal dimensions even on ARB?

**Comment by kvark** [comment]
@fkaa good question! We can detect that and return an error when drawing with EXT only.

**Comment by kvark** [comment]
this happened looong ago
