### ISSUE TITLE
Versioning policy

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#736]
Our versions should come as 0.y.z for the nearest time being. `z` is for non-breaking patches, including those that extend the function. `y` is only increased for breaking changes, which we should do as rare as possible. ~~We can have a milestone for each major (`y`) version - as means to track all the pending breaking changes~~ These are not actually milestones! We could just have issues for tracking. We can also tag the breaking changes in git.

**Comment by kvark** [comment]
We can't submit all the breaking changes as one PR. There might be multiple of them, the first bumping `Cargo.toml`, and the last one publishing it. Hm... this will break all the libraries that use `gfx-rs` by git path.

**Comment by kvark** [comment]
I got an idea - we could branch out for the new release. Make all changes/PRs to the branch, and then merge back when breaking is complete.

**Comment by bvssvni** [comment]
It seems after https://github.com/gfx-rs/gfx/pull/809 got published forgot to merge the 0.7 branch into master. Then came https://github.com/gfx-rs/gfx/pull/810 and https://github.com/gfx-rs/gfx/pull/811 which was merged into the master branch.

**Comment by bvssvni** [comment]
In Piston we work directly against master and bump the first non-zero number for breaking changes. The version change is merged before publishing. This reduces the chance of human error.

**Comment by csherratt** [comment]
810/811 should have been cherry picked into 0.7. Master has changes that break the API which is why the 0.7 branch was created in the first place.

Maybe we should just publish 0.8, then we don't have to maintain two branches. I was hopping to add more features to it but there is really no reason to make releases large.

**Comment by bvssvni** [comment]
@csherratt Sounds nice.

**Comment by kvark** [comment]
Ok, I think this can be closed. The current workflow is:
- develop in master
- when releasing a version, branch out
- back-port the non-breaking fixes on the branch and release minor updates there
