### ISSUE TITLE
Memory views

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#761]
Related to #161, #630

On the lowest level, things like textures or buffers narrow down to chunks of VRAM. What user operates with is some kind of view into these chunks. For example, the same memory could be treated as a texture and a render target given the same tiling mode (compatible with rendering).

Different APIs provide different degrees of freedom w.r.t. memory views. We need to figure out the model we can expose without limiting the use cases, while adding some type safety on the way (*typed* views).

Here is a short recap of what different APIs expose. To be filled with your help!
  - *OpenGL*: textures and buffers are entirely unrelated things. You can't get multiple views into the same memory.
    - `ARB_texture_buffer_object`: allows viewing a buffer through a 1D texture
    - `ARB_texture_view`: allows textures to be viewed via different formats
  - *DirectX10*: there are generic resources (`ID3D10Resource`). One can create multiple shader views (`ID3D10ShaderResourceView`) as well as target views (`ID3D10RenderTargetView`), but the flags enabling these have to be specified upon resource creation.
    - *DX11* also adds UAV views (`ID3D11UnorderedAccessView`) following the same scheme
  - *GNM*: (basically described in the beginning) one allocates memory and treats it as they wish. The compatibility of the views is partially checked by the (optional) validation layer, but the user can still screw up rather badly (by using different sizes, for example).
  - *Vulkan*: TODO

Overall, I believe DX has the most sane model of all, and we should reflect it. Shader resource views should be allowed in unlimited quantities, while the target view should be lifetime bound to the object, thus preventing two writable views from existing simultaneously.

Summoning all the collective mind of @csherratt, @cmr, @fkaa, and even @tomaka from the other side of the moon!

**Comment by kvark** [comment]
We can push the concept even further and treat vertex and index buffers as separate views. In a way, `GL_ARRAY_BUFFER` and `GL_ELEMENT_ARRAY_BUFFER` reflect this distinction, especially considering that GLES doesn't allow changing this bind target. Thus, in GLES, if the user requests a buffer that needs to support both views, we will return an error. It is a better error than the one we issue during rendering since it's going to happen at the initialization time of the app.

**Comment by kvark** [comment]
A possible API example:
```rust
let buf = factory.create(gfx::VERTEX_BUFFER | gfx::TEXTURE).unwrap();
let vertex_buf = factory.view_vertex(buf).unwrap();
```
This is not exactly strongly typed yet. It would be nice to get rid of the last `unwrap()` call by limiting the views that can/can't be create by the type system.

**Comment by fkaa** [comment]
Unfortunately changing target of a OpenGL texture object is not possible. To emulate `ARB_texture_view` on lower-end hardware we could possibly keep a *root* struct which handles the lifetime of all the created views. Some psuedo-rusty-code:
```rust
struct RootTexture<'a> {
  views: Vec<Rc<ViewTexture>>
}

impl<'a> RootTexture {

  pub fn create_view(&self, format: Format) -> Rc<ViewTexture<'a>> {
    if (self.has_format(format)) {
      self.cache[format]
    }

    ViewTexture::new(&self)
  }

  pub fn update(&self, data: &Data) {
    for view in views {
      gl::UpdateTex(view.handle, data);
    }
  }

}

struct ViewTexture<'a> {
  parent: &RootTexture<'a>,
  handle: GLint
}

impl<'a> ViewTexture {

  pub fn update(&mut self, data: &Data) {
    parent.update(&data);
  }

}
```
Feels like it could work but also feels like a pretty big hack. Is it worth it? This would mean that a view doesn't share memory unless they have the same format, which kind of defeats the point. Personally I feel that it could work, since you shouldn't really be creating views left and right. Updates would still cascade through all of the views associated to a texture object.

**Comment by kvark** [comment]
> Unfortunately changing target of a OpenGL texture object is not possible

This is not true. A 3D texture, for example, can be viewed as either a 3D target, or as one of the slices. There are more (similar) examples, which would fit the subject model.

**Comment by fkaa** [comment]
@kvark I was talking more about this part in the docs:
>```C
>void glBindTexture(GLenum target,
>                    GLuint texture);
>```
> **GL_INVALID_OPERATION** is generated if _**texture**_ was previously created with a target that doesn't match that of _**target**_.

Even if you access the 3D layer as a 2D target you'd still have to pass it as a sampler3D in a shader though, right?

**Comment by kvark** [comment]
@fkaa I gave the example for *target* views, not the shader resource views. The latter are indeed fixed by opengl up until `ARB_texture_view`.
