### ISSUE TITLE
arrays of arbitrary size in gfx_parameters! are causing errors

### ISSUE THREAD

**Issue by olsonjeffery** [gfx-rs/gfx#773]
As per https://gist.github.com/olsonjeffery/8d32b855c667c5981fec . On rust beta and OSX Yosemite.

Interestingly, if I change `char_map: [0.0f32; 16384]` to `char_map: [0.0f32; 4]`, in the declaration and instantiation, it will compile. Is this an issue with standard derived traits being implemented for arrays of small sizes, but not arbitrarily large ones? Is there any workaround for this?

**Comment by kvark** [comment]
Fixed size vectors in the uniform parameters are only for shader vectors, not arrays. So their size is expected to be 2,3, or 4, not 16384.
If you need this much storage, use a buffer. See [shadow](https://github.com/gfx-rs/gfx/blob/master/examples/shadow/main.rs#L56) example for some reference code.

**Comment by olsonjeffery** [comment]
great, thanks!
