### ISSUE TITLE
Include full Cargo.toml for examples?

### ISSUE THREAD

**Issue by tyoc213** [gfx-rs/gfx#789]
I think that examples, should include the Cargo.toml for a more easy "introduction".

**Comment by kvark** [comment]
Is there another project having a separate `Cargo.toml` for the examples?

**Comment by tyoc213** [comment]
I see, the point I'm somewhat new to rust and so to this cargo thing, so seeing on the main page you only need cargo

```
[dependencies]
gfx = "*"
```

Didn't understand why doing what is pointed on the main page and trying to do cargo build for the examples didn't work if they don't provide more info for run the examples (directly without take care of more docs than what is on main page and inside the folder example.

**Comment by kvark** [comment]
How about adding a section to the README explaining how to run examples? It's somewhat basic knowledge of Cargo, which is an essential part of Rust ecosystem, so a bit of education will not be wasted.

**Comment by tyoc213** [comment]
Yeah, eventually knowledge will come, but what about a guy/person that say ey that concept sound great I just want to try it out then do it directly (even without knowing what is rust?) what you will love more?? that he continue to see how simple and good this can be like **just run it**? or that he after see the first error try to figure out what is not there in the example??? so to solve this "little errors" stop a little the flow and learn this extra configuration steps? then continue with the previous flow?


I just think it would be amazing if people could say... ey I just want to try this out and copy file by file each folder and run cargo run and that is all (you will not even need to "clone directly" the repo or run it from there??... how you run this samples then???)

**Comment by kvark** [comment]
I do agree with you. Though you are mixing 2 cases together:
  1. A newbie just wants to run the examples. Our README would mention to do it via `cargo run --example XXX`. Problem solved.
  2. A newbie wants to start their own code from an example. So he copies `Cargo.toml` and tries to patch it. This may not work right away. We can solve it by having a standalone example (in its own repository) - either by moving an existing one out, or by adding a new one. Then we'd patch README to mention it as well. How does this sound to you?

**Comment by tyoc213** [comment]
I think if possible use both of them, so the realm would say some like


run the examples with ```cargo run --example XXX``` and also see our linkto:starter_standalone_template and remember read the link:documentation.

That would be great :+1:

**Comment by Trebgarta** [comment]
I think it'd be nice of you to mention how to run examples, either directly giving the command cargo run --example xxx or giving a link to the Rust/cargo doc that teaches how to run examples of any crate.

I'm a newbie and I did not know how to until I stumped upon this issue.

What can also be done on top of that is, just in case a newbie wants to write the example in his own way, simply mention "depends on xxx

**Comment by jacmoe** [comment]
What I would like to have is a list of dependencies for each example.
I had to add the following to my project cargo toml for the triangle example:
```
gfx = "*"
gfx_window_glutin = "*"
gfx_device_gl = "*"
glutin = "*"

```
Luckily, Rust has nice error messages so figuring out the dependencies by trial and error is not difficult..

**Comment by kvark** [comment]
@Trebgarta @jacmoe the examples code is self-documented with regards to dependencies - just open the source and see `extern crate XXX` to see what is needed, and the versions/paths can be seen from the root `Cargo.toml`.

**Comment by kvark** [comment]
@Trebgarta @jacmoe the examples code is self-documented with regards to dependencies - just open the source and see `extern crate XXX` to see what is needed, and the versions/paths can be seen from the root `Cargo.toml`.

**Comment by jacmoe** [comment]
I realize that now - my skills are not Rusty enough yet. Yes, indeed, they are actually self-documented. :+1:

**Comment by kvark** [comment]
@tyoc213 does my [comment](https://github.com/gfx-rs/gfx/issues/789#issuecomment-205948009) address your issue enough so that it can be closed?

**Comment by tyoc213** [comment]
Yes indeed, still think that for newcomers to rust you should not think of them as rustaceans, I mean for starters cargo is not rust... and if an extern person to rust (and its _ecosystem_) the section on README on how to run examples would be just a NTH. Or at less inside the realm for each example, say some like _run me with: cargo run --example name_ or something like that, just to make it straight forward to people that just only want to see some rust running right away.

**Comment by kvark** [comment]
@tyoc213 I agree that README could be updated to include that information. PRs are welcome ;)

**Comment by kiran-kp** [comment]
There's a note on how to run examples in the Getting Started section of the readme. This issue can probably be closed.

**Comment by kvark** [comment]
@kiran-kp agreed.
