### ISSUE TITLE
Intel display driver crashes when closing application, with depth-testing on

### ISSUE THREAD

**Issue by viperscape** [gfx-rs/gfx#802]
So I ran in to this issue where my intel driver on windows 10 crashes as I close the window to my application (thus shutting it down). This only started happening with the additional drawstate command for depthtesting: ``` .depth(gfx::state::Comparison::LessEqual, true) ```

I am using a batch::Core for batch and supplement it during the draw call. Soon as I added the depth test to DrawState I started having this issue. Perhaps I am wrong how I am using drawstate. Most interesting is that if I switch to using the nvidia card the problem subsides. I also tested this on an another computer without intel integrated graphics, and it ran without issue. So this issue is directly related to intel graphics, some how. I have an i7-4712HQ mobile processor with intel HD 4600 integrated. What should I do to fix this? Is there a way to properly shut down the graphics driver in this case, as it looks like it hangs while closing (for about 2 seconds) then closes and crashes.

``` rust

//excerpt from drawing
    pub fn draw<P>(
        &mut self,
        batch : &Batch<P>,
        params: &P,
        )
        where P: gfx::render::shade::ShaderParam<Resources=gl::Resources>,
    {
        self.stream
            .draw(&batch.batch.with(
                &batch.slice,
                params,
                &gfx::DrawState::new().depth(gfx::state::Comparison::LessEqual, true)
                    .blend(gfx::BlendPreset::Alpha),
                ))
            .unwrap_or_else(|e| panic!("Error drawing graphics: {:?}", e));
    }
```

My shader programs are as such:

``` c

// vert
        #version 120

        attribute vec3 pos;
        attribute vec3 norm;

        uniform mat4  model;
        uniform mat4  view;
        uniform mat4  proj;

        uniform float size;
        uniform vec3  color;

        varying vec3 v_color;
        varying vec3 v_position;
        varying vec3 v_normal;

        void main() {
             v_position = pos;
             v_normal = norm;
             gl_Position = proj * view * model * vec4(v_position, 1.0);
             v_color = color;
        }

// frag

       #version 120
       varying vec3 v_normal;
       varying vec3 v_color;

       const vec3 LIGHT = vec3(-0.2, 0.8, 0.1);
       void main() {
            float lum = max(dot(normalize(v_normal), normalize(LIGHT)), 0.0);
            vec3 color = (0.3 + 0.7 * lum) * v_color;
            gl_FragColor = vec4(color, 1.0);
       }
```

**Comment by kvark** [comment]
Could you try testing this with any of the gl-rs examples? Also, what OS/driver are you on?

**Comment by viperscape** [comment]
I'm on Windows 10 64-bit, I realized as I wrote this that I should update my drivers. I'll look through the examples to see if any run depth tests with alpha blending. I'll let you know what I find out

**Comment by viperscape** [comment]
So upgrading my intel driver did not fix this. The program is fine on Radeon and nVidia, but intel 4600 driver itself crashes when *closing* the program-- the program does not crash but does take a while to close and hangs after closing (for about 2 seconds). This only started when I added depth+blend in batch parameters, it was fine before this. Is there an example which uses both depth and alpha blending like the code above? If so I can test against it.

**Comment by kvark** [comment]
Out deferred rendering example [uses it](https://github.com/gfx-rs/gfx/blob/2251adddbfb208a4f06797595969511cd45a04ac/examples/deferred/main.rs#L484-L486), please try it.

**Comment by viperscape** [comment]
I guess I need cmake setup in order to build and run. Unfortunately I'll have to dock this for later, as such we can close this issue for now-- as this is likely an issue with my intel driver/method of using gfx-rs

```
$ cargo run --example deferred
...
Build failed, waiting for other jobs to finish...
failed to run custom build command for `glfw-sys v3.1.3`
Process didn't exit successfully: `C:\Users\Chris\gfx\target\debug\build\glfw-sys-a256251833e28409\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Failed to execute cmake: The system cannot find the file specified.
 (os error 2)', C:\Users\Chris\.cargo\registry\src\github.com-121aea75f9ef2ce2\glfw-sys-3.1.3\build.rs:15
```

**Comment by kvark** [comment]
Actually, you can remove `glfw` dependency from `Cargo.toml` and try again. The deferred example doesn't need it, IIRC.

**Comment by viperscape** [comment]
I can confirm that the example did run, @kvark  and looks fantastic btw :+1:  I'll have to rummage through my code some more when I have a moment, thanks again!

**Comment by kvark** [comment]
Yay! This makes me wonder if we should re-consider stripping the examples out of glfw completely. It doesn't bring much to the table, so I'd be fine with it for as long as Glutin works on all platforms.

**Comment by csherratt** [comment]
I am personally using glutin these days, as glfw is a pain to get up and running on windows compared to glutin. I would not be opposed to migrating the examples away from glfw. But we should probably keep a basic one alive and kicking if we plan to keep supporting gfx_window_glfw. Maybe we can hide it behind a feature flag to make sure it compiles, but wont get in the way of new developers.

**Comment by fkaa** [comment]
:+1:
