### ISSUE TITLE
mismatched types compiling gfx_gl_device

### ISSUE THREAD

**Issue by mathgamain** [gfx-rs/gfx#819]
Hello, I was following this tutorial on Piston http://piston-tutorial.logdown.com/ and when I did "cargo build" during the compiling stage of gfx_device_gl I got a lot of mismatched types errors and it failed:

[code]
   Compiling gfx_device_gl v0.6.0
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/gfx_device_gl-0.6.0/src/lib.rs:185:1
8: 185:35 error: type mismatch resolving `for<'r> <F as core::ops::FnOnce<(&'r str,)>>::Output == *con
st libc::types::common::c95::c_void`:
 expected enum `libc::c_void`,
    found enum `libc::types::common::c95::c_void` [E0271]
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/gfx_device_gl-0.6.0/src/lib.rs:185  
       let gl = gl::Gl::load_with(fn_proc);
                                                                                                      
                ^~~~~~~~~~~~~~~~~
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/gfx_device_gl-0.6.0/src/lib.rs:185:1
8: 185:35 help: run `rustc --explain E0271` to see a detailed explanation
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/gfx_device_gl-0.6.0/src/lib.rs:185:$
8: 185:35 note: required by `gl::Gl::load_with`
error: aborting due to previous error
   Compiling flate2 v0.2.9
Build failed, waiting for other jobs to finish...
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/osmesa/mod.rs:$
1:63: 92:69 error: mismatched types:
 expected `*mut libc::c_void`,
    found `*mut libc::types::common::c95::c_void`
(expected enum `libc::c_void`,
    found enum `libc::types::common::c95::c_void`) [E0308]
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/osmesa/mod.rs:$
1         let ret = osmesa_sys::OSMesaMakeCurrent(self.context, self.buffer.as_ptr()
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/osmesa/mod.rs:$
2                                                 as *mut libc::c_void, 0x1401, self.width
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/osmesa/mod.rs:$
1:63: 92:69 help: run `rustc --explain E0308` to see a detailed explanation
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/x11/window.rs:$
24:38: 524:63 error: mismatched types:
 expected `*mut libc::c_void`,
    found `*mut libc::types::common::c95::c_void`
(expected enum `libc::c_void`,
    found enum `libc::types::common::c95::c_void`) [E0308]
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/x11/window.rs:5
24                 (display.xlib.XFree)(hint as *mut libc::c_void);
                                                                                                      
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/mprodrigues/.cargo/registry/src/github.com-121aea75f9ef2ce2/glutin-0.4.0/src/api/x11/window.rs:5
24:38: 524:63 help: run `rustc --explain E0308` to see a detailed explanation
error: aborting due to 2 previous errors
Could not compile `gfx_device_gl`.
[/code]

I'm using the latest rust. Output of rustc --version is "rustc 1.6.0-nightly (1a2eaffb6 2015-10-31)", but I also tried the stable 1.4 release, with the same error.

**Comment by bvssvni** [comment]
Change `gfx = 0.8.0` in the Cargo.toml.

**Comment by mathgamain** [comment]
but that is the version already being used. What is in my Cargo.lock:

[[package]]
name = "gfx"
version = "0.8.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bitflags 0.3.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "draw_state 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "num 0.1.27 (registry+https://github.com/rust-lang/crates.io-index)",
]

**Comment by bvssvni** [comment]
Sorry. I thought this was an error from your application code.

**Comment by mathgamain** [comment]
looking closer I see two versions of "gfx" are being pulled, gfx-0.8.0 and 0.7.2, gfx_device_gl is 0.5.0 and depends on gfx-0.8.0, could that be causing a conflict?

**Comment by bvssvni** [comment]
@mathgamain The latest version of gfx_device_gl is 0.6.0 https://crates.io/crates/gfx_device_gl

**Comment by mathgamain** [comment]
hi @bvssvni the tutorial uses piston_window 0.24.0 and it pulls gfx0.7.2 and gfx_device_gl0.5.0, but I already tried using piston_window0.27.0 and it pulls gfx0.8.0 and gfx_device_gl0.6.0, but to no avail, the same problem occurs. I tried to run the code in another machine to see if wasnt some exoteric problem happening only in this one, but it happens there too. Btw, I see you are the developer of piston, thanks for your help, do you recommend using rust nightly or stable with piston?

**Comment by sekhat** [comment]
I'd just thought I'd pipe up and say I'm getting the same issue here on windows with MinGW and stable rust 1.4.0

I'm include piston_window latest version, this grabs `gfx 0.8.0` and grabs `gfx_device_gl 0.6.0` amongst other things, and fails with the exact error above.

**Comment by bvssvni** [comment]
@mathgamain There was a bug sneaking into stable right before it got fixed, but that was 1.3.0. https://github.com/PistonDevelopers/piston_window/issues/77.

It could be gfx_graphics, which is 0.13.0 now https://crates.io/crates/piston2d-gfx_graphics.

**Comment by mdeg** [comment]
I am also getting this issue trying to compile an unchanged piece of code that compiled successfully yesterday. The error initially occurred on Rust 1.3.0 stable, I upgraded to 1.4.0 stable in hopes of resolving the issue but there was no change. I also tried downgrading gfx_device_gl to 0.5.0 instead of 0.6.0 but that did not produce any difference. I am on a Linux machine.

It is worth noting that gfx, piston2d-gfx_graphics and gfx_device_gl were all last updated in Cargo on Nov 3, a few days ago. My code compiled fine before and after those changes. However libc - which is mentioned in the error message - released a new version on Nov 4, and then on Nov 5, which would mean the latter update occurred in the gap between my successful and failed compilations.

**Comment by kvark** [comment]
Do I understand correctly that we just need to update `libc` dependency on `gfx_device_gl` and publish a new version?

**Comment by mathgamain** [comment]
Just to notify that with new updates this issue seems resolved

**Comment by AllowFlame** [comment]
I have the same issue.
My project dependencies set like

piston_window = "0.34.0"
find_folder = "*"
gfx_device_gl = "0.8.0"
gfx = "0.9.0"
piston2d-gfx_graphics = "0.18.0"

I tried changing version of each crates, but I got the same error message.
How can I fix this?
Any hint will be appreciated.

**Comment by kvark** [comment]
@AllowFlame gfx_graphics is still being ported to the new gfx (0.9). The version you are using (0.18) works with gfx-0.8 and gfx_device_gl-0.7: https://github.com/PistonDevelopers/gfx_graphics/blob/master/Cargo.toml

**Comment by AllowFlame** [comment]
@kvark Thank you, It works.
