### ISSUE TITLE
Version 0.9

### ISSUE THREAD

**Issue by csherratt** [gfx-rs/gfx#821]
This is an meta issue to track what changes should be published with 0.9

- Strongly Typed Shader Objects -- #820 
- Move to system Arc (removed methods) -- #829
- Add the concept of a PSO object -- #828

**Comment by kvark** [comment]
Thanks @csherratt ! I hope we'll have more breaking stuff coming in.

**Comment by sectopod** [comment]
I propose to have a dedicated version to include everything before the breaking #828 is merged. 0.9 could be such a release, but it would need to wait till #828 is done, so that the merge comes right after.

**Comment by kvark** [comment]
0.9 has been shipped
