### ISSUE TITLE
Yank latest version to avoid breaking existing code downstream

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#826]
- gfx_device_gl 0.6.1
- gfx 0.8.1
- gfx_window_glfw 0.4.1

glfw uses "*" dependencies, but I suggest we fix this by https://github.com/bjz/glfw-rs/issues/325.

We should wait for lower level libraries to update to libc 2.0.

**Comment by csherratt** [comment]
I think `gfx 0.9.x` should upgrade to `libc 0.2` and `gfx 0.8.x` should be `libc 0.1`

`glfw-rs` should probably publish `0.1.2` with fixed dependencies, and publish `0.2.0` with `libc` upgraded.

Pulling `0.8.1` causes anyone using `glutin` to break. The way I see it should have been published with a hard link to `0.8.x` (so should have `0.7`, ect). This was overlooked, and we should fix it now.

**Comment by bvssvni** [comment]
@csherratt I agree.

**Comment by csherratt** [comment]
@bvssvni ok the first part is done. Do it has been published, do we have a downstream component that is know to be effected that can be tested to make sure this worked?

**Comment by mitchmindtree** [comment]
I'll try testing this with piston_window

**Comment by bvssvni** [comment]
The only place I could find that exposes libc is [here](https://github.com/gfx-rs/gfx/blob/de890d83c6f3599b492e0f57e81f67bacf84c03e/src/backend/gl/src/factory.rs#L145). Perhaps Conrod or Hematite can be used as a test case.

**Comment by kvark** [comment]
Can this be closed?

**Comment by mitchmindtree** [comment]
Yeah definitely :+1:
