### ISSUE TITLE
Remove libc references from user API

### ISSUE THREAD

**Issue by csherratt** [gfx-rs/gfx#832]
We should not expose `libc` (or any other uncontrolled libraries) in our external inferences. This is brittle for both our library and the downstream libraries. What I recommend is that if we expose an interface that we intent to be used by the client, we either use a native rust type or define our own for the interface.

eg `*const libc::c_void` should either be `*const ()` (as `glutin` uses) or `*const void` where `void` is defined as a public type by our library.

I suspect that this style should be applied to other projects (`glfw`, `gl-rs`) but for now making sure we are following it would be a good start to helping sanitize the rust gamedev ecosystem.

The rule should be there is no API inside of `gfx` that requires an added `[dependencies]` section in the `Cargo.toml` file of a downstream project. The exception is when the library is an extension of the another, `gfx_window_glutin`.

**Comment by kvark** [comment]
Agreed

**Comment by vickenty** [comment]
Would ``std::os::raw::c_void`` be a good replacement for ``libc::c_void`` in the public API?

**Comment by bjz** [comment]
We're using `raw::c_void` in gl-rs now.
