### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#838]
Sounds reasonable to me. We can add one, especially since #828 changes everything.

https://blog.dbrgn.ch/2015/12/1/rust-crates-keep-a-changelog/

http://keepachangelog.com/

**Comment by kvark** [comment]
Hmm, there is a simpler way, I suppose - have a special "breaking" label for PRs. Each of them would have a "User breaking changes" list at the top of the description (like #828). One would be able to get a list of them with a simple search, and it doesn't require any maintenance.

**Comment by bjz** [comment]
See [this thread](https://www.reddit.com/r/rust/comments/3v1ndl/rustaceans_please_keep_a_changelog/cxjkalu) on [the reddit thread of that changelog post](https://blog.dbrgn.ch/2015/12/1/rust-crates-keep-a-changelog/) for the pros and cons of the labelling/tagged commit approach. tl;dr; a curated, high-level changelog that is diligently kept up to date is easier from the user's perspective.
