### ISSUE TITLE
Rename `Phantom` to `InnerRaw`

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#849]
http://gfx-rs.github.io/gfx/gfx/core/factory/trait.Phantom.html

`Phantom` is a generic name with few associations. I would like it to be easier to remember what it does, even if it is not meant for public use.

**Comment by kvark** [comment]
:+1: for renaming in general, not sure if `InnerRaw` is the perfect name.

**Comment by kvark** [comment]
@bvssvni how about `Typed` name?

**Comment by bvssvni** [comment]
@kvark `Typed` is better.
