### ISSUE TITLE
Weak PSO and components

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#853]
With the PSO revolution in #828 we got strongly-typed PSO and components. Problem is - they are fixed at compile time, well, mostly - unless we do generic PSO definitions, which are blocked on rust macros expressiveness. So when you want to load something from disk, something you don't know exactly, the strong PSO doesn't fit. Hopefully, both PSO and components are interfaced with by traits, so all it takes for us is to introduce weakly typed stuff:
- `WeakVertexBuffer` - to receive the format slice in the init data instead of deriving it from the type
- `WeakPipelineState` - to receive all the components in some serialized form. In fact, the component becomes it's implementation detail, since it's not exposed anywhere.

**Comment by sectopod** [comment]
Most of this task is implemented in #910. The big thing left is loading the whole PSO definition at run-time, although I don't see the use case for it clearly yet.

**Comment by kvark** [comment]
Perhaps, @ebkalderon or other Amethyst devs want to either contribute or express their opinion on having that in gfx-rs.

**Comment by kvark** [comment]
We got a bunch of weak components, closing.
