### ISSUE TITLE
Fix macro namespace conflict with PSO in rust-nightly

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#869]
```
<gfx macros>:4:19: 4:30 error: import `gfx` conflicts with imported crate in this module (maybe you meant `use gfx::*`?) [E0254]

<gfx macros>:4 use $ crate ; use super:: * ; gfx_pipeline_inner ! { $ ( $ field : $ ty , ) *
```
We could import `gfx` in the macro under a different name to avoid collision.

**Comment by Dentosal** [comment]
I can confirm. The error occurs in file `/src/render/src/macros/pso.rs`.
Just removing the line `use $crate;` fixes the error for me. I am not sure if it breaks something, but all the tests run fine after that.

**Comment by kvark** [comment]
Isn't our CI green now? I thought the issue can be closed.

**Comment by Dentosal** [comment]
Oh, sorry, I was looking at my (old) fork. I hadn't noticed that fix. Yes, feel free to close.
