### ISSUE TITLE
Specifying shaders in PSO

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#870]
We've been considering including the rasterizer state inside PSO definition. However, there is an elephant in the room - shaders. Currently, passed in as `ShaderSet` - not the most straightforward or convenient thing to manage. How about specifying the shaders inside PSO definition?

| meta | init | data | comment |
| --- | --- | --- | --- |
| `VertexInput` | `(Shader<R>, Primitive)` | `Slice` | vertex shader |
| `PixelOutput` | `(Shader<R>, Rasterizer)` | ? | pixel shader with the rasterizer |
| `Geometry` | `(Shader<R>, ..)` | ? | geometry shader |
| `Tessellator` | `(Shader<R>, Shader<R>, ..)` | ? | tessellation |

Brief analysis:
- (+) removes the concept of `ShaderSet`
- (+) removes all the init and run-time parameters other than the ones associated with PSO definition
- (+) nicely extendable to tessellation and compute, exposes vertex/pixel shading being optional
- (-) harder to document
- (-) doesn't completely isolate the stages. I.e. if `PixelOutput` is not provided, the `RenderTarget`, `Scissor`, `BlendTarget`, `DepthTarget`, and other components no longer make sense. Perhaps, these need to be hierarchically under the `PixelOutput` parent?..

**Comment by fkaa** [comment]
:+1:

I like the idea of listing the components under `PixelOutput` and friends. Would defining a PSO look roughly like this then?

```rust
gfx_pipeline!(terrain {
    VertexInput {
        vbuf: gfx::VertexBuffer<TerrainVertex> = (),
        model: gfx::Global<[[f32; 4]; 4]> = "u_Model",
        view: gfx::Global<[[f32; 4]; 4]> = "u_View",
        proj: gfx::Global<[[f32; 4]; 4]> = "u_Proj"
    },
    PixelOutput {
        light_buf: gfx::ConstantBuffer<grid::LightInfo> = "u_LightData",
        light_grid: gfx::ConstantBuffer<grid::GridTileData> = "u_LightGrid",
        light_index_tex: gfx::ShaderResource<i32> = "u_LightIndexTex",

        out_color: gfx::RenderTarget<Rgba8> = "o_Color",
        out_depth: gfx::DepthTarget<DepthStencil> = gfx::preset::depth::LESS_EQUAL_WRITE
    }
});
```

**Comment by bvssvni** [comment]
This might increase loading time in gfx_graphics, because the shaders need to recompile for every PSO.

**Comment by kvark** [comment]
@bvssvni Oh no, that's not what's proposed here. We are still going to be compiling shaders as usual. Just instead of providing them in `ShaderSet` they are gonna have fields inside the PSO definition.

**Comment by bvssvni** [comment]
@kvark OK then!

What about shared parameters between shaders? For example, a MVP transform accessed in both vertex and pixel shader.

**Comment by kvark** [comment]
@bvssvni that's the question of dispute here (among other things).

If the pipeline is split into vertex/pixel/geometry/tessellation/compute pipes, and each have their own parameters, then some of them might need to be repeated. In this case GL backend may be a little pressured into supporting separate shader programs per stage, since otherwise it would have to check that we don't try to set 2 different values to the same parameter.

If all the parameters are shared between stages, there should be no problems. However, it doesn't look as nice when all of them are together. Perhaps, we could have a compromise in the form of `Common {}` section where you'd put parameters shared between stages, if any.

**Comment by kvark** [comment]
Still an option for `gfx_render`

**Comment by kvark** [comment]
This is fun, but pre-ll has to go, closing.
