### ISSUE TITLE
Prototyping library

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#876]
We need some way of quick prototyping, like Piston for 3D, or Kiss3D. Looking at the [latter](https://github.com/sebcrozet/kiss3d/blob/master/examples/primitives.rs), there are certainly some usability aspects that could be improved:

``` rust
let c = scene.add_cube(1.0, 1.0, 1.0)
             .color(random(), random(), random())
             .position(Vec3::new(2.0, 0.0, 0.0))
             .pin();
```

A simple library like this would slash the entrance barrier and allow people to do crazy stuff. Also, related to #125

**Comment by kvark** [comment]
@bvssvni what are Piston plans for 3D?

**Comment by bvssvni** [comment]
@kvark There are two projects going on, for 3D: [Turbine](https://github.com/pistondevelopers/turbine) and for prototyping: [Dyon (old name Dynamo)](https://github.com/pistondevelopers/dynamo).

Turbine's goal is to have a built-in level editor with version control for concurrent world editing. Trying to test stuff we already developed, and make Conrod work on top of 3D.

Dyon is a scripting language with a lifetime checker and dynamic modules. Perhaps Dyon will be used in Turbine, depends on how far I get with it. I want to make some small games in Dyon first to see how the language feels like.

We are open for more projects in this area. I would like to see a physically based rendering pipeline.

**Comment by kvark** [comment]
@bvssvni thank you for describing the plans!
I take it you are not really into making a 3D piston, so this space is still vacant:
  - `Turbine` may easily beat it (in terms of prototyping convenience) when it is completed, but overall it has much more ambitious goals, and it is more heavyweight.
  - `Dyon` involves another language, so not every Rustacean will want to use it.

**Comment by kvark** [comment]
Looks like we [have a client](https://botbot.me/mozilla/rust-gamedev/2016-03-07/?msg=61697994&page=5):
> if those high level gfx bindings get done, I'm hopping on that stuff

**Comment by kvark** [comment]
Closing - https://github.com/kvark/three-rs
