### ISSUE TITLE
Example launcher

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#878]
Our monogamy with GL is ending. Now we need all the examples to be written in the backend-agnostic and window-agnostic way. I propose to do the following:
  1. Create a launcher crate in this repository to contain:
    - the application trait that is generic over backends/windows
    - configurable facilities to launch an application with any backend/window
  2. Each example then will need to be updated:
    - will declare a `struct SomeExample`, which implements launcher's `Application` trait, and has all the example logic in it
    - the `main()` body just calls the launcher

**Comment by kvark** [comment]
I just realized one beautiful thing... So what is that launcher? It depends on pretty much everything, since it needs to switch between all the backends/windows. Every example depends on it. We already have a library like this... `gfx_meta`, which is intentionally not published, it used to be an artificial project just for our `cargo test` convenience.

What I'm saying is that the launcher and the application interface should simply been implemented in the root library of this repository, and that crate renamed to `gfx_laucnher` (or `gfx_app`) and published. There is no better place for it!

**Comment by sectopod** [comment]
Grabbing, since I need to test DX11 backend now anyway.

**Comment by sectopod** [comment]
I've got 2 interesting (hopefully) points on the launcher:
  1. The app constructor can't  be completely abstract, since the shaders are different for GL and DX. Well, at least untie we solve #71 puzzle.
  2. DX back buffer doesn't have depth out of the box. GL one does. We need to figure out a compromise. So far I've been creating the depth surface manually to emulate GL behaviour.

**Comment by kvark** [comment]
Blocked by #882 
If the shader selection works, the app can provide all the versions it has, and it will not directly depend on a backend.
