### ISSUE TITLE
Shader version selection is broken

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#882]
Our current `ShaderSource` type can't be used for multiple backends. First problem - it knows about possible backends (HLSL, GLSL, etc), while this is supposed to be a backend-agnostic module. Secondly, since the capabilities only expose `ShaderModel` type, we don't know which backend variation to choose among compatible shader models... We need something more directly connected to the backend.

**Comment by fkaa** [comment]
Furthermore, providing shaders in source form should also allow for preprocessor definitions to be passed along to the compilation.

**Comment by kvark** [comment]
Hmm, to be fair, this bug is not about source form vs binary form. It's simply about `ShaderSource` being broken, which we need to work.

**Comment by fkaa** [comment]
Ah, my bad
