### ISSUE TITLE
Add `Srgba8` format

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#885]
Currently, the only sRGB format is `Srgb` which has no alpha channel.

**Comment by kvark** [comment]
We do support it - `(R8_G8_B8_A8, Srgb)`, there is just no shortcut for it at the moment. Do need the shortcut? Most applications don't care about alpha for the main framebuffer.

**Comment by bvssvni** [comment]
I need it for textures. Currently gfx_texture uses `Rgba8` which gets brighter colors.

Might also need it for frame buffer if we do composed rendering, but don't need it right now.

**Comment by kvark** [comment]
@bvssvni ok, sounds convincing! We'll add the shortcut into v0.9.2

**Comment by kvark** [comment]
Published in https://crates.io/crates/gfx_core v0.1.2
