### ISSUE TITLE
Replace the blog by an actual documentation

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#891]
Our blog doesn't work too well. The contents get deprecated quickly, and it becomes rather useless as a documentation source. It's only valuable as history.

Perhaps, we could have an online book, like Amethyst does:
http://ebkalderon.github.io/amethyst/

We'd need to keep it in sync with the code. As a benefit, it will cut down the entrance barrier for newcomers.

**Comment by Bastacyclop** [comment]
related to #942

**Comment by kvark** [comment]
Documentation for gfx-hal is less of a problem, closing
