### ISSUE TITLE
Setup automatic builds for Windows

### ISSUE THREAD

**Issue by fkaa** [gfx-rs/gfx#894]
AFAIK the most used service is [AppVeyor](https://appveyor.com) which is free for opensource projects.

(cc @retep998)

**Comment by kvark** [comment]
This seems handy: https://github.com/Eljay/directx-sys/blob/master/appveyor.yml
Apparently, no DX12 as of Sep 2015

**Comment by kvark** [comment]
Looks like DX12 will come any moment now - http://help.appveyor.com/discussions/problems/3531-cannot-run-direct12-unit-test

**Comment by retep998** [comment]
Also see https://github.com/retep998/winapi-rs/blob/master/appveyor.yml

**Comment by kvark** [comment]
I've added https://ci.appveyor.com/project/kvark/gfx

**Comment by kvark** [comment]
I've set up the build script and a webhook for gitter. However, I think I got the target config wrong:
"stable-x86_64-pc-windows-msvc" - says it can't be found

**Comment by retep998** [comment]
You can't specify stable- like that because the stable distributions aren't distributed like that. You have to explicitly reference the stable version, like I do with `1.4.0-x86_64-pc-windows-gnu`, or you have to parse the stable channel file to figure out what the current version of stable is.

**Comment by kvark** [comment]
@retep998 Ugh... ok, we can use 1.7.0 for now.
Also, this is the second error:
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles"

**Comment by kvark** [comment]
How about... we feature gate `glfw` or limit it to non-Windows builds?

**Comment by fkaa** [comment]
:+1: to gating GLFW

**Comment by kvark** [comment]
I believe this is working now
