### ISSUE TITLE
Constant buffers are mis-used for structured data

### ISSUE THREAD

**Issue by sectopod** [gfx-rs/gfx#898]
Several examples appear to use constant buffers that only consists of a single array of data:

``` glsl
    uniform u_LightPosBlock {
        vec4 offs[NUM_LIGHTS];
    };
```

The code side effectively treats them as structured buffers: we pass the number of elements on creation, the type is `ConstantBuffer<[f32; 4]>` instead of `ConstantBuffer<LightPosBlock>`, and we even receive a slice of them for updating the buffer. In other words, the buffer API is currently catering to structured buffer users.

We need to fix the constant buffers to stop pretending to be arrays! We need explicit support for structured buffers - these are just regular typed buffers with an SRV for binding to the shader. Problem is - there might be different typing:
1. Simple format, `T: gfx::format::BufferFormat`. Supporting these is straightforward, since we have the same typing for textures.
2. User structure, `T` - not bound by anything.
3. Raw buffer - untyped (or `()` typed for our convenience). Not sure if we have to support these but they exist. The shader to free to load from it in any possible way.

**Comment by kvark** [comment]
This is unfortunate, but not going to be fixed in pre-ll, closing.
