### ISSUE TITLE
`use super::*` compile error in macro

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#900]
Seems to cause compile error when `gfx` is imported in parent module. `use $crate` imports `gfx`, then it is imported once more with `use super::*`. Just my guess.

https://github.com/gfx-rs/gfx/blob/64d8fce8b3d32572a9ba16adbf43f126974ba7d2/src/render/src/macros/pso.rs#L211

Getting this error in https://github.com/PistonDevelopers/piston-examples/pull/333:

```
   Compiling piston-examples v0.0.0 (file:///Users/sven/rust/piston-examples)
<gfx macros>:4:19: 4:30 error: import `gfx` conflicts with imported crate in this module (maybe you meant `use gfx::*`?) [E0254]
<gfx macros>:4 use $ crate ; use super:: * ; gfx_pipeline_inner ! { $ ( $ field : $ ty , ) *
                                 ^~~~~~~~~~~
```

**Comment by kvark** [comment]
I see a different error in this PR:
https://travis-ci.org/PistonDevelopers/piston-examples/jobs/114290470#L733
Are you sure it's actual?

We used to get that "conflicts with imported crate in this module" for a while, mixed with https://github.com/rust-lang/rust/issues/31504. When the ICE got fixed, the conflict error seemed to go away as well.

**Comment by bvssvni** [comment]
The freetype and user_input example is not updated yet.

I'll update Rust nightly and try again.

**Comment by bvssvni** [comment]
It works now with `rustc 1.9.0-nightly (388ccda45 2016-03-07)`. Closing.
