### ISSUE TITLE
gl.Enable(gl::FRAMEBUFFER_SRGB) gives InvalidEnum

### ISSUE THREAD

**Issue by wthrowe** [gfx-rs/gfx#901]
Trying to run the cube example on my machine gives
```
thread '<main>' panicked at 'Error after executing command BindProgram(0): InvalidEnum', src/backend/gl/src/lib.rs:308
```
The error is misleading, as the `BindProgram(0)` is not failing, but the error state was already set before the call.  I've tracked the actual error down to the call to `gl.Enable(gl::FRAMEBUFFER_SRGB)` in `Device::new`.

I don't know enough about graphics to know what that means.  This is on a fairly old Linux machine (only OpenGL 2.1 support, I believe).

**Comment by kvark** [comment]
Thanks @wthrowe , we are definitely missing a check there.
There is more to it though, examples currently use `Srgb` format at compile time by default, which means we are going to just fail faster after this issue is fixed.
