### ISSUE TITLE
D3D11 Deferred Context

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#902]
D3D11 has the concept of a Deferred Context in addition to the Immediate one:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476880%28v=vs.85%29.aspx#Deferred

It's supposed to work similar to Vulkan/Meta/DX12 command buffers, although not used much for some reason. We could have separate `Device` and `CommandBuffer` implementations in our dx11 backend to work with deferred contexts: each command buffer will just wrap one instead of carrying a list of commands. If we are smart enough, we should be able to share the processing logic between these device implementations.

As an option, we could move the command buffer out from the associated type to the generic parameter of the device, and implement `Device<ImmediateCommandBuffer>` and `Device<DeferredCommandBuffer>` for the same structure, which seems convenient.

When this works, we'll be able to profile both immediate and deferred contexts, tell if there is any performance difference. Pinging @sectopod, in case you want to give it a try within #861.

**Comment by kvark** [comment]
There is a `D3D11_CREATE_DEVICE_SINGLETHREADED` flag:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476107(v=vs.85).aspx

Theoretically, using it allows the runtime/driver to avoid any thread checks and synchronization, thus increasing the performance. We should have it enabled for the immediate-context version of the device, and disabled for the deferred context one.

**Comment by sectopod** [comment]
I'll definitely try that! If I'm able to share the code with the immediate context, there shouldn't be too much to add here.

**Comment by sectopod** [comment]
`D3D11_CREATE_DEVICE_SINGLETHREADED` may be useful, but it appears to have nothing to do with deferred contexts. It would make sense with factories that don't implement `Send`.

**Comment by sectopod** [comment]
I gave it a try, and unfortunately there is one obstacle from re-using the same processing code - `DataBuffer`. Commands are supposed to be clonable and sendable, thus we copy the data, such as texture update texels, into the special data buffer and pass along the command buffer.
Problem is - for the true deferred context there should be no external data buffer, and we should operate directly on pointers. Thus, we can't have the same function for processing commands in the device and a deferred context... Needs to be a little more complex to work.
