### ISSUE TITLE
gfx_device_gl 0.8.2 on crates.io and git ICE on latest rustc nightly

### ISSUE THREAD

**Issue by olsonjeffery** [gfx-rs/gfx#904]
On rustc nightly 2016-03-18 (installed from multirust) on OSX El Capitan.

I filed a bug on rust already https://github.com/rust-lang/rust/issues/32336 , thought you'd like to know. The steps to repro are there, as well.

**Comment by olsonjeffery** [comment]
whoops already a dupe of https://github.com/rust-lang/rust/issues/32324

**Comment by kvark** [comment]
Thank you @olsonjeffery !

**Comment by kvark** [comment]
I believe this was fixed
