### ISSUE TITLE
Integrate winit

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#907]
https://github.com/tomaka/winit is not published yet (cc @tomaka). When it releases, we should be able to tightly integrate with it (the list is moved here from #861):
- pass the universal window builder to the `gfx_window_*` initialization
- use the even loop for the application launcher to respond on key presses
- reduce the cruft of the DXGI window implementation

**Comment by tomaka** [comment]
I guess I could publish winit. It just needs to merge the latest changes in glutin.

The biggest work will be to transition glutin to winit.

**Comment by kvark** [comment]
@tomaka thanks! We'll not really benefit from `winit` without `glutin` being ported first, so I suppose there is no rush in publishing the former just yet.

**Comment by tomaka** [comment]
I don't know what you're planning, but winit is supposed to be an implementation detail of glutin. It wouldn't be reexported or accessible or anything.

**Comment by kvark** [comment]
Perhaps, I misunderstand the idea behind winit then? I expect a library for handling window creation and even processing in a cross-platform manner. AFAIK, Glutin's role would become only creating a GL context on top of that. Why wouldn't `winit` be usable directly?

**Comment by tomaka** [comment]
You can use winit directly. What I mean is that the way I see it you wouldn't be able to get a reference to a winit window from a glutin window.

**Comment by kvark** [comment]
Why wouldn't you expose it? I understand that it's an implementation detail, but it's also a separate crate with public interface, so I don't get why you'd want to hide that.

**Comment by tomaka** [comment]
Because I don't want to have to bump the major version of glutin every time I bump the major version of winit.

**Comment by kvark** [comment]
So technically just because you are lazy to get that version bumped, we'll have to write our own glutin clone on top of `winit` if we really want to use the latter.

**Comment by tomaka** [comment]
It's not a matter of being lazy, it's a matter of stability. Glutin has already been broken several times in the past because of bad interactions between libraries when it comes to libc, objc, winapi, etc. If you don't take drastic measures, your library will break every week.

**Comment by kvark** [comment]
I understand your concern, but version bump != broken library. The stuff that works right now (not accessing `winit`) would still work with the new major version (that got published just because `winit` got updated).

**Comment by tomaka** [comment]
The problem is this:

```rust
glutin = "0.4"
winit = "0.1"
```

Now let's say I bump winit, update the winit version used by glutin, and publish glutin 0.4.1.
Boom, every Cargo.toml that uses the structure above breaks.

**Comment by kvark** [comment]
I see. This seems to be a rather fundamental issue with cargo dependencies in general, nothing specific to `glutin`. From your perspective, having this exposes would make `glutin` more vulnerable to breakage, and you are correct here. However, the breakage would only affect libraries using both glutin and winit, which, as far as I can tell, is just GFX and nothing more.

**Comment by kvark** [comment]
Looks like we are no longer blocked as of https://github.com/tomaka/glutin/pull/841
