### ISSUE TITLE
Document the code

### ISSUE THREAD

**Issue by eugene2k** [gfx-rs/gfx#914]
I have finally gotten my rust-sdl app working with gfx! After spending two days working on it. If that doesn't sound bad to you, I'll add that all my app does is draw a triangle. In other words I haven't even done anything other than look into the source code and try to figure out which generic does what. There's a serious lack of comments in the code as well as lack of online documentation (which would be ok if the code was well documented) and it hinders gfx's adoption, in my opinion. 

P.S. Before you refer me to examples/performance please note that that particular example is way out of date.

**Comment by kvark** [comment]
@eugene2k That does sound bad, I agree. Glad you managed to port it at last.

Is `performance` got accidentally disabled on linux build as well? we need to look into that for sure!

Perhaps, you could isolate all the SDL handling stuff inside a separate crate contributed as `gfx_window_sdl`?

**Comment by kvark** [comment]
@eugene2k That does sound bad, I agree. Glad you managed to port it at last.

Is `performance` got accidentally disabled on linux build as well? we need to look into that for sure!

Perhaps, you could isolate all the SDL handling stuff inside a separate crate contributed as `gfx_window_sdl`?

**Comment by eugene2k** [comment]
Performance hasn't been ported, it seems. It appears to be using the pre-PSO interface. I'll give the sdl port a try. Shouldn't be too hard.

**Comment by eugene2k** [comment]
This should do it...
[sdl.patch.gz](https://github.com/gfx-rs/gfx/files/192389/sdl.patch.gz)

**Comment by kvark** [comment]
@eugene2k could you file a PR for it?

**Comment by eugene2k** [comment]
I don't have the repository cloned on github, unfortunately.

**Comment by Bastacyclop** [comment]
redundant with #942
