### ISSUE TITLE
Update the performance example

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#917]
It seems to have fallen off the train lately, and got disabled in `Cargo.toml`.

**Comment by eugene2k** [comment]
#959 fixes this

**Comment by kvark** [comment]
@eugene2k FYI, Github has triggers for this sort of stuff, so you don't need to write a comment like that. E.g. if you put "closes #xxx" or "fixes #xxx" in the description of the PR, not only #xxx will get notified, but it will also be closed automatically upon accepting the said PR.

**Comment by eugene2k** [comment]
Oh, ok! Thx.

**Comment by cruelbob** [comment]
So can this issue be closed now?

**Comment by kvark** [comment]
@cruelbob right!
Fixed by #959
