### ISSUE TITLE
Segfault with i686-pc-windows-msvc 

### ISSUE THREAD

**Issue by pravic** [gfx-rs/gfx#923]
Any example crashed with access violation, stack corrupted.
Guess something violates the calling convention, but i cannot find where.

**Comment by kvark** [comment]
Please post the full output with the corrupted stack.

**Comment by pravic** [comment]
I cannot show stack backtrace, because its corrupted.
But i found a problem, its wrong method signature:
```rust
fn ExecuteCommandList(&mut self, pCommandList: *mut ID3D11CommandList) -> ()
```

```c
        void ( STDMETHODCALLTYPE *ExecuteCommandList )( 
            ID3D11DeviceContext2 * This,
            /* [annotation] */ 
            _In_  ID3D11CommandList *pCommandList,
            BOOL RestoreContextState);
 ```

[msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476423(v=vs.85).aspx)

**Comment by kvark** [comment]
@pravic big thanks for figuring this out and filing the issue to winapi-rs!

**Comment by kvark** [comment]
Looks to be fixed
