### ISSUE TITLE
Remove Bundle from pipeline macro

### ISSUE THREAD

**Issue by vickenty** [gfx-rs/gfx#925]
The way it is now, `Bundle` is only useful in a very small number of cases when user has a PSO per visible object, effectively narrowing its use cases to examples and very simple programs.

`Bundle` can be improved, to take ref instead of ownership. But someone may want to draw his objects in several passes, in which case it should be `Vec<Arc<PipelineState>>`. But if I have one global PSO for everything, both `Vec` and `Arc` are not needed. What I want to say here is that there is no one universal way to combine meshes with pipeline state, each application does its own thing.

Which is why I propose Bundle is removed from gfx and either moved to examples support library (gfx_app or other), or just integrated into the examples themselves (it seems possible to replace `Bundle` with a tuple and keep number of lines the same). Or it could be a start of a higher-level drawing library, as was proposed in #876.

cc @sectopod, @kvark

**Comment by eugene2k** [comment]
Seconded! I just don't see a use case for it in a serious application. It's too niche.

**Comment by kvark** [comment]
I disagree. Any serious app would have some unique draw calls for sure, where `Bundle` perfectly fits. Think of the sky, or some preprocessor passes. It's not a niche use case.

**Comment by vickenty** [comment]
@kvark
It seems counter-intuitive to provide struct only for one use case, and ignore others. It could possibly lead users to believe they are doing something wrong if their design doesn't fit into `Bundle` (myself included).

At the very least it needs to be renamed to suggest that other possibilities exist. Something like `UniqueBundle`. (But then again, why there are no `SharedBundle`, `MultiPassBundle`?)

Looking at the code closer, it doesn't seem that it needs to be generated with a macro at all. It can be just a generic struct, and then it could live in a module inside gfx, alongside other useful bundle flavors. I guess it would make it easier to document it too (when it comes down to it).

**Comment by kvark** [comment]
@vickenty Try moving it out, if you can. My understanding is that it's a part of the macro because it needs to access the struct names, which the macro generates.

**Comment by vickenty** [comment]
Instead of referening pipeline data type directly, this variant takes it as a type parameter. API didn't change much: https://github.com/vickenty/gfx/commit/82551b6e048d424b3937dc1cf57dc9c50385f202

**Comment by kvark** [comment]
@vickenty Looks good, thank you!
Could you move the implementation into `src/render/src/pso/bundle.rs`, add a public export of the `Bundle` class to `src/render/src/lib.rs` and file a PR?

**Comment by vickenty** [comment]
Okay, will do.

Still, it feels very odd to add 25 lines for just 1 liner method. :) Is there anything else that bundle could do? Proxy updates to data maybe?

**Comment by kvark** [comment]
@vickenty it's not jut the `encode` method. The storage struct itself is useful enough. Not sure what else we can do with it.
Also, @csherratt, @sectopod - I suppose this minor change is going to need a minor (not patch) version bump?
