### ISSUE TITLE
gfx_core::tex::Descriptor::to_image_info yields depth=1 even if depth is 0

### ISSUE THREAD

**Issue by oli-obk** [gfx-rs/gfx#928]
I don't understand enough here, but I have tracked down the issue that it's impossible to update a `piston_window::Texture` with the image it was created with.

[This piece of code](https://github.com/gfx-rs/gfx/blob/master/src/core/src/tex.rs#L178) uses `max(1, depth >> level)` to obtain the new depth, but if the starting depth was 0, then it should also yield 0, right?

**Comment by kvark** [comment]
@oli-obk what exactly was the problem? what error did you get?

**Comment by oli-obk** [comment]
I got an [´UpdateError::OutOfBounds´](http://www.piston.rs/docs/piston_window/gfx/enum.UpdateError.html) where the target had 1 for the depth an the source had 0

**Comment by kvark** [comment]
Hmm, interesting. I suppose your PR is good then.

**Comment by kvark** [comment]
This needs a second look.
