### ISSUE TITLE
Fix win32 GNU toolchain build for AppVeyor

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#932]
Something is pulling miniz-sys, which can't be found:

>running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-o" "C:\\projects\\gfx\\target\\debug\\build\\miniz-sys-d03126dbc9ee0074\\out\\miniz.o" "-c" "miniz.c"
 
>failed to execute command: The system cannot find the file specified. (os error 2)
Is `gcc.exe` not installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)

**Comment by fkaa** [comment]
Looks like it comes from `image -> png -> flate2 -> miniz-sys`.

**Comment by kvark** [comment]
That means someone somewhere has likely already faced this, we just need to find their solution.

**Comment by fkaa** [comment]
@kvark it seems the `flate2` dependency [is optional](https://github.com/PistonDevelopers/image-png/blob/master/Cargo.toml#L14), but the `image` crate would have to expose that for us to be able to disable it.
