### ISSUE TITLE
Move CullFace out of RasterMethod

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#936]
It's currently only affecting the triangle rendering. It should affect lines and points as well. Currently the state is leaked when rendering lines, which hurts @Binero project.

**Comment by Binero** [comment]
Seems like this issue stretches over multiple crates.

**Comment by kvark** [comment]
@Binero yes, but since they are on crates.io one doesn't have to update all at once - instead one can just start with the bottom (`draw_state`) and go up (`gfx_core`, `gfx`, etc).

**Comment by Binero** [comment]
I will have a look at draw_state.

**Comment by kvark** [comment]
Fixed by #945
