### ISSUE TITLE
Failure on UpdateTexture

### ISSUE THREAD

**Issue by andrewcsmith** [gfx-rs/gfx#940]
I need a single `R8` texture to be updated with a chunk of data that is `&[u8]`. My code passes all the relevant compile-time checks, but fails with the following error message upon calling `encoder.update_texture`. (Line breaks added for ease of reading)

```
thread '<main>' panicked at 'Error after executing command 
UpdateTexture(1, 
    D2(512, 512, Single), 
    None, 
    DataPointer { offset: 0, size: 11659 }, 
    ImageInfoCommon { xoffset: 0, yoffset: 0, zoffset: 0, width: 89, height: 131, 
        depth: 0, format: Format(R8, Uint), mipmap: 0 }
): InvalidOperation'
```
I'm not sure if this is a "bug" in gfx, as the crash is happening in OpenGL, but I was hoping that passing all the compile-time type checks would allow my update code to run.

Some truncated code follows:
```rust
gfx_pipeline!(
    pipe {
        glyphs: gfx::TextureSampler<u32> = "t_Glyphs",
        ...
    }
);

// setup code
let tex: gfx::handle::Texture<_, f::R8> = 
    factory.create_texture::<f::R8>(
        kind, 1, bind, gfx::Usage::Dynamic, Some(cty)) .unwrap();
let glyph_resource: gfx::handle::ShaderResourceView<_, u32> = 
    factory.view_texture_as_shader_resource::<(f::R8, f::Uint)>(
    &tex, (0, 0), gfx::format::Swizzle::new()).unwrap();
let sampler = factory.create_sampler_linear();
    let mut data = pipe::Data {
        vbuf: vertex_buffer,
        glyphs: (glyph_resource, sampler),
        blend: main_color
    };
let mut data = pipe::Data {
    glyphs: (glyph_resource, sampler),
    ...
};

// in the loop, where d: &[u8], causes crash
// For the above error, d.len() == 11659 (which is expected)
encoder.update_texture::<f::R8, (f::R8, f::Uint)>(
    &tex, None, info, &d[..]).unwrap();
```

**Comment by kvark** [comment]
Thank you for the report! It would help to have an `apitrace` dump of this case.

**Comment by kvark** [comment]
To clarify: gfx aims to prevent all GL errors by either disallowing stuff at compile time, or erroring earlier. So this is definitely our problem.

**Comment by andrewcsmith** [comment]
Oh, good, excellent to hear. [Here's the gist.](https://gist.github.com/andrewcsmith/7ca3b8cc7905c0de99aa2e215cfeec66) In the meantime I might go back to my workaround of creating a dummy array `[u8; 4]` for each rgba value in the texture.

**Comment by kvark** [comment]
Thank you @andrewcsmith ! I wish every bug was reported in such a high quality :)
Looking at the gist, I see nothing wrong with what we are doing. The spec's listed reasons for `GL_INVALID_OPERATION` don't apply here:
>GL_INVALID_OPERATION is generated if the texture array has not been defined by a previous glTexImage2D operation.
> GL_INVALID_OPERATION is generated if type is one of GL_UNSIGNED_BYTE_3_3_2, GL_UNSIGNED_BYTE_2_3_3_REV, GL_UNSIGNED_SHORT_5_6_5, or GL_UNSIGNED_SHORT_5_6_5_REV and format is not GL_RGB.
> GL_INVALID_OPERATION is generated if type is one of GL_UNSIGNED_SHORT_4_4_4_4, GL_UNSIGNED_SHORT_4_4_4_4_REV, GL_UNSIGNED_SHORT_5_5_5_1, GL_UNSIGNED_SHORT_1_5_5_5_REV, GL_UNSIGNED_INT_8_8_8_8, GL_UNSIGNED_INT_8_8_8_8_REV, GL_UNSIGNED_INT_10_10_10_2, or GL_UNSIGNED_INT_2_10_10_10_REV and format is neither GL_RGBA nor GL_BGRA.
> GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and the buffer object's data store is currently mapped.
> GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and the data would be unpacked from the buffer object such that the memory reads required would exceed the data store size.
> GL_INVALID_OPERATION is generated if a non-zero buffer object name is bound to the GL_PIXEL_UNPACK_BUFFER target and data is not evenly divisible into the number of bytes needed to store in memory a datum indicated by type.
> GL_INVALID_OPERATION is generated if glTexSubImage2D is executed between the execution of glBegin and the corresponding execution of glEnd.

**Comment by kvark** [comment]
Relevant lines from the gist:
>103 glPixelStorei(pname = GL_UNPACK_ALIGNMENT, param = 1)
...
>140 glGenTextures(n = 1, textures = &1)
141 glBindTexture(target = GL_TEXTURE_2D, texture = 1)
142 glTexStorage2D(target = GL_TEXTURE_2D, levels = 1, internalformat = GL_R8UI, width = 512, height = 512)
143 glTexParameteri(target = GL_TEXTURE_2D, pname = GL_TEXTURE_BASE_LEVEL, param = 0)
144 glTexParameteri(target = GL_TEXTURE_2D, pname = GL_TEXTURE_MAX_LEVEL, param = 0)
...
>365 glTexSubImage2D(target = GL_TEXTURE_2D, level = 0, xoffset = 0, yoffset = 0, width = 89, height = 131, format = GL_RED, type = GL_UNSIGNED_BYTE, pixels = blob(11659))
366 glGetError() = GL_INVALID_OPERATION

**Comment by kvark** [comment]
In the [GL-4.4 spec](https://www.opengl.org/registry/doc/glspec44.core.pdf) page 174 there is a table of pixel data formats, and it includes `GL_RED_INTEGER`. This is funny since [docs.gl page](http://docs.gl/gl4/glTexSubImage2D) for `glTexSubImage2D` doesn't list those integer formats. We should definitely try this out.

**Comment by kvark** [comment]
A possible fix would be to refactor/rewrite `format_to_glpixel` (https://github.com/gfx-rs/gfx/blob/master/src/backend/gl/src/tex.rs) to return different formats for ints/uints.

**Comment by kvark** [comment]
@andrewcsmith if you could fetch that #941 branch and try it out with cargo override on your test case, to verify that it fixes your issue, that would be totally lovely ;)

**Comment by andrewcsmith** [comment]
I'm getting a bunch of compiler errors when I try to build against any branch on git. I even attempted to build 3c3dfc2dc604b9fadafac92f4d4afc6f73dda1bc but that led to the same errors. Is there a chain of dependencies I need to worry about when building locally or should I just go about fixing these? I was on gfx 0.10.1.

Errors are pretty banal things like this: 
```
src/main.rs:51:9: 51:60 error: the trait `gfx_core::format::Formatted` is not implemented for the type `(gfx_core::format::R8_G8_B8_A8, gfx_core::format::Unorm)` [E0277]
src/main.rs:51         gfx_window_glutin::init::<ColorFormat, DepthFormat>(builder);
```

**Comment by kvark** [comment]
Could you please try cargo override only for the gfx_device_gl crate?

Regards,
Dzmitry

**Comment by andrewcsmith** [comment]
Hm, still has the same error message. I'm wondering if maybe I should fix the errors (and link against `master`) on the chance that fixing those errors will fix my issue. In case you were curious, my card is running GLSL 4.10.

**Comment by andrewcsmith** [comment]
this (plus some bugs worked out in gitter) fixes this issue. thank you!
