### ISSUE TITLE
How to create command buffer in generic code?

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#947]
Trying to upgrade Hematite, and this line https://github.com/PistonDevelopers/hematite/blob/master/src/shader.rs#L102 should be:

```rust
let encoder = factory.create_command_buffer().into();
```

However, this is not possible, since `create_command_buffer` is a method of `gfx_device_gl::Factory` and not the trait `gfx::Factory`.

```
src/shader.rs:109:31: 109:52 error: no method named `create_command_buffer` found for type `F` in the current scope
src/shader.rs:109         let encoder = factory.create_command_buffer().into();
                                                ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by kvark** [comment]
Yes, please make it receive the command buffer right away in the constructor.
Kudos for upgrading Hematite!

**Comment by bvssvni** [comment]
Will try to fix this another way.

**Comment by norru** [comment]
Sorry for the necroposting, but is this the recommended way (create the command buffer in the main program by invoking the concrete factory's methind, and then pass it on) or a stopgap/temporary solution?

I'd like to understand the rationale behind this design choice.

**Comment by kvark** [comment]
@norru it's not set in stone yet, we'll see better when Vulkan and Metal backends are better shaped. The current reasoning is - there might be multiple types of command buffers (e.g. DX11 backend already has native and emulated ones), and we don't know in advance the parameters needed to create one for next-gen APIs (e.g. maximum buffer size allocated).

**Comment by norru** [comment]
I understand.
Would something like `create_simple_command_buffer()` make sense? This could cover just the "typical" use case, regardless of the backend. Similar generic Factory methods exist for other type of buffers.
