### ISSUE TITLE
Refactor `mesh`/`slice` module and items.

### ISSUE THREAD

**Issue by Binero** [gfx-rs/gfx#951]
This issue discusses the refactoring of the `Slice` type, and items relating to it.

- [x] The `Mesh` type is long gone. The `mesh` module must be renamed to `slice`.
- [x] Factory methods creating `VertexBuffer`s should not automatically couple them with `Slice`s. ~~Instead, `Slice` should expose a `from(VertexBuffer)` method. This makes it more clear that a `Slice` is not bound to a `VertexBuffer`.~~
- [x] Factories should instead expose a `create_vertex_buffer_with_slice` and a `create_vertex_buffer_with_index_slice` method, or similar. Again, this is to stress the fact that `Slices` are not specifically bound to a `VertexBuffer`.
- [x] Move the BaseVertex out of the `SliceKind` enum, into the `Slice` type, as it makes sense for all of the variants. 
- [x] Remove `Index8` since it's not supported on DX11
- [x] Document all of the above.

**Comment by kvark** [comment]
Fixed by #955
