### ISSUE TITLE
Version v0.11

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#954]
Stuff to track: ~~#951~~, ~~#950~~, ~~#936~~
Integrate: ~~#953~~

**Comment by nado** [comment]
Got here a bit randomly, but why dont you use native milestones system from github ?

**Comment by kvark** [comment]
@nado Milestones in GH seem to be less visible and provide no particular benefit for the versioned releases. We are only using them for big stuff, like a particular shader model feature set.

**Comment by eugene2k** [comment]
Looks like this can be closed.

**Comment by kvark** [comment]
Done indeed
