### ISSUE TITLE
Implement `ToUniform` for u32

### ISSUE THREAD

**Issue by Binero** [gfx-rs/gfx#956]
There doesn't seem to be anything that is stopping this from being possible.

**Comment by kvark** [comment]
uniforms are the past, constant buffers are the future

**Comment by kvark** [comment]
> uniforms are the past, constant buffers are the future

I wasn't entirely correct (not to mention being dismissive - sorry!). Uniform values still present in next-gen API as root constants / push constants. However, that area belongs to gfx-hal, and I don't think we have an issue there.
