### ISSUE TITLE
Add the CI tests for subpackages

### ISSUE THREAD

**Issue by eugene2k** [gfx-rs/gfx#961]
Currently Travis and Appveyor only run tests for the top-level gfx_app package. Subpackages, such as gfx_core and gfx_window_* are not tested - only built. Travis and Appveyor scripts need to be changed to test all the packages in gfx repository. Cargo has the ability to run tests for a package given its spec: something like `cargo test -p gfx_core` will test the `gfx_core` package. Adding additional test commands to the scripts should be pretty simple.

**Comment by eugene2k** [comment]
Is there any reason to test gfx on rust with gnu toolchain as well as on rust with msvc toolchain? Seems redundant, since all of gfx is written in rust. I can delete the gnu target from appveyor while I'm working on this issue.

**Comment by kvark** [comment]
@retep998 do you see any use of testing the GNU toolchain?

**Comment by retep998** [comment]
It's nice to test the GNU toolchain as it has somewhat different import libraries that can sometimes have issues (such as when the `libd3dcompiler.a` turned out to be for a severely outdated DLL). While I do wish MinGW would just go away, if you can test GNU for free, I don't see why you wouldn't want to keep testing it just in case.

**Comment by retep998** [comment]
That said, do we really need to install mingw through chocolatey? It spams up the build logs like crazy. If the only way to remove the dependency on that is to remove CI for the gnu toolchain, then I'd be okay with that.

**Comment by eugene2k** [comment]
Wouldn't the same kind of testing be done by winapi-rs? It tests both stable and nightly on gnu and msvc.

**Comment by eugene2k** [comment]
As for chocolatey, it seems appveyor only has mingw32 installed, so the only other way to do it would be to manually download and unpack mingw64.

**Comment by retep998** [comment]
winapi doesn't cover integration tests at all. It has no idea whether things actually function correctly. At best I can test whether things link and whether the size/alignment of a type is correct. The d3dcompiler issue for example I wouldn't be able to catch with testing in winapi.

What does gfx depend on that has to compile C/C++ code and so need mingw? If the entire dependency tree is pure Rust then the mingw that is bundled with Rust is good enough and no separate installation is needed.

**Comment by eugene2k** [comment]
The bindings for the miniz library require gcc to build. Though, I'm not sure what requires the miniz library.

**Comment by kvark** [comment]
Piston-image, IIRC

**Comment by eugene2k** [comment]
No, it doesn't look like anything depends on piston-image. It seems that png depends on it, image depends on png and gfx_app in turn depends on image for some of the examples.

**Comment by kvark** [comment]
Yes, that's what I meant.
