### ISSUE TITLE
Reexport `draw_state::target::Rect` somewhere

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#967]
When `gfx::core` was hidden, we forgot to reexport `Rect`. Might be a problem with other structs from the "draw_state" library.

**Comment by kvark** [comment]
Oh, nicely spotted! I wonder why Rust doesn't warn us about this.

**Comment by bvssvni** [comment]
`Typed` is also not reexported. Need it for creating main targets.

**Comment by kvark** [comment]
oh, `Type` is important

**Comment by kvark** [comment]
Actually, the `Rect` is exposed as `gfx::Rect` by this line:
```rust
pub use draw_state::target::*;
```
