### ISSUE TITLE
Change Usage semantics

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#970]
The current `Usage` enum is heavily inspired by DX11. There is nothing wrong with it in particular, it maps nicely to both DX11 and GL. But looking forward, we need more flexibility, since other APIs are not locked to these usage types. I propose a set of flags instead:

``` rust
bitflags!(
    /// CPU transfer operations.
    /// In general, CPU access (read/write) forces a texture to have linear tiling, which reduces the GPU access pattern efficiency (hence, the rendering performance). Addition costs apply to synchronize CPU-GPU interaction by the driver.
    /// It is recommended though (if not enforced in the future) to not have renderable textures that are read/write. Instead, you create 2 separate textures - one for GPU only rendering with `TRANS_COPY` flag. Another - for CPU-only read/write texture ("staging texture" in DX11) that you will copy.
    pub flags Transfer: u8 {
        /// Resource is readable by CPU.
        pub TRANS_READ = 0x1,
        /// Resource is writable by CPU.
        pub TRANS_WRITE = 0x2,
        /// Resource can be copied from/into CPU visible memory. This flag barely affects performance.
        pub TRANS_COPY = 0x4,
    }
);
```

The backend will be able to derive the appropriate internal usage type from the `(Transfer, Bind)` flags. If a resource doesn't have any flags, it's considered immutable (in DX11 terms). `TRANS_WRITE` alone means the resource is dynamic. Both read/write mean the resource is staging. The backends are free to error out on an incompatible set of flags.

**Comment by Bastacyclop** [comment]
I guess it's time to think about this for #1105

**Comment by Bastacyclop** [comment]
| Current | Proposition |
|---------|-------------|
| `GpuOnly` | `COPY` |
|  `Immutable` |  |
| `Dynamic` | `WRITE` |
| `Mappable(access)` | `MAP | access` |
| `CpuOnly(access)` | ? |

**Comment by Bastacyclop** [comment]
is `CpuOnly` going to be a backend choice instead of a user choice then ?

**Comment by Bastacyclop** [comment]
should there be a flag to allow `update_buffer` calls ?

**Comment by kvark** [comment]
Please think of this from the ground up, my original proposal here doesn't look too appealing any more. And in your thought process, don't take GL as a creditable base point, given it's the weakest HW abstracting API among the ones we need to support. DX11 is better, DX12/Vulkan are much better. So consider Vulkan's model for possible simplification and adoption. Let me explain it a bit:
  - whether or not a resource is mappable is defined by the memory heap it's allocated from. A heap can be accessible from GPU only, or from CPU and GPU, or from CPU only with an ability to transfer data to GPU. That is basically what DX11 staging resources are, and what I modelled `CpuOnly` after.
  - Resource flags passed during initialization define if it can be transferred to, transferred from, alongside stuff like "bound as a vertex buffer", "as a texture", and so on. If a resource can be transferred to, you can use stuff like our `update_buffer` providing CPU-side data even if the resource memory is only visible from GPU.

Hope that helps. Please keep up with the constructive discussion! And @snuk182 is invited here too ;)

**Comment by Bastacyclop** [comment]
So I think that we want to be able to determine the memory properties ([`VkMemoryPropertyFlagBits`](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkMemoryPropertyFlagBits)) `DEVICE_LOCAL` and `HOST_VISIBLE`. I don't know how to handle `HOST_COHERENT` and `HOST_CACHED` but my guess is we don't really care about `HOST_COHERENT` while we want `HOST_CACHED` when we are reading from host. Finally, `LAZILY_ALLOCATED` seems out of the scope of this discussion.
`TRANSFER_SRC` and `TRANSFER_DST` are parts of [`Vk{Buffer, Image}UsageFlagBits`](https://www.khronos.org/registry/vulkan/specs/1.0/xhtml/vkspec.html#VkBufferUsageFlagBits) because they are not memory properties, but should we include them in our memory usage or in our bind flags ?

I found [this post](http://gpuopen.com/vulkan-device-memory/) interesting and exposing similarities with [DX12](https://msdn.microsoft.com/en-us/library/windows/desktop/dn770374(v=vs.85).aspx). What if we had:
```rust
pub enum Usage {
    Data, // GpuOnly and Immutable
          // VK DEVICE_LOCAL, D3D12_HEAP_TYPE_DEFAULT
    Upload, // Mappable(WRITE) and CpuOnly(WRITE)
            // VK HOST_VISIBLE and DEVICE_LOCAL if possible, D3D12_HEAP_TYPE_UPLOAD
    Download, // Mappable(READ) and CpuOnly(READ)
              // VK HOST_VISIBLE and HOST_CACHED if possible, D3D12_HEAP_TYPE_READBACK
}
```

**Comment by kvark** [comment]
Thanks @Bastacyclop for the investigation and the API proposal! I see you are starting to like DX12, which is great, considering our PSOs also happen to reflect it more than any other API ;)

The only problem with your proposal is that it mixes `GpuOnly` and `Immutable`. Perhaps, we can have `DataConst` and `DataMut`? Here is why we need immutable resources:
  - D3D11 has then natively
  - for Vulkan, it means we can specify no TRANSFER_DST flag, among other things
  - for core API, we have immutable resource constructors that accept data. I consider it rather elegant to assume no mutability when you request the initial data.

**Comment by Bastacyclop** [comment]
@kvark The idea was that `TRANSFER_DST` and `TRANSFER_SRC` could be in `memory::Bind`
```rust
fn is_mutable(bind: Bind) -> bool {
    let mutable = TRANSFER_DST | UNORDERED_ACCESS | RENDER_TARGET | DEPTH_STENCIL;
    bind.intersects(mutable)
}
```
Another possibility would be to have a parameter like `Data(Transfer)`, whith `Upload` being `TRANSFER_SRC` and `Download` being `TRANSFER_DST`. The benefit is that you can have more than `DataConst = Data(TRANSFER_SRC)` and `DataMut = Data(TRANSFER_SRC | TRANSFER_DST)`, if we care about that.

**Comment by kvark** [comment]
Ok, having the transfer in `memory::Bind` seems to make sense w.r.t. mutability, and that leaves the `Usage::Data` clean, with all the `Usage` resembling DX12 pretty much. Let's go for it!

**Comment by Bastacyclop** [comment]
@kvark Some thoughts about the consequences of this change:
1. Using Upload/Download buffers without mapping them at some point will be a waste, `create_{upload, download}_buffer` utility methods should map the buffers on the way.
2. Constant/Dynamic buffers will be replaced by Upload buffers.
3. Constant buffers will have to be updated by mapping the memory in favor of buffer updates (1 + 2).
4. There will be no `RWable` mappings anymore.

I am also considering changing the current `handle::RawMapping` organisation to:
```rust
pub struct buffer::Raw<R: Resources> {
    resource: R::Buffer,
    info: buffer::Info,
    mapping: Mutex<Option<R::Mapping>>,
}
```
This reduces cross references and complexity, the user won't need to manage `{Read, Writ}able` structs anymore and will only care about `{Read, Writ}er` structs.

**Comment by kvark** [comment]
@Bastacyclop 

> `create_{upload, download}_buffer` utility methods should map the buffers on the way

I don't expect creation of those buffers and their mapping to often be together in *good* code, so I don't think we should map them "on the way"

> Constant/Dynamic buffers will be replaced by Upload buffers.

I think you mean `Immutable/Dynamic` here?

Agreed on the points, thanks for making these clear!

**Comment by Bastacyclop** [comment]
> I don't expect creation of those buffers and their mapping to often be together in good code

What do you mean ? We are talking about persistent mapping right ? When the backend only supports temporary mapping, `map_buffer` is [not doing much](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx11/src/factory.rs#L888).

> I think you mean Immutable/Dynamic here?

I meant [Constant](https://docs.rs/gfx/0.13.0/gfx/buffer/enum.Role.html#variant.Constant) buffers but Dynamic alone is probably clearer.

**Comment by kvark** [comment]
@Bastacyclop ok, I understand what you mean now. All good :)
