### ISSUE TITLE
Problem with normalized Z device coordinates

### ISSUE THREAD

**Issue by kvark** [gfx-rs/gfx#971]
OpenGL has Z output of the vertex shader between -1 and 1.
DirectX has Z output between 0 and 1.

`cgmath`, that we use in the examples, produces matrices for OpenGL style. I assume it works on DirectX by luck, and we'll see distortions and clipping in more complex scenes (like Hematite).

What we can do is - modify HLSL shaders to transfrom Z after applying the matrix:

``` hlsl
OUT.pos.z = 0.5 * OUT.pos.z + OUT.pos.w;
```

**Comment by MaikKlein** [comment]
You probably want to have the depth values between 0 and 1 anways but I think only OpenGL 4.5 can do this.

Here is the best use case for this https://developer.nvidia.com/content/depth-precision-visualized

**Comment by kvark** [comment]
@MaikKlein thanks for the links!
That's not really a problem until we have a unified shader solution, hence the low priority tag.

**Comment by kvark** [comment]
This is unfortunate but manageable by the user, closing.
