### ISSUE TITLE
Allow generic parameters on `gfx_pipeline!` macro

### ISSUE THREAD

**Issue by bvssvni** [gfx-rs/gfx#972]
Currently, you can't write generic libraries for Gfx without overhead that works with both `Rgba8` and `Srgba8` targets. This is because `gfx_pipeline!` expands to a concrete type that is locked to either `Rgba8`, `Srgba8` or if you want to use it with both: [Format](http://gfx-rs.github.io/gfx/gfx/format/struct.Format.html) which encodes these formats at run-time.

It should be easy to write generic code with Gfx, because that is the whole point!

By allowing generic parameters in `gfx_pipeline!`, one could create generic methods when creating the pipeline, which then structures storing the PSO can add a parameter for the format. This will make it possible to infer the format from the actual target the application uses, instead of deciding this upfront by library authors.

**Comment by bvssvni** [comment]
Perhaps this should wait until https://github.com/gfx-rs/gfx/pull/969 has landed.

**Comment by bvssvni** [comment]
Could copy code from the old quack library https://github.com/PistonDevelopers/quack/blob/master/src/lib.rs#L80.

**Comment by kvark** [comment]
@bvssvni it's non-trivial with PSOs, since there are a number of dependent types.

**Comment by kvark** [comment]
not happening in pre-ll, closing
