### ISSUE TITLE
Implement state caching for opengl backend

### ISSUE THREAD

**Issue by reneeichhorn** [gfx-rs/gfx#978]
Simple rendering scenario:

```
encoder.clear(&main_color, ...);
encoder.update_constant_buffer(...);
encoder.draw(...);
encoder.flush(&mut device);
window.swap_buffers().unwrap();
device.cleanup();
```

Resulting gl calls for each frame: 
https://docs.google.com/spreadsheets/d/1oqnSho-hOFrprrUbUwVTzQ-yXWfYqfw5TCzPIpYshq8/edit?usp=sharing

As stated in official opengl documentation: https://www.opengl.org/archives/resources/faq/technical/performance.htm

> While some OpenGL implementations make redundant calls as cheap as possible, making redundant calls generally is considered bad practice. Certainly you shouldn't count on redundant calls as being cheap. Good application developers avoid them when possible.

Besides performance I also think redundant calls makes debugging a bit messy.

For windows and linux users I recommend GPU PerfStudio from AMD for debugging. (works on nvidia hardware as far as I know)
http://developer.amd.com/tools-and-sdks/graphics-development/gpu-perfstudio/

**Comment by kvark** [comment]
@Auruss Thanks for filing this and gathering all the info!
You rock! :guitar:

**Comment by icefoxen** [comment]
is this not related to https://github.com/gfx-rs/gfx/issues/1198 ?

**Comment by kvark** [comment]
Yes, it's done! Thanks!
