### ISSUE TITLE
Simplify target dependencies

### ISSUE THREAD

**Issue by pravic** [gfx-rs/gfx#982]
… in [Cargo.toml](https://github.com/gfx-rs/gfx/blob/master/Cargo.toml#L27-L37), it can be simplified as

```
[target.'cfg(unix)'.dependencies]
gfx_window_glfw = { path = "src/window/glfw", version = "0.10" }
gfx_window_sdl = { path = "src/window/sdl", version = "0.2" }

[target.'cfg(windows)'.dependencies]
gfx_device_dx11 = { path = "src/backend/dx11", version = "0.2" }
gfx_window_dxgi = { path = "src/window/dxgi", version = "0.2" }
```

[Manual](http://doc.crates.io/specifying-dependencies.html), available since Cargo 0.9.0 (Rust 1.8.0, which is stable month ago).

Just as suggestion.

**Comment by kvark** [comment]
I was waiting for this to become available. Thanks for filing an issue!

**Comment by pravic** [comment]
Great.
