### ISSUE TITLE
GL_FRAMEBUFFER_SRGB and Srgba8 vs Rgba8 render target

### ISSUE THREAD

**Issue by norru** [gfx-rs/gfx#992]
I'm working on my toy project, for which I'm using a simple HDR pipeline. All the rendering and postprocessing is linear and I'm using FP16 render targets, until the tonemapping step, when I resolve the framebuffer to Rgba8.

At some point I realized I was missing the gamma conversion step - so I added it to my tone mapping shader.

When I got unexpected results, I guessed it was because the graphics driver was doing the conversion for me automatically. Digging deeper, it turns out it didn't but I could turn the feature on by rendering to a Srgba8 framebuffer.

I got the same results as Rgba8. Doing some investigation, I found that in order for OpenGL backend to to do so, GL_FRAMEBUFFER_SRGB must be enabled (together with setting the render target's format to Srgba8).

GL_FRAMEBUFFER_SRGB doesn't turn out from any search in gfx-rs. Is this a bug?

**Comment by kvark** [comment]
It is enabled by default. Our examples are mostly gamma correct, last time I checked.
Here is a piece from `src/backend/gl/lib.rs`:
```rust
        if caps.srgb_color_supported {
            unsafe {
                gl.Enable(gl::FRAMEBUFFER_SRGB);
            }
        }
```

**Comment by norru** [comment]
Ok, I've missed that bit. Should I switch to Srgba8 then?

**Comment by kvark** [comment]
Yes, that should do it.

**Comment by norru** [comment]
Thanks :)
