### ISSUE TITLE
Build HLSL shaders from build.rs

### ISSUE THREAD

**Issue by rpjohnst** [gfx-rs/gfx#996]
It's pretty easy for shader binaries to get out of date (for example, [this commit](https://github.com/gfx-rs/gfx/commit/70cdeadb6b821dbc4c019414d54280b54acfe5cd) changed the cube example shader in passing but neglected to include updated binaries, so currently the cube example is black on windows). It's not too difficult to build them using `d3dcompiler` instead of `fxc`, perhaps the dx11 backend could include some support for that?

It could be done from `build.rs` with an extra library and/or with a procedural macro to replace `include_bytes!`, perhaps as part of a cross-API shader solution. I can submit a PR if this sounds like a good idea.

**Comment by kvark** [comment]
we aren't getting shader binaries out of date, because pre-ll is no longer actively developed, closing
